"""Structural CFI parity decoder for promised gadget-family rows.

This module generalizes the complete-graph CFI parity solver to regular
non-complete bases generated by ``cfi_base_family_search.py``.  It is a
dequantization baseline, not a graph-isomorphism algorithm: if a candidate uses
these CFI rows under an access model where the gadget-family promise is legal,
the global twist parity is classically transparent.
"""

from __future__ import annotations

import json
from dataclasses import asdict, dataclass, is_dataclass
from pathlib import Path
from typing import Any

import numpy as np

from cfi_base_family_search import DEFAULT_BASE_IDS, base_edges, base_graph_by_id, cfi_parity_graph_from_base
from research_registry import ExperimentResultRecord, NegativeResultRecord, upsert_experiment_result, upsert_negative_result, utc_now


COSET_WORKBENCH_DIR = Path("research/coset_workbench")
CFI_STRUCTURAL_DECODER_PATH = COSET_WORKBENCH_DIR / "cfi_structural_decoder.json"


@dataclass(frozen=True)
class CFIStructuralDecode:
    success: bool
    status: str
    inferred_regular_base_degree: int | None
    inferred_base_vertex_count: int | None
    vertex_count: int
    middle_vertex_count: int
    edge_copy_vertex_count: int
    edge_pair_count: int
    vertex_gadget_count: int
    local_parities: list[int]
    global_twist_parity: int | None
    ambiguity: str
    interpretation: str


@dataclass(frozen=True)
class CFIStructuralDecoderRecord:
    base_id: str
    base_description: str
    base_vertex_count: int
    base_edge_count: int
    cfi_vertex_count: int
    shuffled: bool
    untwisted_decode: CFIStructuralDecode
    twisted_decode: CFIStructuralDecode
    recovers_global_twist: bool
    legal_access_model: str
    status: str
    interpretation: str


@dataclass(frozen=True)
class CFIStructuralDecoderReport:
    created_at: str
    base_ids: list[str]
    records: list[CFIStructuralDecoderRecord]
    headline_metrics: dict[str, int]
    status: str
    summary: str
    falsifiers_triggered: list[str]


def permute_adjacency(adjacency: np.ndarray, seed: int) -> np.ndarray:
    rng = np.random.default_rng(seed)
    permutation = rng.permutation(adjacency.shape[0])
    return adjacency[permutation][:, permutation]


def _failure_decode(
    status: str,
    adjacency: np.ndarray,
    ambiguity: str,
    inferred_regular_base_degree: int | None = None,
    inferred_base_vertex_count: int | None = None,
    middle_vertex_count: int = 0,
    edge_copy_vertex_count: int = 0,
    edge_pair_count: int = 0,
    vertex_gadget_count: int = 0,
) -> CFIStructuralDecode:
    return CFIStructuralDecode(
        success=False,
        status=status,
        inferred_regular_base_degree=inferred_regular_base_degree,
        inferred_base_vertex_count=inferred_base_vertex_count,
        vertex_count=int(adjacency.shape[0]),
        middle_vertex_count=middle_vertex_count,
        edge_copy_vertex_count=edge_copy_vertex_count,
        edge_pair_count=edge_pair_count,
        vertex_gadget_count=vertex_gadget_count,
        local_parities=[],
        global_twist_parity=None,
        ambiguity=ambiguity,
        interpretation=ambiguity,
    )


def decode_regular_cfi_twist_parity(adjacency: np.ndarray) -> CFIStructuralDecode:
    """Recover global CFI twist parity for regular promised-gadget rows.

    The decoder uses only adjacency structure.  It infers middle vertices and
    edge-copy vertices from the two degree classes, pairs edge copies by their
    shared middle-neighbor signatures, reconstructs vertex gadgets, and sums
    the locally uniform parity assignments.  Arbitrary bit choices inside each
    recovered edge pair cancel globally because each base edge touches two
    vertex gadgets.
    """

    matrix = np.asarray(adjacency, dtype=np.uint8)
    if matrix.ndim != 2 or matrix.shape[0] != matrix.shape[1]:
        return _failure_decode("not-square-adjacency", matrix, "Adjacency matrix must be square.")

    degrees = matrix.sum(axis=1).astype(int)
    degree_values = sorted(set(int(value) for value in degrees.tolist()))
    if len(degree_values) != 2:
        return _failure_decode(
            "not-regular-cfi-degree-profile",
            matrix,
            f"Expected two CFI degree classes for regular bases, found {degree_values}.",
        )

    middle_degree, edge_copy_degree = degree_values
    if middle_degree < 3:
        return _failure_decode(
            "unsupported-low-degree-cfi-base",
            matrix,
            f"Degree {middle_degree} CFI bases do not separate middle and edge-copy structure robustly.",
            inferred_regular_base_degree=middle_degree,
        )
    expected_edge_copy_degree = 1 << (middle_degree - 1)
    if edge_copy_degree != expected_edge_copy_degree:
        return _failure_decode(
            "not-regular-cfi-count-profile",
            matrix,
            (
                f"Regular degree-{middle_degree} CFI edge-copy vertices should have degree "
                f"{expected_edge_copy_degree}, found {edge_copy_degree}."
            ),
            inferred_regular_base_degree=middle_degree,
        )

    middle_vertices = [idx for idx, degree in enumerate(degrees.tolist()) if degree == middle_degree]
    edge_copy_vertices = [idx for idx, degree in enumerate(degrees.tolist()) if degree == edge_copy_degree]
    expected_gadget_size = 1 << (middle_degree - 1)
    if len(middle_vertices) % expected_gadget_size != 0 or len(edge_copy_vertices) % 2 != 0:
        return _failure_decode(
            "not-regular-cfi-count-profile",
            matrix,
            "Middle or edge-copy counts are not divisible by the regular CFI gadget sizes.",
            inferred_regular_base_degree=middle_degree,
            middle_vertex_count=len(middle_vertices),
            edge_copy_vertex_count=len(edge_copy_vertices),
        )

    inferred_base_vertex_count = len(middle_vertices) // expected_gadget_size
    expected_edge_pair_count = inferred_base_vertex_count * middle_degree // 2
    if len(edge_copy_vertices) // 2 != expected_edge_pair_count:
        return _failure_decode(
            "not-regular-cfi-count-profile",
            matrix,
            (
                "Edge-copy count does not match the handshaking count for an inferred regular "
                f"degree-{middle_degree} base."
            ),
            inferred_regular_base_degree=middle_degree,
            inferred_base_vertex_count=inferred_base_vertex_count,
            middle_vertex_count=len(middle_vertices),
            edge_copy_vertex_count=len(edge_copy_vertices),
        )

    middle_set = set(middle_vertices)
    middle_neighbors = {
        vertex: set(int(item) for item in np.flatnonzero(matrix[vertex]) if int(item) in middle_set)
        for vertex in edge_copy_vertices
    }
    signatures: dict[int, tuple[int, ...]] = {}
    for vertex in edge_copy_vertices:
        sharing = [
            other
            for other in edge_copy_vertices
            if other != vertex and middle_neighbors[vertex].intersection(middle_neighbors[other])
        ]
        signatures[vertex] = tuple(sorted(sharing))

    signature_groups: dict[tuple[int, ...], list[int]] = {}
    for vertex, signature in signatures.items():
        signature_groups.setdefault(signature, []).append(vertex)
    group_sizes = sorted(len(group) for group in signature_groups.values())
    if any(size != 2 for size in group_sizes):
        return _failure_decode(
            "ambiguous-edge-copy-pairing",
            matrix,
            (
                "Edge-copy twin signatures are not canonical size-two pairs. "
                f"Observed group sizes: {group_sizes[:12]}."
            ),
            inferred_regular_base_degree=middle_degree,
            inferred_base_vertex_count=inferred_base_vertex_count,
            middle_vertex_count=len(middle_vertices),
            edge_copy_vertex_count=len(edge_copy_vertices),
        )

    pair_id: dict[int, int] = {}
    pair_bit: dict[int, int] = {}
    for idx, group in enumerate(sorted(tuple(sorted(group)) for group in signature_groups.values())):
        for bit, vertex in enumerate(group):
            pair_id[vertex] = idx
            pair_bit[vertex] = bit

    gadget_bits: dict[tuple[int, ...], list[tuple[int, ...]]] = {}
    for middle in middle_vertices:
        high_neighbors = [int(item) for item in np.flatnonzero(matrix[middle]) if int(item) in pair_id]
        key = tuple(sorted(pair_id[item] for item in high_neighbors))
        bits = tuple(pair_bit[item] for item in sorted(high_neighbors, key=lambda item: pair_id[item]))
        if len(key) != middle_degree or len(set(key)) != middle_degree:
            return _failure_decode(
                "invalid-middle-gadget-incidence",
                matrix,
                "A reconstructed middle vertex is not incident to one copy from each local base edge.",
                inferred_regular_base_degree=middle_degree,
                inferred_base_vertex_count=inferred_base_vertex_count,
                middle_vertex_count=len(middle_vertices),
                edge_copy_vertex_count=len(edge_copy_vertices),
                edge_pair_count=len(signature_groups),
            )
        gadget_bits.setdefault(key, []).append(bits)

    if len(gadget_bits) != inferred_base_vertex_count:
        return _failure_decode(
            "invalid-vertex-gadget-count",
            matrix,
            f"Recovered {len(gadget_bits)} vertex gadgets, expected {inferred_base_vertex_count}.",
            inferred_regular_base_degree=middle_degree,
            inferred_base_vertex_count=inferred_base_vertex_count,
            middle_vertex_count=len(middle_vertices),
            edge_copy_vertex_count=len(edge_copy_vertices),
            edge_pair_count=len(signature_groups),
            vertex_gadget_count=len(gadget_bits),
        )

    local_parities: list[int] = []
    for key, assignments in sorted(gadget_bits.items()):
        parities = {sum(bits) % 2 for bits in assignments}
        if len(assignments) != expected_gadget_size or len(parities) != 1:
            return _failure_decode(
                "invalid-vertex-gadget-parity-profile",
                matrix,
                (
                    "A reconstructed vertex gadget does not have the expected number of even/odd "
                    "mask assignments with uniform local parity."
                ),
                inferred_regular_base_degree=middle_degree,
                inferred_base_vertex_count=inferred_base_vertex_count,
                middle_vertex_count=len(middle_vertices),
                edge_copy_vertex_count=len(edge_copy_vertices),
                edge_pair_count=len(signature_groups),
                vertex_gadget_count=len(gadget_bits),
            )
        local_parities.append(next(iter(parities)))

    global_parity = sum(local_parities) % 2
    return CFIStructuralDecode(
        success=True,
        status="decoded-global-twist-parity",
        inferred_regular_base_degree=middle_degree,
        inferred_base_vertex_count=inferred_base_vertex_count,
        vertex_count=int(matrix.shape[0]),
        middle_vertex_count=len(middle_vertices),
        edge_copy_vertex_count=len(edge_copy_vertices),
        edge_pair_count=len(signature_groups),
        vertex_gadget_count=len(gadget_bits),
        local_parities=local_parities,
        global_twist_parity=global_parity,
        ambiguity="none",
        interpretation=(
            "Recovered regular-base CFI global twist parity from degree classes, edge-copy twin pairs, "
            "and vertex-gadget parity profiles."
        ),
    )


def audit_cfi_structural_decoder_record(
    base_id: str,
    shuffle: bool = True,
    seed: int = 9041,
) -> CFIStructuralDecoderRecord:
    description, base = base_graph_by_id(base_id)
    edge = base_edges(base)[0]
    untwisted = cfi_parity_graph_from_base(base, twisted_edge=None)
    twisted = cfi_parity_graph_from_base(base, twisted_edge=edge)
    if shuffle:
        untwisted = permute_adjacency(untwisted, seed + 17 * len(base_id))
        twisted = permute_adjacency(twisted, seed + 101 + 17 * len(base_id))

    untwisted_decode = decode_regular_cfi_twist_parity(untwisted)
    twisted_decode = decode_regular_cfi_twist_parity(twisted)
    recovers = (
        untwisted_decode.success
        and twisted_decode.success
        and untwisted_decode.global_twist_parity == 0
        and twisted_decode.global_twist_parity == 1
    )
    if recovers:
        status = "dequantized-by-structural-cfi-decoder"
        interpretation = (
            f"CFI base {base_id} has global twist parity classically recovered from the unlabeled adjacency matrix "
            "under the explicit regular CFI-gadget promise."
        )
    elif "ambiguous" in untwisted_decode.status or "ambiguous" in twisted_decode.status:
        status = "structural-decoder-ambiguous-proof-debt"
        interpretation = (
            f"CFI base {base_id} has ambiguous edge-copy reconstruction for this decoder; keep it as proof debt, "
            "not positive evidence."
        )
    else:
        status = "structural-decoder-failed-proof-debt"
        interpretation = (
            f"CFI base {base_id} was not decoded by the current structural baseline; this is proof debt, "
            "not a quantum speedup signal."
        )

    return CFIStructuralDecoderRecord(
        base_id=base_id,
        base_description=description,
        base_vertex_count=int(base.shape[0]),
        base_edge_count=len(base_edges(base)),
        cfi_vertex_count=int(untwisted.shape[0]),
        shuffled=shuffle,
        untwisted_decode=untwisted_decode,
        twisted_decode=twisted_decode,
        recovers_global_twist=recovers,
        legal_access_model="unlabeled adjacency matrix with regular CFI gadget-family promise",
        status=status,
        interpretation=interpretation,
    )


def run_cfi_structural_decoder(
    base_ids: list[str] | None = None,
    shuffle: bool = True,
    seed: int = 9041,
) -> CFIStructuralDecoderReport:
    active = base_ids or DEFAULT_BASE_IDS
    records = [audit_cfi_structural_decoder_record(base_id, shuffle=shuffle, seed=seed) for base_id in active]
    metrics = {
        "base_count": len(records),
        "decoded_count": sum(1 for record in records if record.untwisted_decode.success and record.twisted_decode.success),
        "dequantized_count": sum(1 for record in records if record.status == "dequantized-by-structural-cfi-decoder"),
        "ambiguous_count": sum(1 for record in records if record.status == "structural-decoder-ambiguous-proof-debt"),
        "failed_count": sum(1 for record in records if record.status == "structural-decoder-failed-proof-debt"),
        "max_vertex_count": max((record.cfi_vertex_count for record in records), default=0),
    }
    if metrics["dequantized_count"]:
        status = "regular-cfi-family-dequantized-under-gadget-promise"
    elif metrics["ambiguous_count"] or metrics["failed_count"]:
        status = "regular-cfi-structural-decoder-proof-debt"
    else:
        status = "regular-cfi-structural-decoder-incomplete"
    summary = (
        f"Ran structural CFI gadget decoding on {metrics['base_count']} base family row(s). "
        f"{metrics['dequantized_count']} row(s) were dequantized under the regular-gadget promise; "
        f"{metrics['ambiguous_count'] + metrics['failed_count']} remain proof debt."
    )
    falsifiers = []
    if metrics["dequantized_count"]:
        falsifiers.append("Regular CFI gadget-family structure classically reveals global twist parity.")
    if metrics["ambiguous_count"] or metrics["failed_count"]:
        falsifiers.append("Rows not decoded by this baseline remain proof debt, not positive evidence.")
    return CFIStructuralDecoderReport(utc_now(), active, records, metrics, status, summary, falsifiers)


def _json_ready(value: Any) -> Any:
    if is_dataclass(value):
        return _json_ready(asdict(value))
    if isinstance(value, dict):
        return {str(key): _json_ready(item) for key, item in value.items()}
    if isinstance(value, list):
        return [_json_ready(item) for item in value]
    if isinstance(value, tuple):
        return _json_ready(list(value))
    if isinstance(value, np.integer):
        return int(value)
    if isinstance(value, np.bool_):
        return bool(value)
    return value


def _safe_id(value: str) -> str:
    return "".join(ch if ch.isalnum() else "_" for ch in value.upper()).strip("_")


def write_cfi_structural_decoder_negative_results(report: CFIStructuralDecoderReport) -> int:
    written = 0
    for record in report.records:
        if record.status != "dequantized-by-structural-cfi-decoder":
            continue
        upsert_negative_result(
            NegativeResultRecord(
                id=f"CFI-STRUCTURAL-DECODER-DEQUANTIZED-{_safe_id(record.base_id)}",
                source="cfi_structural_decoder.py",
                claim=(
                    f"CFI base {record.base_id} parity twist supplies nonclassical coset-state evidence "
                    "under the CFI gadget promise."
                ),
                reason_invalid=record.interpretation,
                lesson=(
                    "Promised regular CFI gadget rows expose a classical structural parity decoder. "
                    "Do not count them as evidence for a nonabelian speedup unless the access model removes the "
                    "gadget promise or the family escapes this reconstruction."
                ),
                applies_to=["CODE-COSET-COLLECTIVE", "PO-DEQUANTIZATION", "PO-MEASUREMENT"],
                evidence=asdict(record),
            )
        )
        written += 1
    return written


def write_cfi_structural_decoder_report(
    output_path: Path = CFI_STRUCTURAL_DECODER_PATH,
    base_ids: list[str] | None = None,
    shuffle: bool = True,
    seed: int = 9041,
    write_registry: bool = True,
    registry_experiment_id: str = "EXP-COSET-CFI-STRUCTURAL-DECODER",
    registry_candidate_id: str = "CODE-COSET-COLLECTIVE",
    registry_result_id: str = "RESULT-COSET-CFI-STRUCTURAL-DECODER-LATEST",
) -> dict[str, Any]:
    report = run_cfi_structural_decoder(base_ids=base_ids, shuffle=shuffle, seed=seed)
    payload = _json_ready(report)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(json.dumps(payload, indent=2, sort_keys=True))

    if write_registry:
        negative_results_written = write_cfi_structural_decoder_negative_results(report)
        metrics = dict(report.headline_metrics)
        metrics["negative_results_written"] = negative_results_written
        upsert_experiment_result(
            ExperimentResultRecord(
                id=registry_result_id,
                experiment_id=registry_experiment_id,
                candidate_id=registry_candidate_id,
                created_at=report.created_at,
                status=report.status,
                summary=report.summary,
                metrics=metrics,
                falsifiers_triggered=report.falsifiers_triggered,
                artifacts={"cfi_structural_decoder": str(output_path)},
            )
        )
    return payload
