"""Exact marked-cycle certificate for the stable hierarchical Racah trace.

Let W_n=(n-2,2) and xi_n=(n-3,2,1).  On the multiplicity space
Hom_Sn(V_xi, V_xi tensor V_W), the second-stage orbit Hamiltonian is the
simultaneous-conjugacy sum generated by a transposition tau=(1 2) and an
oriented 3-cycle c=(1 2 3).  Its trace is

    n(n-1)(n-2)/n! * sum_g chi_xi(g) chi_xi(g tau) chi_W(g c).

This module evaluates that shifted character correlation exactly.  Character
polynomials are expanded in falling cycle counts.  Products of selected cycles
become finite partial-permutation constraints; equality patterns among at most
eight selected points contribute (n-3)_k/(n)_r.  The stable sum simplifies to

    4 n^3 - 46 n^2 + 149 n - 118.

The equality-pattern argument is literal for n>=8.  An exact S_7 character sum
closes the endpoint.  This proves one power trace only; the remaining quartic
coefficients, root separation, coherent circuit, and decoder remain open.
"""

from __future__ import annotations

import itertools
import json
import math
from collections import defaultdict
from dataclasses import asdict, dataclass
from fractions import Fraction
from functools import lru_cache
from pathlib import Path
from typing import TypeAlias

import sympy as sp

from research_registry import (
    ExperimentResultRecord,
    NegativeResultRecord,
    upsert_experiment_result,
    upsert_negative_result,
    utc_now,
)
from symmetric_character import symmetric_character


COSET_STABLE_TRACE_CERTIFICATE_PATH = Path(
    "research/representation/coset_stable_trace_certificate.json"
)
DEFAULT_EXPERIMENT_ID = "EXP-COSET-STABLE-TRACE-CERTIFICATE"
DEFAULT_CANDIDATE_ID = "CODE-COSET-COLLECTIVE"

CycleMonomial: TypeAlias = tuple[int, ...]
FallingCharacterTerms: TypeAlias = tuple[tuple[CycleMonomial, Fraction], ...]

XI_CHARACTER_TERMS: FallingCharacterTerms = (
    ((1,), Fraction(1)),
    ((1, 1), Fraction(-1)),
    ((1, 1, 1), Fraction(1, 3)),
    ((3,), Fraction(-1)),
)
W_CHARACTER_TERMS: FallingCharacterTerms = (
    ((1, 1), Fraction(1, 2)),
    ((1,), Fraction(-1)),
    ((2,), Fraction(1)),
)


@dataclass(frozen=True)
class StableTraceCertificate:
    created_at: str
    theorem: dict[str, object]
    character_polynomial_certificate: dict[str, object]
    equality_pattern_certificate: dict[str, object]
    stable_symbolic_certificate: dict[str, object]
    endpoint_certificate: dict[str, object]
    headline_metrics: dict[str, int | float]
    claim_gate: dict[str, bool | str]
    status: str
    summary: str
    falsifiers_triggered: list[str]


def _falling(value: sp.Expr, count: int) -> sp.Expr:
    return sp.prod(value - offset for offset in range(count))


def _cycle_layout(
    lengths_by_factor: tuple[CycleMonomial, CycleMonomial, CycleMonomial]
) -> tuple[list[tuple[int, list[int]]], list[int], int]:
    cycles: list[tuple[int, list[int]]] = []
    factors: list[int] = []
    position = 0
    for factor, lengths in enumerate(lengths_by_factor):
        for length in lengths:
            positions = list(range(position, position + length))
            cycles.append((factor, positions))
            factors.extend([factor] * length)
            position += length
    return cycles, factors, position


@lru_cache(maxsize=None)
def equality_pattern_counts(
    first: CycleMonomial,
    second: CycleMonomial,
    third: CycleMonomial,
) -> tuple[tuple[tuple[int, int], int], ...]:
    """Count canonical selected-cycle assignments by generic labels and constraints."""

    cycles, factors, position_count = _cycle_layout((first, second, third))
    multipliers = (
        {},
        {0: 1, 1: 0},
        {0: 1, 1: 2, 2: 0},
    )
    counts: defaultdict[tuple[int, int], int] = defaultdict(int)
    assigned: list[int] = []
    used_by_factor = [set(), set(), set()]

    def visit(position: int, generic_count: int) -> None:
        if position == position_count:
            partial_map: dict[int, int] = {}
            inverse_map: dict[int, int] = {}
            for factor, cycle_positions in cycles:
                multiplier = multipliers[factor]
                values = [assigned[index] for index in cycle_positions]
                for index, value in enumerate(values):
                    domain = multiplier.get(value, value) if value < 3 else value
                    output = values[(index + 1) % len(values)]
                    if domain in partial_map and partial_map[domain] != output:
                        return
                    if output in inverse_map and inverse_map[output] != domain:
                        return
                    partial_map[domain] = output
                    inverse_map[output] = domain
            counts[(generic_count, len(partial_map))] += 1
            return

        factor = factors[position]
        existing_values = [*range(3), *range(3, 3 + generic_count)]
        for value in existing_values:
            if value in used_by_factor[factor]:
                continue
            assigned.append(value)
            used_by_factor[factor].add(value)
            visit(position + 1, generic_count)
            used_by_factor[factor].remove(value)
            assigned.pop()

        new_value = 3 + generic_count
        assigned.append(new_value)
        used_by_factor[factor].add(new_value)
        visit(position + 1, generic_count + 1)
        used_by_factor[factor].remove(new_value)
        assigned.pop()

    visit(0, 0)
    return tuple(sorted(counts.items()))


def selected_cycle_expectation(
    n: sp.Symbol,
    lengths: tuple[CycleMonomial, CycleMonomial, CycleMonomial],
) -> sp.Expr:
    rotation_denominator = math.prod(
        length for monomial in lengths for length in monomial
    )
    return sp.factor(
        sum(
            sp.Rational(pattern_count, rotation_denominator)
            * _falling(n - 3, generic_count)
            / _falling(n, constraint_count)
            for (generic_count, constraint_count), pattern_count in equality_pattern_counts(
                *lengths
            )
        )
    )


@lru_cache(maxsize=1)
def symbolic_shifted_character_trace() -> dict[str, object]:
    n = sp.symbols("n", integer=True, positive=True)
    correlation = sp.Integer(0)
    pattern_type_count = 0
    canonical_pattern_count = 0
    maximum_selected_points = 0
    maximum_constraint_count = 0
    for first, first_coefficient in XI_CHARACTER_TERMS:
        for second, second_coefficient in XI_CHARACTER_TERMS:
            for third, third_coefficient in W_CHARACTER_TERMS:
                lengths = (first, second, third)
                pattern_counts = equality_pattern_counts(*lengths)
                pattern_type_count += 1
                canonical_pattern_count += sum(
                    count for _, count in pattern_counts
                )
                maximum_selected_points = max(
                    maximum_selected_points, sum(map(sum, lengths))
                )
                maximum_constraint_count = max(
                    maximum_constraint_count,
                    max((key[1] for key, _ in pattern_counts), default=0),
                )
                coefficient = (
                    sp.Rational(first_coefficient.numerator, first_coefficient.denominator)
                    * sp.Rational(second_coefficient.numerator, second_coefficient.denominator)
                    * sp.Rational(third_coefficient.numerator, third_coefficient.denominator)
                )
                correlation += coefficient * selected_cycle_expectation(n, lengths)
    correlation = sp.factor(correlation)
    orbit_size = n * (n - 1) * (n - 2)
    trace = sp.factor(orbit_size * correlation)
    expected = 4 * n**3 - 46 * n**2 + 149 * n - 118
    return {
        "shifted_character_correlation": correlation,
        "orbit_size": orbit_size,
        "trace": trace,
        "expected_trace": expected,
        "identity_verified": sp.simplify(trace - expected) == 0,
        "falling_monomial_product_count": pattern_type_count,
        "canonical_equality_pattern_count": canonical_pattern_count,
        "maximum_selected_point_count": maximum_selected_points,
        "maximum_partial_permutation_constraint_count": maximum_constraint_count,
    }


def _compose(left: tuple[int, ...], right: tuple[int, ...]) -> tuple[int, ...]:
    return tuple(left[right[index]] for index in range(len(left)))


def _cycle_type(permutation: tuple[int, ...]) -> tuple[int, ...]:
    visited: set[int] = set()
    lengths: list[int] = []
    for start in range(len(permutation)):
        if start in visited:
            continue
        point = start
        length = 0
        while point not in visited:
            visited.add(point)
            length += 1
            point = permutation[point]
        lengths.append(length)
    return tuple(sorted(lengths, reverse=True))


@lru_cache(maxsize=1)
def exact_s7_endpoint_trace() -> dict[str, int | bool]:
    n = 7
    xi = (4, 2, 1)
    source = (5, 2)
    transposition = list(range(n))
    transposition[0], transposition[1] = 1, 0
    cycle = list(range(n))
    cycle[0], cycle[1], cycle[2] = 1, 2, 0
    correlation_sum = 0
    for permutation in itertools.permutations(range(n)):
        correlation_sum += (
            symmetric_character(xi, _cycle_type(permutation))
            * symmetric_character(
                xi, _cycle_type(_compose(permutation, tuple(transposition)))
            )
            * symmetric_character(
                source, _cycle_type(_compose(permutation, tuple(cycle)))
            )
        )
    orbit_size = n * (n - 1) * (n - 2)
    numerator = orbit_size * correlation_sum
    trace, remainder = divmod(numerator, math.factorial(n))
    formula_value = 4 * n**3 - 46 * n**2 + 149 * n - 118
    return {
        "n": n,
        "group_order": math.factorial(n),
        "orbit_size": orbit_size,
        "integer_character_correlation_sum": correlation_sum,
        "trace": trace,
        "division_remainder": remainder,
        "formula_value": formula_value,
        "formula_verified": remainder == 0 and trace == formula_value,
    }


@lru_cache(maxsize=1)
def build_stable_trace_certificate() -> StableTraceCertificate:
    symbolic = symbolic_shifted_character_trace()
    endpoint = exact_s7_endpoint_trace()
    symbolic_proved = bool(symbolic["identity_verified"])
    endpoint_proved = bool(endpoint["formula_verified"])
    theorem_proved = symbolic_proved and endpoint_proved
    return StableTraceCertificate(
        created_at=utc_now(),
        theorem={
            "source_partition": "W_n=(n-2,2)",
            "intermediate_and_final_partition": "xi_n=(n-3,2,1)",
            "range": "every integer n>=7",
            "statement": (
                "The second-stage support-intersection-two orbit Hamiltonian has trace "
                "4n^3-46n^2+149n-118 on Hom_Sn(V_xi,V_xi tensor V_W)."
            ),
            "proved": theorem_proved,
        },
        character_polynomial_certificate={
            "W_n": "binomial(X1,2)+X2-X1",
            "xi_n": "(X1^3-6*X1^2+8*X1)/3-X3",
            "W_falling_cycle_terms": [
                {"cycle_lengths": term, "coefficient": str(coefficient)}
                for term, coefficient in W_CHARACTER_TERMS
            ],
            "xi_falling_cycle_terms": [
                {"cycle_lengths": term, "coefficient": str(coefficient)}
                for term, coefficient in XI_CHARACTER_TERMS
            ],
            "shifted_correlation": (
                "E_g[chi_xi(g) chi_xi(g tau) chi_W(g c)] for tau=(1 2), c=(1 2 3)"
            ),
        },
        equality_pattern_certificate={
            "method": (
                "Selected falling-factorial cycles impose a partial bijection on g. A canonical equality pattern "
                "with k generic labels and r constraints contributes (n-3)_k/(n)_r, divided by cycle rotations."
            ),
            "falling_monomial_product_count": symbolic[
                "falling_monomial_product_count"
            ],
            "canonical_equality_pattern_count": symbolic[
                "canonical_equality_pattern_count"
            ],
            "maximum_selected_point_count": symbolic[
                "maximum_selected_point_count"
            ],
            "maximum_partial_permutation_constraint_count": symbolic[
                "maximum_partial_permutation_constraint_count"
            ],
            "literal_stable_range": "n>=8",
            "exact_rational_arithmetic": True,
        },
        stable_symbolic_certificate={
            "range": "n>=8",
            "shifted_character_correlation": str(
                symbolic["shifted_character_correlation"]
            ),
            "orbit_size": str(symbolic["orbit_size"]),
            "trace": str(symbolic["trace"]),
            "identity_verified": symbolic_proved,
        },
        endpoint_certificate=endpoint,
        headline_metrics={
            "exact_marked_cycle_trace_theorem_count": int(theorem_proved),
            "stable_symbolic_range_proved_count": int(symbolic_proved),
            "exact_endpoint_verified_count": int(endpoint_proved),
            "minimum_proved_n": 7,
            "falling_monomial_product_count": int(
                symbolic["falling_monomial_product_count"]
            ),
            "canonical_equality_pattern_count": int(
                symbolic["canonical_equality_pattern_count"]
            ),
            "all_n_quartic_theorem_count": 0,
            "all_n_root_separation_theorem_count": 0,
            "uniform_polynomial_racah_circuit_count": 0,
            "hidden_involution_decoder_count": 0,
        },
        claim_gate={
            "exact_marked_cycle_trace_proved": theorem_proved,
            "complete_quartic_formula_proved": False,
            "root_separation_proved": False,
            "uniform_polynomial_racah_circuit_proved": False,
            "hidden_involution_decoder_proved": False,
            "speedup_claim_allowed": False,
            "reason": (
                "The exact first power trace is proved. Three additional power traces, Newton reconstruction, root "
                "separation, complete sector coverage, coherent synthesis, and decoding remain open."
            ),
        },
        status=(
            "exact-stable-racah-trace-proved-full-quartic-open"
            if theorem_proved
            else "stable-racah-trace-certificate-failed"
        ),
        summary=(
            "Proved the cubic stable-channel trace for every n>=7 by exact falling-cycle equality patterns plus "
            "an exact S_7 endpoint character sum; the full quartic and gap theorem remain open."
        ),
        falsifiers_triggered=[
            "The trace identity alone does not determine a multiplicity-four characteristic polynomial.",
            "A characteristic polynomial still needs an all-n normalized root-separation theorem.",
            "One stable channel does not cover every Racah sector required by a decoder.",
            "No coherent circuit or hidden-involution decoder follows from the trace calculation.",
        ],
    )


def write_stable_trace_certificate(
    output_path: Path = COSET_STABLE_TRACE_CERTIFICATE_PATH,
    write_registry: bool = True,
    registry_experiment_id: str = DEFAULT_EXPERIMENT_ID,
    registry_candidate_id: str = DEFAULT_CANDIDATE_ID,
    registry_result_id: str | None = None,
) -> dict:
    payload = asdict(build_stable_trace_certificate())
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(json.dumps(payload, indent=2, sort_keys=True))
    if write_registry:
        upsert_negative_result(
            NegativeResultRecord(
                id="NEG-COSET-EXACT-TRACE-AS-COMPLETE-QUARTIC-GAP",
                source=str(output_path),
                claim=(
                    "The exact first power trace determines the stable quartic spectrum and an efficient Racah transform."
                ),
                reason_invalid=(
                    "A 4x4 characteristic polynomial requires three additional independent coefficients or power "
                    "traces, followed by root separation and circuit synthesis."
                ),
                lesson=(
                    "Apply the same marked-cycle machinery to H^2, H^3, and H^4, use Newton identities, and prove "
                    "normalized root separation before promotion."
                ),
                applies_to=[registry_candidate_id, registry_experiment_id],
                evidence=payload["headline_metrics"],
            )
        )
        result_id = registry_result_id or f"RESULT-{registry_experiment_id}-LATEST"
        upsert_experiment_result(
            ExperimentResultRecord(
                id=result_id,
                experiment_id=registry_experiment_id,
                candidate_id=registry_candidate_id,
                created_at=payload["created_at"],
                status=payload["status"],
                summary=payload["summary"],
                metrics=payload["headline_metrics"],
                falsifiers_triggered=payload["falsifiers_triggered"],
                artifacts={"coset_stable_trace_certificate": str(output_path)},
            )
        )
    return payload
