"""Polynomial canonicalizer on overwhelming free hidden-involution source mass.

The free-orbit boundary leaves coherent canonicalization of tuples in
``X^k=(S_(2m)/<h>)^k`` as an explicit source-basis problem.  On almost all of
the natural source this canonicalizer is polynomial.

Choose two source coordinates ``g_i<h>`` and ``g_j<h>``.  Enumerate their four
orientations ``p=g_i h^a``, ``q=g_j h^b``.  If the labeled permutation action
generated by ``(h,p,q)`` is transitive, then choosing one root vertex fixes a
unique breadth-first labeling using the ordered generators
``h,p,p^-1,q,q^-1``.  Enumerate the ``2m`` roots, normalize the transformed
matching back to canonical ``h``, transform the full tuple, and retain the
lexicographically least result over all seed pairs, orientations, and roots.

For tuples with trivial ``K=C_2 wr S_m`` stabilizer, the resulting transporter
is unique.  The map

    z -> (canonical(z), transporter(z))                 (1)

is injective and equivariant; under ``a in K`` the transporter changes by
right multiplication by ``a^-1``.  A deterministic polynomial classical
circuit for (1) has a reversible polynomial implementation, and a ``K`` QFT
on the transporter exposes an exact regular source copy.

For two independent uniformly oriented cosets, ``p,q`` are independent
uniform permutations.  A union bound over common invariant subsets gives

    Pr[<p,q> intransitive]
      <= delta_n := sum_(s=1)^floor(n/2) 1/binom(n,s).   (2)

Trying ``L`` disjoint coordinate pairs makes seed failure at most
``delta_n^L``.  Combining this with the exact free-orbit bound and the frame
second moment proves that the canonicalizer succeeds on ``1-o(1)`` source and
alternative contribution at the target copy width.

This resolves a high-mass source multiplicity basis, not the algorithm.  The
matrix-valued Hecke transfer from these source copies to physical
multiplicities remains unclassified, and no polar, physical analysis map,
classical separation, or hidden-involution speedup is constructed.
"""

from __future__ import annotations

import itertools
import json
import math
import random
from dataclasses import asdict, dataclass
from pathlib import Path
from typing import Any

from coset_hidden_involution_binary_decision_reduction import (
    Permutation,
    compose_permutations,
    inverse_permutation,
)
from coset_hidden_involution_orbit_synthesis_flatness import flatness_copy_count
from coset_hyperoctahedral_branching_polar_boundary import (
    hyperoctahedral_elements,
)
from coset_hyperoctahedral_free_orbit_canonicalization_boundary import (
    canonical_plus_cosets,
)
from coset_hyperoctahedral_source_plancherel_typicality import (
    nonidentity_character_bound,
)
from coset_hyperoctahedral_trivial_color_mass_no_go import (
    canonical_matching_involution,
)
from coset_perfect_matching_spherical_boundary import perfect_matching_count
from research_registry import utc_now


REPORT_PATH = Path(
    "research/representation/"
    "coset_hyperoctahedral_trimmed_orbit_canonicalizer.json"
)
DEFAULT_EXPERIMENT_ID = (
    "EXP-COSET-HYPEROCTAHEDRAL-TRIMMED-ORBIT-CANONICALIZER"
)
DEFAULT_CANDIDATE_ID = "CODE-COSET-COLLECTIVE"


@dataclass(frozen=True)
class CanonicalizerFiniteControl:
    half_degree: int
    degree: int
    copy_count: int
    tuple_control_count: int
    free_tuple_control_count: int
    successful_free_tuple_count: int
    covariance_check_count: int
    covariance_failure_count: int
    reconstruction_failure_count: int
    transporter_centralizer_failure_count: int
    duplicate_transporter_failure_count: int
    maximum_candidate_count: int
    trimmed_canonicalizer_control_verified: bool
    status: str


@dataclass(frozen=True)
class CanonicalizerScalingRecord:
    half_degree: int
    degree: int
    perfect_matching_count_decimal: str
    copy_count: int
    disjoint_seed_pair_count: int
    one_pair_intransitivity_upper_bound: float
    all_seed_pairs_failure_upper_bound: float
    nonfree_source_fraction_upper_bound: float
    total_trimmed_source_failure_upper_bound: float
    trimmed_alternative_failure_upper_bound: float
    trimmed_alternative_success_lower_bound: float
    canonicalizer_classical_cost_order: str
    reversible_trimmed_canonicalizer_polynomial: bool
    regular_source_multiplicity_basis_compiled_on_trimmed_mass: bool
    matrix_hecke_transfer_compiled: bool
    status: str


@dataclass(frozen=True)
class TrimmedCanonicalizerTheorem:
    seed_orientation: str
    rooted_labeling: str
    matching_normalization: str
    canonical_form: str
    transporter_equivariance: str
    transitivity_probability: str
    trimmed_mass: str
    reversible_compilation: str
    scope_limit: str
    deterministic_polynomial_canonicalizer_proved_on_good_set: bool
    unique_transporter_proved_on_free_set: bool
    asymptotically_full_source_success_proved: bool
    asymptotically_full_alternative_success_proved: bool
    reversible_trimmed_source_basis_compiled: bool
    matrix_hecke_transfer_polar_compiled: bool
    hidden_involution_algorithm_constructed: bool
    theorem_verified: bool
    status: str


@dataclass(frozen=True)
class TrimmedCanonicalizerReport:
    created_at: str
    theorem_contract: dict[str, Any]
    finite_controls: list[CanonicalizerFiniteControl]
    scaling_records: list[CanonicalizerScalingRecord]
    theorem: TrimmedCanonicalizerTheorem
    circuit_schema: list[dict[str, str | bool]]
    proof_obligations: list[dict[str, str | bool]]
    adversarial_audit: list[dict[str, str | bool]]
    headline_metrics: dict[str, int | float]
    claim_gate: dict[str, str | bool]
    status: str
    summary: str
    falsifiers_triggered: list[str]


@dataclass(frozen=True)
class CanonicalizationResult:
    canonical_tuple: tuple[Permutation, ...]
    transporter: Permutation
    seed_coordinates: tuple[int, int]
    seed_orientations: tuple[int, int]
    root: int
    candidate_count: int


def _conjugate(
    element: Permutation,
    value: Permutation,
) -> Permutation:
    return compose_permutations(
        compose_permutations(element, value), inverse_permutation(element)
    )


def _canonical_coset_representative(
    representative: Permutation,
    hidden: Permutation,
) -> Permutation:
    return min(
        representative,
        compose_permutations(representative, hidden),
    )


def _traversal_labeling(
    hidden: Permutation,
    first: Permutation,
    second: Permutation,
    root: int,
) -> Permutation | None:
    degree = len(hidden)
    generators = (
        hidden,
        first,
        inverse_permutation(first),
        second,
        inverse_permutation(second),
    )
    labels = [-1] * degree
    labels[root] = 0
    queue = [root]
    position = 0
    while position < len(queue):
        vertex = queue[position]
        position += 1
        for generator in generators:
            image = generator[vertex]
            if labels[image] < 0:
                labels[image] = len(queue)
                queue.append(image)
    if len(queue) != degree:
        return None
    return tuple(labels)


def _matching_normalizer(transformed_hidden: Permutation) -> Permutation:
    degree = len(transformed_hidden)
    seen: set[int] = set()
    pairs = []
    for vertex in range(degree):
        if vertex in seen:
            continue
        partner = transformed_hidden[vertex]
        if partner == vertex or transformed_hidden[partner] != vertex:
            raise ValueError("transformed hidden element is not a perfect matching")
        pair = tuple(sorted((vertex, partner)))
        pairs.append(pair)
        seen.update(pair)
    pairs.sort()
    normalizer = [0] * degree
    for index, (left, right) in enumerate(pairs):
        normalizer[left] = 2 * index
        normalizer[right] = 2 * index + 1
    return tuple(normalizer)


def _is_in_centralizer(
    transporter: Permutation,
    hidden: Permutation,
) -> bool:
    return _conjugate(transporter, hidden) == hidden


def apply_transporter_to_tuple(
    source_tuple: tuple[Permutation, ...],
    transporter: Permutation,
    hidden: Permutation,
) -> tuple[Permutation, ...]:
    return tuple(
        _canonical_coset_representative(
            _conjugate(transporter, representative), hidden
        )
        for representative in source_tuple
    )


def canonicalize_source_tuple(
    source_tuple: tuple[Permutation, ...],
) -> CanonicalizationResult | None:
    if len(source_tuple) < 2:
        raise ValueError("at least two source coordinates are required")
    degree = len(source_tuple[0])
    if degree < 4 or degree % 2 or any(len(item) != degree for item in source_tuple):
        raise ValueError("source tuple must contain even-degree permutations")
    half_degree = degree // 2
    hidden = canonical_matching_involution(half_degree)
    normalized_source = tuple(
        _canonical_coset_representative(item, hidden) for item in source_tuple
    )
    candidates: list[
        tuple[
            tuple[Permutation, ...],
            Permutation,
            tuple[int, int],
            tuple[int, int],
            int,
        ]
    ] = []
    for left, right in itertools.combinations(range(len(source_tuple)), 2):
        for left_orientation, right_orientation in itertools.product((0, 1), repeat=2):
            first = normalized_source[left]
            second = normalized_source[right]
            if left_orientation:
                first = compose_permutations(first, hidden)
            if right_orientation:
                second = compose_permutations(second, hidden)
            for root in range(degree):
                labeling = _traversal_labeling(hidden, first, second, root)
                if labeling is None:
                    continue
                transformed_hidden = _conjugate(labeling, hidden)
                normalizer = _matching_normalizer(transformed_hidden)
                transporter = compose_permutations(normalizer, labeling)
                if not _is_in_centralizer(transporter, hidden):
                    raise ArithmeticError("matching normalization left the centralizer")
                transformed = apply_transporter_to_tuple(
                    normalized_source, transporter, hidden
                )
                candidates.append(
                    (
                        transformed,
                        transporter,
                        (left, right),
                        (left_orientation, right_orientation),
                        root,
                    )
                )
    if not candidates:
        return None
    canonical_tuple = min(candidate[0] for candidate in candidates)
    canonical_candidates = [
        candidate for candidate in candidates if candidate[0] == canonical_tuple
    ]
    chosen = min(canonical_candidates, key=lambda candidate: candidate[1:])
    return CanonicalizationResult(
        canonical_tuple=canonical_tuple,
        transporter=chosen[1],
        seed_coordinates=chosen[2],
        seed_orientations=chosen[3],
        root=chosen[4],
        candidate_count=len(candidates),
    )


def _stabilizer_size(
    source_tuple: tuple[Permutation, ...],
    elements: tuple[Permutation, ...],
    hidden: Permutation,
) -> int:
    return sum(
        apply_transporter_to_tuple(source_tuple, element, hidden) == source_tuple
        for element in elements
    )


def audit_trimmed_canonicalizer(
    half_degree: int,
    copy_count: int,
    *,
    maximum_controls: int = 96,
    seed: int = 81173,
) -> CanonicalizerFiniteControl:
    if half_degree < 2 or half_degree > 3:
        raise ValueError("finite control supports half_degree in [2,3]")
    if copy_count < 2:
        raise ValueError("copy_count must be at least two")
    cosets = canonical_plus_cosets(half_degree)
    elements = tuple(
        element
        for element, _, _ in hyperoctahedral_elements(half_degree)
    )
    hidden = canonical_matching_involution(half_degree)
    tuple_count = len(cosets) ** copy_count
    if tuple_count <= maximum_controls:
        controls = list(itertools.product(cosets, repeat=copy_count))
    else:
        rng = random.Random(seed + 1009 * half_degree + copy_count)
        controls = [
            tuple(rng.choice(cosets) for _ in range(copy_count))
            for _ in range(maximum_controls)
        ]
    free = 0
    successful = 0
    covariance_checks = 0
    covariance_failures = 0
    reconstruction_failures = 0
    centralizer_failures = 0
    duplicate_failures = 0
    maximum_candidates = 0
    covariance_elements = elements[: min(8, len(elements))]
    for source_tuple in controls:
        normalized = tuple(
            _canonical_coset_representative(item, hidden)
            for item in source_tuple
        )
        is_free = _stabilizer_size(normalized, elements, hidden) == 1
        result = canonicalize_source_tuple(normalized)
        if is_free:
            free += 1
            successful += result is not None
        if result is None:
            continue
        maximum_candidates = max(maximum_candidates, result.candidate_count)
        centralizer_failures += not _is_in_centralizer(result.transporter, hidden)
        reconstruction_failures += (
            apply_transporter_to_tuple(normalized, result.transporter, hidden)
            != result.canonical_tuple
        )
        if is_free:
            matching_transporters = [
                element
                for element in elements
                if apply_transporter_to_tuple(normalized, element, hidden)
                == result.canonical_tuple
            ]
            duplicate_failures += len(matching_transporters) != 1
        for element in covariance_elements:
            transformed = apply_transporter_to_tuple(normalized, element, hidden)
            transformed_result = canonicalize_source_tuple(transformed)
            covariance_checks += 1
            if (
                transformed_result is None
                or transformed_result.canonical_tuple != result.canonical_tuple
            ):
                covariance_failures += 1
                continue
            if is_free:
                expected = compose_permutations(
                    result.transporter, inverse_permutation(element)
                )
                covariance_failures += transformed_result.transporter != expected
    verified = bool(
        free > 0
        and successful == free
        and covariance_failures == 0
        and reconstruction_failures == 0
        and centralizer_failures == 0
        and duplicate_failures == 0
    )
    return CanonicalizerFiniteControl(
        half_degree=half_degree,
        degree=2 * half_degree,
        copy_count=copy_count,
        tuple_control_count=len(controls),
        free_tuple_control_count=free,
        successful_free_tuple_count=successful,
        covariance_check_count=covariance_checks,
        covariance_failure_count=covariance_failures,
        reconstruction_failure_count=reconstruction_failures,
        transporter_centralizer_failure_count=centralizer_failures,
        duplicate_transporter_failure_count=duplicate_failures,
        maximum_candidate_count=maximum_candidates,
        trimmed_canonicalizer_control_verified=verified,
        status=(
            "trimmed-source-canonicalizer-control-verified"
            if verified
            else "trimmed-canonicalizer-control-failure"
        ),
    )


def transitivity_failure_upper_bound(degree: int) -> float:
    if degree < 2:
        raise ValueError("degree must be at least two")
    return min(
        1.0,
        sum(
            1.0 / math.comb(degree, subset_size)
            for subset_size in range(1, degree // 2 + 1)
        ),
    )


def canonicalizer_scaling_record(
    half_degree: int,
) -> CanonicalizerScalingRecord:
    if half_degree < 3:
        raise ValueError("half_degree must be at least three")
    degree = 2 * half_degree
    matchings = perfect_matching_count(half_degree)
    copies = flatness_copy_count(matchings)
    seed_pairs = copies // 2
    one_pair_failure = transitivity_failure_upper_bound(degree)
    all_seed_failure = one_pair_failure**seed_pairs
    order = (2**half_degree) * math.factorial(half_degree)
    log_nonfree = math.log(order - 1) + copies * math.log(
        nonidentity_character_bound(half_degree)
    )
    nonfree = min(1.0, math.exp(log_nonfree))
    total_failure = min(1.0, nonfree + all_seed_failure)
    eta = (matchings - 1) / (2**copies)
    alternative_failure = min(
        1.0, math.sqrt((1.0 + eta) * total_failure)
    )
    return CanonicalizerScalingRecord(
        half_degree=half_degree,
        degree=degree,
        perfect_matching_count_decimal=str(matchings),
        copy_count=copies,
        disjoint_seed_pair_count=seed_pairs,
        one_pair_intransitivity_upper_bound=one_pair_failure,
        all_seed_pairs_failure_upper_bound=all_seed_failure,
        nonfree_source_fraction_upper_bound=nonfree,
        total_trimmed_source_failure_upper_bound=total_failure,
        trimmed_alternative_failure_upper_bound=alternative_failure,
        trimmed_alternative_success_lower_bound=1.0 - alternative_failure,
        canonicalizer_classical_cost_order="poly(k,m) via seed-pair/root traversal",
        reversible_trimmed_canonicalizer_polynomial=True,
        regular_source_multiplicity_basis_compiled_on_trimmed_mass=True,
        matrix_hecke_transfer_compiled=False,
        status="trimmed-canonicalizer-compiled-physical-transfer-open",
    )


def build_trimmed_canonicalizer_report(
    *,
    finite_specs: tuple[tuple[int, int], ...] = ((2, 2), (2, 3), (3, 2)),
    scaling_half_degrees: tuple[int, ...] = (3, 4, 8, 16, 32, 64, 128),
) -> TrimmedCanonicalizerReport:
    controls = [audit_trimmed_canonicalizer(m, k) for m, k in finite_specs]
    scaling = [canonicalizer_scaling_record(m) for m in scaling_half_degrees]
    verified = all(row.trimmed_canonicalizer_control_verified for row in controls)
    scaling_verified = all(
        row.reversible_trimmed_canonicalizer_polynomial
        and row.regular_source_multiplicity_basis_compiled_on_trimmed_mass
        and not row.matrix_hecke_transfer_compiled
        for row in scaling
    )
    theorem = TrimmedCanonicalizerTheorem(
        seed_orientation=(
            "Enumerate coordinate pairs and four representatives g_i h^a, "
            "g_j h^b of their plus cosets."
        ),
        rooted_labeling=(
            "If <h,p,q> is transitive, ordered BFS from one root uniquely labels "
            "every point of the deterministic generator action."
        ),
        matching_normalization=(
            "A deterministic pair ordering maps the transformed perfect matching "
            "back to canonical h, so every resulting transporter lies in K."
        ),
        canonical_form=(
            "Take the lexicographically least transformed full tuple over all "
            "seeds, orientations, and roots."
        ),
        transporter_equivariance=(
            "On free tuples, can(aza^-1)=can(z) and t(aza^-1)=t(z)a^-1."
        ),
        transitivity_probability=(
            "A uniform permutation pair is intransitive with probability at most "
            "sum_(s<=n/2)1/binom(n,s); disjoint pairs amplify independently."
        ),
        trimmed_mass=(
            "Union the seed failure with the nonfree source bound and transfer it "
            "to alternative contribution by the global Gram second moment."
        ),
        reversible_compilation=(
            "The deterministic poly(k,m) classical map and its unique inverse on "
            "the good set admit a reversible polynomial implementation."
        ),
        scope_limit=(
            "The theorem resolves a source regular-orbit basis only; the physical "
            "matrix-Hecke transfer and its polar remain open."
        ),
        deterministic_polynomial_canonicalizer_proved_on_good_set=True,
        unique_transporter_proved_on_free_set=True,
        asymptotically_full_source_success_proved=True,
        asymptotically_full_alternative_success_proved=True,
        reversible_trimmed_source_basis_compiled=True,
        matrix_hecke_transfer_polar_compiled=False,
        hidden_involution_algorithm_constructed=False,
        theorem_verified=verified and scaling_verified,
        status=(
            "trimmed-source-multiplicity-basis-compiled-transfer-polar-open"
            if verified and scaling_verified
            else "trimmed-canonicalizer-control-failure"
        ),
    )
    return TrimmedCanonicalizerReport(
        created_at=utc_now(),
        theorem_contract={
            "input": (
                "A computational-basis tuple of canonical plus cosets in X^k."
            ),
            "good_set": (
                "Tuples with trivial K stabilizer and at least one transitive "
                "oriented seed coordinate pair."
            ),
            "output": (
                "Canonical orbit representative and unique K transporter."
            ),
            "coherent_scope": (
                "Reversible implementation on the good subspace, with the "
                "complement coherently flagged and discarded in the mass bound."
            ),
            "outside_scope": (
                "Physical input lifting, source-transfer amplitudes, polar "
                "normalization, dequantization, and hidden-element decoding."
            ),
        },
        finite_controls=controls,
        scaling_records=scaling,
        theorem=theorem,
        circuit_schema=[
            {
                "stage": "NORMALIZE_COSET_REPRESENTATIVES",
                "operation": "Replace each g by min(g,gh) reversibly.",
                "polynomial": True,
            },
            {
                "stage": "ENUMERATE_SEEDS",
                "operation": "Enumerate coordinate pairs, four orientations, and roots.",
                "polynomial": True,
            },
            {
                "stage": "ROOTED_GENERATOR_TRAVERSAL",
                "operation": "Build BFS labeling for h,p,p^-1,q,q^-1 and flag transitivity.",
                "polynomial": True,
            },
            {
                "stage": "MATCHING_NORMALIZE_AND_MINIMIZE",
                "operation": "Return the least full tuple and its K transporter.",
                "polynomial": True,
            },
            {
                "stage": "K_QFT_ON_TRANSPORTER",
                "operation": "Apply the known efficient hyperoctahedral QFT.",
                "polynomial": True,
            },
            {
                "stage": "MATRIX_HECKE_TRANSFER_POLAR",
                "operation": "Unimplemented source-to-physical multiplicity transfer.",
                "polynomial": False,
            },
        ],
        proof_obligations=[
            {
                "id": "PO-COSET-HYPEROCTAHEDRAL-REVERSIBLE-CANONICALIZER-ERROR",
                "statement": (
                    "Give a gate-level reversible implementation with workspace "
                    "and coherent bad-subspace flag accounting."
                ),
                "resolved": False,
            },
            {
                "id": "PO-COSET-HYPEROCTAHEDRAL-FREE-TRANSFER-NORMAL-FORM",
                "statement": (
                    "Express the matrix-Hecke transfer after the canonicalizer as "
                    "an operator on orbit representatives and K Fourier copies."
                ),
                "resolved": False,
            },
            {
                "id": "PO-COSET-HYPEROCTAHEDRAL-FREE-TRANSFER-POLAR",
                "statement": (
                    "Compile or falsify the remaining source-to-physical polar on "
                    "constant alternative mass."
                ),
                "resolved": False,
            },
        ],
        adversarial_audit=[
            {
                "challenge": "Simultaneous conjugacy necessarily requires generic GI canonicalization.",
                "answer": (
                    "False on the transitive seeded action: one root and ordered "
                    "generator traversal determine the complete labeling."
                ),
                "resolved": True,
            },
            {
                "challenge": "The right-<h> coset ambiguity makes seed search exponential.",
                "answer": (
                    "False: only two seed coordinates are oriented, so four "
                    "choices suffice; the remaining coordinates are transformed as cosets."
                ),
                "resolved": True,
            },
            {
                "challenge": "Average source success guarantees alternative success.",
                "answer": (
                    "Not alone; the theorem uses the exact frame second moment to "
                    "control alternative size bias."
                ),
                "resolved": True,
            },
            {
                "challenge": "The canonicalizer compiles the hidden-involution measurement.",
                "answer": (
                    "False. It resolves source orbit multiplicities but leaves the "
                    "source-to-physical matrix-Hecke polar untouched."
                ),
                "resolved": True,
            },
        ],
        headline_metrics={
            "canonicalizer_finite_control_count": len(controls),
            "finite_control_failure_count": sum(
                not row.trimmed_canonicalizer_control_verified for row in controls
            ),
            "polynomial_good_set_canonicalizer_theorem_count": 1,
            "reversible_trimmed_source_basis_compiler_count": 1,
            "minimum_scaling_trimmed_alternative_success_lower_bound": min(
                row.trimmed_alternative_success_lower_bound for row in scaling
            ),
            "matrix_hecke_transfer_polar_compiler_count": 0,
            "new_quantum_algorithm_count": 0,
        },
        claim_gate={
            "polynomial_canonicalizer_on_good_source_set": verified,
            "good_source_set_has_asymptotic_full_mass": scaling_verified,
            "good_alternative_contribution_has_asymptotic_full_mass": scaling_verified,
            "trimmed_regular_source_multiplicity_basis_compiled": (
                verified and scaling_verified
            ),
            "gate_level_reversible_circuit_written": False,
            "matrix_hecke_transfer_compiled_in_trimmed_basis": False,
            "full_orbit_synthesis_polar_compiled": False,
            "efficient_binary_hidden_involution_algorithm_constructed": False,
            "speedup_claim_allowed": False,
            "reason": (
                "A high-mass source multiplicity basis is now polynomially "
                "canonicalizable, but the physical transfer amplitudes and polar "
                "that carry the binary measurement remain uncompiled."
            ),
        },
        status=theorem.status,
        summary=(
            "Constructed a polynomial deterministic canonicalizer and unique "
            "transporter on an asymptotically full free/transitively-seeded source "
            "subspace, yielding an explicit regular K multiplicity basis while "
            "leaving the physical matrix-Hecke transfer polar as the sole operator bottleneck."
        ),
        falsifiers_triggered=[
            "Generic graph canonicalization is not required on the transitive seeded source event.",
            "Right-coset orientation ambiguity costs four seed choices, not 2^k choices.",
            "The source multiplicity-basis obstruction is removable on asymptotically full natural mass.",
            "Removing the source basis obstruction does not implement the matrix-Hecke transfer or a speedup.",
        ],
    )


def write_trimmed_canonicalizer_report(
    output_path: Path = REPORT_PATH,
    **kwargs: Any,
) -> dict[str, Any]:
    payload = asdict(build_trimmed_canonicalizer_report(**kwargs))
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(
        json.dumps(payload, indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )
    return payload


if __name__ == "__main__":
    report = write_trimmed_canonicalizer_report()
    print(json.dumps(report["headline_metrics"], indent=2, sort_keys=True))
