"""Exact small-instance graph audit for 2-adic subset-sum fiber transport.

Vertices are assignments in a low-bit fiber F_k(t).  Edges are generated by
the explicit local transports certified in dcp_two_adic_fiber_transport:
divisible-coordinate flips, equal-low-residue coordinate swaps, and fixed
small-block pattern substitutions with equal low-bit sums.

The audit measures component fragmentation, child-bit mixing, and the
normalized-adjacency spectral gap on the largest component.  The same graph is
given to a classical BFS baseline.  All calculations are finite and exact up
to the floating-point eigenvalue computation; no finite gap is promoted to a
uniform polynomial-gap theorem.
"""

from __future__ import annotations

import json
import math
import random
from dataclasses import asdict, dataclass
from pathlib import Path
from typing import Sequence

import networkx as nx
import numpy as np
from scipy.sparse import csr_matrix, diags

from dcp_two_adic_fiber_transport import subset_sum, swap_coordinates
from research_registry import (
    ExperimentResultRecord,
    NegativeResultRecord,
    upsert_experiment_result,
    upsert_negative_result,
    utc_now,
)


DCP_FIBER_TRANSPORT_GRAPH_PATH = Path(
    "research/phase_workbench/dcp_fiber_transport_graph.json"
)
DEFAULT_EXPERIMENT_ID = "EXP-DHS-DCP-FIBER-TRANSPORT-GRAPH"
DEFAULT_CANDIDATE_ID = "DHS-GOWERS-SIEVE"


@dataclass(frozen=True)
class FiberGraphRow:
    n_bits: int
    register_count: int
    depth: int
    trial_index: int
    block_size: int
    target_low_residue: int
    supported_low_residue_count: int
    fiber_vertex_count: int
    edge_count: int
    connected_component_count: int
    largest_component_size: int
    largest_component_fraction: float
    cross_child_component_count: int
    cross_child_vertex_fraction: float
    child_zero_count: int
    child_one_count: int
    child_balance: float
    cross_child_edge_count: int
    mean_degree: float
    largest_component_normalized_adjacency_gap: float
    classical_bfs_vertex_visits: int
    classical_bfs_edge_scans: int
    exact_uniform_legal_low_residue_source: bool
    polynomial_gap_proved: bool
    polynomial_start_state_preparation_proved: bool


@dataclass(frozen=True)
class GraphInvariantRecord:
    invariant_id: str
    preserved_by_coordinate_flips: bool
    preserved_by_coordinate_swaps: bool
    preserved_by_block_substitutions: bool
    obstruction_scope: str


@dataclass(frozen=True)
class FiberTransportGraphReport:
    created_at: str
    graph_contract: dict[str, str]
    rows: list[FiberGraphRow]
    invariants: list[GraphInvariantRecord]
    headline_metrics: dict[str, int | float]
    claim_gate: dict[str, bool | str]
    status: str
    summary: str
    falsifiers_triggered: list[str]


def enumerate_low_fibers(
    labels: Sequence[int],
    depth: int,
) -> dict[int, list[int]]:
    modulus = 1 << depth
    fibers: dict[int, list[int]] = {}
    for assignment in range(1 << len(labels)):
        residue = subset_sum(labels, assignment) % modulus
        fibers.setdefault(residue, []).append(assignment)
    return fibers


def _block_replacements(
    labels: Sequence[int],
    depth: int,
    block_size: int,
) -> list[tuple[int, int, dict[int, tuple[int, ...]]]]:
    modulus = 1 << depth
    replacements: list[tuple[int, int, dict[int, tuple[int, ...]]]] = []
    for start in range(0, len(labels), block_size):
        block = labels[start : start + block_size]
        width = len(block)
        by_residue: dict[int, list[int]] = {}
        for pattern in range(1 << width):
            residue = subset_sum(block, pattern) % modulus
            by_residue.setdefault(residue, []).append(pattern)
        replacement_map: dict[int, tuple[int, ...]] = {}
        for patterns in by_residue.values():
            if len(patterns) < 2:
                continue
            for pattern in patterns:
                replacement_map[pattern] = tuple(other for other in patterns if other != pattern)
        replacements.append((start, width, replacement_map))
    return replacements


def build_fiber_transport_graph(
    labels: Sequence[int],
    depth: int,
    target_low_residue: int,
    block_size: int = 3,
) -> nx.Graph:
    fibers = enumerate_low_fibers(labels, depth)
    vertices = fibers.get(target_low_residue, [])
    vertex_set = set(vertices)
    graph = nx.Graph()
    graph.add_nodes_from(vertices)
    modulus = 1 << depth

    divisible_coordinates = [
        index for index, label in enumerate(labels) if label % modulus == 0
    ]
    swappable_pairs = [
        (left, right)
        for left in range(len(labels))
        for right in range(left + 1, len(labels))
        if (labels[left] - labels[right]) % modulus == 0
    ]
    block_replacements = _block_replacements(labels, depth, block_size)

    for assignment in vertices:
        for coordinate in divisible_coordinates:
            neighbor = assignment ^ (1 << coordinate)
            if neighbor in vertex_set:
                graph.add_edge(assignment, neighbor, transport="coordinate-flip")
        for left, right in swappable_pairs:
            neighbor = swap_coordinates(assignment, left, right)
            if neighbor != assignment and neighbor in vertex_set:
                graph.add_edge(assignment, neighbor, transport="coordinate-swap")
        for start, width, replacement_map in block_replacements:
            mask = (1 << width) - 1
            pattern = (assignment >> start) & mask
            for replacement in replacement_map.get(pattern, ()):
                neighbor = (assignment & ~(mask << start)) | (replacement << start)
                if neighbor in vertex_set:
                    graph.add_edge(assignment, neighbor, transport="block-substitution")
    return graph


def _normalized_adjacency_gap(graph: nx.Graph, component: set[int]) -> float:
    if len(component) < 2:
        return 0.0
    nodes = sorted(component)
    index = {node: position for position, node in enumerate(nodes)}
    rows: list[int] = []
    cols: list[int] = []
    for left, right in graph.subgraph(component).edges():
        i = index[left]
        j = index[right]
        rows.extend((i, j))
        cols.extend((j, i))
    if not rows:
        return 0.0
    adjacency = csr_matrix(
        (np.ones(len(rows), dtype=float), (rows, cols)),
        shape=(len(nodes), len(nodes)),
    )
    degrees = np.asarray(adjacency.sum(axis=1)).ravel()
    if np.any(degrees == 0):
        return 0.0
    inverse_sqrt = diags(1.0 / np.sqrt(degrees))
    normalized = inverse_sqrt @ adjacency @ inverse_sqrt
    eigenvalues = np.linalg.eigvalsh(normalized.toarray())
    stationary_index = int(np.argmax(eigenvalues))
    nontrivial = np.delete(eigenvalues, stationary_index)
    second_absolute = float(np.max(np.abs(nontrivial))) if nontrivial.size else 1.0
    return max(0.0, min(1.0, 1.0 - second_absolute))


def analyze_fiber_graph(
    n_bits: int,
    register_offset: int,
    depth: int,
    trial_index: int,
    seed: int,
    block_size: int = 3,
) -> FiberGraphRow:
    if not 1 <= depth < n_bits:
        raise ValueError("depth must satisfy 1 <= depth < n_bits")
    register_count = n_bits + register_offset
    if register_count > 18:
        raise ValueError("exact graph enumeration is capped at 18 assignment bits")
    rng = random.Random(seed)
    labels = [rng.randrange(1 << n_bits) for _ in range(register_count)]
    fibers = enumerate_low_fibers(labels, depth)
    supported = sorted(fibers)
    target = supported[rng.randrange(len(supported))]
    graph = build_fiber_transport_graph(labels, depth, target, block_size=block_size)
    components = [set(component) for component in nx.connected_components(graph)]
    largest = max(components, key=len) if components else set()

    child = {
        assignment: (subset_sum(labels, assignment) >> depth) & 1
        for assignment in graph.nodes
    }
    cross_components = [
        component for component in components if {child[node] for node in component} == {0, 1}
    ]
    cross_vertices = sum(len(component) for component in cross_components)
    cross_edges = sum(child[left] != child[right] for left, right in graph.edges())
    child_zero = sum(value == 0 for value in child.values())
    child_one = sum(value == 1 for value in child.values())
    vertex_count = graph.number_of_nodes()
    edge_count = graph.number_of_edges()
    return FiberGraphRow(
        n_bits=n_bits,
        register_count=register_count,
        depth=depth,
        trial_index=trial_index,
        block_size=block_size,
        target_low_residue=target,
        supported_low_residue_count=len(supported),
        fiber_vertex_count=vertex_count,
        edge_count=edge_count,
        connected_component_count=len(components),
        largest_component_size=len(largest),
        largest_component_fraction=len(largest) / vertex_count if vertex_count else 0.0,
        cross_child_component_count=len(cross_components),
        cross_child_vertex_fraction=cross_vertices / vertex_count if vertex_count else 0.0,
        child_zero_count=child_zero,
        child_one_count=child_one,
        child_balance=(2.0 * min(child_zero, child_one) / vertex_count if vertex_count else 0.0),
        cross_child_edge_count=cross_edges,
        mean_degree=(2.0 * edge_count / vertex_count if vertex_count else 0.0),
        largest_component_normalized_adjacency_gap=_normalized_adjacency_gap(graph, largest),
        classical_bfs_vertex_visits=vertex_count,
        classical_bfs_edge_scans=2 * edge_count,
        exact_uniform_legal_low_residue_source=True,
        polynomial_gap_proved=False,
        polynomial_start_state_preparation_proved=depth <= math.ceil(math.log2(n_bits)),
    )


def _default_depths(n_bits: int) -> tuple[int, ...]:
    values = {
        max(1, math.ceil(math.log2(n_bits))),
        max(1, n_bits // 2),
        max(1, min(n_bits - 1, math.ceil(2 * math.log2(n_bits)))),
    }
    return tuple(sorted(value for value in values if value < n_bits))


def build_graph_invariants() -> list[GraphInvariantRecord]:
    return [
        GraphInvariantRecord(
            invariant_id="HAMMING-WEIGHT",
            preserved_by_coordinate_flips=False,
            preserved_by_coordinate_swaps=True,
            preserved_by_block_substitutions=False,
            obstruction_scope="Only obstructs swap-only graphs; flips and unequal-weight block substitutions break it.",
        ),
        GraphInvariantRecord(
            invariant_id="ASSIGNMENT-PARITY",
            preserved_by_coordinate_flips=False,
            preserved_by_coordinate_swaps=True,
            preserved_by_block_substitutions=False,
            obstruction_scope="Only obstructs move sets whose block substitutions preserve pattern parity.",
        ),
        GraphInvariantRecord(
            invariant_id="LOW-SUBSET-SUM-RESIDUE",
            preserved_by_coordinate_flips=True,
            preserved_by_coordinate_swaps=True,
            preserved_by_block_substitutions=True,
            obstruction_scope="Defines the intended fiber rather than fragmenting it further.",
        ),
    ]


def run_fiber_transport_graph_audit(
    n_values: Sequence[int] = (8, 10, 12, 14),
    register_offset: int = 2,
    trials_per_depth: int = 2,
    seed: int = 0,
    block_size: int = 3,
) -> FiberTransportGraphReport:
    rows = [
        analyze_fiber_graph(
            n_bits,
            register_offset,
            depth,
            trial,
            seed + 1_000_003 * n_index + 10_007 * depth + trial,
            block_size=block_size,
        )
        for n_index, n_bits in enumerate(n_values)
        for depth in _default_depths(n_bits)
        for trial in range(trials_per_depth)
    ]
    linear_rows = [row for row in rows if row.depth >= row.n_bits // 2]
    metrics: dict[str, int | float] = {
        "row_count": len(rows),
        "linear_depth_row_count": len(linear_rows),
        "zero_cross_child_linear_depth_row_count": sum(
            row.cross_child_vertex_fraction == 0.0 for row in linear_rows
        ),
        "fragmented_linear_depth_row_count": sum(
            row.connected_component_count > 1 for row in linear_rows
        ),
        "minimum_linear_depth_largest_component_fraction": min(
            (row.largest_component_fraction for row in linear_rows), default=0.0
        ),
        "minimum_linear_depth_cross_child_vertex_fraction": min(
            (row.cross_child_vertex_fraction for row in linear_rows), default=0.0
        ),
        "minimum_positive_linear_depth_spectral_gap": min(
            (
                row.largest_component_normalized_adjacency_gap
                for row in linear_rows
                if row.largest_component_normalized_adjacency_gap > 0.0
            ),
            default=0.0,
        ),
        "maximum_linear_depth_classical_bfs_vertex_visits": max(
            (row.classical_bfs_vertex_visits for row in linear_rows), default=0
        ),
        "uniform_polynomial_spectral_gap_theorem_count": 0,
        "linear_depth_polynomial_start_state_preparation_count": 0,
        "proved_polynomial_fiber_transport_walk_count": 0,
        "proved_classical_separation_count": 0,
    }
    return FiberTransportGraphReport(
        created_at=utc_now(),
        graph_contract={
            "vertices": "all assignments in one uniformly selected supported low residue F_k(t)",
            "edges": "divisible-coordinate flips, equal-low-residue swaps, and contiguous small-block equal-residue substitutions",
            "child_label": "bit k of the full subset sum",
            "quantum_signal": "large cross-child component plus uniform inverse-polynomial spectral gap and efficient start/reflection circuits",
            "classical_baseline": "exact BFS on the identical graph; finite traversal cost is charged explicitly",
            "source_scope": "uniform supported low residue for each random A, not planted-witness sampling",
        },
        rows=rows,
        invariants=build_graph_invariants(),
        headline_metrics=metrics,
        claim_gate={
            "finite_exact_graphs_computed": True,
            "uniform_legal_low_residue_source_used": True,
            "classical_same_graph_baseline_charged": True,
            "uniform_polynomial_spectral_gap_proved": False,
            "linear_depth_start_state_preparation_proved": False,
            "polynomial_fiber_transport_walk_constructed": False,
            "classical_separation_proved": False,
            "speedup_claim_allowed": False,
            "reason": (
                "Finite graph connectivity and spectral gaps are mechanism probes only. Linear-depth state preparation, "
                "uniform conductance, coherent updates, verified relation output, and a classical separation remain open."
            ),
        },
        status="finite-fiber-graphs-audited-no-polynomial-walk-theorem",
        summary=(
            f"Audited {len(rows)} exact low-fiber transport graphs, including {len(linear_rows)} linear-depth rows. "
            f"Fragmented linear rows={metrics['fragmented_linear_depth_row_count']}; zero cross-child rows="
            f"{metrics['zero_cross_child_linear_depth_row_count']}; polynomial walk theorems=0."
        ),
        falsifiers_triggered=[
            "Connectivity of a finite fiber graph is not a polynomial spectral-gap theorem.",
            "A positive finite gap is unusable without polynomial preparation of the linear-depth fiber state.",
            "Classical BFS accesses exactly the same local move graph and must be charged before claiming a quantum walk separation.",
            "Uniform supported low residues avoid planted-witness multiplicity bias but do not prove full source composition.",
            "Component fragmentation or zero cross-child mass kills the tested local move set, not implicit global transports.",
        ],
    )


def write_fiber_transport_graph_audit(
    path: Path = DCP_FIBER_TRANSPORT_GRAPH_PATH,
    n_values: Sequence[int] = (8, 10, 12, 14),
    register_offset: int = 2,
    trials_per_depth: int = 2,
    seed: int = 0,
    block_size: int = 3,
    write_registry: bool = True,
    registry_experiment_id: str = DEFAULT_EXPERIMENT_ID,
    registry_candidate_id: str = DEFAULT_CANDIDATE_ID,
    registry_result_id: str | None = None,
) -> dict:
    payload = asdict(
        run_fiber_transport_graph_audit(
            n_values=n_values,
            register_offset=register_offset,
            trials_per_depth=trials_per_depth,
            seed=seed,
            block_size=block_size,
        )
    )
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, indent=2, sort_keys=True))
    if write_registry:
        negatives = (
            (
                "NEG-DCP-FINITE-FIBER-GRAPH-GAP-AS-POLYNOMIAL-WALK",
                "A positive spectral gap on exact small subset-sum fiber graphs proves a polynomial quantum relation walk.",
                "No all-n gap, linear-depth start-state preparation, coherent reflection cost, or verified output theorem follows from finite eigenspectra.",
            ),
            (
                "NEG-DCP-FIBER-WALK-WITHOUT-CLASSICAL-GRAPH-BASELINE",
                "Local fiber connectivity is inherently quantum evidence.",
                "Classical BFS traverses the identical finite graph; a quantum claim needs an asymptotic oracle/runtime separation after charging graph access."
            ),
            (
                "NEG-DCP-PLANTED-FIBER-GRAPH-SOURCE-SUBSTITUTION",
                "A planted witness is an acceptable source for fiber transport graph evidence.",
                "Planting size-biases fibers; this audit instead samples uniformly from supported low residues and still withholds full-source promotion."
            ),
        )
        for negative_id, claim, reason in negatives:
            upsert_negative_result(
                NegativeResultRecord(
                    id=negative_id,
                    source=str(path),
                    claim=claim,
                    reason_invalid=reason,
                    lesson=(
                        "Demand a uniform spectral theorem, polynomial state preparation and updates, verified relation "
                        "output, exact source coverage, and classical baselines before promoting a fiber walk."
                    ),
                    applies_to=[registry_candidate_id, registry_experiment_id],
                    evidence=payload["headline_metrics"],
                )
            )
        result_id = registry_result_id or f"RESULT-{registry_experiment_id}-DCP-FIBER-TRANSPORT-GRAPH"
        upsert_experiment_result(
            ExperimentResultRecord(
                id=result_id,
                experiment_id=registry_experiment_id,
                candidate_id=registry_candidate_id,
                created_at=payload["created_at"],
                status=payload["status"],
                summary=payload["summary"],
                metrics=payload["headline_metrics"],
                falsifiers_triggered=payload["falsifiers_triggered"],
                artifacts={"dcp_fiber_transport_graph": str(path)},
            )
        )
    return payload
