"""Conditioned-fiber tail theorem for fixed-order subset-sum signals.

For fixed order k, let B_k be the nonnegative contribution of source-nongeneric
ordered assignment tuples to the k-th factorial representation moment.  The
all-fixed-order transfer theorem gives ``E[B_k] <= poly_k(n) rho_k^n`` with
``rho_k <= 1-2^-k``.

For any exposed low-bit sigma-field F, define ``Z_k=E[B_k | F]``.  The tower
property preserves the same mean.  Markov's inequality then gives, for every
fixed threshold degree d,

  Pr_F[Z_k >= n^-d] <= poly_(k,d)(n) (1-2^-k)^n.

Thus no inverse-polynomial source mass of low-bit fibers has an
inverse-polynomial generic fixed-order bad-tuple signal.  This does not control
moment order growing with n, signed observables not dominated by B_k, or
reduced-basis geometry.
"""

from __future__ import annotations

import json
from dataclasses import asdict, dataclass
from pathlib import Path
from typing import Sequence

from dcp_subset_sum_fixed_order_moment_theorem import fixed_order_moment_certificate
from research_registry import (
    ExperimentResultRecord,
    NegativeResultRecord,
    upsert_experiment_result,
    upsert_negative_result,
    utc_now,
)


DCP_SUBSET_SUM_CONDITIONED_TAIL_PATH = Path(
    "research/classical_baselines/dcp_subset_sum_conditioned_tail_theorem.json"
)
DEFAULT_EXPERIMENT_ID = "EXP-DHS-DCP-SUBSET-SUM-CONDITIONED-FIXED-MOMENT-TAIL"
DEFAULT_CANDIDATE_ID = "DHS-GOWERS-SIEVE"


@dataclass(frozen=True)
class ConditionedTailCertificate:
    moment_order: int
    inverse_polynomial_threshold_degree: int
    bad_growth_ratio_upper_bound_numerator: int
    bad_growth_ratio_upper_bound_denominator: int
    bad_growth_ratio_upper_bound: float
    bad_tuple_contribution_nonnegative: bool
    tower_property_applies_to_arbitrary_low_bit_sigma_field: bool
    markov_tail_bound_proved: bool
    inverse_polynomial_mass_and_signal_ruled_out: bool
    tail_bound: str
    proof: str
    limitations: list[str]


@dataclass(frozen=True)
class DCPSubsetSumConditionedTailReport:
    created_at: str
    theorem_contract: dict[str, str]
    certificates: list[ConditionedTailCertificate]
    headline_metrics: dict[str, int | float]
    claim_gate: dict[str, bool | str]
    status: str
    summary: str
    falsifiers_triggered: list[str]


def conditioned_tail_certificate(
    moment_order: int,
    threshold_degree: int,
) -> ConditionedTailCertificate:
    if threshold_degree < 0:
        raise ValueError("threshold_degree must be nonnegative")
    source = fixed_order_moment_certificate(moment_order)
    return ConditionedTailCertificate(
        moment_order=moment_order,
        inverse_polynomial_threshold_degree=threshold_degree,
        bad_growth_ratio_upper_bound_numerator=source.bad_growth_ratio_upper_bound_numerator,
        bad_growth_ratio_upper_bound_denominator=source.bad_growth_ratio_upper_bound_denominator,
        bad_growth_ratio_upper_bound=source.bad_growth_ratio_upper_bound,
        bad_tuple_contribution_nonnegative=True,
        tower_property_applies_to_arbitrary_low_bit_sigma_field=True,
        markov_tail_bound_proved=True,
        inverse_polynomial_mass_and_signal_ruled_out=True,
        tail_bound=(
            f"Pr[E[B_{moment_order}|F] >= n^-{threshold_degree}] <= "
            f"poly_({moment_order},{threshold_degree})(n)*(1-2^-{moment_order})^n"
        ),
        proof=(
            "B_k is a sum of indicators over source-nongeneric distinct assignment tuples and is nonnegative. "
            "The fixed-order transfer theorem bounds E[B_k]. For every sigma-field F generated by exposed low data, "
            "E[E[B_k|F]]=E[B_k]. Markov at threshold n^-d multiplies the mean bound by n^d, which remains "
            "exponentially small for fixed k and d."
        ),
        limitations=[
            "Moment order and threshold degree are fixed while n grows.",
            "The theorem controls the nonnegative bad-tuple contribution, not every signed statistic.",
            "It does not bound explicit reduced-basis events or nonlinear decoder geometry.",
            "It does not apply uniformly when k grows with n.",
            "It supplies no decoder or computational lower bound.",
        ],
    )


def run_conditioned_tail_theorem(
    moment_orders: Sequence[int] = tuple(range(2, 13)),
    threshold_degrees: Sequence[int] = (1, 2, 4),
) -> DCPSubsetSumConditionedTailReport:
    certificates = [
        conditioned_tail_certificate(order, degree)
        for order in moment_orders
        for degree in threshold_degrees
    ]
    proved = sum(item.inverse_polynomial_mass_and_signal_ruled_out for item in certificates)
    metrics: dict[str, int | float] = {
        "certificate_count": len(certificates),
        "proved_conditioned_tail_bound_count": proved,
        "general_fixed_order_conditioned_tail_theorem_count": int(
            bool(certificates) and proved == len(certificates)
        ),
        "largest_instantiated_fixed_order": max((item.moment_order for item in certificates), default=0),
        "largest_instantiated_threshold_degree": max(
            (item.inverse_polynomial_threshold_degree for item in certificates), default=0
        ),
        "proved_growing_order_conditioned_tail_count": 0,
        "proved_signed_statistic_tail_count": 0,
        "proved_reduced_basis_event_tail_count": 0,
        "polynomial_witness_decoder_count": 0,
    }
    return DCPSubsetSumConditionedTailReport(
        created_at=utc_now(),
        theorem_contract={
            "random_variable": "B_k=sum of exact-hit indicators over source-nongeneric ordered distinct k-tuples",
            "conditioning": "any sigma-field generated by exposed low bits of labels and target",
            "signal_threshold": "n^-d for fixed d",
            "source_regime": "m=n+c for fixed c and fixed k",
            "conclusion": "inverse-polynomial conditional bad signal occurs on exponentially small source mass",
        },
        certificates=certificates,
        headline_metrics=metrics,
        claim_gate={
            "all_fixed_order_bad_tuple_conditioned_tails_closed": True,
            "growing_order_conditioned_tails_closed": False,
            "arbitrary_signed_statistics_closed": False,
            "reduced_basis_geometry_closed": False,
            "polynomial_witness_decoder_constructed": False,
            "speedup_claim_allowed": False,
            "reason": (
                "No inverse-polynomial mass of low fibers has inverse-polynomial conditional signal from a fixed-order "
                "bad-tuple moment. A surviving route must use growing order, a signed/non-moment observable, or explicit "
                "basis geometry with a decoder implication."
            ),
        },
        status="fixed-order-conditioned-bad-tuple-tails-asymptotically-obstructed",
        summary=(
            f"Certified {proved}/{len(certificates)} conditioned Markov bounds through fixed order "
            f"{metrics['largest_instantiated_fixed_order']} and threshold degree "
            f"{metrics['largest_instantiated_threshold_degree']}. Growing order, signed statistics, and reduced-basis "
            "events remain open."
        ),
        falsifiers_triggered=[
            "Selected low fibers with large finite fixed-order energy do not establish inverse-polynomial source mass.",
            "Any fixed-order bad-tuple signal above an inverse-polynomial threshold occurs on exponentially small mass.",
            "Escalating the fixed threshold polynomial degree does not evade exponential contraction.",
            "The theorem cannot be cited against signed observables or explicit reduced-basis events without domination.",
        ],
    )


def write_conditioned_tail_theorem(
    path: Path = DCP_SUBSET_SUM_CONDITIONED_TAIL_PATH,
    moment_orders: Sequence[int] = tuple(range(2, 13)),
    threshold_degrees: Sequence[int] = (1, 2, 4),
    write_registry: bool = True,
    registry_experiment_id: str = DEFAULT_EXPERIMENT_ID,
    registry_candidate_id: str = DEFAULT_CANDIDATE_ID,
    registry_result_id: str | None = None,
) -> dict:
    report = run_conditioned_tail_theorem(
        moment_orders=moment_orders,
        threshold_degrees=threshold_degrees,
    )
    payload = asdict(report)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, indent=2, sort_keys=True))
    if write_registry:
        upsert_negative_result(
            NegativeResultRecord(
                id="NEG-DCP-SUBSET-SUM-FIXED-MOMENT-CONDITIONED-TAIL",
                source=str(path),
                claim=(
                    "An inverse-polynomial mass of logarithmic low-bit fibers has inverse-polynomial conditional signal "
                    "from a source-nongeneric fixed-order tuple moment."
                ),
                reason_invalid=(
                    "Tower plus Markov transfers the all-fixed-order exponentially decaying bad-tuple mean into an "
                    "exponentially small bound on fibers above every inverse-polynomial threshold."
                ),
                lesson=(
                    "Do not select energetic finite fibers. Prove growing-order resource control, a signed observable not "
                    "dominated by bad tuples, or an explicit reduced-basis event with source coverage and decoding."
                ),
                applies_to=[registry_candidate_id, registry_experiment_id],
                evidence=payload["headline_metrics"],
            )
        )
        result_id = registry_result_id or f"RESULT-{registry_experiment_id}-CONDITIONED-FIXED-MOMENT-TAIL"
        upsert_experiment_result(
            ExperimentResultRecord(
                id=result_id,
                experiment_id=registry_experiment_id,
                candidate_id=registry_candidate_id,
                created_at=payload["created_at"],
                status=payload["status"],
                summary=payload["summary"],
                metrics=payload["headline_metrics"],
                falsifiers_triggered=payload["falsifiers_triggered"],
                artifacts={"dcp_subset_sum_conditioned_tail_theorem": str(path)},
            )
        )
    return payload
