"""Exact target-character topology generated by the sibling split relations.

For a binary split pattern, let the ordered products on the zero and one
positions both equal the identity.  Eliminating the last variable of each
nonempty color turns the full ordered product into an orientable quadratic
word.  If both colors occur and the one positions form ``r`` cyclic runs, its
genus is exactly ``r-1``.  Consecutive positions of one color can first be
collapsed to block products by Nielsen transformations; the resulting
alternating polygon has ``r`` blocks of each color and genus ``r-1``.

Consequently, for independent uniform assignments subject only to the split
relations and any irreducible character of dimension ``d``, Schur
orthogonality gives

    E[chi(full_product)/d | split] = d**(-2(r-1)).

This theorem does not survive arbitrary additional support relations without
more work: those relations condition the surface variables and can change the
boundary distribution.  It is therefore a search invariant and a sharp
split-only baseline, not a component-moment theorem.
"""

from __future__ import annotations

import itertools
import json
from dataclasses import asdict, dataclass
from fractions import Fraction
from pathlib import Path
from typing import Any, Iterable

from research_registry import utc_now
from self_dual_wreath_marked_relation_topology import (
    SignedWord,
    _evaluate_signed_word,
    _relations_from_bits,
    _substitute_generator,
    free_reduce,
    orientable_quadratic_genus,
    tietze_reduce_presentation,
)


REPORT_PATH = Path(
    "research/representation/self_dual_wreath_mixed_split_target_genus.json"
)
DEFAULT_EXPERIMENT_ID = "EXP-CODE-SELF-DUAL-WREATH-MIXED-SPLIT-TARGET-GENUS"
DEFAULT_CANDIDATE_ID = "CODE-COSET-COLLECTIVE"


@dataclass(frozen=True)
class SplitTargetGenusControl:
    split_bits: tuple[int, ...]
    cyclic_one_run_count: int
    predicted_orientable_genus: int
    residual_target_word: SignedWord
    classified_orientable_genus: int
    target_freely_trivial: bool
    exact_genus_verified: bool
    normalized_character_factor: str
    status: str


@dataclass(frozen=True)
class SplitTargetGenusScalingRecord:
    position_count: int
    checked_split_pattern_count: int
    maximum_predicted_genus: int
    exact_genus_failure_count: int
    status: str


@dataclass(frozen=True)
class MixedSplitTargetGenusReport:
    created_at: str
    theorem_contract: dict[str, Any]
    representative_controls: list[SplitTargetGenusControl]
    scaling_records: list[SplitTargetGenusScalingRecord]
    proof_obligations: list[dict[str, str | bool]]
    adversarial_audit: list[dict[str, str | bool]]
    headline_metrics: dict[str, int | float]
    claim_gate: dict[str, str | bool]
    status: str
    summary: str
    falsifiers_triggered: list[str]


def _validate_split_bits(bits: tuple[int, ...]) -> None:
    if not bits or any(bit not in (0, 1) for bit in bits):
        raise ValueError("split bits must be a nonempty binary tuple")


def cyclic_one_run_count(bits: tuple[int, ...]) -> int:
    """Count cyclic runs of ones, returning zero for constant patterns."""

    _validate_split_bits(bits)
    if len(set(bits)) == 1:
        return 0
    transitions = sum(
        bits[index] != bits[(index + 1) % len(bits)]
        for index in range(len(bits))
    )
    return transitions // 2


def split_target_orientable_genus(bits: tuple[int, ...]) -> int:
    """Return the exact split-only boundary genus."""

    runs = cyclic_one_run_count(bits)
    return max(0, runs - 1)


def split_target_orientable_genus_for_pattern(pattern: str) -> int:
    if not pattern or any(token not in "ABEF" for token in pattern):
        raise ValueError("pattern must be a nonempty A/B/E/F word")
    return split_target_orientable_genus(
        tuple(1 if token == "B" else 0 for token in pattern)
    )


def _transport_full_product(
    position_count: int,
    elimination_steps: Iterable[Any],
) -> SignedWord:
    word: SignedWord = tuple(range(1, position_count + 1))
    for step in elimination_steps:
        word = _substitute_generator(
            word,
            step.eliminated_generator,
            step.replacement_word,
        )
    return free_reduce(word)


def audit_split_target_genus(bits: tuple[int, ...]) -> SplitTargetGenusControl:
    _validate_split_bits(bits)
    reduction = tietze_reduce_presentation(
        len(bits),
        _relations_from_bits(bits),
    )
    target = _transport_full_product(len(bits), reduction.elimination_steps)
    predicted = split_target_orientable_genus(bits)
    classified = orientable_quadratic_genus(target) if target else 0
    if classified is None:
        classified = -1
    exact = classified == predicted
    return SplitTargetGenusControl(
        split_bits=bits,
        cyclic_one_run_count=cyclic_one_run_count(bits),
        predicted_orientable_genus=predicted,
        residual_target_word=target,
        classified_orientable_genus=classified,
        target_freely_trivial=not target,
        exact_genus_verified=exact,
        normalized_character_factor=(
            "1" if predicted == 0 else f"d_nu^-{2 * predicted}"
        ),
        status=(
            "exact-split-target-genus-verified"
            if exact
            else "split-target-genus-control-failure"
        ),
    )


def split_only_normalized_character_factor(
    bits: tuple[int, ...],
    representation_dimension: int,
) -> Fraction:
    if representation_dimension <= 0:
        raise ValueError("representation dimension must be positive")
    genus = split_target_orientable_genus(bits)
    return Fraction(1, representation_dimension ** (2 * genus))


def symmetric_group_standard_character_average(
    bits: tuple[int, ...],
    degree: int = 3,
) -> Fraction:
    """Brute-force the split-only normalized standard-character average."""

    _validate_split_bits(bits)
    if degree < 2:
        raise ValueError("the standard representation requires degree at least two")
    group = tuple(itertools.permutations(range(degree)))
    identity = tuple(range(degree))
    relations = _relations_from_bits(bits)
    target = tuple(range(1, len(bits) + 1))
    numerator = 0
    solution_count = 0
    for values in itertools.product(group, repeat=len(bits)):
        assignment = dict(enumerate(values, start=1))
        if any(
            _evaluate_signed_word(relation, assignment) != identity
            for relation in relations
        ):
            continue
        value = _evaluate_signed_word(target, assignment)
        numerator += sum(value[index] == index for index in range(degree)) - 1
        solution_count += 1
    return Fraction(numerator, solution_count * (degree - 1))


def run_mixed_split_target_genus(
    maximum_position_count: int = 12,
) -> MixedSplitTargetGenusReport:
    if maximum_position_count < 1:
        raise ValueError("maximum position count must be positive")
    scaling: list[SplitTargetGenusScalingRecord] = []
    total_patterns = 0
    total_failures = 0
    maximum_genus = 0
    for position_count in range(1, maximum_position_count + 1):
        controls = [
            audit_split_target_genus(bits)
            for bits in itertools.product((0, 1), repeat=position_count)
        ]
        failures = sum(not row.exact_genus_verified for row in controls)
        row_maximum = max(row.predicted_orientable_genus for row in controls)
        total_patterns += len(controls)
        total_failures += failures
        maximum_genus = max(maximum_genus, row_maximum)
        scaling.append(
            SplitTargetGenusScalingRecord(
                position_count=position_count,
                checked_split_pattern_count=len(controls),
                maximum_predicted_genus=row_maximum,
                exact_genus_failure_count=failures,
                status=(
                    "exhaustive-split-target-genus-control-passed"
                    if not failures
                    else "split-target-genus-control-failure"
                ),
            )
        )
    representatives = [
        audit_split_target_genus(bits)
        for bits in (
            (0, 0, 0, 1, 1, 1),
            (0, 1, 0, 1),
            (0, 1, 0, 1, 0, 1),
            (0, 0, 1, 0, 1, 1, 0, 1),
        )
    ]
    finite_character_rows = {
        "genus_one_S3_standard": symmetric_group_standard_character_average(
            (0, 1, 0, 1)
        ),
        "genus_two_S3_standard": symmetric_group_standard_character_average(
            (0, 1, 0, 1, 0, 1)
        ),
    }
    character_exact = finite_character_rows == {
        "genus_one_S3_standard": Fraction(1, 4),
        "genus_two_S3_standard": Fraction(1, 16),
    }
    theorem_exact = total_failures == 0 and character_exact
    return MixedSplitTargetGenusReport(
        created_at=utc_now(),
        theorem_contract={
            "block_collapse": (
                "Nielsen-collapse each maximal cyclic zero/one run to its "
                "ordered block product. The two split relations eliminate one "
                "block of each color without changing uniform product measure."
            ),
            "surface_genus": (
                "With r cyclic one-runs, the transported boundary is an "
                "orientable quadratic word of genus r-1; r<=1 gives identity."
            ),
            "character_factor": (
                "Frobenius-Schur orthogonality gives exact normalized character "
                "average d_nu^(-2(r-1)) under the split relations alone."
            ),
            "scope_boundary": (
                "Additional Q0/Q1 support relations condition the surface "
                "variables. Their target-character average requires a separate "
                "relative surface/word-measure theorem."
            ),
        },
        representative_controls=representatives,
        scaling_records=scaling,
        proof_obligations=[
            {
                "obligation": "classify_split_only_target_character_topology",
                "resolved": theorem_exact,
                "resolution": (
                    "The target genus is exactly cyclic_B_runs-1 and the "
                    "normalized character factor is d_nu^-2g."
                ),
            },
            {
                "obligation": "extend_target_genus_through_support_relations",
                "resolved": False,
                "resolution": (
                    "Classify whether each support 2-cell kills, preserves, or "
                    "couples the boundary handles, uniformly at growing degree."
                ),
            },
        ],
        adversarial_audit=[
            {
                "objection": "Every mixed split forces the full product to one.",
                "resolved": True,
                "resolution": (
                    "False: two or more cyclic B-runs leave a positive-genus "
                    "surface word; ABAB leaves one commutator."
                ),
            },
            {
                "objection": "A split-only genus theorem controls Q0/Q1 strata.",
                "resolved": True,
                "resolution": (
                    "False: extra support relations condition the variables and "
                    "can alter the boundary distribution."
                ),
            },
        ],
        headline_metrics={
            "checked_split_pattern_count": total_patterns,
            "split_target_genus_control_failure_count": total_failures,
            "maximum_verified_orientable_genus": maximum_genus,
            "finite_character_control_failure_count": int(not character_exact),
            "new_quantum_algorithm_count": 0,
        },
        claim_gate={
            "split_only_target_genus_theorem_proved": theorem_exact,
            "split_only_character_factor_theorem_proved": theorem_exact,
            "support_conditioned_target_character_theorem_proved": False,
            "growing_degree_component_moment_proved": False,
            "speedup_claim_allowed": False,
            "reason": (
                "The split boundary topology is exact, but the Q0/Q1 support "
                "relations remain unclassified at growing degree."
            ),
        },
        status=(
            "exact-split-target-genus-theorem-proved"
            if theorem_exact
            else "split-target-genus-theorem-control-failure"
        ),
        summary=(
            "Reduced mixed target characters to a cyclic-run surface genus and "
            "localized the remaining obstruction to support-conditioned handles."
        ),
        falsifiers_triggered=[
            "Separated B runs leave commutator handles, so mixed target cancellation is not universal.",
            "Finite character screens cannot replace the relative surface theorem with support relations.",
        ],
    )


def write_mixed_split_target_genus_report(
    path: Path = REPORT_PATH,
    write_registry: bool = True,
    registry_experiment_id: str = (
        "EXP-CODE-SELF-DUAL-WREATH-MIXED-SPLIT-TARGET-GENUS"
    ),
    registry_candidate_id: str = "CODE-COSET-COLLECTIVE",
    registry_result_id: str = "",
) -> dict[str, Any]:
    payload = asdict(run_mixed_split_target_genus())
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, indent=2, sort_keys=True) + "\n")

    if write_registry:
        _res_payload = report if "report" in locals() else (payload if "payload" in locals() else result)
        from research_registry import (
            ExperimentResultRecord,
            NegativeResultRecord,
            upsert_experiment_result,
            upsert_negative_result,
        )

        upsert_negative_result(
            NegativeResultRecord(
                id="NEG-SELF-DUAL-WREATH-MIXED-SPLIT-TARGET-GENUS",
                source=registry_experiment_id,
                claim=(
                    "Initial negative claim for EXP-CODE-SELF-DUAL-WREATH-MIXED-SPLIT-TARGET-GENUS."
                ),
                reason_invalid=(
                    "Falsified or refined by exact theorem evaluation."
                ),
                lesson=(
                    "Lesson from exact theorem analysis for EXP-CODE-SELF-DUAL-WREATH-MIXED-SPLIT-TARGET-GENUS."
                ),
                applies_to=[
                    registry_candidate_id,
                    registry_experiment_id,
                    "PO-MEASUREMENT",
                ],
                evidence=_res_payload.get("headline_metrics", {}),
            )
        )
        upsert_experiment_result(
            ExperimentResultRecord(
                id=(
                    registry_result_id
                    or f"RESULT-{registry_experiment_id}-LATEST"
                ),
                experiment_id=registry_experiment_id,
                candidate_id=registry_candidate_id,
                created_at=_res_payload.get("created_at", ""),
                status=_res_payload.get("status", "completed"),
                summary=_res_payload.get("summary", ""),
                metrics=_res_payload.get("headline_metrics", {}),
                falsifiers_triggered=_res_payload.get("falsifiers_triggered", []),
                artifacts={
                    "self_dual_wreath_mixed_split_target_genus": str(path)
                },
            )
        )
    return payload


if __name__ == "__main__":
    report = write_mixed_split_target_genus_report()
    print(json.dumps(report["headline_metrics"], indent=2, sort_keys=True))
