"""Constant-gap contraction for the shared-generator wreath word walk.

The natural k-copy moment word map can be viewed as a Markov chain on H_n^k,
where H_n is the subgroup generated by the bridge conjugacy class C_n.  At
each step the chain samples c uniformly from C_n and independently either
multiplies or does not multiply each coordinate by c.  Its transition
operator is

    M_k = E_c tensor_i (I + R_c) / 2.

Each bridge is an involution, so every factor P_c=(I+R_c)/2 is an orthogonal
projection.  On any tensor sector with a nonconstant coordinate j,

    tensor_i P_c <= P_c^(j).

The one-coordinate bridge walk has nonconstant spectrum at most 3/4.
Consequently M_k has a k-independent spectral gap of at least 1/4 on the
orthogonal complement of the constants.

For f=1_e+1_C/|C| and a_m the single-label subset word statistic, this gives

    |E[a_m^k] - (2/(n!)^2)^k|
        <= (3/4)^m (1 + 1/n!)^(k/2).

This is a genuine all-order coupled-walk contraction.  It is not yet the
needed typical-source moment theorem: at the certificate order the transient
term still dominates the stationary term, while the stationary term itself
comes from exponentially rare equal one-dimensional source sectors.
"""

from __future__ import annotations

import itertools
import json
import math
from dataclasses import asdict, dataclass
from fractions import Fraction
from pathlib import Path
from typing import Any

from research_registry import (
    ExperimentResultRecord,
    NegativeResultRecord,
    upsert_experiment_result,
    upsert_negative_result,
    utc_now,
)
from self_dual_wreath_character_moments import bridge_element
from self_dual_wreath_natural_moment_word_map import (
    exact_source_averaged_normalized_moment,
    is_bridge_class_element,
    is_identity_wreath,
)
from self_dual_wreath_pgm_polar_audit import (
    run_self_dual_wreath_pgm_polar_audit,
)
from self_dual_wreath_subset_carrier_algebra import (
    WreathElement,
    wreath_multiply,
)


REPORT_PATH = Path(
    "research/representation/self_dual_wreath_coupled_word_walk_gap.json"
)
WREATH_PGM_PATH = Path(
    "research/representation/self_dual_wreath_pgm_polar_audit.json"
)
DEFAULT_EXPERIMENT_ID = (
    "EXP-CODE-SELF-DUAL-WREATH-COUPLED-WORD-WALK-GAP"
)
DEFAULT_CANDIDATE_ID = "CODE-COSET-COLLECTIVE"


@dataclass(frozen=True)
class CoupledWalkValidationRecord:
    n: int
    copy_count: int
    moment_order: int
    bridge_sequence_count: int
    direct_word_map_moment: str
    coupled_walk_dynamic_moment: str
    exact_match: bool


@dataclass(frozen=True)
class BridgeSubgroupValidationRecord:
    n: int
    wreath_group_order: int
    generated_subgroup_order: int
    expected_index_two_subgroup_order: int
    index_two_verified: bool


@dataclass(frozen=True)
class CoupledWalkScalingRecord:
    n: int
    copy_count: int
    moment_order: int
    coupled_nonconstant_spectral_radius_upper_bound: float
    coupled_spectral_gap_lower_bound: float
    log2_stationary_kth_moment: float
    log2_transient_error_upper_bound: float
    log2_transient_to_stationary_ratio_upper_bound: float
    log2_coupled_kth_moment_upper_bound: float
    log2_normalized_moment_root_upper_bound: float
    log2_second_moment_eigenvalue_scale: float
    log2_root_to_second_moment_scale_gap: float
    stationary_scale_reached_at_certificate_order: bool
    typical_all_unequal_conditioning_required: bool
    status: str


@dataclass(frozen=True)
class WreathCoupledWordWalkGapReport:
    created_at: str
    theorem_contract: dict[str, Any]
    bridge_subgroup_validations: list[BridgeSubgroupValidationRecord]
    exact_moment_validations: list[CoupledWalkValidationRecord]
    scaling_records: list[CoupledWalkScalingRecord]
    headline_metrics: dict[str, int | float]
    claim_gate: dict[str, bool | str]
    status: str
    summary: str
    falsifiers_triggered: list[str]


def _identity_wreath(n: int) -> WreathElement:
    identity = tuple(range(n))
    return identity, identity, 0


def bridge_generated_subgroup(n: int) -> tuple[WreathElement, ...]:
    if n < 2:
        raise ValueError("n must be at least two")
    bridges = tuple(
        bridge_element(permutation)
        for permutation in itertools.permutations(range(n))
    )
    identity = _identity_wreath(n)
    discovered = {identity}
    frontier = [identity]
    while frontier:
        current = frontier.pop()
        for bridge in bridges:
            product = wreath_multiply(current, bridge)
            if product not in discovered:
                discovered.add(product)
                frontier.append(product)
    return tuple(discovered)


def validate_bridge_subgroup(n: int) -> BridgeSubgroupValidationRecord:
    factorial = math.factorial(n)
    generated_order = len(bridge_generated_subgroup(n))
    return BridgeSubgroupValidationRecord(
        n=n,
        wreath_group_order=2 * factorial * factorial,
        generated_subgroup_order=generated_order,
        expected_index_two_subgroup_order=factorial * factorial,
        index_two_verified=generated_order == factorial * factorial,
    )


def _endpoint_factor(element: WreathElement, bridge_count: int) -> Fraction:
    if is_identity_wreath(element):
        return Fraction(1)
    if is_bridge_class_element(element):
        return Fraction(1, bridge_count)
    return Fraction()


def exact_coupled_walk_moment(
    n: int,
    copy_count: int,
    moment_order: int,
) -> Fraction:
    if n < 2:
        raise ValueError("n must be at least two")
    if copy_count < 1:
        raise ValueError("copy_count must be positive")
    if moment_order < 1:
        raise ValueError("moment_order must be positive")
    bridges = tuple(
        bridge_element(permutation)
        for permutation in itertools.permutations(range(n))
    )
    identity = _identity_wreath(n)
    start = (identity,) * copy_count
    counts: dict[tuple[WreathElement, ...], int] = {start: 1}
    step_denominator = len(bridges) * (1 << copy_count)
    for _ in range(moment_order):
        next_counts: dict[tuple[WreathElement, ...], int] = {}
        for state, multiplicity in counts.items():
            for bridge in bridges:
                for mask in range(1 << copy_count):
                    target = tuple(
                        wreath_multiply(element, bridge)
                        if mask & (1 << index)
                        else element
                        for index, element in enumerate(state)
                    )
                    next_counts[target] = (
                        next_counts.get(target, 0) + multiplicity
                    )
        counts = next_counts
    numerator = sum(
        Fraction(multiplicity)
        * math.prod(
            _endpoint_factor(element, len(bridges))
            for element in state
        )
        for state, multiplicity in counts.items()
    )
    return numerator / step_denominator**moment_order


def validate_coupled_walk_moment(
    n: int,
    copy_count: int,
    moment_order: int,
) -> CoupledWalkValidationRecord:
    direct, _ = exact_source_averaged_normalized_moment(
        n=n,
        moment_order=moment_order,
        copy_count=copy_count,
    )
    dynamic = exact_coupled_walk_moment(
        n=n,
        copy_count=copy_count,
        moment_order=moment_order,
    )
    return CoupledWalkValidationRecord(
        n=n,
        copy_count=copy_count,
        moment_order=moment_order,
        bridge_sequence_count=math.factorial(n) ** moment_order,
        direct_word_map_moment=str(direct),
        coupled_walk_dynamic_moment=str(dynamic),
        exact_match=direct == dynamic,
    )


def _log2_add(left: float, right: float) -> float:
    high = max(left, right)
    low = min(left, right)
    if high == -math.inf:
        return high
    return high + math.log2(1 + 2 ** (low - high))


def coupled_scaling_record(
    n: int,
    copy_count: int,
    moment_order: int,
    second_moment_eigenvalue_scale: float,
) -> CoupledWalkScalingRecord:
    factorial = math.factorial(n)
    log2_factorial = math.lgamma(n + 1) / math.log(2)
    stationary_log2 = copy_count * (1 - 2 * log2_factorial)
    transient_log2 = (
        moment_order * math.log2(Fraction(3, 4))
        + 0.5 * copy_count * math.log2(1 + Fraction(1, factorial))
    )
    upper_log2 = _log2_add(stationary_log2, transient_log2)
    root_log2 = upper_log2 / moment_order
    second_scale_log2 = (
        math.log2(second_moment_eigenvalue_scale)
        if second_moment_eigenvalue_scale > 0
        else -math.inf
    )
    return CoupledWalkScalingRecord(
        n=n,
        copy_count=copy_count,
        moment_order=moment_order,
        coupled_nonconstant_spectral_radius_upper_bound=0.75,
        coupled_spectral_gap_lower_bound=0.25,
        log2_stationary_kth_moment=stationary_log2,
        log2_transient_error_upper_bound=transient_log2,
        log2_transient_to_stationary_ratio_upper_bound=(
            transient_log2 - stationary_log2
        ),
        log2_coupled_kth_moment_upper_bound=upper_log2,
        log2_normalized_moment_root_upper_bound=root_log2,
        log2_second_moment_eigenvalue_scale=second_scale_log2,
        log2_root_to_second_moment_scale_gap=(
            root_log2 - second_scale_log2
        ),
        stationary_scale_reached_at_certificate_order=(
            transient_log2 <= stationary_log2
        ),
        typical_all_unequal_conditioning_required=True,
        status=(
            "constant-gap-coupled-contraction-"
            "rare-equal-sector-contamination-open"
        ),
    )


def _read_json(path: Path) -> dict[str, Any]:
    if not path.exists():
        return {}
    try:
        payload = json.loads(path.read_text())
    except (json.JSONDecodeError, OSError):
        return {}
    return payload if isinstance(payload, dict) else {}


def run_wreath_coupled_word_walk_gap() -> WreathCoupledWordWalkGapReport:
    subgroup_validations = [
        validate_bridge_subgroup(n) for n in (2, 3, 4)
    ]
    exact_validations = [
        validate_coupled_walk_moment(n, copy_count, moment_order)
        for n, copy_count, moment_order in (
            (2, 1, 1),
            (2, 2, 2),
            (2, 3, 3),
            (3, 1, 3),
            (3, 2, 2),
            (3, 2, 3),
        )
    ]
    wreath = _read_json(WREATH_PGM_PATH)
    if not wreath:
        wreath = asdict(run_self_dual_wreath_pgm_polar_audit())
    scaling = [
        coupled_scaling_record(
            n=int(record["n"]),
            copy_count=int(record["copy_count"]),
            moment_order=math.ceil(
                float(record["log2_kcopy_hilbert_dimension"])
            ),
            second_moment_eigenvalue_scale=float(
                record["frame_eigenvalue_second_moment_scale"]
            ),
        )
        for record in wreath.get("records", [])
    ]
    subgroup_failures = sum(
        not record.index_two_verified for record in subgroup_validations
    )
    moment_failures = sum(
        not record.exact_match for record in exact_validations
    )
    tail = scaling[-1]
    metrics: dict[str, int | float] = {
        "bridge_subgroup_validation_count": len(subgroup_validations),
        "bridge_subgroup_validation_failure_count": subgroup_failures,
        "exact_coupled_moment_validation_count": len(exact_validations),
        "exact_coupled_moment_validation_failure_count": moment_failures,
        "constant_coupled_spectral_gap_theorem_count": 1,
        "coupled_k_walk_contraction_count": 1,
        "tail_coupled_spectral_gap_lower_bound": (
            tail.coupled_spectral_gap_lower_bound
        ),
        "tail_log2_stationary_kth_moment": (
            tail.log2_stationary_kth_moment
        ),
        "tail_log2_transient_error_upper_bound": (
            tail.log2_transient_error_upper_bound
        ),
        "tail_log2_transient_to_stationary_ratio_upper_bound": (
            tail.log2_transient_to_stationary_ratio_upper_bound
        ),
        "tail_log2_normalized_moment_root_upper_bound": (
            tail.log2_normalized_moment_root_upper_bound
        ),
        "tail_log2_second_moment_eigenvalue_scale": (
            tail.log2_second_moment_eigenvalue_scale
        ),
        "tail_log2_root_to_second_moment_scale_gap": (
            tail.log2_root_to_second_moment_scale_gap
        ),
        "certificate_order_stationary_scale_row_count": sum(
            record.stationary_scale_reached_at_certificate_order
            for record in scaling
        ),
        "typical_all_unequal_conditioned_kernel_count": 0,
        "natural_average_inverse_polynomial_conclusive_theorem_count": 0,
        "structured_maximal_effect_dilation_count": 0,
        "polynomial_hidden_permutation_decoder_count": 0,
    }
    verified = subgroup_failures == 0 and moment_failures == 0
    return WreathCoupledWordWalkGapReport(
        created_at=utc_now(),
        theorem_contract={
            "coupled_transition": (
                "M_k=E_c tensor_i P_c with P_c=(I+R_c)/2"
            ),
            "projection_domination": (
                "On every sector with nonconstant coordinate j, "
                "tensor_i P_c<=P_c^(j)"
            ),
            "constant_gap": (
                "The one-coordinate nonconstant radius is at most 3/4, "
                "hence the coupled radius is at most 3/4 independently of k"
            ),
            "endpoint_bound": (
                "|E[a_m^k]-(2/(n!)^2)^k|<="
                "(3/4)^m(1+1/n!)^(k/2)"
            ),
            "remaining_boundary": (
                "At m=ceil(log2 D), the transient still dominates the rare "
                "equal-sector stationary floor; condition on all-unequal "
                "labels and derive its character kernel"
            ),
        },
        bridge_subgroup_validations=subgroup_validations,
        exact_moment_validations=exact_validations,
        scaling_records=scaling,
        headline_metrics=metrics,
        claim_gate={
            "coupled_chain_identity_proved": verified,
            "bridge_generated_index_two_subgroup_verified": verified,
            "constant_coupled_spectral_gap_proved": verified,
            "coupled_k_walk_contraction_proved": verified,
            "certificate_order_reaches_stationary_scale": all(
                record.stationary_scale_reached_at_certificate_order
                for record in scaling
            ),
            "typical_all_unequal_conditioned_kernel_derived": False,
            "natural_average_inverse_polynomial_conclusive_proved": False,
            "structured_maximal_effect_dilation_proved": False,
            "polynomial_hidden_permutation_decoder_proved": False,
            "speedup_claim_allowed": False,
            "reason": (
                "The shared-generator chain has a constant gap, but its "
                "unconditional moment is contaminated by rare equal "
                "one-dimensional sectors and the finite certificate-order "
                "bound remains far above the second-moment eigenvalue scale."
            ),
        },
        status=(
            "constant-gap-coupled-word-contraction-proved-"
            "all-unequal-conditioning-open"
        ),
        summary=(
            "Proved a k-independent 1/4 gap for the coupled bridge word walk "
            f"and matched {len(exact_validations)} exact word-count controls; "
            "the tail normalized moment-root bound remains "
            f"{tail.log2_root_to_second_moment_scale_gap:.6g} bits above the "
            "second-moment eigenvalue scale."
        ),
        falsifiers_triggered=[
            "The shared bridge generator does not force a 1/k spectral-gap loss.",
            "A constant coupled-walk gap still does not reach the stationary moment scale at the certificate order.",
            "Rare equal one-dimensional source sectors contaminate the unconditional high moment.",
            "An unconditional source average cannot replace an all-unequal conditioned character kernel.",
            "No measurement circuit, hidden-permutation decoder, or classical separation follows from the gap theorem.",
        ],
    )


def write_wreath_coupled_word_walk_gap_report(
    path: Path = REPORT_PATH,
    write_registry: bool = True,
    registry_experiment_id: str = DEFAULT_EXPERIMENT_ID,
    registry_candidate_id: str = DEFAULT_CANDIDATE_ID,
    registry_result_id: str | None = None,
) -> dict[str, Any]:
    payload = asdict(run_wreath_coupled_word_walk_gap())
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, indent=2, sort_keys=True))
    if write_registry:
        upsert_negative_result(
            NegativeResultRecord(
                id=(
                    "NEG-CODE-WREATH-COUPLED-GAP-"
                    "NOT-TYPICAL-MOMENT"
                ),
                source=str(path),
                claim=(
                    "A constant spectral gap for the shared-generator word "
                    "walk closes the natural high-moment certificate."
                ),
                reason_invalid=(
                    "At the certificate order the transient remains above the "
                    "stationary scale, and rare equal one-dimensional labels "
                    "contaminate the unconditional source moment."
                ),
                lesson=(
                    "Condition the character average on all-unequal "
                    "Plancherel labels and analyze the resulting signed kernel."
                ),
                applies_to=[
                    registry_candidate_id,
                    registry_experiment_id,
                    "PO-COMPLEXITY",
                    "PO-SUCCESS",
                ],
                evidence=payload["headline_metrics"],
            )
        )
        upsert_experiment_result(
            ExperimentResultRecord(
                id=(
                    registry_result_id
                    or f"RESULT-{registry_experiment_id}-LATEST"
                ),
                experiment_id=registry_experiment_id,
                candidate_id=registry_candidate_id,
                created_at=payload["created_at"],
                status=payload["status"],
                summary=payload["summary"],
                metrics=payload["headline_metrics"],
                falsifiers_triggered=payload["falsifiers_triggered"],
                artifacts={
                    "self_dual_wreath_coupled_word_walk_gap": str(path)
                },
            )
        )
    return payload


if __name__ == "__main__":
    report = write_wreath_coupled_word_walk_gap_report()
    print(json.dumps(report["headline_metrics"], indent=2, sort_keys=True))
