"""Uniform rank collapse for the periodic nonidentity frame family.

The periodic frame-fiber construction makes the generic support-entropy bound
nearly tight, but its same-support relators have much more structure.  For a
zero-containing support ``U`` and an anchor ``a in U``, XOR re-rooting sends
the ordered-subword relators to those indexed by ``U xor a``.  If coordinate
``i`` has a row that agrees with ``a`` strictly after ``i`` and flips bit
``i``, the re-rooted relator contains ``x_i`` exactly once and no later
generator.  Descending through the coordinates therefore eliminates every
such generator over every group.  Only suffix-forced coordinates remain.

For the exact S3 periodic family, put

    P = 001110100010111010000011101000   (six periods),
    Q = 10011                            (one period).

Both the selected and complementary ordered products of ``P`` are identity,
as are those of the all-zero six-period block.  The pair for ``Q`` is the
same-fiber target.  Exact finite-state witnesses prove:

* in the first ``P`` block every coordinate except 1, 2, and 5 branches;
* in every later ``P`` block all 30 coordinates branch, using a witness on
  the preceding and current block;
* all five coordinates of the terminal ``Q`` branch, using a witness on
  ``P Q``.

Hence the frame presentation for ``P^m Q`` is generated by at most three
elements for every ``m >= 1``.  The ``m=0`` terminal block also has a
three-generator bound, using one same-fiber witness and the adjoined empty
relator.  This is a universal finite-group statement, not an extrapolation.

The existing outer conjugacy normal form contributes at most ``|G| k(G)``
assignments.  Thus the full marked presentation has at most

    |G|^4 k(G)

solutions.  For ``G=S_n`` this is ``|S_n|^(4+o(1))``.  Along ``k=6m+1`` the
same-fiber size is exactly

    S_m=(16*2^(30m)+8*2^(24m)-4*2^(6m)-2)/9,

and ``D_m=S_m+1``.  Since ``S_m <= 2^(u-4)`` for ``u=30m+5``, the scalar
crossing-pressure margin above ``-1`` is uniformly at least

    1 - 0.5*log2(3/2) > 0.70.

The periodic counterfamily therefore falsifies a uniform *support-only* gap,
but it cannot carry leading symmetric-group mass.  Its unresolved target
character is immaterial to this candidate because the unsigned mass is
already uniformly subleading.
"""

from __future__ import annotations

import json
import math
from dataclasses import asdict, dataclass
from pathlib import Path
from typing import Any, Iterable

from research_registry import utc_now
from self_dual_wreath_periodic_frame_fiber_counterfamily import (
    FRAME_BLOCK,
    IDENTITY,
    SAME_SUBSEQUENCE_STATE,
    State,
    _period_fiber_counts,
    audit_transfer_certificate,
    compose,
)


REPORT_PATH = Path(
    "research/representation/"
    "self_dual_wreath_periodic_frame_rank_collapse.json"
)
DEFAULT_EXPERIMENT_ID = (
    "EXP-CODE-SELF-DUAL-WREATH-PERIODIC-FRAME-RANK-COLLAPSE"
)
DEFAULT_CANDIDATE_ID = "CODE-COSET-COLLECTIVE"

Assignment = tuple[int, ...]

NEUTRAL_BLOCK: Assignment = tuple(
    int(bit) for bit in "001110100010111010000011101000"
)
TERMINAL_BLOCK: Assignment = tuple(int(bit) for bit in "10011")
NEUTRAL_STATE: State = (IDENTITY, IDENTITY)


@dataclass(frozen=True)
class SuffixBranchWitness:
    coordinate_one_based: int
    anchor: Assignment
    witness: Assignment
    target_state: State
    bit_flipped: bool
    strict_suffix_agreement: bool
    witness_state_verified: bool
    status: str


@dataclass(frozen=True)
class PeriodicSuffixBranchCertificate:
    neutral_block: Assignment
    terminal_block: Assignment
    neutral_block_state: State
    zero_neutral_block_state: State
    terminal_block_state: State
    first_neutral_block_branch_coordinates: tuple[int, ...]
    first_neutral_block_unresolved_coordinates: tuple[int, ...]
    repeated_neutral_block_branch_coordinates: tuple[int, ...]
    terminal_block_branch_coordinates: tuple[int, ...]
    single_terminal_same_fiber_branch_coordinates: tuple[int, ...]
    single_terminal_exception_branch_coordinates: tuple[int, ...]
    first_neutral_block_witnesses: tuple[SuffixBranchWitness, ...]
    repeated_neutral_block_witnesses: tuple[SuffixBranchWitness, ...]
    terminal_block_witnesses: tuple[SuffixBranchWitness, ...]
    single_terminal_witnesses: tuple[SuffixBranchWitness, ...]
    universal_finite_group_frame_generator_upper_bound: int
    exact_suffix_branch_elimination_lemma_applied: bool
    neutral_concatenation_induction_verified: bool
    status: str


@dataclass(frozen=True)
class PeriodicFiberClosedFormCertificate:
    subsequence: str
    checked_m_values: tuple[int, ...]
    transfer_fiber_sizes: tuple[int, ...]
    closed_form_fiber_sizes: tuple[int, ...]
    recurrence_roots: tuple[int, ...]
    closed_form_coefficients: tuple[str, ...]
    exact_transfer_annihilator_imported: bool
    initial_values_determine_closed_form: bool
    closed_form_verified: bool
    uniform_density_bound: str
    uniform_density_bound_verified: bool
    status: str


@dataclass(frozen=True)
class PeriodicRankCollapseScalingRecord:
    m_value: int
    period_count: int
    frame_position_count: int
    same_support_size: int
    different_support_size: int
    support_entropy_exponent: float
    frame_generator_upper_bound: int
    full_solution_exponent_before_conjugacy_classes: int
    scalar_crossing_pressure_upper_bound: float
    scalar_crossing_pressure_margin: float
    uniform_margin_lower_bound: float
    status: str


@dataclass(frozen=True)
class PeriodicFrameRankCollapseReport:
    created_at: str
    theorem_contract: dict[str, Any]
    suffix_branch_certificate: PeriodicSuffixBranchCertificate
    fiber_closed_form_certificate: PeriodicFiberClosedFormCertificate
    scaling_records: list[PeriodicRankCollapseScalingRecord]
    proof_obligations: list[dict[str, str | bool]]
    adversarial_audit: list[dict[str, str | bool]]
    headline_metrics: dict[str, int | float]
    claim_gate: dict[str, str | bool]
    status: str
    summary: str
    falsifiers_triggered: list[str]


def frame_pair(assignment: Assignment) -> State:
    if not assignment or len(assignment) % len(FRAME_BLOCK):
        raise ValueError("assignment must contain a positive whole number of periods")
    if any(bit not in (0, 1) for bit in assignment):
        raise ValueError("assignment must be binary")
    left = IDENTITY
    right = IDENTITY
    for value, bit in zip(
        FRAME_BLOCK * (len(assignment) // len(FRAME_BLOCK)),
        assignment,
    ):
        if bit:
            left = compose(left, value)
        else:
            right = compose(right, value)
    return left, right


def _suffix_branch_witness(
    anchor: Assignment,
    target_state: State,
    coordinate: int,
) -> SuffixBranchWitness | None:
    """Find a lexicographically first exact branch witness by 36-state DP."""

    if coordinate < 0 or coordinate >= len(anchor):
        raise ValueError("coordinate is outside the anchor")
    values = FRAME_BLOCK * (len(anchor) // len(FRAME_BLOCK))
    prefix_states: dict[State, Assignment] = {NEUTRAL_STATE: ()}
    for index in range(coordinate + 1):
        options = (1 - anchor[index],) if index == coordinate else (0, 1)
        output: dict[State, Assignment] = {}
        for (left, right), prefix in prefix_states.items():
            for bit in options:
                value = values[index]
                state = (
                    (compose(left, value), right)
                    if bit
                    else (left, compose(right, value))
                )
                output.setdefault(state, (*prefix, bit))
        prefix_states = output

    suffix = anchor[coordinate + 1 :]
    for state, prefix in prefix_states.items():
        left, right = state
        for value, bit in zip(values[coordinate + 1 :], suffix):
            if bit:
                left = compose(left, value)
            else:
                right = compose(right, value)
        if (left, right) != target_state:
            continue
        witness = (*prefix, *suffix)
        bit_flipped = witness[coordinate] == 1 - anchor[coordinate]
        suffix_agreement = witness[coordinate + 1 :] == suffix
        state_verified = frame_pair(witness) == target_state
        exact = bit_flipped and suffix_agreement and state_verified
        return SuffixBranchWitness(
            coordinate_one_based=coordinate + 1,
            anchor=anchor,
            witness=witness,
            target_state=target_state,
            bit_flipped=bit_flipped,
            strict_suffix_agreement=suffix_agreement,
            witness_state_verified=state_verified,
            status=(
                "exact-suffix-branch-witness" if exact else "suffix-witness-failure"
            ),
        )
    return None


def _witnesses(
    anchor: Assignment,
    target_state: State,
    coordinates: Iterable[int],
) -> tuple[SuffixBranchWitness, ...]:
    output = []
    for coordinate in coordinates:
        witness = _suffix_branch_witness(anchor, target_state, coordinate)
        if witness is not None:
            output.append(witness)
    return tuple(output)


def audit_periodic_suffix_branch_certificate() -> PeriodicSuffixBranchCertificate:
    first = _witnesses(
        NEUTRAL_BLOCK,
        NEUTRAL_STATE,
        range(len(NEUTRAL_BLOCK)),
    )
    repeated_anchor = (*NEUTRAL_BLOCK, *NEUTRAL_BLOCK)
    repeated = _witnesses(
        repeated_anchor,
        NEUTRAL_STATE,
        range(len(NEUTRAL_BLOCK), len(repeated_anchor)),
    )
    terminal_anchor = (*NEUTRAL_BLOCK, *TERMINAL_BLOCK)
    terminal = _witnesses(
        terminal_anchor,
        SAME_SUBSEQUENCE_STATE,
        range(len(NEUTRAL_BLOCK), len(terminal_anchor)),
    )
    single_terminal = _witnesses(
        TERMINAL_BLOCK,
        SAME_SUBSEQUENCE_STATE,
        range(len(TERMINAL_BLOCK)),
    )
    first_coordinates = tuple(row.coordinate_one_based for row in first)
    first_unresolved = tuple(
        coordinate
        for coordinate in range(1, len(NEUTRAL_BLOCK) + 1)
        if coordinate not in first_coordinates
    )
    repeated_coordinates = tuple(
        row.coordinate_one_based - len(NEUTRAL_BLOCK) for row in repeated
    )
    terminal_coordinates = tuple(
        row.coordinate_one_based - len(NEUTRAL_BLOCK) for row in terminal
    )
    single_coordinates = tuple(
        row.coordinate_one_based for row in single_terminal
    )
    zero_neutral = frame_pair((0,) * len(NEUTRAL_BLOCK))
    exact_witnesses = all(
        row.bit_flipped
        and row.strict_suffix_agreement
        and row.witness_state_verified
        for row in (*first, *repeated, *terminal, *single_terminal)
    )
    exact = (
        frame_pair(NEUTRAL_BLOCK) == NEUTRAL_STATE
        and zero_neutral == NEUTRAL_STATE
        and frame_pair(TERMINAL_BLOCK) == SAME_SUBSEQUENCE_STATE
        and first_unresolved == (1, 2, 5)
        and repeated_coordinates == tuple(range(1, 31))
        and terminal_coordinates == tuple(range(1, 6))
        and single_coordinates == (4,)
        and TERMINAL_BLOCK[-1] == 1
        and exact_witnesses
    )
    return PeriodicSuffixBranchCertificate(
        neutral_block=NEUTRAL_BLOCK,
        terminal_block=TERMINAL_BLOCK,
        neutral_block_state=frame_pair(NEUTRAL_BLOCK),
        zero_neutral_block_state=zero_neutral,
        terminal_block_state=frame_pair(TERMINAL_BLOCK),
        first_neutral_block_branch_coordinates=first_coordinates,
        first_neutral_block_unresolved_coordinates=first_unresolved,
        repeated_neutral_block_branch_coordinates=repeated_coordinates,
        terminal_block_branch_coordinates=terminal_coordinates,
        single_terminal_same_fiber_branch_coordinates=single_coordinates,
        single_terminal_exception_branch_coordinates=(5,),
        first_neutral_block_witnesses=first,
        repeated_neutral_block_witnesses=repeated,
        terminal_block_witnesses=terminal,
        single_terminal_witnesses=single_terminal,
        universal_finite_group_frame_generator_upper_bound=3,
        exact_suffix_branch_elimination_lemma_applied=exact,
        neutral_concatenation_induction_verified=exact,
        status=(
            "exact-all-period-suffix-branch-rank-collapse"
            if exact
            else "periodic-suffix-branch-certificate-failure"
        ),
    )


def periodic_same_fiber_closed_form(m_value: int) -> int:
    if m_value < 0:
        raise ValueError("m must be nonnegative")
    numerator = (
        16 * 2 ** (30 * m_value)
        + 8 * 2 ** (24 * m_value)
        - 4 * 2 ** (6 * m_value)
        - 2
    )
    if numerator % 9:
        raise AssertionError("closed-form fiber numerator is not divisible by nine")
    return numerator // 9


def audit_periodic_fiber_closed_form(
    maximum_checked_m: int = 6,
) -> PeriodicFiberClosedFormCertificate:
    checked = tuple(range(maximum_checked_m + 1))
    transfer_sizes = tuple(
        _period_fiber_counts(6 * m_value + 1)[SAME_SUBSEQUENCE_STATE]
        for m_value in checked
    )
    closed_sizes = tuple(periodic_same_fiber_closed_form(m_value) for m_value in checked)
    transfer = audit_transfer_certificate()
    recurrence_roots = (2**30, 2**24, 2**6, 1)
    initial_determines = transfer.exact_annihilating_polynomial_verified and all(
        transfer_sizes[index] == closed_sizes[index] for index in range(4)
    )
    density = all(
        size <= 2 ** (30 * m_value + 1)
        for m_value, size in zip(checked, transfer_sizes)
    )
    exact = initial_determines and transfer_sizes == closed_sizes and density
    return PeriodicFiberClosedFormCertificate(
        subsequence="k=6m+1, u=30m+5",
        checked_m_values=checked,
        transfer_fiber_sizes=transfer_sizes,
        closed_form_fiber_sizes=closed_sizes,
        recurrence_roots=recurrence_roots,
        closed_form_coefficients=("16/9", "8/9", "-4/9", "-2/9"),
        exact_transfer_annihilator_imported=(
            transfer.exact_annihilating_polynomial_verified
        ),
        initial_values_determine_closed_form=initial_determines,
        closed_form_verified=exact,
        uniform_density_bound="S_m <= 2^(u-4)",
        uniform_density_bound_verified=density,
        status=(
            "exact-periodic-fiber-closed-form-and-density-bound"
            if exact
            else "periodic-fiber-closed-form-failure"
        ),
    )


def periodic_rank_collapse_scaling_records(
    maximum_m: int = 6,
) -> list[PeriodicRankCollapseScalingRecord]:
    uniform_margin = 1.0 - 0.5 * math.log2(3.0 / 2.0)
    output = []
    for m_value in range(maximum_m + 1):
        width = 30 * m_value + 5
        same_size = periodic_same_fiber_closed_form(m_value)
        different_size = same_size + 1
        entropy = 0.5 * math.log2(same_size * different_size)
        pressure = 4.0 + entropy - width - 2.0
        margin = -1.0 - pressure
        output.append(
            PeriodicRankCollapseScalingRecord(
                m_value=m_value,
                period_count=6 * m_value + 1,
                frame_position_count=width,
                same_support_size=same_size,
                different_support_size=different_size,
                support_entropy_exponent=entropy,
                frame_generator_upper_bound=3,
                full_solution_exponent_before_conjugacy_classes=4,
                scalar_crossing_pressure_upper_bound=pressure,
                scalar_crossing_pressure_margin=margin,
                uniform_margin_lower_bound=uniform_margin,
                status=(
                    "periodic-family-uniformly-subleading"
                    if margin >= uniform_margin - 1e-12
                    else "periodic-rank-margin-certificate-failure"
                ),
            )
        )
    return output


def run_periodic_frame_rank_collapse() -> PeriodicFrameRankCollapseReport:
    suffix = audit_periodic_suffix_branch_certificate()
    closed = audit_periodic_fiber_closed_form()
    scaling = periodic_rank_collapse_scaling_records()
    uniform_margin = min(row.scalar_crossing_pressure_margin for row in scaling)
    exact = (
        suffix.exact_suffix_branch_elimination_lemma_applied
        and suffix.neutral_concatenation_induction_verified
        and closed.closed_form_verified
        and closed.uniform_density_bound_verified
        and all(row.scalar_crossing_pressure_margin > 0 for row in scaling)
    )
    return PeriodicFrameRankCollapseReport(
        created_at=utc_now(),
        theorem_contract={
            "suffix_branch_lemma": (
                "After XOR re-rooting at an anchor, every support row that flips "
                "coordinate i while agreeing on the strict suffix gives a relator "
                "that determines x_i from lower-index generators."
            ),
            "all_period_rank_bound": (
                "Exact neutral-block, repeated-block, and terminal witnesses leave "
                "at most three frame generators for every k=6m+1."
            ),
            "full_solution_bound": (
                "The mixed-frame outer conjugacy normal form then gives at most "
                "|G|^4 k(G) full solutions over every finite group G."
            ),
            "symmetric_group_consequence": (
                "For S_n, k(S_n)=|S_n|^o(1), so the family has exponent at most "
                "4+o(1) and a scalar crossing-pressure margin uniformly above zero."
            ),
            "scope": (
                "This kills this exact periodic family. It is not a no-go theorem "
                "for every nonidentity frame fiber or every interleaved word."
            ),
        },
        suffix_branch_certificate=suffix,
        fiber_closed_form_certificate=closed,
        scaling_records=scaling,
        proof_obligations=[
            {
                "obligation": "classify_periodic_same_fiber_frame_rank",
                "resolved": exact,
                "resolution": (
                    "A finite suffix-witness catalog plus neutral concatenation "
                    "proves the universal three-generator bound."
                ),
            },
            {
                "obligation": "prove_or_falsify_leading_Sn_mass_for_periodic_family",
                "resolved": exact,
                "resolution": (
                    "Falsified: |Hom| <= |S_n|^(4+o(1)) gives a uniform positive "
                    "pressure margin on the entire infinite subsequence."
                ),
            },
            {
                "obligation": "classify_periodic_target_character",
                "resolved": exact,
                "resolution": (
                    "Obviated for candidate survival: normalized characters are at "
                    "most one in magnitude and cannot recover the missing scalar mass."
                ),
            },
        ],
        adversarial_audit=[
            {
                "objection": "The rank bound is inferred from k<=4 Tietze controls.",
                "resolved": True,
                "resolution": (
                    "False. The proof uses exact suffix witnesses and a neutral "
                    "six-period concatenation induction valid for every m."
                ),
            },
            {
                "objection": "A vanishing support-only margin can imply leading mass.",
                "resolved": True,
                "resolution": (
                    "False for this family: support cardinality misses a uniform "
                    "three-generator presentation collapse."
                ),
            },
            {
                "objection": "A nonidentity finite target may rescue the channel.",
                "resolved": True,
                "resolution": (
                    "No normalized target character exceeds one, so it cannot undo "
                    "the uniform unsigned-mass exponent loss."
                ),
            },
        ],
        headline_metrics={
            "all_period_suffix_branch_rank_theorem_count": int(exact),
            "universal_frame_generator_upper_bound": 3,
            "full_Sn_solution_exponent_upper_bound": 4,
            "minimum_checked_scalar_pressure_margin": uniform_margin,
            "proved_uniform_scalar_pressure_margin_lower_bound": (
                1.0 - 0.5 * math.log2(3.0 / 2.0)
            ),
            "periodic_family_leading_Sn_mass_count": 0,
            "periodic_family_surviving_candidate_count": 0,
            "new_quantum_algorithm_count": 0,
        },
        claim_gate={
            "periodic_frame_rank_collapse_proved": exact,
            "periodic_family_uniformly_subleading_in_Sn": exact,
            "periodic_family_target_character_still_relevant": False,
            "periodic_family_survives": False,
            "natural_component_M4_positive": False,
            "speedup_claim_allowed": False,
            "reason": (
                "The exact periodic support mechanism collapses to at most three "
                "frame generators and cannot carry leading S_n mass."
            ),
        },
        status=(
            "periodic-counterfamily-falsified-by-uniform-rank-collapse"
            if exact
            else "periodic-rank-collapse-certificate-failure"
        ),
        summary=(
            "Closed the periodic nonidentity family by proving a universal "
            "three-generator frame bound and uniform scalar-pressure loss."
        ),
        falsifiers_triggered=[
            "Vanishing support-size margins need not survive presentation structure.",
            "Exponential automaton fibers need not produce leading group-solution mass.",
            "Finite nonidentity target bias is irrelevant after uniform scalar suppression.",
        ],
    )


def write_periodic_frame_rank_collapse_report(
    path: Path = REPORT_PATH,
    write_registry: bool = True,
    registry_experiment_id: str = (
        "EXP-CODE-SELF-DUAL-WREATH-PERIODIC-FRAME-RANK-COLLAPSE"
    ),
    registry_candidate_id: str = "CODE-COSET-COLLECTIVE",
    registry_result_id: str = "",
) -> dict[str, Any]:
    report = asdict(run_periodic_frame_rank_collapse())
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(report, indent=2, sort_keys=True) + "\n")

    return report


if __name__ == "__main__":
    result = write_periodic_frame_rank_collapse_report()
    print(json.dumps(result["headline_metrics"], indent=2, sort_keys=True))
