"""Stable-partition rank and natural-mass audit for mixed commutator kernels.

Stable partitions with bounded boxes below the first row have character
polynomials and are the most plausible low-complexity sector for a four-class
commutator contraction. This module tests that shortcut in two ways:

* on finite S_n controls, it computes exact modular ranks of the Hadamard
  algebra generated by physical third-moment features on the refined
  (r,q,r^-1q,[r,q]) class kernel;
* at growing n, it computes the exact Plancherel mass of partitions with at
  most b boxes below the first row.

The physical wreath irrep label law is an unordered pair of independent
Plancherel partitions after equal signs are summed. Thus a bounded-tail source
set has one-copy physical mass equal to the square of its Plancherel mass.
For every fixed b this is poly(n)/n! per source and vanishes. A stable-sector
recoupling rule cannot establish a typical-sector decoder.
"""

from __future__ import annotations

import itertools
import json
import math
from dataclasses import asdict, dataclass
from fractions import Fraction
from pathlib import Path
from typing import Any, Iterable

from representation_obstruction import (
    hook_length_dimension,
    integer_partitions,
)
from research_registry import (
    ExperimentResultRecord,
    NegativeResultRecord,
    upsert_experiment_result,
    upsert_negative_result,
    utc_now,
)
from self_dual_wreath_character_moments import (
    PhysicalWreathIrrepDescriptor,
    equal_pair_descriptor,
    physical_wreath_character,
    unequal_pair_descriptor,
)
from self_dual_wreath_equal_commutator_audit import (
    ClassQuadruple,
    refined_commutator_kernel,
)
from symmetric_character import symmetric_character


SELF_DUAL_WREATH_STABLE_COMMUTATOR_RANK_PATH = Path(
    "research/representation/"
    "self_dual_wreath_stable_commutator_rank.json"
)
DEFAULT_EXPERIMENT_ID = (
    "EXP-CODE-SELF-DUAL-WREATH-STABLE-COMMUTATOR-RANK"
)
DEFAULT_CANDIDATE_ID = "CODE-COSET-COLLECTIVE"
MODULAR_PRIME = 1_000_003


@dataclass(frozen=True)
class StableFeatureRankRecord:
    n: int
    tail_budget: int
    stable_partition_count: int
    physical_descriptor_count: int
    refined_kernel_support_count: int
    maximum_degree: int
    monomial_count: int
    modular_rank_by_degree: list[int]
    final_modular_rank: int
    final_rank_fraction: float
    full_kernel_separated: bool
    status: str


@dataclass(frozen=True)
class StableMassRecord:
    n: int
    tail_budget: int
    stable_partition_count: int
    threshold_copy_count: int
    exact_source_plancherel_mass: str
    log2_source_plancherel_mass: float
    exact_one_copy_physical_label_mass: str
    log2_one_copy_physical_label_mass: float
    log2_all_threshold_labels_stable_mass: float
    fixed_tail_mass_vanishes: bool
    typical_sector_coverage: bool
    status: str


@dataclass(frozen=True)
class SelfDualWreathStableCommutatorRankReport:
    created_at: str
    stable_sector_contract: dict[str, Any]
    rank_records: list[StableFeatureRankRecord]
    mass_records: list[StableMassRecord]
    headline_metrics: dict[str, int | float]
    claim_gate: dict[str, bool | str]
    status: str
    summary: str
    falsifiers_triggered: list[str]


def bounded_tail_partitions(
    n: int,
    tail_budget: int,
) -> tuple[tuple[int, ...], ...]:
    if n < 1:
        raise ValueError("n must be positive")
    if tail_budget < 0:
        raise ValueError("tail_budget must be nonnegative")
    result = []
    for tail_size in range(min(tail_budget, n - 1) + 1):
        tails = ((),) if tail_size == 0 else integer_partitions(tail_size)
        for tail in tails:
            first = n - tail_size
            if tail and first < tail[0]:
                continue
            result.append((first, *tail))
    return tuple(sorted(set(result), reverse=True))


def stable_physical_descriptors(
    n: int,
    tail_budget: int,
) -> tuple[PhysicalWreathIrrepDescriptor, ...]:
    partitions = bounded_tail_partitions(n, tail_budget)
    descriptors: list[PhysicalWreathIrrepDescriptor] = []
    for partition in partitions:
        descriptors.append(equal_pair_descriptor(partition, 1))
        descriptors.append(equal_pair_descriptor(partition, -1))
    for left_index, left in enumerate(partitions):
        for right in partitions[left_index + 1 :]:
            descriptors.append(unequal_pair_descriptor(left, right))
    return tuple(descriptors)


def physical_third_feature(
    descriptor: PhysicalWreathIrrepDescriptor,
    quadruple: ClassQuadruple,
) -> int:
    alpha, beta, gamma, commutator = quadruple
    if descriptor.kind == "equal-pair-extension":
        partition = descriptor.left_partition
        return (
            descriptor.dimension
            + 3 * descriptor.bridge_character
            + symmetric_character(partition, alpha) ** 2
            + symmetric_character(partition, beta) ** 2
            + symmetric_character(partition, gamma) ** 2
            + int(descriptor.sign or 0)
            * symmetric_character(partition, commutator)
        )
    return (
        descriptor.dimension
        + 2
        * symmetric_character(descriptor.left_partition, alpha)
        * symmetric_character(descriptor.right_partition, alpha)
        + 2
        * symmetric_character(descriptor.left_partition, beta)
        * symmetric_character(descriptor.right_partition, beta)
        + 2
        * symmetric_character(descriptor.left_partition, gamma)
        * symmetric_character(descriptor.right_partition, gamma)
    )


def _insert_modular_vector(
    vector: Iterable[int],
    basis: dict[int, dict[int, int]],
    prime: int,
) -> bool:
    sparse = {
        index: value % prime
        for index, value in enumerate(vector)
        if value % prime
    }
    while sparse:
        pivot = min(sparse)
        pivot_value = sparse[pivot]
        if pivot not in basis:
            inverse = pow(pivot_value, -1, prime)
            basis[pivot] = {
                index: value * inverse % prime
                for index, value in sparse.items()
                if value % prime
            }
            return True
        row = basis[pivot]
        for index, value in row.items():
            reduced = (
                sparse.get(index, 0) - pivot_value * value
            ) % prime
            if reduced:
                sparse[index] = reduced
            elif index in sparse:
                del sparse[index]
    return False


def audit_stable_feature_rank(
    n: int,
    tail_budget: int = 2,
    maximum_degree: int = 4,
    prime: int = MODULAR_PRIME,
) -> StableFeatureRankRecord:
    kernel = refined_commutator_kernel(n)
    support = tuple(quadruple for quadruple, _ in kernel)
    descriptors = stable_physical_descriptors(n, tail_budget)
    features = [
        tuple(
            physical_third_feature(descriptor, quadruple)
            for quadruple in support
        )
        for descriptor in descriptors
    ]
    basis: dict[int, dict[int, int]] = {}
    _insert_modular_vector((1,) * len(support), basis, prime)
    ranks = []
    monomial_count = 1
    for degree in range(1, maximum_degree + 1):
        for indices in itertools.combinations_with_replacement(
            range(len(features)), degree
        ):
            vector = [
                math.prod(features[index][row] for index in indices)
                for row in range(len(support))
            ]
            _insert_modular_vector(vector, basis, prime)
            monomial_count += 1
            if len(basis) == len(support):
                break
        ranks.append(len(basis))
        if len(basis) == len(support):
            ranks.extend(
                [len(basis)] * (maximum_degree - degree)
            )
            break
    rank = len(basis)
    return StableFeatureRankRecord(
        n=n,
        tail_budget=tail_budget,
        stable_partition_count=len(
            bounded_tail_partitions(n, tail_budget)
        ),
        physical_descriptor_count=len(descriptors),
        refined_kernel_support_count=len(support),
        maximum_degree=maximum_degree,
        monomial_count=monomial_count,
        modular_rank_by_degree=ranks,
        final_modular_rank=rank,
        final_rank_fraction=round(
            rank / len(support) if support else 0.0,
            12,
        ),
        full_kernel_separated=rank == len(support),
        status=(
            "stable-feature-algebra-saturates-finite-kernel"
            if rank == len(support)
            else "stable-feature-algebra-finite-low-rank-control"
        ),
    )


def stable_source_plancherel_mass(
    n: int,
    tail_budget: int,
) -> Fraction:
    numerator = sum(
        hook_length_dimension(partition) ** 2
        for partition in bounded_tail_partitions(n, tail_budget)
    )
    return Fraction(numerator, math.factorial(n))


def _fraction_log2(value: Fraction) -> float:
    if value <= 0:
        return -math.inf
    return math.log2(value.numerator) - math.log2(value.denominator)


def stable_mass_record(
    n: int,
    tail_budget: int,
) -> StableMassRecord:
    source_mass = stable_source_plancherel_mass(n, tail_budget)
    physical_mass = source_mass * source_mass
    copy_count = math.ceil(math.log2(math.factorial(n)))
    log_source = _fraction_log2(source_mass)
    log_physical = 2 * log_source
    return StableMassRecord(
        n=n,
        tail_budget=tail_budget,
        stable_partition_count=len(
            bounded_tail_partitions(n, tail_budget)
        ),
        threshold_copy_count=copy_count,
        exact_source_plancherel_mass=str(source_mass),
        log2_source_plancherel_mass=round(log_source, 12),
        exact_one_copy_physical_label_mass=str(physical_mass),
        log2_one_copy_physical_label_mass=round(log_physical, 12),
        log2_all_threshold_labels_stable_mass=round(
            copy_count * log_physical,
            12,
        ),
        fixed_tail_mass_vanishes=True,
        typical_sector_coverage=False,
        status="bounded-tail-plancherel-mass-vanishes",
    )


def run_self_dual_wreath_stable_commutator_rank() -> (
    SelfDualWreathStableCommutatorRankReport
):
    rank_records = [
        audit_stable_feature_rank(n)
        for n in (3, 4, 5, 6)
    ]
    mass_records = [
        stable_mass_record(n, tail_budget)
        for n in (8, 12, 16, 24, 32, 48, 64)
        for tail_budget in (2, 4, 6)
    ]
    metrics: dict[str, int | float] = {
        "finite_rank_record_count": len(rank_records),
        "maximum_rank_control_n": max(
            record.n for record in rank_records
        ),
        "maximum_stable_feature_algebra_rank": max(
            record.final_modular_rank for record in rank_records
        ),
        "maximum_refined_kernel_support_count": max(
            record.refined_kernel_support_count
            for record in rank_records
        ),
        "finite_full_kernel_separation_count": sum(
            record.full_kernel_separated for record in rank_records
        ),
        "mass_scaling_record_count": len(mass_records),
        "maximum_mass_scaling_n": max(
            record.n for record in mass_records
        ),
        "fixed_tail_vanishing_mass_theorem_count": 1,
        "minimum_log2_one_copy_physical_stable_mass": min(
            record.log2_one_copy_physical_label_mass
            for record in mass_records
        ),
        "minimum_log2_threshold_all_stable_mass": min(
            record.log2_all_threshold_labels_stable_mass
            for record in mass_records
        ),
        "typical_sector_coverage_count": 0,
        "polynomial_typical_four_class_contraction_count": 0,
        "support_gap_theorem_count": 0,
        "coherent_blockwise_frame_pseudoinverse_count": 0,
        "polynomial_hidden_permutation_decoder_count": 0,
    }
    return SelfDualWreathStableCommutatorRankReport(
        created_at=utc_now(),
        stable_sector_contract={
            "stable_partitions": (
                "lambda_1 >= n-b, equivalently at most b boxes "
                "below the first row"
            ),
            "finite_feature_algebra": (
                "Hadamard algebra generated by physical third-moment "
                "features on four-class kernel support"
            ),
            "source_mass": (
                "M_b(n)=sum_(lambda_1>=n-b) d_lambda^2/n!"
            ),
            "physical_label_mass": (
                "after equal signs are summed, physical labels are "
                "unordered pairs of iid Plancherel partitions; mass=M_b(n)^2"
            ),
            "fixed_tail_bound": (
                "for fixed b, each d_(n-|tau|,tau) is polynomial in n, "
                "so M_b(n)=poly_b(n)/n! and vanishes"
            ),
        },
        rank_records=rank_records,
        mass_records=mass_records,
        headline_metrics=metrics,
        claim_gate={
            "stable_feature_algebra_finite_rank_measured": True,
            "fixed_tail_plancherel_mass_vanishing_proved": True,
            "stable_sector_has_typical_natural_mass": False,
            "polynomial_typical_four_class_contraction_proved": False,
            "support_gap_theorem_proved": False,
            "coherent_blockwise_frame_pseudoinverse_proved": False,
            "polynomial_hidden_permutation_decoder_proved": False,
            "speedup_claim_allowed": False,
            "reason": (
                "Bounded-tail stable sectors can be algebraically structured "
                "but have vanishing Plancherel and physical-label mass. "
                "Typical partitions must be handled."
            ),
        },
        status=(
            "stable-sector-shortcut-rejected-"
            "typical-partition-recoupling-required"
        ),
        summary=(
            "Measured stable physical feature algebras on four-class kernels "
            f"through n={metrics['maximum_rank_control_n']} and proved fixed-"
            "tail physical label mass vanishes through scaling n="
            f"{metrics['maximum_mass_scaling_n']}; typical-sector coverage "
            "and decoding remain zero."
        ),
        falsifiers_triggered=[
            "Stable physical features can have nontrivial finite Hadamard-algebra growth.",
            "The physical irrep label law reduces to two independent Plancherel source partitions after sign aggregation.",
            "Every fixed bounded-tail partition family has only polynomial total squared dimension over n!.",
            "Consequently bounded-tail physical label mass and all-threshold-copy mass vanish.",
            "A stable character-polynomial contraction cannot establish a typical-sector decoder.",
        ],
    )


def write_self_dual_wreath_stable_commutator_rank(
    path: Path = SELF_DUAL_WREATH_STABLE_COMMUTATOR_RANK_PATH,
    write_registry: bool = True,
    registry_experiment_id: str = DEFAULT_EXPERIMENT_ID,
    registry_candidate_id: str = DEFAULT_CANDIDATE_ID,
    registry_result_id: str | None = None,
) -> dict[str, Any]:
    payload = asdict(run_self_dual_wreath_stable_commutator_rank())
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, indent=2, sort_keys=True))
    return payload


if __name__ == "__main__":
    report = write_self_dual_wreath_stable_commutator_rank()
    print(json.dumps(report["headline_metrics"], indent=2, sort_keys=True))
