"""Parity-component reduction of the homogeneous orientation incidence.

Use the homogeneous model

    Omega = Gamma semidirect B,
    Gamma = S_n^(2K+1),  B=C_2^K,

with zero-orientation diagonal subgroup ``D``.  For
``gamma=(t,x_1,y_1,...,x_K,y_K)``, define the syndrome

    z_i(gamma) = sgn(t) + sgn(x_i) + sgn(y_i) mod 2.       (1)

Pair swaps preserve (1), so it extends to a homomorphism
``z:Omega->F_2^K``.  Both ``B`` and ``D`` lie in its kernel.

For ``n>=5``, the affine generated-subgroup theorem identifies the subgroup
generated by all orientation diagonals as the preimage of the incidence sign
code, with an independent ``A_n`` on every target/source coordinate.  Since
``B`` conjugates ``D`` through all orientations,

    L=<B,D>=ker(z),
    |L|=|S_n|^(2K+1),
    [Omega:L]=2^K.                                         (2)

The bipartite incidence between ``Omega/D`` and ``Omega/B`` has connected
components equal to right ``L`` cosets.  Hence the complete synthesis and its
polar split as

    T  is unitarily equivalent to I_(2^K) tensor T_0,
    polar(T) is unitarily equivalent to I_(2^K) tensor polar(T_0),  (3)

where ``T_0`` is the connected incidence ``L/D -> L/B``.  Its source and
physical dimensions are respectively

    |L:D|=|S_n|^(2K),   |L:B|=|S_n|^(2K+1)/2^K.             (4)

The syndrome is efficiently computable from permutation parities.  A fixed
odd permutation in the first coordinate of pair ``i`` supplies a representative
for syndrome bit ``i``; controlled multiplication canonicalizes every component
to zero syndrome.  Thus future compiler work only needs one connected block.

This is a structural reduction, not the polar.  Branch-controlled translations,
syndrome Fourier transforms, and other unitaries acting before or after the
normalized incidence ``T_0/sqrt(2^K)`` preserve all singular values.  They
cannot turn it into its polar unless its nonzero singular values were already
one.  The finite controls have a constant distance from that condition, while
the natural flat benchmark has singular amplitude ``Theta(|S_n|^-1/2)``.
Syndrome relocation therefore removes component replication but not the
inverse-width normalization or the high-rank matrix-CS recoupling.

The syndrome is a conserved gauge charge, not a hidden-label statistic.  No
orientation-polar circuit, decoder, classical separation, or speedup is
claimed.
"""

from __future__ import annotations

import json
import math
from collections import deque
from dataclasses import asdict, dataclass
from pathlib import Path
from typing import Any

import numpy as np

from research_registry import utc_now
from self_dual_wreath_orientation_homogeneous_space_polar import (
    GammaElement,
    OmegaElement,
    _group_data,
    _identity,
    direct_orientation_synthesis,
    omega_multiply,
)


REPORT_PATH = Path(
    "research/representation/"
    "self_dual_wreath_orientation_syndrome_component_reduction.json"
)
DEFAULT_EXPERIMENT_ID = (
    "EXP-CODE-SELF-DUAL-WREATH-ORIENTATION-SYNDROME-COMPONENT-REDUCTION"
)
DEFAULT_CANDIDATE_ID = "CODE-COSET-COLLECTIVE"


@dataclass(frozen=True)
class SyndromeComponentControl:
    n: int
    copy_count: int
    orientation_count: int
    omega_order: int
    generated_subgroup_order: int
    syndrome_kernel_order: int
    generated_subgroup_equals_syndrome_kernel: bool
    component_count: int
    predicted_component_count: int
    physical_component_dimension: int
    source_component_dimension: int
    maximum_off_syndrome_incidence: float
    maximum_component_singular_spectrum_residual: float
    maximum_syndrome_canonicalization_failure_count: int
    minimum_normalized_component_positive_singular_value: float
    maximum_normalized_component_positive_singular_value: float
    minimum_unitary_only_distance_to_component_polar: float
    exact_syndrome_component_reduction_verified: bool
    status: str


@dataclass(frozen=True)
class SyndromeComponentScalingRecord:
    n: int
    group_order_log2: float
    copy_count: int
    component_count_log2: int
    connected_group_order_log2: float
    source_component_dimension_log2: float
    physical_component_dimension_log2: float
    source_to_physical_component_dimension_ratio: float
    frame_first_moment_per_physical_dimension: float
    frame_second_to_first_moment_ratio: float
    total_support_rank_fraction_lower_bound: float
    flat_benchmark_normalized_singular_amplitude_log2: float
    syndrome_computation_polynomial: bool
    zero_component_canonicalization_polynomial: bool
    syndrome_only_polar_compiler_proved: bool
    status: str


@dataclass(frozen=True)
class SyndromeComponentTheorem:
    syndrome: str
    generated_group: str
    incidence_components: str
    polar_reduction: str
    canonicalization: str
    unitary_only_boundary: str
    compiler_target: str
    scope: str
    theorem_verified: bool
    status: str


@dataclass(frozen=True)
class SyndromeComponentReport:
    created_at: str
    theorem_contract: dict[str, Any]
    theorem: SyndromeComponentTheorem
    finite_controls: list[SyndromeComponentControl]
    scaling_records: list[SyndromeComponentScalingRecord]
    proof_obligations: list[dict[str, str | bool]]
    adversarial_audit: list[dict[str, str | bool]]
    headline_metrics: dict[str, int | float]
    claim_gate: dict[str, str | bool]
    status: str
    summary: str
    falsifiers_triggered: list[str]


def permutation_parity(permutation: tuple[int, ...]) -> int:
    inversions = sum(
        permutation[left] > permutation[right]
        for left in range(len(permutation))
        for right in range(left + 1, len(permutation))
    )
    return inversions & 1


def component_syndrome(gamma: GammaElement) -> int:
    if len(gamma) % 2 != 1:
        raise ValueError("Gamma must have one target and source pairs")
    copy_count = (len(gamma) - 1) // 2
    target = permutation_parity(gamma[0])
    syndrome = 0
    for pair_index in range(copy_count):
        bit = (
            target
            ^ permutation_parity(gamma[1 + 2 * pair_index])
            ^ permutation_parity(gamma[2 + 2 * pair_index])
        )
        syndrome |= bit << pair_index
    return syndrome


def omega_syndrome(element: OmegaElement) -> int:
    return component_syndrome(element[0])


def syndrome_representative(
    n: int,
    copy_count: int,
    syndrome: int,
) -> OmegaElement:
    if n < 2 or not 0 <= syndrome < 1 << copy_count:
        raise ValueError("invalid degree, copy count, or syndrome")
    identity = _identity(n)
    odd = list(range(n))
    odd[0], odd[1] = odd[1], odd[0]
    gamma = [identity for _ in range(2 * copy_count + 1)]
    for pair_index in range(copy_count):
        if syndrome & (1 << pair_index):
            gamma[1 + 2 * pair_index] = tuple(odd)
    return tuple(gamma), 0


def _generated_subgroup(
    generators: tuple[OmegaElement, ...],
) -> frozenset[OmegaElement]:
    if not generators:
        raise ValueError("at least one generator is required")
    identity_gamma = tuple(
        _identity(len(generators[0][0][0])) for _ in generators[0][0]
    )
    identity: OmegaElement = (identity_gamma, 0)
    found = {identity}
    queue: deque[OmegaElement] = deque((identity,))
    while queue:
        current = queue.popleft()
        for generator in generators:
            image = omega_multiply(current, generator)
            if image not in found:
                found.add(image)
                queue.append(image)
    return frozenset(found)


def _source_column_syndromes(
    n: int,
    copy_count: int,
    labels: tuple[tuple[int, int], ...],
    gamma: tuple[GammaElement, ...],
) -> tuple[int, ...]:
    del n, copy_count
    return tuple(component_syndrome(gamma[label]) for _orientation, label in labels)


def audit_syndrome_component_reduction(
    n: int,
    copy_count: int,
    *,
    tolerance: float = 1e-9,
) -> SyndromeComponentControl:
    group, gamma, omega, branch_subgroup, diagonal_subgroup = _group_data(
        n,
        copy_count,
    )
    generated = _generated_subgroup(branch_subgroup + diagonal_subgroup)
    kernel = frozenset(element for element in omega if omega_syndrome(element) == 0)
    synthesis, labels, direct_gamma = direct_orientation_synthesis(n, copy_count)
    row_syndromes = tuple(component_syndrome(point) for point in direct_gamma)
    column_syndromes = _source_column_syndromes(
        n,
        copy_count,
        labels,
        direct_gamma,
    )
    orientation_count = 1 << copy_count
    blocks: list[np.ndarray] = []
    off_syndrome = 0.0
    for row in range(synthesis.shape[0]):
        for column in np.flatnonzero(np.abs(synthesis[row]) > tolerance):
            if row_syndromes[row] != column_syndromes[column]:
                off_syndrome = max(off_syndrome, abs(float(synthesis[row, column])))
    for syndrome in range(orientation_count):
        rows = [index for index, value in enumerate(row_syndromes) if value == syndrome]
        columns = [
            index for index, value in enumerate(column_syndromes) if value == syndrome
        ]
        blocks.append(synthesis[np.ix_(rows, columns)])
    reference = np.linalg.svd(blocks[0], compute_uv=False)
    spectrum_residual = max(
        float(np.max(np.abs(np.linalg.svd(block, compute_uv=False) - reference)))
        for block in blocks
    )
    normalized_positive = reference[reference > tolerance] / math.sqrt(orientation_count)
    unitary_distance = max(
        abs(1.0 - float(value)) for value in normalized_positive
    )

    canonicalization_failures = 0
    for element in omega:
        syndrome = omega_syndrome(element)
        representative = syndrome_representative(n, copy_count, syndrome)
        if omega_syndrome(omega_multiply(representative, element)) != 0:
            canonicalization_failures += 1

    expected_component_count = orientation_count
    physical_component_dimension = len(gamma) // orientation_count
    source_component_dimension = synthesis.shape[1] // orientation_count
    verified = bool(
        generated == kernel
        and len(kernel) * orientation_count == len(omega)
        and off_syndrome <= tolerance
        and spectrum_residual <= tolerance
        and canonicalization_failures == 0
        and all(block.shape == blocks[0].shape for block in blocks)
    )
    return SyndromeComponentControl(
        n=n,
        copy_count=copy_count,
        orientation_count=orientation_count,
        omega_order=len(omega),
        generated_subgroup_order=len(generated),
        syndrome_kernel_order=len(kernel),
        generated_subgroup_equals_syndrome_kernel=generated == kernel,
        component_count=len(blocks),
        predicted_component_count=expected_component_count,
        physical_component_dimension=physical_component_dimension,
        source_component_dimension=source_component_dimension,
        maximum_off_syndrome_incidence=off_syndrome,
        maximum_component_singular_spectrum_residual=spectrum_residual,
        maximum_syndrome_canonicalization_failure_count=canonicalization_failures,
        minimum_normalized_component_positive_singular_value=float(
            np.min(normalized_positive)
        ),
        maximum_normalized_component_positive_singular_value=float(
            np.max(normalized_positive)
        ),
        minimum_unitary_only_distance_to_component_polar=unitary_distance,
        exact_syndrome_component_reduction_verified=verified,
        status=(
            "exact-syndrome-components-reduced-to-one-connected-incidence"
            if verified
            else "syndrome-component-control-failure"
        ),
    )


def syndrome_component_scaling_record(
    n: int,
    *,
    extra_copies: int = 2,
) -> SyndromeComponentScalingRecord:
    if n < 5 or extra_copies < 0:
        raise ValueError("n>=5 and nonnegative copy offset are required")
    group_order = math.factorial(n)
    group_log2 = math.log2(group_order)
    copy_count = (group_order - 1).bit_length() + extra_copies
    orientation_count = 1 << copy_count
    ratio = orientation_count / group_order
    gamma = 1.0 + (orientation_count - 1) / group_order
    return SyndromeComponentScalingRecord(
        n=n,
        group_order_log2=group_log2,
        copy_count=copy_count,
        component_count_log2=copy_count,
        connected_group_order_log2=(2 * copy_count + 1) * group_log2,
        source_component_dimension_log2=2 * copy_count * group_log2,
        physical_component_dimension_log2=(
            (2 * copy_count + 1) * group_log2 - copy_count
        ),
        source_to_physical_component_dimension_ratio=ratio,
        frame_first_moment_per_physical_dimension=ratio,
        frame_second_to_first_moment_ratio=gamma,
        total_support_rank_fraction_lower_bound=ratio / gamma,
        flat_benchmark_normalized_singular_amplitude_log2=-0.5 * group_log2,
        syndrome_computation_polynomial=True,
        zero_component_canonicalization_polynomial=True,
        syndrome_only_polar_compiler_proved=False,
        status="one-connected-component-canonicalized-matrix-cs-polar-open",
    )


def run_syndrome_component_reduction() -> SyndromeComponentReport:
    controls = [
        audit_syndrome_component_reduction(2, 1),
        audit_syndrome_component_reduction(2, 2),
        audit_syndrome_component_reduction(3, 1),
    ]
    scaling = [
        syndrome_component_scaling_record(n)
        for n in (5, 6, 8, 10, 12, 16, 20, 24, 32, 48, 64, 96, 128)
    ]
    failures = sum(
        not row.exact_syndrome_component_reduction_verified for row in controls
    )
    verified = failures == 0
    theorem = SyndromeComponentTheorem(
        syndrome="z_i=sgn(t)+sgn(x_i)+sgn(y_i) mod 2",
        generated_group=(
            "For n>=5, <B,D>=ker(z)=N semidirect B, where N is the full "
            "orientation-diagonal generated subgroup."
        ),
        incidence_components=(
            "Connected components of the Omega/D--Omega/B incidence are right "
            "cosets of ker(z), hence are indexed by F_2^K."
        ),
        polar_reduction="T is equivalent to I_(2^K) tensor T_0, and so is polar(T).",
        canonicalization=(
            "Compute permutation parities and multiply controlled odd-coordinate "
            "representatives to map every component coherently to syndrome zero."
        ),
        unitary_only_boundary=(
            "Syndrome translations and Fourier transforms preserve singular "
            "values of T_0/sqrt(2^K) and cannot supply its polar normalization."
        ),
        compiler_target=(
            "Compile the single connected L/D->L/B matrix-CS polar after "
            "syndrome canonicalization."
        ),
        scope=(
            "No connected-component CS transform, complete orientation polar, "
            "hidden-label statistic, classical separation, or speedup."
        ),
        theorem_verified=verified,
        status=(
            "orientation-polar-reduced-to-one-syndrome-connected-component"
            if verified
            else "orientation-syndrome-component-control-failure"
        ),
    )
    return SyndromeComponentReport(
        created_at=utc_now(),
        theorem_contract=asdict(theorem),
        theorem=theorem,
        finite_controls=controls,
        scaling_records=scaling,
        proof_obligations=[
            {
                "obligation": "identify_branch_diagonal_generated_subgroup",
                "resolved": True,
                "resolution": (
                    "The affine orientation theorem gives the full incidence sign "
                    "code and independent alternating factors; adjoining B gives ker(z)."
                ),
            },
            {
                "obligation": "decompose_incidence_and_polar_by_syndrome",
                "resolved": verified,
                "resolution": (
                    "Three finite quotient controls have exactly 2^K blocks, zero "
                    "off-syndrome incidence, and identical singular spectra."
                ),
            },
            {
                "obligation": "compile_component_canonicalization",
                "resolved": verified,
                "resolution": (
                    "Permutation parity and K controlled odd-coordinate multiplications "
                    "map every tested element to the zero-syndrome kernel."
                ),
            },
            {
                "obligation": "compile_connected_component_matrix_cs_polar",
                "resolved": False,
                "resolution": (
                    "Canonicalization removes replicated components but leaves the "
                    "same nonunit singular spectrum and many-way recoupling."
                ),
            },
        ],
        adversarial_audit=[
            {
                "objection": "The K syndrome bits are hidden-label information.",
                "resolved": True,
                "resolution": (
                    "They are conserved component charges of the regular incidence "
                    "and are independent of the hidden permutation label."
                ),
            },
            {
                "objection": "Relocating the branch index into syndrome implements the polar.",
                "resolved": True,
                "resolution": (
                    "Branch-controlled translations are unitary and preserve every "
                    "singular value; the finite normalized blocks remain separated "
                    "from a partial isometry."
                ),
            },
            {
                "objection": "The 2^K components create an independent exponential compiler cost.",
                "resolved": True,
                "resolution": (
                    "False. Compute and canonicalize the K-bit syndrome coherently, "
                    "then apply one zero-component compiler if it is found."
                ),
            },
            {
                "objection": "Connectedness of T_0 supplies a useful spectral gap.",
                "resolved": True,
                "resolution": (
                    "False. Graph connectedness only removes exact component "
                    "multiplicity and gives no lower bound on principal angles."
                ),
            },
        ],
        headline_metrics={
            "syndrome_kernel_generated_subgroup_theorem_count": 1,
            "identical_component_polar_reduction_theorem_count": int(verified),
            "finite_control_count": len(controls),
            "finite_control_failure_count": failures,
            "maximum_off_syndrome_incidence": max(
                row.maximum_off_syndrome_incidence for row in controls
            ),
            "maximum_component_spectrum_residual": max(
                row.maximum_component_singular_spectrum_residual for row in controls
            ),
            "minimum_finite_unitary_only_polar_distance": min(
                row.minimum_unitary_only_distance_to_component_polar
                for row in controls
            ),
            "scaling_record_count": len(scaling),
            "syndrome_canonicalization_compiler_count": int(verified),
            "connected_component_matrix_cs_polar_compiler_count": 0,
            "complete_orientation_polar_compiler_count": 0,
            "new_quantum_algorithm_count": 0,
        },
        claim_gate={
            "branch_diagonal_generated_group_equals_syndrome_kernel": True,
            "complete_polar_is_repeated_zero_syndrome_component_polar": verified,
            "syndrome_computation_and_canonicalization_compiled": verified,
            "syndrome_is_hidden_label_signal": False,
            "syndrome_only_unitaries_compile_connected_polar": False,
            "connected_component_matrix_cs_polar_compiled": False,
            "complete_natural_orientation_polar_compiled": False,
            "classical_separation_proved": False,
            "speedup_claim_allowed": False,
            "reason": (
                "The exact K-bit component replication is removable at polynomial "
                "cost, but the single connected matrix-CS polar retains the full "
                "normalization and recoupling obstruction."
            ),
        },
        status=theorem.status,
        summary=(
            "Identified the exact parity quotient, reduced all orientation-polar "
            "components to one coherently canonical zero-syndrome incidence, and "
            "proved that syndrome relocation alone cannot polarize it."
        ),
        falsifiers_triggered=[
            "The apparent 2^K component replication is not an independent circuit barrier.",
            "The component syndrome is a conserved gauge charge, not a hidden-label statistic.",
            "Unitary syndrome relocation preserves the normalized incidence singular values and is not the missing polar.",
        ],
    )


def write_syndrome_component_reduction_report(
    path: Path = REPORT_PATH,
) -> dict[str, Any]:
    payload = asdict(run_syndrome_component_reduction())
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, indent=2, sort_keys=True) + "\n")
    return payload


if __name__ == "__main__":
    report = write_syndrome_component_reduction_report()
    print(json.dumps(report["headline_metrics"], indent=2, sort_keys=True))
