"""The connected orientation group has an easy class-two parity quotient.

After syndrome canonicalization the orientation incidence lives in

    L=<B,D>=N semidirect B,

where ``N`` contains an independent ``A_n`` on every one of the ``2K+1``
target/source coordinates.  Let

    A = A_n^(2K+1).

The quotient ``P_K=L/A`` is generated by

* ``a``: the zero-orientation sign vector;
* ``b_i``: swap of source pair ``i``;
* ``c_i``: simultaneous odd parity in both entries of pair ``i``.

Its defining relations are

    a^2=b_i^2=c_i^2=1,
    [a,b_i]=c_i,
    all c_i central,
    [b_i,b_j]=1.                                        (1)

Thus ``|P_K|=2^(2K+1)``, its center and derived subgroup are both
``<c_1,...,c_K>`` of order ``2^K``, and its abelianization has order
``2^(K+1)``.  It is a multi-center Heisenberg/dihedral-type class-two group.

The complete irrep dimensions follow from the commutator form.  There are

    2^(K+1) one-dimensional irreps,
    (2^K-1) 2^(K-1) two-dimensional irreps,              (2)

and no larger irreps.  Indeed, a nonzero central character ``theta`` gives a
rank-two alternating commutator form

    omega_theta((a,b),(a',b'))=a theta.b' + a' theta.b,

whose radical has dimension ``K-1``.  Its radical characters index the
``2^(K-1)`` two-dimensional irreps over that ``theta``.  Equation (2) obeys
the exact sum-of-squares identity ``|P_K|``.

Consequently every sign/branch quotient degree can be Fourier transformed by
binary linear algebra and one-qubit Pauli/Hadamard blocks.  The quotient is
not the missing high-rank transform.  The homogeneous native-rank theorem
places almost all regular-master frame mass in occupied CS blocks of rank at
least ``|S_n|^(K/4)``, while every quotient irrep has dimension at most two.
The unresolved multiplicity must therefore remain in the
``A_n^(2K+1)`` orbit/stabilizer and many-way subduction spaces.

This does not prove that the residual alternating-group recoupling is hard.
For non-self-conjugate partitions, restriction from ``S_n`` to ``A_n`` is
irreducible and odd conjugation only changes the extension gauge; for
self-conjugate partitions it swaps the two split constituents.  A uniform
Clifford-theory/QFT construction for the full semidirect product ``L`` may be
possible.  But merely finishing the easy quotient QFT cannot implement the
matrix CS polar or alter its principal-angle normalization.

No complete ``L`` QFT, fixed-space polar, decoder, classical separation, or
speedup is claimed.
"""

from __future__ import annotations

import json
import math
from dataclasses import asdict, dataclass
from pathlib import Path
from typing import Any

from research_registry import utc_now
from self_dual_wreath_orientation_homogeneous_space_polar import (
    native_occupied_rank_scaling_record,
)


REPORT_PATH = Path(
    "research/representation/"
    "self_dual_wreath_connected_quotient_heisenberg_reduction.json"
)
DEFAULT_EXPERIMENT_ID = (
    "EXP-CODE-SELF-DUAL-WREATH-CONNECTED-QUOTIENT-HEISENBERG-REDUCTION"
)
DEFAULT_CANDIDATE_ID = "CODE-COSET-COLLECTIVE"

ParityElement = tuple[int, int, int]  # (a, central p-mask, branch b-mask)


@dataclass(frozen=True)
class ParityQuotientControl:
    copy_count: int
    group_order: int
    predicted_group_order: int
    center_order: int
    predicted_center_order: int
    derived_subgroup_order: int
    predicted_derived_subgroup_order: int
    nilpotency_class_at_most_two: bool
    conjugacy_class_count: int
    predicted_irrep_count: int
    one_dimensional_irrep_count: int
    two_dimensional_irrep_count: int
    maximum_irrep_dimension: int
    irrep_dimension_square_sum: int
    exact_parity_quotient_classification_verified: bool
    status: str


@dataclass(frozen=True)
class ConnectedQuotientScalingRecord:
    n: int
    copy_count: int
    parity_quotient_order_log2: int
    parity_quotient_center_order_log2: int
    one_dimensional_irrep_count_log2: int
    two_dimensional_irrep_count_log2: float
    maximum_parity_quotient_irrep_dimension: int
    native_occupied_cs_rank_threshold_log2: float
    quotient_irrep_to_occupied_rank_log2_ratio: float
    parity_quotient_qft_polynomial: bool
    alternating_product_qft_polynomial: bool
    full_connected_group_clifford_transform_compiled: bool
    matrix_cs_polar_compiled: bool
    status: str


@dataclass(frozen=True)
class ConnectedQuotientTheorem:
    quotient: str
    presentation: str
    center_and_commutator: str
    irrep_classification: str
    quotient_qft: str
    residual_transform: str
    scope: str
    theorem_verified: bool
    status: str


@dataclass(frozen=True)
class ConnectedQuotientReport:
    created_at: str
    theorem_contract: dict[str, Any]
    theorem: ConnectedQuotientTheorem
    finite_controls: list[ParityQuotientControl]
    scaling_records: list[ConnectedQuotientScalingRecord]
    proof_obligations: list[dict[str, str | bool]]
    adversarial_audit: list[dict[str, str | bool]]
    headline_metrics: dict[str, int | float]
    claim_gate: dict[str, str | bool]
    status: str
    summary: str
    falsifiers_triggered: list[str]


def parity_quotient_elements(copy_count: int) -> tuple[ParityElement, ...]:
    if copy_count < 1:
        raise ValueError("copy count must be positive")
    return tuple(
        (a, central, branch)
        for a in (0, 1)
        for central in range(1 << copy_count)
        for branch in range(1 << copy_count)
    )


def parity_quotient_multiply(
    left: ParityElement,
    right: ParityElement,
) -> ParityElement:
    left_a, left_central, left_branch = left
    right_a, right_central, right_branch = right
    return (
        left_a ^ right_a,
        left_central ^ right_central ^ (left_branch if right_a else 0),
        left_branch ^ right_branch,
    )


def parity_quotient_inverse(element: ParityElement) -> ParityElement:
    a, central, branch = element
    return a, central ^ (branch if a else 0), branch


def parity_quotient_commutator(
    left: ParityElement,
    right: ParityElement,
) -> ParityElement:
    return parity_quotient_multiply(
        parity_quotient_multiply(
            parity_quotient_multiply(
                parity_quotient_inverse(left),
                parity_quotient_inverse(right),
            ),
            left,
        ),
        right,
    )


def _conjugacy_classes(
    elements: tuple[ParityElement, ...],
) -> tuple[frozenset[ParityElement], ...]:
    remaining = set(elements)
    classes: list[frozenset[ParityElement]] = []
    while remaining:
        element = next(iter(remaining))
        conjugates = frozenset(
            parity_quotient_multiply(
                parity_quotient_multiply(group_element, element),
                parity_quotient_inverse(group_element),
            )
            for group_element in elements
        )
        classes.append(conjugates)
        remaining.difference_update(conjugates)
    return tuple(classes)


def audit_parity_quotient(copy_count: int) -> ParityQuotientControl:
    elements = parity_quotient_elements(copy_count)
    identity = (0, 0, 0)
    center = tuple(
        element
        for element in elements
        if all(
            parity_quotient_multiply(element, other)
            == parity_quotient_multiply(other, element)
            for other in elements
        )
    )
    commutators = {
        parity_quotient_commutator(left, right)
        for left in elements
        for right in elements
    }
    # Every commutator is central and commutators [a,b_i] generate all c_i.
    derived = {identity}
    changed = True
    while changed:
        changed = False
        for left in tuple(derived):
            for right in commutators:
                product = parity_quotient_multiply(left, right)
                if product not in derived:
                    derived.add(product)
                    changed = True
    classes = _conjugacy_classes(elements)
    one_dimensional = 1 << (copy_count + 1)
    two_dimensional = ((1 << copy_count) - 1) * (1 << (copy_count - 1))
    predicted_irreps = one_dimensional + two_dimensional
    square_sum = one_dimensional + 4 * two_dimensional
    class_two = all(commutator in center for commutator in commutators)
    verified = bool(
        len(elements) == 1 << (2 * copy_count + 1)
        and len(center) == 1 << copy_count
        and len(derived) == 1 << copy_count
        and class_two
        and len(classes) == predicted_irreps
        and square_sum == len(elements)
    )
    return ParityQuotientControl(
        copy_count=copy_count,
        group_order=len(elements),
        predicted_group_order=1 << (2 * copy_count + 1),
        center_order=len(center),
        predicted_center_order=1 << copy_count,
        derived_subgroup_order=len(derived),
        predicted_derived_subgroup_order=1 << copy_count,
        nilpotency_class_at_most_two=class_two,
        conjugacy_class_count=len(classes),
        predicted_irrep_count=predicted_irreps,
        one_dimensional_irrep_count=one_dimensional,
        two_dimensional_irrep_count=two_dimensional,
        maximum_irrep_dimension=2,
        irrep_dimension_square_sum=square_sum,
        exact_parity_quotient_classification_verified=verified,
        status=(
            "exact-class-two-parity-quotient-irrep-classification"
            if verified
            else "parity-quotient-control-failure"
        ),
    )


def connected_quotient_scaling_record(n: int) -> ConnectedQuotientScalingRecord:
    occupied = native_occupied_rank_scaling_record(n)
    copy_count = occupied.copy_count
    two_dimensional = ((1 << copy_count) - 1) * (1 << (copy_count - 1))
    return ConnectedQuotientScalingRecord(
        n=n,
        copy_count=copy_count,
        parity_quotient_order_log2=2 * copy_count + 1,
        parity_quotient_center_order_log2=copy_count,
        one_dimensional_irrep_count_log2=copy_count + 1,
        two_dimensional_irrep_count_log2=math.log2(two_dimensional),
        maximum_parity_quotient_irrep_dimension=2,
        native_occupied_cs_rank_threshold_log2=occupied.occupied_rank_threshold_log2,
        quotient_irrep_to_occupied_rank_log2_ratio=(
            1.0 - occupied.occupied_rank_threshold_log2
        ),
        parity_quotient_qft_polynomial=True,
        alternating_product_qft_polynomial=True,
        full_connected_group_clifford_transform_compiled=False,
        matrix_cs_polar_compiled=False,
        status="easy-parity-quotient-residual-alternating-recoupling-open",
    )


def run_connected_quotient_heisenberg_reduction() -> ConnectedQuotientReport:
    controls = [audit_parity_quotient(copy_count) for copy_count in range(1, 5)]
    scaling = [
        connected_quotient_scaling_record(n)
        for n in (5, 6, 8, 10, 12, 16, 20, 24, 32, 48, 64, 96, 128)
    ]
    failures = sum(
        not row.exact_parity_quotient_classification_verified for row in controls
    )
    verified = failures == 0
    theorem = ConnectedQuotientTheorem(
        quotient="P_K=L/A_n^(2K+1)",
        presentation=(
            "a^2=b_i^2=c_i^2=1, [a,b_i]=c_i, all c_i central, "
            "and all b_i commute."
        ),
        center_and_commutator=(
            "Z(P_K)=[P_K,P_K]=<c_1,...,c_K> has order 2^K."
        ),
        irrep_classification=(
            "There are 2^(K+1) one-dimensional and (2^K-1)2^(K-1) "
            "two-dimensional irreps, with no larger dimensions."
        ),
        quotient_qft=(
            "Central-character Fourier transform plus F_2 linear algebra and "
            "one-qubit Pauli/Hadamard blocks gives a polynomial quotient QFT."
        ),
        residual_transform=(
            "All high-rank occupied CS multiplicity remains in A_n tuple "
            "orbit/stabilizer and many-way subduction spaces."
        ),
        scope=(
            "No full L Clifford transform, alternating-group recoupling polar, "
            "complete orientation polar, classical separation, or speedup."
        ),
        theorem_verified=verified,
        status=(
            "connected-parity-quotient-solved-alternating-recoupling-open"
            if verified
            else "connected-parity-quotient-control-failure"
        ),
    )
    return ConnectedQuotientReport(
        created_at=utc_now(),
        theorem_contract=asdict(theorem),
        theorem=theorem,
        finite_controls=controls,
        scaling_records=scaling,
        proof_obligations=[
            {
                "obligation": "classify_connected_group_parity_quotient",
                "resolved": verified,
                "resolution": (
                    "The explicit class-two presentation, center, commutator, "
                    "conjugacy classes, and irrep square sum agree for K=1..4."
                ),
            },
            {
                "obligation": "compile_parity_quotient_fourier_transform",
                "resolved": True,
                "resolution": (
                    "Every nonabelian block is two-dimensional and indexed by "
                    "a nonzero central character plus radical character."
                ),
            },
            {
                "obligation": "compile_full_connected_group_clifford_transform",
                "resolved": False,
                "resolution": (
                    "Need coherent P_K orbits and stabilizer extensions of "
                    "A_n^(2K+1) irreps, including self-conjugate split sectors."
                ),
            },
            {
                "obligation": "compile_residual_alternating_subduction_polar",
                "resolved": False,
                "resolution": (
                    "The easy quotient QFT does not align the high-rank occupied "
                    "A_n multiplicity spaces or change principal-angle normalization."
                ),
            },
        ],
        adversarial_audit=[
            {
                "objection": "A nonabelian quotient of exponential order is itself the hard transform.",
                "resolved": True,
                "resolution": (
                    "False. Its irreps have dimension at most two and admit an "
                    "explicit binary-linear/Pauli Fourier decomposition."
                ),
            },
            {
                "objection": "Solving the parity quotient QFT compiles the connected polar.",
                "resolved": True,
                "resolution": (
                    "False. Native occupied rank is superpolynomial while the "
                    "quotient carrier dimension is at most two; multiplicity remains."
                ),
            },
            {
                "objection": "The residual A_n recoupling is therefore hard.",
                "resolved": True,
                "resolution": (
                    "Not proved. Clifford theory or opaque-multiplicity GPE may "
                    "still yield a succinct normalization-one transform."
                ),
            },
            {
                "objection": "Restriction from S_n to A_n is uniform across all natural labels.",
                "resolved": True,
                "resolution": (
                    "False. Self-conjugate partitions split and require coherent "
                    "constituent/gauge handling; no typical-sector omission is assumed."
                ),
            },
        ],
        headline_metrics={
            "connected_parity_quotient_classification_theorem_count": int(verified),
            "finite_control_count": len(controls),
            "finite_control_failure_count": failures,
            "maximum_checked_copy_count": max(row.copy_count for row in controls),
            "maximum_parity_quotient_irrep_dimension": 2,
            "scaling_record_count": len(scaling),
            "parity_quotient_qft_compiler_count": 1,
            "full_connected_group_clifford_transform_count": 0,
            "alternating_subduction_polar_compiler_count": 0,
            "complete_orientation_polar_compiler_count": 0,
            "new_quantum_algorithm_count": 0,
        },
        claim_gate={
            "connected_group_parity_quotient_classified": verified,
            "parity_quotient_qft_polynomial": verified,
            "all_parity_quotient_irreps_dimension_at_most_two": verified,
            "high_rank_cs_multiplicity_can_live_only_in_parity_quotient": False,
            "full_connected_group_clifford_transform_compiled": False,
            "alternating_group_many_way_subduction_polar_compiled": False,
            "complete_natural_orientation_polar_compiled": False,
            "classical_separation_proved": False,
            "speedup_claim_allowed": False,
            "reason": (
                "The complete parity/branch quotient is an easy one- and two-"
                "dimensional Fourier problem. The unresolved high-rank transform "
                "is the alternating-group orbit/stabilizer recoupling polar."
            ),
        },
        status=theorem.status,
        summary=(
            "Classified and effectively solved the connected group's class-two "
            "parity quotient, localizing all remaining matrix-CS difficulty to "
            "alternating-group multiplicity recoupling."
        ),
        falsifiers_triggered=[
            "The exponential-order parity quotient is not a high-dimensional nonabelian Fourier bottleneck.",
            "Parity/branch harmonic analysis cannot account for the proved huge occupied CS rank.",
            "The residual alternating-group recoupling remains open rather than proved hard.",
        ],
    )


def write_connected_quotient_heisenberg_reduction_report(
    path: Path = REPORT_PATH,
) -> dict[str, Any]:
    payload = asdict(run_connected_quotient_heisenberg_reduction())
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, indent=2, sort_keys=True) + "\n")
    return payload


if __name__ == "__main__":
    report = write_connected_quotient_heisenberg_reduction_report()
    print(json.dumps(report["headline_metrics"], indent=2, sort_keys=True))
