"""Exact mixed-state covariant decoder criterion for the wreath HSP.

The physical source-conditioned HSP input is a normalized projector orbit,
not a pure matrix-coefficient state.  Let a finite group ``G`` act as

    U = direct_sum_nu rho_nu tensor I_(M_nu)

and let ``rho_g=U_g rho U_g^*``.  Its average is

    B = direct_sum_nu I_(d_nu)/d_nu tensor C_nu,
    C_nu = Tr_(V_nu)(Pi_nu rho Pi_nu).

A covariant POVM is generated by one positive seed ``E``.  On the support of
``B`` its exact completeness constraints are

    Tr_(V_nu)(Pi_nu E Pi_nu)
      = d_nu/|G| Pi_(supp C_nu).                         (1)

Writing ``E=sum_a |eta_a><eta_a|`` turns (1) into a tight-frame condition on
row-to-multiplicity maps.  If ``r_nu=rank(C_nu)``, every vector contributes
rank at most ``d_nu`` to the partial trace, so

    rank(E) >= max_nu ceil(r_nu/d_nu).                  (2)

Thus a single pure coherent Fourier seed is generally not a decoder for the
mixed physical state.  The canonical PGM seed is

    E_PGM = |G|^-1 B^-1/2 rho B^-1/2,                  (3)

which satisfies (1) exactly and has

    P_PGM = |G|^-1 Tr(B^-1/2 rho B^-1/2 rho).          (4)

Equations (1)--(4) replace the informal "extract one dual row" target by the
correct task: coherently implement a multiplicity tight frame, including the
sector operators ``C_nu^-1/2``, while preserving cross-sector coherence.

Finite physical W_3 controls below show that cross-isotypic coherence can
raise PGM success above the exact-label dephasing ceiling, while the required
seed rank is already greater than one.  A separate all-n frame-moment theorem
proves constant global PGM success.  These controls do not prove efficient
whitening, branchwise-uniform success, PGM optimality, or a new algorithm.
"""

from __future__ import annotations

import json
import math
from dataclasses import asdict, dataclass
from pathlib import Path
from typing import Any

import numpy as np

from representation_obstruction import hook_length_dimension, integer_partitions
from research_registry import utc_now
from self_dual_wreath_sector_weight_concentration import portfolio_sector_weight
from self_dual_wreath_subgroup_twirl_reduction import (
    Label,
    _base_tensor_projector,
    _direct_frame,
    _isotypic_projector,
    tuple_left_subgroup_matrices,
)


REPORT_PATH = Path(
    "research/representation/self_dual_wreath_mixed_covariant_decoder.json"
)
DEFAULT_EXPERIMENT_ID = (
    "EXP-CODE-SELF-DUAL-WREATH-MIXED-COVARIANT-DECODER"
)
DEFAULT_CANDIDATE_ID = "CODE-COSET-COLLECTIVE"

Partition = tuple[int, ...]


@dataclass(frozen=True)
class MixedDecoderSectorRecord:
    partition: Partition
    irrep_dimension: int
    sector_probability: float
    character_formula_sector_probability: float
    sector_probability_formula_residual: float
    multiplicity_support_rank: int
    minimum_seed_junk_rank: int
    pure_rank_one_sector_seed_possible: bool


@dataclass(frozen=True)
class MixedCovariantDecoderControl:
    control_id: str
    n: int
    labels: tuple[Label, ...]
    hidden_label_count: int
    physical_dimension: int
    base_projector_rank: int
    average_frame_support_rank: int
    pgm_seed_rank: int
    global_seed_junk_rank_lower_bound: int
    support_rank_global_lower_bound: int
    pure_coherent_fourier_seed_possible: bool
    pgm_correct_success_probability: float
    isotypically_dephased_pgm_seed_success_probability: float
    cross_isotypic_coherence_success_contribution: float
    exact_label_dephasing_success_upper_bound: float
    pgm_beats_exact_label_dephasing_ceiling: bool
    orbit_average_residual: float
    pgm_seed_support_completeness_residual: float
    minimum_pgm_seed_eigenvalue: float
    maximum_sector_probability_formula_residual: float
    sector_records: list[MixedDecoderSectorRecord]
    exact_finite_mixed_decoder_validation: bool
    finite_validation_only: bool
    status: str


@dataclass(frozen=True)
class MixedCovariantDecoderReport:
    created_at: str
    theorem_contract: dict[str, Any]
    finite_controls: list[MixedCovariantDecoderControl]
    proof_obligations: list[dict[str, bool | str]]
    adversarial_audit: list[dict[str, bool | str]]
    headline_metrics: dict[str, int | float]
    claim_gate: dict[str, bool | str]
    status: str
    summary: str
    falsifiers_triggered: list[str]


def _psd_support_and_inverse_sqrt(
    matrix: np.ndarray,
    tolerance: float,
) -> tuple[np.ndarray, np.ndarray, int]:
    hermitian = (matrix + matrix.conj().T) / 2
    eigenvalues, eigenvectors = np.linalg.eigh(hermitian)
    positive = eigenvalues > tolerance
    support = eigenvectors[:, positive] @ eigenvectors[:, positive].conj().T
    inverse_values = np.zeros_like(eigenvalues)
    inverse_values[positive] = 1 / np.sqrt(eigenvalues[positive])
    inverse_sqrt = (
        eigenvectors * inverse_values
    ) @ eigenvectors.conj().T
    return support, inverse_sqrt, int(np.count_nonzero(positive))


def canonical_pgm_seed(
    state: np.ndarray,
    average_state: np.ndarray,
    group_order: int,
    *,
    tolerance: float = 1e-10,
) -> np.ndarray:
    if group_order < 1:
        raise ValueError("group order must be positive")
    _, inverse_sqrt, _ = _psd_support_and_inverse_sqrt(
        average_state,
        tolerance,
    )
    seed = inverse_sqrt @ state @ inverse_sqrt / group_order
    return (seed + seed.conj().T) / 2


def minimum_covariant_seed_rank(
    sector_multiplicity_support: tuple[tuple[int, int], ...],
) -> int:
    """Return ``max_nu ceil(rank(C_nu)/d_nu)``."""

    if not sector_multiplicity_support:
        return 0
    bounds = []
    for dimension, support_rank in sector_multiplicity_support:
        if dimension < 1 or support_rank < 0:
            raise ValueError("sector dimensions and ranks must be valid")
        bounds.append(math.ceil(support_rank / dimension))
    return max(bounds)


def _matrix_rank(matrix: np.ndarray, tolerance: float) -> int:
    return int(np.count_nonzero(np.linalg.eigvalsh((matrix + matrix.T) / 2) > tolerance))


def audit_physical_projector_orbit(
    control_id: str,
    labels: tuple[Label, ...],
    *,
    tolerance: float = 1e-9,
) -> MixedCovariantDecoderControl:
    if not labels:
        raise ValueError("at least one physical label is required")
    n = sum(labels[0][0])
    if any(
        sum(left) != n or sum(right) != n or left == right
        for left, right in labels
    ):
        raise ValueError("unequal source partitions of one common size are required")

    group_order = math.factorial(n)
    group_rows = tuple_left_subgroup_matrices(labels)
    base_projector = _base_tensor_projector(labels)
    base_rank = int(round(float(np.trace(base_projector).real)))
    state = base_projector / base_rank
    average_projector = _direct_frame(labels)
    average_state = average_projector / base_rank
    support, _, support_rank = _psd_support_and_inverse_sqrt(
        average_state,
        tolerance,
    )
    seed = canonical_pgm_seed(
        state,
        average_state,
        group_order,
        tolerance=tolerance,
    )

    orbit_average = sum(
        matrix @ state @ matrix.conj().T
        for _, matrix in group_rows
    ) / group_order
    orbit_average_residual = float(
        np.linalg.norm(orbit_average - average_state, ord=2)
    )
    completeness = sum(
        matrix @ seed @ matrix.conj().T
        for _, matrix in group_rows
    )
    completeness_residual = float(np.linalg.norm(completeness - support, ord=2))
    seed_eigenvalues = np.linalg.eigvalsh(seed)
    seed_rank = int(np.count_nonzero(seed_eigenvalues > tolerance))
    success = float(np.trace(seed @ state).real)

    projectors = [
        _isotypic_projector(n, target, group_rows)
        for target in integer_partitions(n)
    ]
    dephased_seed = sum(projector @ seed @ projector for projector in projectors)
    dephased_success = float(np.trace(dephased_seed @ state).real)

    sector_records: list[MixedDecoderSectorRecord] = []
    support_profile: list[tuple[int, int]] = []
    maximum_formula_residual = 0.0
    active_dimensions: list[int] = []
    for target, projector in zip(integer_partitions(n), projectors):
        dimension = hook_length_dimension(target)
        sector_probability = float(np.trace(projector @ state).real)
        formula_probability = float(
            portfolio_sector_weight(n, target, labels)
        )
        formula_residual = abs(sector_probability - formula_probability)
        maximum_formula_residual = max(maximum_formula_residual, formula_residual)
        sector_frame = projector @ average_state @ projector
        sector_support_rank = _matrix_rank(sector_frame, tolerance)
        if sector_support_rank % dimension:
            raise ArithmeticError("isotypic support rank is not divisible by d_nu")
        multiplicity_support_rank = sector_support_rank // dimension
        support_profile.append((dimension, multiplicity_support_rank))
        if multiplicity_support_rank:
            active_dimensions.append(dimension)
        minimum_rank = math.ceil(multiplicity_support_rank / dimension)
        sector_records.append(
            MixedDecoderSectorRecord(
                partition=target,
                irrep_dimension=dimension,
                sector_probability=sector_probability,
                character_formula_sector_probability=formula_probability,
                sector_probability_formula_residual=formula_residual,
                multiplicity_support_rank=multiplicity_support_rank,
                minimum_seed_junk_rank=minimum_rank,
                pure_rank_one_sector_seed_possible=(minimum_rank <= 1),
            )
        )

    junk_lower_bound = minimum_covariant_seed_rank(tuple(support_profile))
    global_lower_bound = math.ceil(support_rank / group_order)
    dephasing_bound = max(dimension * dimension for dimension in active_dimensions) / group_order
    covariance_verified = orbit_average_residual <= tolerance
    verified = (
        covariance_verified
        and completeness_residual <= 100 * tolerance
        and seed_eigenvalues[0] >= -100 * tolerance
        and maximum_formula_residual <= 100 * tolerance
        and seed_rank >= junk_lower_bound >= global_lower_bound
    )
    return MixedCovariantDecoderControl(
        control_id=control_id,
        n=n,
        labels=labels,
        hidden_label_count=group_order,
        physical_dimension=len(state),
        base_projector_rank=base_rank,
        average_frame_support_rank=support_rank,
        pgm_seed_rank=seed_rank,
        global_seed_junk_rank_lower_bound=junk_lower_bound,
        support_rank_global_lower_bound=global_lower_bound,
        pure_coherent_fourier_seed_possible=(junk_lower_bound <= 1),
        pgm_correct_success_probability=success,
        isotypically_dephased_pgm_seed_success_probability=dephased_success,
        cross_isotypic_coherence_success_contribution=(success - dephased_success),
        exact_label_dephasing_success_upper_bound=dephasing_bound,
        pgm_beats_exact_label_dephasing_ceiling=(success > dephasing_bound + tolerance),
        orbit_average_residual=orbit_average_residual,
        pgm_seed_support_completeness_residual=completeness_residual,
        minimum_pgm_seed_eigenvalue=float(seed_eigenvalues[0]),
        maximum_sector_probability_formula_residual=maximum_formula_residual,
        sector_records=sector_records,
        exact_finite_mixed_decoder_validation=verified,
        finite_validation_only=True,
        status=(
            "exact-mixed-covariant-pgm-control"
            if verified
            else "mixed-covariant-decoder-validation-failure"
        ),
    )


def run_mixed_covariant_decoder() -> MixedCovariantDecoderReport:
    controls = [
        audit_physical_projector_orbit(
            "W3-THREE-UNEQUAL-TYPES",
            (
                ((3,), (2, 1)),
                ((3,), (1, 1, 1)),
                ((2, 1), (1, 1, 1)),
            ),
        ),
        audit_physical_projector_orbit(
            "W3-REPEATED-STANDARD-UNEQUAL",
            (((3,), (2, 1)),) * 3,
        ),
        audit_physical_projector_orbit(
            "W3-TRIVIAL-SIGN-COLLAPSE-CONTROL",
            (((3,), (1, 1, 1)),) * 3,
        ),
    ]
    failures = sum(not row.exact_finite_mixed_decoder_validation for row in controls)
    coherent_gains = [
        row for row in controls if row.pgm_beats_exact_label_dephasing_ceiling
    ]
    verified = failures == 0
    return MixedCovariantDecoderReport(
        created_at=utc_now(),
        theorem_contract={
            "covariant_average": (
                "B=direct_sum_nu I_dnu/d_nu tensor C_nu with "
                "C_nu=Tr_V(Pi_nu rho Pi_nu)."
            ),
            "seed_constraint": (
                "Tr_V(Pi_nu E Pi_nu)=d_nu/|G| Pi_supp(C_nu)."
            ),
            "tight_frame_factorization": (
                "For E=sum_a |eta_a><eta_a|, the row-to-multiplicity maps "
                "obey sum_a X_a,nu^* X_a,nu=d_nu/|G| Pi_supp(C_nu)."
            ),
            "seed_rank_lower_bound": (
                "rank(E)>=max_nu ceil(rank(C_nu)/d_nu)>=ceil(rank(B)/|G|)."
            ),
            "canonical_pgm_seed": (
                "E_PGM=|G|^-1 B^-1/2 rho B^-1/2 on supp(B)."
            ),
            "pgm_success": (
                "P_PGM=|G|^-1 Tr(B^-1/2 rho B^-1/2 rho)."
            ),
            "implementation_target": (
                "Implement the canonical multiplicity tight frame and C_nu^-1/2 "
                "coherently across nu; one pure dual-row state is not enough."
            ),
        },
        finite_controls=controls,
        proof_obligations=[
            {
                "obligation": "mixed_covariant_seed_characterization",
                "resolved": verified,
                "resolution": (
                    "Schur twirling turns POVM completeness into the exact "
                    "sector partial-trace constraints."
                ),
            },
            {
                "obligation": "multiplicity_tight_frame_rank_lower_bound",
                "resolved": verified,
                "resolution": (
                    "Each seed factor has multiplicity partial-trace rank at most "
                    "d_nu, forcing at least ceil(rank(C_nu)/d_nu) factors."
                ),
            },
            {
                "obligation": "canonical_pgm_seed_feasibility",
                "resolved": verified,
                "resolution": (
                    "Covariance of B makes the sum of conjugated PGM seeds equal "
                    "to the support projector of B."
                ),
            },
            {
                "obligation": "typical_physical_multiplicity_spectrum",
                "resolved": False,
                "resolution": (
                    "Sector-weight concentration fixes Tr(C_nu), not rank, condition "
                    "number, or the spectral distribution of C_nu."
                ),
            },
            {
                "obligation": "polynomial_coherent_multiplicity_whitening",
                "resolved": False,
                "resolution": (
                    "No source-adapted circuit implements C_nu^-1/2 across coherent "
                    "isotypic sectors without factorial spectral resolution."
                ),
            },
            {
                "obligation": "global_information_theoretic_pgm_success",
                "resolved": True,
                "resolution": (
                    "The separate projector-frame Holder theorem proves P_PGM>1/2 "
                    "at k=ceil(log2 n!) for the full natural ensemble. It does not "
                    "prove uniform conditional-branch success or PGM optimality."
                ),
            },
        ],
        adversarial_audit=[
            {
                "objection": "Plancherel sector weights make inverse QFT sufficient.",
                "resolved": False,
                "resolution": (
                    "They control only Tr(C_nu). Mixed decoding depends on the full "
                    "multiplicity operators and their coherent tight-frame factors."
                ),
            },
            {
                "objection": "Large seed rank proves exponential time.",
                "resolved": False,
                "resolution": (
                    "No. Exponentially many orthogonal junk states fit in polynomially "
                    "many qubits; rank is a structural correction, not a time lower bound."
                ),
            },
            {
                "objection": "Finite PGM success near one is algorithmic evidence.",
                "resolved": False,
                "resolution": (
                    "The controls are W_3 only and use dense inverse square roots. They "
                    "test the theorem, not asymptotic efficiency."
                ),
            },
            {
                "objection": "Measuring nu and decoding each sector preserves the gain.",
                "resolved": True,
                "resolution": (
                    "The controls lose roughly half their correct probability when the "
                    "PGM seed is dephased across nu; cross-sector coherence is operational."
                ),
            },
        ],
        headline_metrics={
            "mixed_covariant_seed_theorem_count": 1,
            "multiplicity_tight_frame_theorem_count": 1,
            "seed_rank_lower_bound_theorem_count": 1,
            "canonical_pgm_seed_theorem_count": 1,
            "finite_control_count": len(controls),
            "finite_control_failure_count": failures,
            "pure_rank_one_seed_impossible_control_count": sum(
                not row.pure_coherent_fourier_seed_possible for row in controls
            ),
            "pgm_beats_dephasing_ceiling_control_count": len(coherent_gains),
            "maximum_finite_pgm_success_probability": max(
                row.pgm_correct_success_probability for row in controls
            ),
            "maximum_cross_isotypic_success_contribution": max(
                row.cross_isotypic_coherence_success_contribution for row in controls
            ),
            "maximum_finite_seed_junk_rank_lower_bound": max(
                row.global_seed_junk_rank_lower_bound for row in controls
            ),
            "typical_multiplicity_spectrum_theorem_count": 0,
            "polynomial_multiplicity_whitening_count": 0,
            "global_information_theoretic_pgm_success_theorem_count": 1,
            "conditional_branch_uniform_success_theorem_count": 0,
            "new_quantum_algorithm_count": 0,
        },
        claim_gate={
            "mixed_covariant_decoder_criterion_proved": verified,
            "pure_coherent_fourier_state_is_general_physical_decoder": False,
            "cross_isotypic_coherence_is_operationally_relevant": bool(coherent_gains),
            "typical_physical_multiplicity_spectrum_controlled": False,
            "polynomial_coherent_multiplicity_whitening_proved": False,
            "global_information_theoretic_pgm_success_proved": True,
            "conditional_branch_uniform_success_proved": False,
            "pgm_optimality_proved": False,
            "end_to_end_hidden_permutation_decoder_proved": False,
            "classical_separation_proved": False,
            "speedup_claim_allowed": False,
            "reason": (
                "The correct mixed-state decoder is a coherent multiplicity tight "
                "frame. Its finite behavior is validated, but the typical C_nu "
                "spectra and an efficient coherent whitening circuit are unknown."
            ),
        },
        status=(
            "mixed-covariant-decoder-reduced-to-multiplicity-tight-frame"
            if verified
            else "mixed-covariant-decoder-validation-failure"
        ),
        summary=(
            "Replaced the pure dual-row heuristic by the exact mixed-state "
            "covariant seed, tight-frame, rank, and PGM whitening criteria."
        ),
        falsifiers_triggered=[
            (
                "The pure coherent Fourier decoder is only a benchmark: the physical "
                "mixed projector orbit generally requires multiple coherent junk rows."
            ),
            (
                "Sector-weight concentration alone cannot certify a decoder because it "
                "does not control multiplicity support or C_nu conditioning."
            ),
            (
                "W_3 PGM gains above the exact-label ceiling disappear substantially "
                "under isotypic dephasing, confirming the need for cross-sector coherence."
            ),
            (
                "Large tight-frame rank does not by itself imply computational hardness."
            ),
        ],
    )


def write_mixed_covariant_decoder_report(
    path: Path = REPORT_PATH,
    write_registry: bool = True,
    registry_experiment_id: str = (
        "EXP-CODE-SELF-DUAL-WREATH-MIXED-COVARIANT-DECODER"
    ),
    registry_candidate_id: str = "CODE-COSET-COLLECTIVE",
    registry_result_id: str = "",
) -> dict[str, Any]:
    payload = asdict(run_mixed_covariant_decoder())
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, indent=2, sort_keys=True))

    return payload


if __name__ == "__main__":
    report = write_mixed_covariant_decoder_report()
    print(json.dumps(report["headline_metrics"], indent=2, sort_keys=True))
