"""Affine-rank payment of marked support entropy.

For nonempty supports ``S,D subset {0,1}^u``, form the exponent-sum matrix of
the split relation, all same-coordinate partition relations, all
different-coordinate partition relations, and the all-ones row generated by
each color/complement pair.  Its rational rank ``R`` obeys

    R >= 2 + 0.5 log2|S| + 0.5 log2|D|.                 (1)

Indeed, a cube subset of size ``k`` has real affine dimension at least
``log2(k)``.  The span of same-support vectors contains its affine direction
space; differences of different-support vectors contain the other direction
space.  Their maximum dimension dominates the average support entropy.  The
different E/F leaf offset supplies one further direction, and the all-ones
row is independent of every partition vector.

For a crossing pressure target, (1) pays every support-entropy exponent except
at most one.  What remains is nonabelian: prove that rational relation rank
lifts to the corresponding leading ``S_n`` solution loss, with a surface or
power-word certificate supplying the final crossing exponent.  Abelian rank
alone does not prove that lift.
"""

from __future__ import annotations

import itertools
import json
import math
from dataclasses import asdict, dataclass
from fractions import Fraction
from pathlib import Path
from typing import Any, Iterable

from research_registry import utc_now


REPORT_PATH = Path(
    "research/representation/self_dual_wreath_support_affine_rank_entropy.json"
)
DEFAULT_EXPERIMENT_ID = (
    "EXP-CODE-SELF-DUAL-WREATH-SUPPORT-AFFINE-RANK-ENTROPY"
)
DEFAULT_CANDIDATE_ID = "CODE-COSET-COLLECTIVE"

Assignment = tuple[int, ...]


@dataclass(frozen=True)
class SupportAffineRankControl:
    control_id: str
    frame_position_count: int
    crossing: bool
    frame_types: tuple[str, ...]
    same_support: tuple[Assignment, ...]
    different_support: tuple[Assignment, ...]
    same_support_affine_dimension: int
    different_support_affine_dimension: int
    relation_exponent_matrix_rank: int
    support_entropy_bits: float
    entropy_rank_lower_bound: float
    rank_margin_above_entropy_bound: float
    crossing_extra_exponent_debt_upper_bound: float
    exact_rank_entropy_inequality_verified: bool
    status: str


@dataclass(frozen=True)
class SupportAffineRankScalingRecord:
    frame_position_count: int
    checked_support_profile_count: int
    minimum_rank_margin: float
    rank_entropy_failure_count: int
    status: str


@dataclass(frozen=True)
class SupportAffineRankEntropyReport:
    created_at: str
    theorem_contract: dict[str, Any]
    representative_controls: list[SupportAffineRankControl]
    scaling_records: list[SupportAffineRankScalingRecord]
    proof_obligations: list[dict[str, str | bool]]
    adversarial_audit: list[dict[str, str | bool]]
    headline_metrics: dict[str, int | float]
    claim_gate: dict[str, str | bool]
    status: str
    summary: str
    falsifiers_triggered: list[str]


def _matrix_rank(rows: Iterable[Iterable[int]]) -> int:
    matrix = [list(map(Fraction, row)) for row in rows]
    if not matrix:
        return 0
    rank = 0
    for column in range(len(matrix[0])):
        pivot = next(
            (
                row
                for row in range(rank, len(matrix))
                if matrix[row][column]
            ),
            None,
        )
        if pivot is None:
            continue
        matrix[rank], matrix[pivot] = matrix[pivot], matrix[rank]
        pivot_value = matrix[rank][column]
        matrix[rank] = [value / pivot_value for value in matrix[rank]]
        for row in range(len(matrix)):
            if row == rank or not matrix[row][column]:
                continue
            factor = matrix[row][column]
            matrix[row] = [
                left - factor * right
                for left, right in zip(matrix[row], matrix[rank])
            ]
        rank += 1
    return rank


def affine_dimension(support: tuple[Assignment, ...]) -> int:
    if not support:
        raise ValueError("support must be nonempty")
    width = len(support[0])
    if any(
        len(assignment) != width or any(bit not in (0, 1) for bit in assignment)
        for assignment in support
    ):
        raise ValueError("support must contain equally sized binary assignments")
    anchor = support[0]
    return _matrix_rank(
        tuple(
            value - base
            for value, base in zip(assignment, anchor)
        )
        for assignment in support[1:]
    )


def relation_exponent_matrix(
    frame_types: tuple[str, ...],
    same_support: tuple[Assignment, ...],
    different_support: tuple[Assignment, ...],
    *,
    crossing: bool,
) -> tuple[tuple[int, ...], ...]:
    frame_count = len(frame_types)
    if any(token not in "AB" for token in frame_types):
        raise ValueError("frame types must be A or B")
    if not same_support or not different_support:
        raise ValueError("same and different supports must be nonempty")
    if any(len(row) != frame_count for row in (*same_support, *different_support)):
        raise ValueError("support assignment width must match frame types")
    leaf_different = (0, 1, 0, 1) if crossing else (0, 0, 1, 1)
    rows = [
        (1,) * (frame_count + 4),
        (0, 0, 0, 0, *(token == "B" for token in frame_types)),
    ]
    rows.extend((0, 0, 0, 0, *assignment) for assignment in same_support)
    rows.extend((*leaf_different, *assignment) for assignment in different_support)
    return tuple(tuple(map(int, row)) for row in rows)


def audit_support_affine_rank(
    control_id: str,
    frame_types: tuple[str, ...],
    same_support: tuple[Assignment, ...],
    different_support: tuple[Assignment, ...],
    *,
    crossing: bool = True,
) -> SupportAffineRankControl:
    matrix = relation_exponent_matrix(
        frame_types,
        same_support,
        different_support,
        crossing=crossing,
    )
    rank = _matrix_rank(matrix)
    same_dimension = affine_dimension(same_support)
    different_dimension = affine_dimension(different_support)
    entropy = 0.5 * math.log2(len(same_support)) + 0.5 * math.log2(
        len(different_support)
    )
    lower_bound = 2 + entropy
    margin = rank - lower_bound
    exact = (
        same_dimension + 1e-12 >= math.log2(len(same_support))
        and different_dimension + 1e-12
        >= math.log2(len(different_support))
        and margin >= -1e-12
    )
    return SupportAffineRankControl(
        control_id=control_id,
        frame_position_count=len(frame_types),
        crossing=crossing,
        frame_types=frame_types,
        same_support=same_support,
        different_support=different_support,
        same_support_affine_dimension=same_dimension,
        different_support_affine_dimension=different_dimension,
        relation_exponent_matrix_rank=rank,
        support_entropy_bits=entropy,
        entropy_rank_lower_bound=lower_bound,
        rank_margin_above_entropy_bound=margin,
        crossing_extra_exponent_debt_upper_bound=max(0.0, 3 + entropy - rank),
        exact_rank_entropy_inequality_verified=exact,
        status=(
            "exact-support-affine-rank-entropy-bound-verified"
            if exact
            else "support-affine-rank-entropy-control-failure"
        ),
    )


def _nonempty_supports(frame_count: int) -> tuple[tuple[Assignment, ...], ...]:
    assignments = tuple(itertools.product((0, 1), repeat=frame_count))
    return tuple(
        tuple(
            assignment
            for index, assignment in enumerate(assignments)
            if mask >> index & 1
        )
        for mask in range(1, 1 << len(assignments))
    )


def run_support_affine_rank_entropy() -> SupportAffineRankEntropyReport:
    scaling: list[SupportAffineRankScalingRecord] = []
    total_profiles = 0
    total_failures = 0
    minimum_margin = math.inf
    for frame_count in (1, 2):
        supports = _nonempty_supports(frame_count)
        failures = 0
        row_minimum = math.inf
        checks = 0
        for frame_types in itertools.product("AB", repeat=frame_count):
            for same in supports:
                for different in supports:
                    control = audit_support_affine_rank(
                        "EXHAUSTIVE",
                        frame_types,
                        same,
                        different,
                    )
                    checks += 1
                    failures += not control.exact_rank_entropy_inequality_verified
                    row_minimum = min(
                        row_minimum,
                        control.rank_margin_above_entropy_bound,
                    )
        total_profiles += checks
        total_failures += failures
        minimum_margin = min(minimum_margin, row_minimum)
        scaling.append(
            SupportAffineRankScalingRecord(
                frame_position_count=frame_count,
                checked_support_profile_count=checks,
                minimum_rank_margin=row_minimum,
                rank_entropy_failure_count=failures,
                status=(
                    "exhaustive-rank-entropy-control-passed"
                    if not failures
                    else "rank-entropy-control-failure"
                ),
            )
        )
    cube4 = tuple(itertools.product((0, 1), repeat=4))
    even4 = tuple(row for row in cube4 if sum(row) % 2 == 0)
    representatives = [
        audit_support_affine_rank(
            "SINGLETON-ONE-EXPONENT-DEBT",
            ("A",),
            ((0,),),
            ((0,),),
        ),
        audit_support_affine_rank(
            "FULL-CUBE-ENTROPY-TIGHT",
            ("A", "B", "A", "B"),
            cube4,
            cube4,
        ),
        audit_support_affine_rank(
            "PARITY-SUPPORT",
            ("B", "A", "B", "A"),
            even4,
            tuple(row for row in cube4 if sum(row) % 2 == 1),
        ),
    ]
    representative_failures = sum(
        not row.exact_rank_entropy_inequality_verified
        for row in representatives
    )
    exact = total_failures == representative_failures == 0
    return SupportAffineRankEntropyReport(
        created_at=utc_now(),
        theorem_contract={
            "cube_affine_dimension": (
                "A real affine d-plane contains at most 2^d vertices of a "
                "hypercube, so affdim(S)>=log2|S|."
            ),
            "relation_span": (
                "The relation span contains the larger support direction space, "
                "the independent differing-leaf offset, and the all-ones row."
            ),
            "entropy_payment": (
                "Therefore rational relation rank is at least two plus the "
                "average logarithmic support size."
            ),
            "scope_boundary": (
                "Rational exponent-sum rank is not an S_n solution-count bound; "
                "power words and nonprimitive relators require separate control."
            ),
        },
        representative_controls=representatives,
        scaling_records=scaling,
        proof_obligations=[
            {
                "obligation": "pay_support_entropy_in_abelian_relation_rank",
                "resolved": exact,
                "resolution": (
                    "R>=2+0.5log|S|+0.5log|D| for every nonempty cube support pair."
                ),
            },
            {
                "obligation": "lift_relation_rank_to_symmetric_group_solution_loss",
                "resolved": False,
                "resolution": (
                    "Prove a primitive/surface/power decomposition whose total "
                    "leading S_n loss matches rank up to o(1)."
                ),
            },
            {
                "obligation": "supply_final_crossing_surface_exponent",
                "resolved": False,
                "resolution": (
                    "When rank is entropy-tight, prove that the E/F crossing "
                    "boundary contributes the remaining one exponent."
                ),
            },
        ],
        adversarial_audit=[
            {
                "objection": "Large support entropy requires equally many ad hoc surfaces.",
                "resolved": True,
                "resolution": (
                    "False at the linear level: affine rank already pays all but "
                    "at most one required crossing exponent."
                ),
            },
            {
                "objection": "Abelian rank proves the nonabelian solution exponent.",
                "resolved": True,
                "resolution": (
                    "False: x^k has rank one but can have a weaker root-count "
                    "loss; a proof-carrying word-topology lift is still required."
                ),
            },
        ],
        headline_metrics={
            "checked_support_profile_count": total_profiles,
            "rank_entropy_failure_count": total_failures,
            "minimum_rank_margin_above_entropy_bound": minimum_margin,
            "maximum_unpaid_crossing_exponent": max(
                row.crossing_extra_exponent_debt_upper_bound
                for row in representatives
            ),
            "new_quantum_algorithm_count": 0,
        },
        claim_gate={
            "support_entropy_paid_in_abelian_rank": exact,
            "unpaid_crossing_debt_at_most_one_exponent": exact,
            "symmetric_group_rank_lift_proved": False,
            "growing_degree_pressure_separation_proved": False,
            "natural_component_M4_positive": False,
            "speedup_claim_allowed": False,
            "reason": (
                "The entropy bottleneck is reduced to one nonabelian exponent, "
                "but relation rank has not been lifted to S_n solution counts."
            ),
        },
        status=(
            "support-entropy-abelian-rank-theorem-proved"
            if exact
            else "support-affine-rank-entropy-control-failure"
        ),
        summary=(
            "Paid marked-support entropy in affine relation rank and isolated "
            "one remaining nonabelian crossing exponent."
        ),
        falsifiers_triggered=[
            "Singleton all-A supports attain the one-exponent crossing debt, so rank alone cannot finish the theorem.",
            "Large Smith torsion or nonprimitive relators could prevent rational rank from becoming equal S_n exponent loss.",
        ],
    )


def write_support_affine_rank_entropy_report(
    path: Path = REPORT_PATH,
    write_registry: bool = True,
    registry_experiment_id: str = (
        "EXP-CODE-SELF-DUAL-WREATH-SUPPORT-AFFINE-RANK-ENTROPY"
    ),
    registry_candidate_id: str = "CODE-COSET-COLLECTIVE",
    registry_result_id: str = "",
) -> dict[str, Any]:
    payload = asdict(run_support_affine_rank_entropy())
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, indent=2, sort_keys=True) + "\n")

    return payload


if __name__ == "__main__":
    report = write_support_affine_rank_entropy_report()
    print(json.dumps(report["headline_metrics"], indent=2, sort_keys=True))
