from fractions import Fraction

import numpy as np
import pytest

from self_dual_wreath_codimension_one_commuting_compression_no_go import (
    audit_codimension_one_compression,
    codimension_one_no_go_theorem,
    codimension_one_scaling_record,
    construct_codimension_one_projection_frame,
    exact_family_parameters,
    run_codimension_one_commuting_compression_no_go,
)


def test_exact_family_parameters_close_scalar_frame_identity() -> None:
    for r in (2, 3, 17, 128):
        cosine_squared, sine_squared, frame_scalar = exact_family_parameters(r)
        assert cosine_squared + sine_squared == 1
        assert 1 + 2 * cosine_squared == frame_scalar
        assert 2 * r * sine_squared == frame_scalar
        assert cosine_squared / frame_scalar == Fraction(2 * r - 1, 6 * r)


def test_construction_has_exact_codimension_one_and_rank_one_leaves() -> None:
    leaves, common = construct_codimension_one_projection_frame(7)
    assert len(leaves) == 21
    assert common.shape == (8, 7)
    np.testing.assert_allclose(common.conj().T @ common, np.eye(7), atol=1e-12)
    for leaf in leaves:
        np.testing.assert_allclose(leaf @ leaf, leaf, atol=1e-12)
        assert np.linalg.matrix_rank(leaf, tol=1e-10) == 1


def test_codimension_one_compression_commutes_despite_pair_budget_obstruction() -> None:
    control = audit_codimension_one_compression(8)
    assert control.exact_counterfamily_verified
    assert control.common_codimension == 1
    assert control.exact_pair_intersection_budget == 0
    assert control.total_leaf_rank_excess == 15
    assert control.full_support_pair_budget_obstructs_commuting_effects
    assert control.maximum_full_effect_commutator_norm > 1e-4
    assert control.compressed_effects_commute
    assert control.maximum_compressed_effect_commutator_norm < 1e-10
    assert control.minimum_positive_compressed_effect_eigenvalue >= 0.25
    assert control.nonscalarity_defect_minimum_eigenvalue > 0


def test_scaling_keeps_coarse_controls_while_relative_codimension_vanishes() -> None:
    records = [codimension_one_scaling_record(r) for r in (4, 16, 64, 256)]
    assert all(record.common_codimension == 1 for record in records)
    assert all(record.frame_condition_number == 1.0 for record in records)
    assert all(record.total_leaf_rank_to_common_aspect == 3.0 for record in records)
    assert all(record.exact_pair_intersection_budget == 0 for record in records)
    assert all(record.component_positive_edge >= 0.25 for record in records)
    assert all(record.compressed_effects_commute for record in records)
    assert records[-1].common_relative_rank > records[0].common_relative_rank
    assert records[-1].maximum_leaf_rank_to_common_ratio < 0.004
    assert abs(records[-1].cross_coordinate_noncommuting_pair_fraction - 4 / 9) < 0.003


def test_report_refuses_natural_M4_and_speedup_claims() -> None:
    report = run_codimension_one_commuting_compression_no_go()
    assert report.headline_metrics["codimension_one_discontinuity_theorem_count"] == 1
    assert report.headline_metrics["finite_control_failure_count"] == 0
    assert report.claim_gate["literal_full_support_or_direct_natural_analysis_required"]
    assert not report.claim_gate["near_full_support_generic_transfer_valid"]
    assert not report.claim_gate["natural_component_M4_positive"]
    assert not report.claim_gate["speedup_claim_allowed"]


def test_invalid_dimension_is_rejected() -> None:
    with pytest.raises(ValueError, match="at least two"):
        exact_family_parameters(1)
    with pytest.raises(ValueError, match="at least two"):
        construct_codimension_one_projection_frame(0)


def test_theorem_scope_is_explicitly_generic() -> None:
    theorem = codimension_one_no_go_theorem()
    assert theorem.theorem_verified
    assert theorem.exact_common_codimension_one
    assert theorem.scalar_tight_frame
    assert theorem.zero_physical_pair_budget
    assert theorem.constant_component_edge
    assert theorem.full_rank_nonscalarity
    assert theorem.proper_compression_commutative
    assert "not generated by natural wreath sources" in theorem.scope_limit
