"""Natural-source mass of the trivial-color wreath fusion sector.

The generic hyperoctahedral Clebsch--Gordan transform contains the ordinary
``S_m`` Kronecker transform on trivial-color irreps.  This module tests whether
that embedded sector is actually important for the hidden-involution source.

Let ``G=S_(2m)``, let ``h`` be the canonical perfect matching, let
``K=C_2 wr S_m``, and let ``N=(C_2)^m`` be the normal subgroup generated by
the individual matching swaps.  The one-copy source fiber

    R = ran((I+R_h)/2)

has the explicit ``K``-permutation basis ``C[G/<h>]`` under conjugation.  The
sum of all trivial-color ``K`` isotypic sectors is exactly ``R^N``.  If
``a in N`` flips ``t`` matching pairs, then

    chi_R(a) = |C_G(a)|/2 * (1 + 1[t=m-t]),             (1)
    |C_G(a)| = 2^t t! (2m-2t)!.

For ``k`` tensor copies, Burnside projection gives the exact source fraction

    w_(m,k) = 2^-m sum_(t=0)^m binom(m,t)
      [2^t t!(2m-2t)!/(2m)! * (1+1[2t=m])]^k.          (2)

For every ``m>=2`` the nonidentity normalized character is at most ``1/3``.
At the orbit-flatness width ``k>=m``, therefore

    w_(m,k) <= 2^-m + (1-2^-m)3^-k <= 2^(1-m).         (3)

Let ``x`` be the unnormalized orbit-synthesis Gram eigenvalue under the
uniform source law.  The exact moment theorem gives
``E[x^2]=1+(M-1)/2^k``.  Cauchy--Schwarz bounds the alternative contribution
of any source subspace of fraction ``w`` by

    Tr(rho_alt from that subspace) <= sqrt((1+eta)w).   (4)

At ``k=ceil(log2(64M))``, ``eta<=1/64``, so the entire trivial-color sector
has exponentially vanishing alternative contribution.  Thus the embedded
ordinary Kronecker transform is not a natural-source bottleneck at this copy
width.  This does not show that source-heavy colored wreath sectors are easy,
nor does it construct their fusion transform or the full matrix-Hecke polar.
"""

from __future__ import annotations

import itertools
import json
import math
from dataclasses import asdict, dataclass
from fractions import Fraction
from pathlib import Path
from typing import Any

from coset_hidden_involution_binary_decision_reduction import (
    Permutation,
    compose_permutations,
    inverse_permutation,
    symmetric_group,
)
from coset_hidden_involution_orbit_synthesis_flatness import (
    flatness_copy_count,
)
from coset_perfect_matching_spherical_boundary import perfect_matching_count
from research_registry import utc_now


REPORT_PATH = Path(
    "research/representation/"
    "coset_hyperoctahedral_trivial_color_mass_no_go.json"
)
DEFAULT_EXPERIMENT_ID = (
    "EXP-COSET-HYPEROCTAHEDRAL-TRIVIAL-COLOR-MASS-NO-GO"
)
DEFAULT_CANDIDATE_ID = "CODE-COSET-COLLECTIVE"


@dataclass(frozen=True)
class TrivialColorMassFiniteControl:
    half_degree: int
    degree: int
    copy_count: int
    group_order: int
    base_subgroup_order: int
    one_copy_fiber_dimension: int
    direct_character_mismatch_count: int
    exact_invariant_dimension_decimal: str
    exact_tensor_fiber_dimension_decimal: str
    exact_source_fraction: float
    character_formula_source_fraction: float
    source_fraction_residual: float
    exact_burnside_formula_verified: bool
    status: str


@dataclass(frozen=True)
class TrivialColorMassScalingRecord:
    half_degree: int
    degree: int
    perfect_matching_count_decimal: str
    copy_count: int
    exact_source_fraction: float
    exact_source_fraction_log2: float
    elementary_source_fraction_upper_bound: float
    alternative_contribution_upper_bound: float
    alternative_contribution_log2_upper_bound: float
    embedded_kronecker_sector_has_constant_alternative_mass: bool
    generic_wreath_cg_is_natural_source_bottleneck: bool
    colored_source_fusion_compiled: bool
    status: str


@dataclass(frozen=True)
class TrivialColorMassTheorem:
    source_permutation_module: str
    base_invariant_identity: str
    character_formula: str
    burnside_fraction: str
    uniform_bound: str
    alternative_mass_transfer: str
    architecture_consequence: str
    scope_limit: str
    exact_source_fraction_proved: bool
    exponential_source_mass_upper_bound_proved: bool
    exponential_alternative_mass_upper_bound_proved: bool
    generic_kronecker_sector_natural_bottleneck: bool
    source_heavy_colored_fusion_compiled: bool
    full_matrix_hecke_polar_compiled: bool
    theorem_verified: bool
    status: str


@dataclass(frozen=True)
class TrivialColorMassReport:
    created_at: str
    theorem_contract: dict[str, Any]
    finite_controls: list[TrivialColorMassFiniteControl]
    scaling_records: list[TrivialColorMassScalingRecord]
    theorem: TrivialColorMassTheorem
    proof_obligations: list[dict[str, str | bool]]
    adversarial_audit: list[dict[str, str | bool]]
    headline_metrics: dict[str, int | float]
    claim_gate: dict[str, str | bool]
    status: str
    summary: str
    falsifiers_triggered: list[str]


def canonical_matching_involution(half_degree: int) -> Permutation:
    if half_degree < 1:
        raise ValueError("half_degree must be positive")
    return tuple(
        value
        for pair in range(half_degree)
        for value in (2 * pair + 1, 2 * pair)
    )


def base_subgroup_element(
    half_degree: int,
    mask: int,
) -> Permutation:
    if half_degree < 1 or not 0 <= mask < 2**half_degree:
        raise ValueError("invalid half_degree or mask")
    output = list(range(2 * half_degree))
    for pair in range(half_degree):
        if (mask >> pair) & 1:
            output[2 * pair], output[2 * pair + 1] = (
                output[2 * pair + 1],
                output[2 * pair],
            )
    return tuple(output)


def normalized_fiber_character(
    half_degree: int,
    flipped_pairs: int,
) -> Fraction:
    if half_degree < 1 or not 0 <= flipped_pairs <= half_degree:
        raise ValueError("invalid half_degree or flipped_pairs")
    degree = 2 * half_degree
    centralizer = (
        (2**flipped_pairs)
        * math.factorial(flipped_pairs)
        * math.factorial(degree - 2 * flipped_pairs)
    )
    conjugate_after_hidden = int(2 * flipped_pairs == half_degree)
    return Fraction(
        centralizer * (1 + conjugate_after_hidden),
        math.factorial(degree),
    )


def exact_trivial_color_source_fraction(
    half_degree: int,
    copy_count: int,
) -> Fraction:
    if half_degree < 1 or copy_count < 1:
        raise ValueError("half_degree and copy_count must be positive")
    return sum(
        Fraction(math.comb(half_degree, flipped_pairs), 2**half_degree)
        * normalized_fiber_character(half_degree, flipped_pairs) ** copy_count
        for flipped_pairs in range(half_degree + 1)
    )


def _conjugate(
    element: Permutation,
    value: Permutation,
) -> Permutation:
    return compose_permutations(
        compose_permutations(element, value), inverse_permutation(element)
    )


def _direct_fiber_character(
    half_degree: int,
    element: Permutation,
) -> int:
    group = symmetric_group(2 * half_degree)
    hidden = canonical_matching_involution(half_degree)
    unseen = set(group)
    representatives = []
    while unseen:
        representative = min(unseen)
        representatives.append(representative)
        unseen.discard(representative)
        unseen.discard(compose_permutations(representative, hidden))
    return sum(
        min(
            _conjugate(element, representative),
            compose_permutations(
                _conjugate(element, representative), hidden
            ),
        )
        == representative
        for representative in representatives
    )


def audit_trivial_color_mass(
    half_degree: int,
    copy_count: int,
) -> TrivialColorMassFiniteControl:
    if half_degree < 1 or half_degree > 3:
        raise ValueError("finite control supports half_degree in [1,3]")
    if copy_count < 1:
        raise ValueError("copy_count must be positive")
    group_order = math.factorial(2 * half_degree)
    fiber_dimension = group_order // 2
    mismatch = 0
    direct_characters = []
    for mask in range(2**half_degree):
        element = base_subgroup_element(half_degree, mask)
        direct = _direct_fiber_character(half_degree, element)
        flipped = mask.bit_count()
        predicted = (
            normalized_fiber_character(half_degree, flipped)
            * fiber_dimension
        )
        if predicted.denominator != 1 or direct != predicted.numerator:
            mismatch += 1
        direct_characters.append(direct)
    invariant_dimension = sum(
        character**copy_count for character in direct_characters
    ) // (2**half_degree)
    tensor_dimension = fiber_dimension**copy_count
    direct_fraction = Fraction(invariant_dimension, tensor_dimension)
    formula_fraction = exact_trivial_color_source_fraction(
        half_degree, copy_count
    )
    residual = abs(float(direct_fraction - formula_fraction))
    verified = bool(
        mismatch == 0 and direct_fraction == formula_fraction and residual == 0.0
    )
    return TrivialColorMassFiniteControl(
        half_degree=half_degree,
        degree=2 * half_degree,
        copy_count=copy_count,
        group_order=group_order,
        base_subgroup_order=2**half_degree,
        one_copy_fiber_dimension=fiber_dimension,
        direct_character_mismatch_count=mismatch,
        exact_invariant_dimension_decimal=str(invariant_dimension),
        exact_tensor_fiber_dimension_decimal=str(tensor_dimension),
        exact_source_fraction=float(direct_fraction),
        character_formula_source_fraction=float(formula_fraction),
        source_fraction_residual=residual,
        exact_burnside_formula_verified=verified,
        status=(
            "exact-trivial-color-source-mass-verified"
            if verified
            else "trivial-color-mass-control-failure"
        ),
    )


def _logsumexp(values: list[float]) -> float:
    maximum = max(values)
    return maximum + math.log(sum(math.exp(value - maximum) for value in values))


def _source_fraction_log(half_degree: int, copy_count: int) -> float:
    degree = 2 * half_degree
    terms = []
    for flipped in range(half_degree + 1):
        log_combination = (
            math.lgamma(half_degree + 1)
            - math.lgamma(flipped + 1)
            - math.lgamma(half_degree - flipped + 1)
        )
        log_character = (
            flipped * math.log(2.0)
            + math.lgamma(flipped + 1)
            + math.lgamma(degree - 2 * flipped + 1)
            - math.lgamma(degree + 1)
        )
        if 2 * flipped == half_degree:
            log_character += math.log(2.0)
        terms.append(log_combination + copy_count * log_character)
    return _logsumexp(terms) - half_degree * math.log(2.0)


def trivial_color_mass_scaling_record(
    half_degree: int,
) -> TrivialColorMassScalingRecord:
    if half_degree < 2:
        raise ValueError("half_degree must be at least two")
    matchings = perfect_matching_count(half_degree)
    copies = flatness_copy_count(matchings)
    log_source = _source_fraction_log(half_degree, copies)
    source_fraction = math.exp(log_source)
    elementary_bound = 2.0 ** (-half_degree) + (
        1.0 - 2.0 ** (-half_degree)
    ) * 3.0 ** (-copies)
    eta = (matchings - 1) / (2**copies)
    alternative_bound = math.sqrt((1.0 + eta) * source_fraction)
    return TrivialColorMassScalingRecord(
        half_degree=half_degree,
        degree=2 * half_degree,
        perfect_matching_count_decimal=str(matchings),
        copy_count=copies,
        exact_source_fraction=source_fraction,
        exact_source_fraction_log2=log_source / math.log(2.0),
        elementary_source_fraction_upper_bound=elementary_bound,
        alternative_contribution_upper_bound=alternative_bound,
        alternative_contribution_log2_upper_bound=math.log2(
            alternative_bound
        ),
        embedded_kronecker_sector_has_constant_alternative_mass=False,
        generic_wreath_cg_is_natural_source_bottleneck=False,
        colored_source_fusion_compiled=False,
        status="trivial-color-sector-negligible-colored-fusion-open",
    )


def build_trivial_color_mass_report(
    *,
    finite_specs: tuple[tuple[int, int], ...] = (
        (1, 1),
        (2, 1),
        (2, 2),
        (3, 1),
        (3, 2),
    ),
    scaling_half_degrees: tuple[int, ...] = (3, 4, 8, 16, 32, 64, 128),
) -> TrivialColorMassReport:
    controls = [audit_trivial_color_mass(m, k) for m, k in finite_specs]
    scaling = [
        trivial_color_mass_scaling_record(m)
        for m in scaling_half_degrees
    ]
    verified = all(row.exact_burnside_formula_verified for row in controls)
    scaling_verified = all(
        row.exact_source_fraction
        <= row.elementary_source_fraction_upper_bound * (1.0 + 1e-12)
        and row.elementary_source_fraction_upper_bound <= 2.0 ** (1 - row.half_degree)
        and not row.embedded_kronecker_sector_has_constant_alternative_mass
        for row in scaling
    )
    theorem = TrivialColorMassTheorem(
        source_permutation_module=(
            "ran((I+R_h)/2) has basis (|g>+|gh>)/sqrt(2), hence is the "
            "K permutation module C[G/<h>] under conjugation."
        ),
        base_invariant_identity=(
            "The direct sum of K irreps (lambda,empty) is exactly the invariant "
            "subspace for the normal base group N=(C_2)^m."
        ),
        character_formula=(
            "For a in N with t swaps, chi_R(a)=|C_G(a)|/2 times "
            "(1+1[2t=m])."
        ),
        burnside_fraction=(
            "w_(m,k)=2^-m sum_t binom(m,t)[2^t t!(2m-2t)!/(2m)! "
            "times (1+1[2t=m])]^k."
        ),
        uniform_bound=(
            "For m>=2 and k>=m, every nonidentity term is at most 3^-k, "
            "so w_(m,k)<=2^(1-m)."
        ),
        alternative_mass_transfer=(
            "Cauchy-Schwarz with E_source[x^2]=1+(M-1)/2^k bounds the "
            "alternative contribution by sqrt((1+eta)w)."
        ),
        architecture_consequence=(
            "The trivial-color embedded S_m Kronecker transform has vanishing "
            "natural alternative mass and is not the next compiler target."
        ),
        scope_limit=(
            "No claim is made about source-heavy colored sectors, their wreath "
            "fusion complexity, or the complete matrix-Hecke polar."
        ),
        exact_source_fraction_proved=True,
        exponential_source_mass_upper_bound_proved=True,
        exponential_alternative_mass_upper_bound_proved=True,
        generic_kronecker_sector_natural_bottleneck=False,
        source_heavy_colored_fusion_compiled=False,
        full_matrix_hecke_polar_compiled=False,
        theorem_verified=verified and scaling_verified,
        status=(
            "embedded-kronecker-sector-negligible-colored-transfer-open"
            if verified and scaling_verified
            else "trivial-color-mass-control-failure"
        ),
    )
    return TrivialColorMassReport(
        created_at=utc_now(),
        theorem_contract={
            "family": (
                "Fixed-point-free involutions in S_(2m), canonical centralizer "
                "K=C_2 wr S_m, and k-copy canonical plus fiber."
            ),
            "sector": (
                "All trivial-base-color K irreps (lambda,empty), equivalently "
                "the N-invariant source subspace."
            ),
            "copy_width": (
                "k=ceil(log2(64(2m-1)!!)) for the asymptotic alternative bound."
            ),
            "outside_scope": (
                "Colored wreath sectors, arbitrary source subspaces, and any "
                "algorithmic lower bound."
            ),
        },
        finite_controls=controls,
        scaling_records=scaling,
        theorem=theorem,
        proof_obligations=[
            {
                "id": "PO-COSET-HYPEROCTAHEDRAL-COLORED-SOURCE-MASS",
                "statement": (
                    "Identify which nontrivial base-color bipartition sectors "
                    "carry constant natural alternative mass."
                ),
                "resolved": False,
            },
            {
                "id": "PO-COSET-HYPEROCTAHEDRAL-COLORED-TRANSFER-BASIS",
                "statement": (
                    "Find a succinct transform for only those source-heavy "
                    "colored matrix-Hecke sectors."
                ),
                "resolved": False,
            },
            {
                "id": "PO-COSET-HYPEROCTAHEDRAL-COLOR-DEQUANTIZATION",
                "statement": (
                    "Compare any surviving colored-sector observable with "
                    "classical matching-cycle and representation invariants."
                ),
                "resolved": False,
            },
        ],
        adversarial_audit=[
            {
                "challenge": "The generic wreath-CG Kronecker reduction is naturally decisive.",
                "answer": (
                    "False at the flatness width: its entire trivial-color source "
                    "and alternative contributions vanish exponentially."
                ),
                "resolved": True,
            },
            {
                "challenge": "Small source rank fraction alone implies small alternative mass.",
                "answer": (
                    "Not alone. The conclusion uses the exact global Gram second "
                    "moment and Cauchy-Schwarz to control size bias."
                ),
                "resolved": True,
            },
            {
                "challenge": "All wreath fusion is therefore irrelevant.",
                "answer": (
                    "False. Colored sectors dominate the remaining source and "
                    "their transfer structure is unclassified."
                ),
                "resolved": True,
            },
        ],
        headline_metrics={
            "exact_burnside_control_count": len(controls),
            "finite_control_failure_count": sum(
                not row.exact_burnside_formula_verified for row in controls
            ),
            "exponential_source_mass_no_go_count": 1,
            "exponential_alternative_mass_no_go_count": 1,
            "maximum_scaling_alternative_contribution_upper_bound": max(
                row.alternative_contribution_upper_bound for row in scaling
            ),
            "minimum_scaling_alternative_contribution_log2_upper_bound": min(
                row.alternative_contribution_log2_upper_bound for row in scaling
            ),
            "source_heavy_colored_fusion_compiler_count": 0,
            "new_quantum_algorithm_count": 0,
        },
        claim_gate={
            "trivial_color_source_fraction_formula_proved": verified,
            "embedded_symmetric_kronecker_sector_negligible": (
                verified and scaling_verified
            ),
            "generic_wreath_cg_is_natural_source_bottleneck": False,
            "source_heavy_colored_sectors_classified": False,
            "colored_matrix_hecke_transform_compiled": False,
            "full_orbit_synthesis_polar_compiled": False,
            "efficient_binary_hidden_involution_algorithm_constructed": False,
            "speedup_claim_allowed": False,
            "reason": (
                "The generic Kronecker-containing trivial-color sector has "
                "vanishing alternative mass. The dominant colored source "
                "transfer remains unclassified and uncompiled."
            ),
        },
        status=theorem.status,
        summary=(
            "Computed the exact Burnside mass of the trivial-color wreath "
            "sector and used global frame moments to prove its alternative "
            "contribution vanishes exponentially, redirecting the compiler "
            "search to source-heavy colored matrix-Hecke sectors."
        ),
        falsifiers_triggered=[
            "The embedded ordinary Kronecker transform is not a constant-mass natural-source obstruction.",
            "Regular parity-conditioned mass was not silently substituted for the natural source; the natural fiber was computed exactly.",
            "Source rank fraction alone was not used as an alternative-mass claim; the frame second moment supplies the transfer bound.",
            "Colored wreath fusion and the full matrix-Hecke polar remain open.",
        ],
    )


def write_trivial_color_mass_report(
    output_path: Path = REPORT_PATH,
    **kwargs: Any,
) -> dict[str, Any]:
    payload = asdict(build_trivial_color_mass_report(**kwargs))
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(
        json.dumps(payload, indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )
    return payload


if __name__ == "__main__":
    report = write_trivial_color_mass_report()
    print(json.dumps(report["headline_metrics"], indent=2, sort_keys=True))
