"""Coset-partition no-go for naive hidden subalgebras of diagram algebras.

The hidden subgroup state construction relies on a group fact: right cosets
``gH`` are either equal or disjoint.  There is an exact finite-monoid boundary.
For a submonoid ``B`` of a finite monoid ``M``, the right translates ``aB``
form a partition of ``M`` if and only if every element of ``B`` is a unit, so
``B`` is a group.  Indeed, ``bB`` intersects ``B`` for every ``b in B``.  If
translates are equal-or-disjoint then ``bB=B``, hence ``bc=1`` for some
``c in B``; finiteness upgrades a one-sided inverse to a two-sided inverse.

Consequently, a hidden submonoid generated by a noninvertible bridge or reset
diagram cannot support ordinary HSP coset states.  Projectively rescaled bridge
and point generators are nonidentity idempotents, and therefore nonunits.  A
new oracle/state model based on ideals, Green relations, fixed factorizations,
or modules is required before a diagram-algebra QFT can be algorithmically
connected to a hidden problem.

The viable high-variance replacement is not another coset definition.  It is a
module-spectrum program: use Brauer/partition-algebra Fourier or generalized
Schur transforms to expose multiplicities or invariant subspaces in natural
orthogonal-tensor, permutation-tensor, code, or tensor-isomorphism instances.
That program remains proof-gated by a natural decision reduction, input-state
preparation, the published large-loop-parameter regime, and dequantization.
"""

from __future__ import annotations

import itertools
import json
import math
from dataclasses import asdict, dataclass
from pathlib import Path
from typing import Any, Hashable, Iterable, Mapping

from research_registry import utc_now


REPORT_PATH = Path(
    "research/reductions/diagram_hidden_subalgebra_coset_no_go.json"
)
DEFAULT_EXPERIMENT_ID = "EXP-DIAGRAM-HIDDEN-SUBALGEBRA-COSET-NO-GO"
DEFAULT_CANDIDATE_ID = "DIAGRAM-MODULE-SPECTRAL"

Element = Hashable
MultiplicationTable = Mapping[tuple[Element, Element], Element]


@dataclass(frozen=True)
class FiniteMonoidCosetControl:
    control_id: str
    monoid_order: int
    submonoid_order: int
    submonoid_is_group: bool
    right_translate_count: int
    right_translates_equal_or_disjoint: bool
    right_translates_cover_monoid: bool
    overlapping_unequal_translate_pair_count: int
    theorem_equivalence_verified: bool
    status: str


@dataclass(frozen=True)
class DiagramQFTScalingBoundary:
    diagram_order: int
    brauer_basis_dimension_decimal: str
    brauer_basis_dimension_log2: float
    partition_basis_dimension_decimal: str
    partition_basis_dimension_log2: float
    necessary_brauer_loop_parameter_log2_from_published_factor: float
    necessary_partition_loop_parameter_log2_from_published_factor: float
    ordinary_coset_partition_available_for_bridge_generated_subalgebra: bool
    efficient_qft_implies_hidden_problem_solver: bool
    module_spectrum_direction_not_killed_by_coset_no_go: bool
    status: str


@dataclass(frozen=True)
class FiniteMonoidCosetTheorem:
    statement: str
    forward_implication: str
    finite_inverse_step: str
    converse: str
    diagram_generator_consequence: str
    projective_rescaling_scope: str
    equal_or_disjoint_implies_group: bool
    group_implies_equal_or_disjoint: bool
    bridge_generated_hidden_cosets_valid: bool
    theorem_verified: bool
    status: str


@dataclass(frozen=True)
class DiagramModuleReplacementHypothesis:
    hypothesis_id: str
    problem_family: str
    input_model: str
    mechanism: str
    target_reduction: str
    classical_baselines: tuple[str, ...]
    required_proof_obligations: tuple[str, ...]
    decisive_falsifiers: tuple[str, ...]
    natural_decision_reduction_proved: bool
    coherent_input_preparation_proved: bool
    asymptotically_unitary_parameter_regime_proved: bool
    dequantization_survived: bool
    proof_gate_passed: bool
    status: str


@dataclass(frozen=True)
class DiagramHiddenSubalgebraCosetNoGoReport:
    created_at: str
    theorem_contract: dict[str, Any]
    finite_controls: list[FiniteMonoidCosetControl]
    scaling_records: list[DiagramQFTScalingBoundary]
    theorem: FiniteMonoidCosetTheorem
    replacement_hypothesis: DiagramModuleReplacementHypothesis
    proof_obligations: list[dict[str, str | bool]]
    adversarial_audit: list[dict[str, str | bool]]
    literature_links: list[dict[str, str | bool]]
    headline_metrics: dict[str, int | float]
    claim_gate: dict[str, str | bool]
    status: str
    summary: str
    falsifiers_triggered: list[str]


def multiply(
    table: MultiplicationTable,
    left: Element,
    right: Element,
) -> Element:
    try:
        return table[(left, right)]
    except KeyError as error:
        raise ValueError("multiplication table is incomplete") from error


def validate_finite_monoid(
    elements: Iterable[Element],
    identity: Element,
    table: MultiplicationTable,
) -> tuple[Element, ...]:
    universe = tuple(elements)
    if not universe or len(set(universe)) != len(universe):
        raise ValueError("elements must be a nonempty duplicate-free collection")
    if identity not in universe:
        raise ValueError("identity is absent")
    element_set = set(universe)
    for left in universe:
        for right in universe:
            product = multiply(table, left, right)
            if product not in element_set:
                raise ValueError("multiplication is not closed")
            if multiply(table, identity, left) != left:
                raise ValueError("left identity law failed")
            if multiply(table, left, identity) != left:
                raise ValueError("right identity law failed")
            for third in universe:
                if multiply(table, product, third) != multiply(
                    table, left, multiply(table, right, third)
                ):
                    raise ValueError("associativity failed")
    return universe


def is_submonoid(
    subset: Iterable[Element],
    identity: Element,
    table: MultiplicationTable,
) -> bool:
    members = set(subset)
    return bool(members) and identity in members and all(
        multiply(table, left, right) in members
        for left in members
        for right in members
    )


def submonoid_is_group(
    subset: Iterable[Element],
    identity: Element,
    table: MultiplicationTable,
) -> bool:
    members = set(subset)
    if not is_submonoid(members, identity, table):
        raise ValueError("subset is not a submonoid")
    return all(
        any(
            multiply(table, element, candidate) == identity
            and multiply(table, candidate, element) == identity
            for candidate in members
        )
        for element in members
    )


def right_translates(
    elements: Iterable[Element],
    subset: Iterable[Element],
    table: MultiplicationTable,
) -> tuple[frozenset[Element], ...]:
    universe = tuple(elements)
    members = tuple(subset)
    return tuple(
        frozenset(multiply(table, element, member) for member in members)
        for element in universe
    )


def translate_partition_statistics(
    elements: Iterable[Element],
    subset: Iterable[Element],
    table: MultiplicationTable,
) -> tuple[int, bool, bool, int]:
    universe = tuple(elements)
    translates = right_translates(universe, subset, table)
    unique = tuple(dict.fromkeys(translates))
    overlapping_unequal = sum(
        bool(left & right) and left != right
        for index, left in enumerate(unique)
        for right in unique[index + 1 :]
    )
    equal_or_disjoint = overlapping_unequal == 0
    cover = set().union(*unique) == set(universe)
    return len(unique), equal_or_disjoint, cover, overlapping_unequal


def audit_monoid_submonoid(
    control_id: str,
    elements: Iterable[Element],
    identity: Element,
    table: MultiplicationTable,
    subset: Iterable[Element],
) -> FiniteMonoidCosetControl:
    universe = validate_finite_monoid(elements, identity, table)
    members = tuple(subset)
    if not is_submonoid(members, identity, table):
        raise ValueError("control subset is not a submonoid")
    group = submonoid_is_group(members, identity, table)
    translate_count, equal_or_disjoint, cover, overlap_count = (
        translate_partition_statistics(universe, members, table)
    )
    verified = equal_or_disjoint == group and cover
    return FiniteMonoidCosetControl(
        control_id=control_id,
        monoid_order=len(universe),
        submonoid_order=len(members),
        submonoid_is_group=group,
        right_translate_count=translate_count,
        right_translates_equal_or_disjoint=equal_or_disjoint,
        right_translates_cover_monoid=cover,
        overlapping_unequal_translate_pair_count=overlap_count,
        theorem_equivalence_verified=verified,
        status=(
            "group-coset-partition-control"
            if verified and group
            else (
                "nonunit-overlapping-translate-control"
                if verified
                else "finite-monoid-coset-control-failure"
            )
        ),
    )


def transformation_monoid(degree: int) -> tuple[tuple[tuple[int, ...], ...], dict]:
    if degree < 1:
        raise ValueError("degree must be positive")
    elements = tuple(itertools.product(range(degree), repeat=degree))
    table = {
        (left, right): tuple(left[right[index]] for index in range(degree))
        for left in elements
        for right in elements
    }
    return elements, table


def enumerate_submonoids(
    elements: tuple[Element, ...],
    identity: Element,
    table: MultiplicationTable,
) -> tuple[frozenset[Element], ...]:
    if len(elements) > 16:
        raise ValueError("exhaustive submonoid enumeration is capped at order 16")
    output = []
    others = tuple(element for element in elements if element != identity)
    for mask in range(1 << len(others)):
        subset = {identity}
        subset.update(
            others[index]
            for index in range(len(others))
            if mask & (1 << index)
        )
        if is_submonoid(subset, identity, table):
            output.append(frozenset(subset))
    return tuple(output)


def odd_double_factorial(value: int) -> int:
    output = 1
    for factor in range(1, value + 1, 2):
        output *= factor
    return output


def bell_number(value: int) -> int:
    if value < 0:
        raise ValueError("value must be nonnegative")
    row = [1]
    for size in range(1, value + 1):
        next_row = [row[-1]]
        for index in range(1, size + 1):
            next_row.append(next_row[-1] + row[index - 1])
        row = next_row
    return row[0]


def diagram_qft_scaling_boundary(
    diagram_order: int,
) -> DiagramQFTScalingBoundary:
    if diagram_order < 1:
        raise ValueError("diagram_order must be positive")
    brauer_dimension = odd_double_factorial(2 * diagram_order - 1)
    partition_dimension = bell_number(2 * diagram_order)
    brauer_log = math.log2(brauer_dimension)
    partition_log = math.log2(partition_dimension)
    return DiagramQFTScalingBoundary(
        diagram_order=diagram_order,
        brauer_basis_dimension_decimal=str(brauer_dimension),
        brauer_basis_dimension_log2=brauer_log,
        partition_basis_dimension_decimal=str(partition_dimension),
        partition_basis_dimension_log2=partition_log,
        necessary_brauer_loop_parameter_log2_from_published_factor=(
            2.0 * brauer_log
        ),
        necessary_partition_loop_parameter_log2_from_published_factor=(
            2.0 * partition_log
        ),
        ordinary_coset_partition_available_for_bridge_generated_subalgebra=False,
        efficient_qft_implies_hidden_problem_solver=False,
        module_spectrum_direction_not_killed_by_coset_no_go=True,
        status="naive-cosets-impossible-module-spectrum-model-open",
    )


def finite_monoid_coset_theorem() -> FiniteMonoidCosetTheorem:
    return FiniteMonoidCosetTheorem(
        statement=(
            "For a submonoid B of a finite monoid M, the family {aB:a in M} "
            "is equal-or-disjoint if and only if B is a group of units."
        ),
        forward_implication=(
            "For b in B, bB intersects B at b, hence bB=B. Therefore 1=bc "
            "for some c in B."
        ),
        finite_inverse_step=(
            "In a finite monoid, bc=1 makes right multiplication by b "
            "injective and hence surjective; a left inverse exists and equals c."
        ),
        converse=(
            "If B is a group and ab=a'b', then a=a'b'b^-1, so intersecting "
            "right translates are equal."
        ),
        diagram_generator_consequence=(
            "A nonidentity bridge/reset idempotent is a nonunit, so any hidden "
            "submonoid containing it fails the ordinary coset partition."
        ),
        projective_rescaling_scope=(
            "The conclusion applies to the projective diagram-basis monoid "
            "after removing nonzero loop scalars; it does not classify arbitrary "
            "linear subspaces or module-theoretic hiding notions."
        ),
        equal_or_disjoint_implies_group=True,
        group_implies_equal_or_disjoint=True,
        bridge_generated_hidden_cosets_valid=False,
        theorem_verified=True,
        status="finite-monoid-coset-partition-iff-group-proved",
    )


def replacement_hypothesis() -> DiagramModuleReplacementHypothesis:
    return DiagramModuleReplacementHypothesis(
        hypothesis_id="HYP-DIAGRAM-MODULE-SPECTRAL",
        problem_family=(
            "Promise module-isomorphism or invariant-multiplicity problems for "
            "orthogonal/permutation tensor actions, with Brauer or partition "
            "algebra as the explicit commutant"
        ),
        input_model=(
            "Succinct reversible preparation of module states plus block access "
            "to diagram-generator actions; no arbitrary hidden-coset oracle"
        ),
        mechanism=(
            "Diagram-algebra QFT or generalized Schur transform, followed by "
            "irrep/multiplicity interference and a decision observable"
        ),
        target_reduction=(
            "Find a natural tensor/code/isomorphism promise whose YES/NO cases "
            "differ in a diagram-module multiplicity accessible at inverse-"
            "polynomial source mass"
        ),
        classical_baselines=(
            "explicit invariant and canonical-form algorithms",
            "randomized trace/moment estimation",
            "tensor-network contraction at matched width",
            "low-dimensional and low-rank multiplicity formulas",
            "classical sampling of the measured Fourier marginal",
        ),
        required_proof_obligations=(
            "natural scalable decision problem and reduction",
            "succinct coherent input and generator access",
            "valid large-loop-parameter regime at polynomial input length",
            "inverse-polynomial informative Fourier mass",
            "efficient decision observable after the QFT",
            "superpolynomial classical barrier in the same access model",
        ),
        decisive_falsifiers=(
            "classical canonicalization is polynomial on the promised family",
            "the Fourier marginal is classically sampleable",
            "informative sectors have exponentially small source mass",
            "the required loop parameter or state preparation is exponentially encoded",
            "the reduction lands on NP-complete unrestricted contraction equivalence",
        ),
        natural_decision_reduction_proved=False,
        coherent_input_preparation_proved=False,
        asymptotically_unitary_parameter_regime_proved=False,
        dequantization_survived=False,
        proof_gate_passed=False,
        status="high-variance-replacement-hypothesis-proof-gate-open",
    )


def run_diagram_hidden_subalgebra_coset_no_go(
) -> DiagramHiddenSubalgebraCosetNoGoReport:
    t2_elements, t2_table = transformation_monoid(2)
    identity = (0, 1)
    swap = (1, 0)
    constant_zero = (0, 0)
    controls = [
        audit_monoid_submonoid(
            "T2-UNIT-GROUP",
            t2_elements,
            identity,
            t2_table,
            (identity, swap),
        ),
        audit_monoid_submonoid(
            "T2-RESET-IDEMPOTENT",
            t2_elements,
            identity,
            t2_table,
            (identity, constant_zero),
        ),
        audit_monoid_submonoid(
            "T2-TRIVIAL-GROUP",
            t2_elements,
            identity,
            t2_table,
            (identity,),
        ),
    ]
    all_t2_submonoids = enumerate_submonoids(t2_elements, identity, t2_table)
    exhaustive_failures = sum(
        translate_partition_statistics(t2_elements, subset, t2_table)[1]
        != submonoid_is_group(subset, identity, t2_table)
        for subset in all_t2_submonoids
    )
    scaling = [diagram_qft_scaling_boundary(n) for n in (4, 8, 16, 32)]
    theorem = finite_monoid_coset_theorem()
    hypothesis = replacement_hypothesis()
    control_failures = sum(not row.theorem_equivalence_verified for row in controls)
    verified = (
        theorem.theorem_verified
        and control_failures == 0
        and exhaustive_failures == 0
    )
    metrics: dict[str, int | float] = {
        "finite_monoid_coset_partition_iff_group_theorem_count": int(verified),
        "finite_control_count": len(controls),
        "finite_control_failure_count": control_failures,
        "exhaustive_t2_submonoid_count": len(all_t2_submonoids),
        "exhaustive_t2_equivalence_failure_count": exhaustive_failures,
        "nonunit_overlapping_translate_control_count": sum(
            not row.submonoid_is_group
            and row.overlapping_unequal_translate_pair_count > 0
            for row in controls
        ),
        "maximum_brauer_basis_dimension_log2": max(
            row.brauer_basis_dimension_log2 for row in scaling
        ),
        "maximum_partition_basis_dimension_log2": max(
            row.partition_basis_dimension_log2 for row in scaling
        ),
        "naive_hidden_subalgebra_coset_model_count": 0,
        "replacement_hypothesis_proof_gate_pass_count": int(
            hypothesis.proof_gate_passed
        ),
        "new_quantum_algorithm_count": 0,
    }
    return DiagramHiddenSubalgebraCosetNoGoReport(
        created_at=utc_now(),
        theorem_contract={
            "object": "finite projective diagram-basis monoid",
            "naive_hidden_structure": "submonoid generated by diagram generators",
            "coset_requirement": "right translates are equal or disjoint",
            "theorem_boundary": "this happens exactly for subgroups of units",
            "replacement_search_space": (
                "module spectra, multiplicities, and invariant subspaces under "
                "succinct diagram-algebra actions"
            ),
        },
        finite_controls=controls,
        scaling_records=scaling,
        theorem=theorem,
        replacement_hypothesis=hypothesis,
        proof_obligations=[
            {
                "obligation": "test_naive_hidden_subalgebra_coset_partition",
                "resolved": verified,
                "resolution": (
                    "The finite-monoid theorem proves that nonunit diagram "
                    "generators make ordinary cosets impossible."
                ),
            },
            {
                "obligation": "define_a_valid_noncoset_oracle_state_model",
                "resolved": False,
                "resolution": (
                    "Ideals, Green relations, and fixed factorizations have not "
                    "yet been connected to orthogonal quantum sample states."
                ),
            },
            {
                "obligation": "reduce_a_natural_problem_to_module_spectral_data",
                "resolved": False,
                "resolution": (
                    "The replacement hypothesis names tensor/code families but "
                    "does not yet prove a YES/NO multiplicity separation."
                ),
            },
            {
                "obligation": "satisfy_the_published_qft_parameter_regime",
                "resolved": False,
                "resolution": (
                    "The approximation factor is at least linear in algebra "
                    "dimension, requiring a separate sufficiently large loop "
                    "parameter and a compatible input representation."
                ),
            },
            {
                "obligation": "survive_matched_classical_baselines",
                "resolved": False,
                "resolution": "No module-spectrum candidate has yet passed dequantization.",
            },
        ],
        adversarial_audit=[
            {
                "challenge": "A fixed factorization restores ordinary cosets.",
                "survives": False,
                "response": (
                    "A factorization may define a different sample model, but it "
                    "does not make overlapping principal translates disjoint."
                ),
            },
            {
                "challenge": "Rescaling an idempotent bridge makes it invertible.",
                "survives": False,
                "response": (
                    "A nonidentity idempotent cannot be a unit; projective loop "
                    "rescaling does not restore lost propagating rank."
                ),
            },
            {
                "challenge": "An efficient algebra QFT automatically defines an HSP.",
                "survives": False,
                "response": (
                    "The transform diagonalizes algebra action but supplies no "
                    "hiding relation, orthogonal coset samples, or decoder."
                ),
            },
            {
                "challenge": "The NP-complete contraction connection is positive evidence.",
                "survives": False,
                "response": (
                    "It is evidence against an unrestricted BQP algorithm. A "
                    "credible route needs an intermediate promise and a matched "
                    "classical barrier."
                ),
            },
            {
                "challenge": "The no-go also kills module-spectrum algorithms.",
                "survives": False,
                "response": (
                    "Module decompositions do not require principal translates "
                    "to partition the diagram basis."
                ),
            },
        ],
        literature_links=[
            {
                "paper_id": "FOXMAN-NEHORAN-DING-2026",
                "title": "Efficient Quantum Fourier Transforms For Semisimple Algebras",
                "url": "https://arxiv.org/abs/2605.05337",
                "use": (
                    "Primary QFT theorem and explicit hidden-subalgebra caveats; "
                    "source of the module-spectrum replacement direction"
                ),
                "external_theorem_not_reproved_here": True,
            }
        ],
        headline_metrics=metrics,
        claim_gate={
            "naive_diagram_hidden_subalgebra_has_hsp_cosets": False,
            "bridge_or_reset_generated_right_translates_partition_basis": False,
            "efficient_diagram_qft_alone_implies_hidden_problem_algorithm": False,
            "module_spectrum_replacement_direction_structurally_open": True,
            "module_spectrum_replacement_passes_proof_gate": False,
            "natural_decision_reduction_proved": False,
            "dequantization_survived": False,
            "speedup_claim_allowed": False,
            "reason": (
                "Noninvertible diagram generators forbid ordinary coset "
                "partitions. A module-based problem may use the new QFT, but no "
                "natural reduction or quantum advantage has been established."
            ),
        },
        status=(
            "naive-hidden-subalgebra-cosets-killed-module-spectrum-open"
            if verified
            else "finite-monoid-coset-theorem-control-failure"
        ),
        summary=(
            "Proved that HSP-style right cosets in a finite diagram-basis "
            "monoid are possible only for hidden groups of units, killing the "
            "naive bridge/reset hidden-subalgebra model and redirecting the "
            "semisimple-QFT opportunity toward proof-gated module spectra."
        ),
        falsifiers_triggered=[
            "Noninvertible bridge/reset generators cannot define equal-or-disjoint right cosets.",
            "A fixed factorization is a new oracle model, not a repair of the coset partition.",
            "An efficient semisimple-algebra QFT does not itself define a hidden problem or decoder.",
            "The unrestricted graph-contraction connection is NP-complete and therefore not a credible BQP target without a promise.",
            "The published QFT approximation requires a separate large loop-parameter regime.",
            "The module-spectrum replacement has not passed its reduction or dequantization gates.",
        ],
    )


def write_diagram_hidden_subalgebra_coset_no_go(
    path: Path = REPORT_PATH,
    write_registry: bool = True,
    registry_experiment_id: str = (
        "EXP-DIAGRAM-HIDDEN-SUBALGEBRA-COSET-NO-GO"
    ),
    registry_candidate_id: str = "CODE-COSET-COLLECTIVE",
    registry_result_id: str = "",
    **kwargs: Any,
) -> dict[str, Any]:
    path = path
    output_path = path
    for _k in ("write_registry", "registry_experiment_id", "registry_candidate_id", "registry_result_id"):
        kwargs.pop(_k, None)
    payload = asdict(run_diagram_hidden_subalgebra_coset_no_go())
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, indent=2, sort_keys=True))
    return payload


if __name__ == "__main__":
    output = write_diagram_hidden_subalgebra_coset_no_go()
    print(json.dumps(output["headline_metrics"], indent=2, sort_keys=True))
