"""Constant-mass Plancherel portfolios for physical wreath recoupling.

The stable-sector audit proves fixed bounded tails have vanishing mass. The
next possible shortcut is an explicit catalog of high-Plancherel typical
partitions. This module computes the smallest exact top-atom catalogs reaching
fixed source mass and translates that into physical pair-label coverage.

Aggarwal and Elboim (arXiv:2605.25995) prove that the largest S_n Plancherel
atom is exp(-Theta(sqrt(n))). Therefore every fixed-positive-mass catalog has
exp(Omega(sqrt(n))) entries. No polynomial list of partition-specific
recoupling certificates can cover natural inputs. A viable construction must
be uniform in a sampled partition description.

Finite S_3 through S_6 controls also measure the exact modular Hadamard rank of
physical third-moment features generated by an 80%-source-mass portfolio on
the four-class commutator kernel. These are mechanism controls only.
"""

from __future__ import annotations

import itertools
import json
import math
from dataclasses import asdict, dataclass
from fractions import Fraction
from pathlib import Path
from typing import Any

from representation_obstruction import (
    hook_length_dimension,
    integer_partitions,
)
from research_registry import (
    ExperimentResultRecord,
    NegativeResultRecord,
    upsert_experiment_result,
    upsert_negative_result,
    utc_now,
)
from self_dual_wreath_character_moments import (
    PhysicalWreathIrrepDescriptor,
    equal_pair_descriptor,
    unequal_pair_descriptor,
)
from self_dual_wreath_equal_commutator_audit import (
    refined_commutator_kernel,
)
from self_dual_wreath_stable_commutator_rank import (
    MODULAR_PRIME,
    _insert_modular_vector,
    physical_third_feature,
)


SELF_DUAL_WREATH_TYPICAL_PARTITION_PORTFOLIO_PATH = Path(
    "research/representation/"
    "self_dual_wreath_typical_partition_portfolio.json"
)
DEFAULT_EXPERIMENT_ID = (
    "EXP-CODE-SELF-DUAL-WREATH-TYPICAL-PARTITION-PORTFOLIO"
)
DEFAULT_CANDIDATE_ID = "CODE-COSET-COLLECTIVE"
MAXIMAL_DIMENSION_PAPER_ID = "aggarwal-elboim-maximal-dimension-2026"
MAXIMAL_DIMENSION_PAPER_URL = "https://arxiv.org/abs/2605.25995"


@dataclass(frozen=True)
class TypicalCatalogRecord:
    n: int
    partition_count: int
    target_source_mass: str
    catalog_partition_count: int
    exact_catalog_source_mass: str
    exact_physical_pair_label_mass: str
    maximum_atom_partition: tuple[int, ...]
    exact_maximum_plancherel_atom: str
    maximum_atom_count_lower_bound: int
    polynomial_catalog_can_cover_target_asymptotically: bool
    status: str


@dataclass(frozen=True)
class TypicalFeatureRankRecord:
    n: int
    target_source_mass: str
    selected_partition_count: int
    exact_selected_source_mass: str
    exact_selected_physical_pair_mass: str
    physical_descriptor_count: int
    refined_kernel_support_count: int
    maximum_degree: int
    monomial_count: int
    modular_rank_by_degree: list[int]
    final_modular_rank: int
    full_kernel_separated: bool
    finite_control_only: bool
    status: str


@dataclass(frozen=True)
class SelfDualWreathTypicalPartitionPortfolioReport:
    created_at: str
    literature_linked_theorem: dict[str, Any]
    portfolio_contract: dict[str, Any]
    catalog_records: list[TypicalCatalogRecord]
    rank_records: list[TypicalFeatureRankRecord]
    headline_metrics: dict[str, int | float]
    claim_gate: dict[str, bool | str]
    status: str
    summary: str
    falsifiers_triggered: list[str]


def plancherel_atoms(
    n: int,
) -> tuple[tuple[tuple[int, ...], Fraction], ...]:
    if n < 1:
        raise ValueError("n must be positive")
    order = math.factorial(n)
    rows = [
        (
            partition,
            Fraction(hook_length_dimension(partition) ** 2, order),
        )
        for partition in integer_partitions(n)
    ]
    return tuple(sorted(rows, key=lambda row: (-row[1], row[0])))


def minimal_plancherel_catalog(
    n: int,
    target_mass: Fraction,
) -> tuple[tuple[tuple[int, ...], ...], Fraction]:
    if not 0 < target_mass <= 1:
        raise ValueError("target_mass must lie in (0,1]")
    selected = []
    total = Fraction()
    for partition, mass in plancherel_atoms(n):
        selected.append(partition)
        total += mass
        if total >= target_mass:
            return tuple(selected), total
    raise ArithmeticError("Plancherel atoms did not reach target mass")


def catalog_record(
    n: int,
    target_mass: Fraction,
) -> TypicalCatalogRecord:
    atoms = plancherel_atoms(n)
    selected, total = minimal_plancherel_catalog(n, target_mass)
    maximum_partition, maximum_atom = atoms[0]
    lower_bound = math.ceil(target_mass / maximum_atom)
    return TypicalCatalogRecord(
        n=n,
        partition_count=len(atoms),
        target_source_mass=str(target_mass),
        catalog_partition_count=len(selected),
        exact_catalog_source_mass=str(total),
        exact_physical_pair_label_mass=str(total * total),
        maximum_atom_partition=maximum_partition,
        exact_maximum_plancherel_atom=str(maximum_atom),
        maximum_atom_count_lower_bound=lower_bound,
        polynomial_catalog_can_cover_target_asymptotically=False,
        status="constant-mass-catalog-superpolynomial-asymptotically",
    )


def portfolio_descriptors(
    partitions: tuple[tuple[int, ...], ...],
) -> tuple[PhysicalWreathIrrepDescriptor, ...]:
    descriptors: list[PhysicalWreathIrrepDescriptor] = []
    for partition in partitions:
        descriptors.append(equal_pair_descriptor(partition, 1))
        descriptors.append(equal_pair_descriptor(partition, -1))
    for left_index, left in enumerate(partitions):
        for right in partitions[left_index + 1 :]:
            descriptors.append(unequal_pair_descriptor(left, right))
    return tuple(descriptors)


def audit_typical_feature_rank(
    n: int,
    target_source_mass: Fraction = Fraction(4, 5),
    maximum_degree: int = 4,
    prime: int = MODULAR_PRIME,
) -> TypicalFeatureRankRecord:
    partitions, source_mass = minimal_plancherel_catalog(
        n, target_source_mass
    )
    descriptors = portfolio_descriptors(partitions)
    support = tuple(
        quadruple
        for quadruple, _ in refined_commutator_kernel(n)
    )
    features = [
        tuple(
            physical_third_feature(descriptor, quadruple)
            for quadruple in support
        )
        for descriptor in descriptors
    ]
    basis: dict[int, dict[int, int]] = {}
    _insert_modular_vector((1,) * len(support), basis, prime)
    ranks = []
    monomial_count = 1
    for degree in range(1, maximum_degree + 1):
        for indices in itertools.combinations_with_replacement(
            range(len(features)), degree
        ):
            vector = [
                math.prod(features[index][row] for index in indices)
                for row in range(len(support))
            ]
            _insert_modular_vector(vector, basis, prime)
            monomial_count += 1
            if len(basis) == len(support):
                break
        ranks.append(len(basis))
        if len(basis) == len(support):
            ranks.extend(
                [len(basis)] * (maximum_degree - degree)
            )
            break
    return TypicalFeatureRankRecord(
        n=n,
        target_source_mass=str(target_source_mass),
        selected_partition_count=len(partitions),
        exact_selected_source_mass=str(source_mass),
        exact_selected_physical_pair_mass=str(
            source_mass * source_mass
        ),
        physical_descriptor_count=len(descriptors),
        refined_kernel_support_count=len(support),
        maximum_degree=maximum_degree,
        monomial_count=monomial_count,
        modular_rank_by_degree=ranks,
        final_modular_rank=len(basis),
        full_kernel_separated=len(basis) == len(support),
        finite_control_only=True,
        status=(
            "finite-typical-portfolio-separates-kernel"
            if len(basis) == len(support)
            else "finite-typical-portfolio-partial-rank"
        ),
    )


def run_self_dual_wreath_typical_partition_portfolio() -> (
    SelfDualWreathTypicalPartitionPortfolioReport
):
    target_masses = (Fraction(1, 2), Fraction(4, 5), Fraction(9, 10))
    catalog_records = [
        catalog_record(n, target)
        for n in (8, 12, 16, 20, 24, 28, 32)
        for target in target_masses
    ]
    rank_records = [
        audit_typical_feature_rank(n)
        for n in (3, 4, 5, 6)
    ]
    ninety = [
        record
        for record in catalog_records
        if record.target_source_mass == "9/10"
    ]
    metrics: dict[str, int | float] = {
        "catalog_record_count": len(catalog_records),
        "maximum_catalog_n": max(
            record.n for record in catalog_records
        ),
        "maximum_partition_count": max(
            record.partition_count for record in catalog_records
        ),
        "maximum_ninety_percent_catalog_count": max(
            record.catalog_partition_count for record in ninety
        ),
        "maximum_ninety_percent_atom_lower_bound": max(
            record.maximum_atom_count_lower_bound for record in ninety
        ),
        "constant_mass_polynomial_catalog_no_go_theorem_count": 1,
        "finite_typical_rank_record_count": len(rank_records),
        "maximum_typical_rank_control_n": max(
            record.n for record in rank_records
        ),
        "maximum_typical_feature_algebra_rank": max(
            record.final_modular_rank for record in rank_records
        ),
        "maximum_typical_refined_kernel_support_count": max(
            record.refined_kernel_support_count
            for record in rank_records
        ),
        "finite_typical_full_kernel_separation_count": sum(
            record.full_kernel_separated for record in rank_records
        ),
        "uniform_partition_description_recoupling_rule_count": 0,
        "polynomial_typical_four_class_contraction_count": 0,
        "coherent_blockwise_frame_pseudoinverse_count": 0,
        "polynomial_hidden_permutation_decoder_count": 0,
    }
    return SelfDualWreathTypicalPartitionPortfolioReport(
        created_at=utc_now(),
        literature_linked_theorem={
            "paper_id": MAXIMAL_DIMENSION_PAPER_ID,
            "url": MAXIMAL_DIMENSION_PAPER_URL,
            "statement": (
                "max_lambda d_lambda=sqrt(n!) "
                "exp(-(d+o(1))sqrt(n)), d>0"
            ),
            "consequence": (
                "the maximum Plancherel atom is "
                "exp(-Theta(sqrt(n))), so fixed-positive mass needs "
                "exp(Omega(sqrt(n))) partition labels"
            ),
        },
        portfolio_contract={
            "source_catalog": (
                "smallest descending-Plancherel atom prefix reaching "
                "the declared exact source mass"
            ),
            "physical_pair_coverage": (
                "source catalog mass squared after equal signs are aggregated"
            ),
            "finite_rank_control": (
                "Hadamard feature algebra generated by all physical labels "
                "whose two source partitions lie in an 80%-mass catalog"
            ),
            "algorithmic_requirement": (
                "one uniform reversible rule taking arbitrary sampled "
                "partition descriptions; no explicit precertified catalog"
            ),
        },
        catalog_records=catalog_records,
        rank_records=rank_records,
        headline_metrics=metrics,
        claim_gate={
            "constant_mass_catalog_counts_computed": True,
            "constant_mass_polynomial_catalog_ruled_out": True,
            "finite_typical_feature_algebra_rank_measured": True,
            "uniform_partition_description_recoupling_rule_proved": False,
            "polynomial_typical_four_class_contraction_proved": False,
            "coherent_blockwise_frame_pseudoinverse_proved": False,
            "polynomial_hidden_permutation_decoder_proved": False,
            "speedup_claim_allowed": False,
            "reason": (
                "Constant natural mass requires a superpolynomial catalog of "
                "typical partitions. Finite feature rank does not provide a "
                "uniform partition-description recoupling rule."
            ),
        },
        status=(
            "constant-mass-catalog-shortcut-rejected-"
            "uniform-typical-recoupling-required"
        ),
        summary=(
            "Computed exact constant-mass Plancherel catalogs through n="
            f"{metrics['maximum_catalog_n']} and finite typical four-class "
            f"feature ranks through n={metrics['maximum_typical_rank_control_n']}; "
            "the maximal-atom theorem rules out polynomial precertified "
            "catalog coverage, leaving a uniform partition-description rule."
        ),
        falsifiers_triggered=[
            "Physical pair-label coverage is the square of source catalog mass.",
            "The exact top-atom catalog needed for fixed mass grows across the finite scaling sweep.",
            "The maximal Plancherel atom theorem makes every constant-mass explicit catalog superpolynomial.",
            "Finite constant-mass feature rank is a mechanism control, not a uniform growing-n construction.",
            "No partition-description-uniform recoupling transform, support gap, pseudoinverse, or decoder exists.",
        ],
    )


def write_self_dual_wreath_typical_partition_portfolio(
    path: Path = SELF_DUAL_WREATH_TYPICAL_PARTITION_PORTFOLIO_PATH,
    write_registry: bool = True,
    registry_experiment_id: str = DEFAULT_EXPERIMENT_ID,
    registry_candidate_id: str = DEFAULT_CANDIDATE_ID,
    registry_result_id: str | None = None,
) -> dict[str, Any]:
    payload = asdict(run_self_dual_wreath_typical_partition_portfolio())
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, indent=2, sort_keys=True))
    return payload


if __name__ == "__main__":
    report = write_self_dual_wreath_typical_partition_portfolio()
    print(json.dumps(report["headline_metrics"], indent=2, sort_keys=True))
