"""Binary endpoint compilation needs aggregate metrics, not a small algebra.

At one hierarchical merge, quotient the internal child relations and retain
the common crossing coefficient space.  In internal/crossing coordinates let
the two positive child kernels be

    G_s = [D_s  B_s; B_s^*  C_s],       s in {L,R}.

The exact child short metrics are the Schur shorts

    E_s = C_s - B_s^* D_s^+ B_s,                         (1)

and the binary relative isometry and effects are

    M   = E_L+E_R,
    T_s = E_s^(1/2) M^(-1/2),
    K_s = T_s^*T_s = M^(-1/2)E_sM^(-1/2).                (2)

Equation (1) is the explicit operator-valued Schur/Racah normal form.  With
coordinate projections ``P_I,P_C``, its embedded version is

    P_C G_s P_C
      - P_C G_s P_I (P_I G_s P_I)^+ P_I G_s P_C.         (3)

Thus ``E_s`` lies in the finite-dimensional rational C*-closure generated by
the local physical/Racah kernel and the coordinate projections.  This is an
exact structural reduction, but it does not imply that the generated algebra
has polynomial dimension.

There is nevertheless a complete conditional binary compiler.  Suppose one
has coherent block encodings of ``E_L,E_R`` with normalization at most
``beta``, on one parent-propagated retained fiber satisfying

    a I <= E_s <= b I.                                    (4)

QSVT gives the contractions

    R_s = E_s^(1/2)/sqrt(b),
    Q   = sqrt(2a) M^(-1/2).

One address qubit prepares ``Y=2^(-1/2)[R_L;R_R]``.  Then exactly

    YQ = sqrt(a/b) T,       T=[T_L;T_R],                  (5)

so the endpoint signal normalization is ``sqrt(b/a)``, independent of the
leaf count.  Moreover

    K_s >= a/(2b) I,        I-K_s >= a/(2b) I.            (6)

For ``beta/a=poly(n)`` and inverse-polynomial requested error, standard
block-encoding functional calculus and robust oblivious amplification give a
polynomial coherent two-outcome dilation.  Per-level errors and discarded
native mass add.  At tree depth ``L``, one therefore needs local error
``O(epsilon/L)`` and conditional native loss ``o(1/L)`` per level.

The small-algebra shortcut is false even under stronger promises.  Let

    A=diag(a_1,...,a_D),       B=I+eta |v><v|,

where the ``a_i`` are distinct in ``[1,3/2]`` and every entry of ``v`` is
``1/sqrt(D)``.  If ``P_i`` are the spectral projections of ``A``, then

    P_i(B-I)P_j = (eta/D) |i><j|.                         (7)

Hence two positive generators with condition numbers at most ``3/2``
generate all of ``M_D(C)``, of dimension ``D^2``.  Their binary endpoint is
also uniformly separated from zero and one.  Fixed arity, conditioning, and
a constant endpoint gap therefore do not force a poly-dimensional Racah
algebra.  This is not a circuit lower bound: succinct block encodings of two
full-algebra generators can still make (5) efficient.

The present GPE/addressed-cross-map stack does not meet the positive premise.
It supplies leaf projectors or individual cross blocks.  Uniformly assembling
an aggregate child frame from ``q_s`` leaves exposes ``F_s/q_s``; obtaining
``E_s=X^*F_s^+X`` through that canonical route retains the leaf-width scale.
Finite physical vertex-kernel extraction proves (1) algebraically but does
not provide a reversible all-``n`` node labeler or a polynomial-normalized
aggregate block encoding.  Weak final-root/eight-way spectral laws supply
fixed-window native mass for those fixed levels, not the all-depth
``o(1/L)`` recurrence.

Consequently the next gate is exact and narrow: construct a uniform coherent
aggregate short-metric oracle (or implement (5) directly) for every retained
node.  A direct representation-specific Schur/Racah Naimark transform remains
possible.  No arbitrary-query lower bound, physical PGM, decoder, classical
separation, or speedup is proved.
"""

from __future__ import annotations

import json
import math
from dataclasses import asdict, dataclass
from pathlib import Path
from typing import Any

import numpy as np

from research_registry import (
    ExperimentRecord,
    NegativeResultRecord,
    upsert_experiment,
    upsert_negative_result,
    utc_now,
)


REPORT_PATH = Path(
    "research/representation/"
    "self_dual_wreath_hierarchical_endpoint_schur_algebra_boundary.json"
)
DEFAULT_EXPERIMENT_ID = (
    "EXP-CODE-SELF-DUAL-WREATH-HIERARCHICAL-ENDPOINT-"
    "SCHUR-ALGEBRA-BOUNDARY"
)
DEFAULT_CANDIDATE_ID = "CODE-COSET-COLLECTIVE"
NEGATIVE_RESULT_ID = (
    "SCHUR-COMPANION-FIXED-ARITY-WELL-CONDITIONED-"
    "NO-POLY-DIMENSIONAL-ENDPOINT-ALGEBRA"
)
QSVT_URL = "https://arxiv.org/abs/1806.01838"


@dataclass(frozen=True)
class OperatorSchurShortControl:
    control_id: str
    internal_dimension: int
    crossing_dimension: int
    full_kernel_dimension: int
    left_full_kernel_minimum_eigenvalue: float
    right_full_kernel_minimum_eigenvalue: float
    left_internal_minimum_eigenvalue: float
    right_internal_minimum_eigenvalue: float
    left_short_minimum_eigenvalue: float
    left_short_maximum_eigenvalue: float
    right_short_minimum_eigenvalue: float
    right_short_maximum_eigenvalue: float
    short_metric_commutator_norm: float
    maximum_direct_to_rational_short_residual: float
    parent_metric_minimum_eigenvalue: float
    parent_metric_maximum_eigenvalue: float
    endpoint_effect_sum_residual: float
    endpoint_isometry_residual: float
    endpoint_effect_minimum_eigenvalue: float
    endpoint_complement_minimum_eigenvalue: float
    exact_operator_schur_endpoint_normal_form_verified: bool
    status: str


@dataclass(frozen=True)
class ConditionalEndpointCompilerControl:
    control_id: str
    fiber_dimension: int
    short_metric_lower_bound: float
    short_metric_upper_bound: float
    supplied_block_encoding_normalization: float
    normalized_metric_signal_lower_edge: float
    normalized_metric_signal_upper_edge: float
    parent_inverse_root_contraction_norm: float
    maximum_child_root_contraction_norm: float
    binary_stack_contraction_norm: float
    direct_endpoint_isometry_residual: float
    compiled_signal_normalization: float
    predicted_signal_normalization: float
    compiled_to_scaled_endpoint_residual: float
    endpoint_effect_lower_bound: float
    observed_endpoint_effect_minimum: float
    observed_endpoint_complement_minimum: float
    qsvt_degree_upper_proxy: int
    robust_amplification_call_proxy: int
    postselection_required_after_amplification: bool
    exact_conditional_endpoint_compiler_verified: bool
    status: str


@dataclass(frozen=True)
class FullMatrixAlgebraControl:
    logical_dimension: int
    generator_count: int
    first_generator_minimum_eigenvalue: float
    first_generator_maximum_eigenvalue: float
    second_generator_minimum_eigenvalue: float
    second_generator_maximum_eigenvalue: float
    maximum_generator_condition_number: float
    generator_commutator_norm: float
    constructed_matrix_unit_count: int
    generated_algebra_dimension: int
    full_matrix_algebra_dimension: int
    maximum_matrix_unit_reconstruction_residual: float
    endpoint_effect_minimum_eigenvalue: float
    endpoint_complement_minimum_eigenvalue: float
    endpoint_two_sided_edge: float
    fixed_arity_well_conditioned_implies_small_algebra: bool
    exact_full_matrix_algebra_counterfamily_verified: bool
    status: str


@dataclass(frozen=True)
class EndpointAccessInterfaceRecord:
    interface_id: str
    supplied_object: str
    normalization: str
    reversible_uniform_node_labeler: bool
    supplies_parent_common_fiber: bool
    supplies_aggregate_short_metric_block_encoding: bool
    supplies_retained_spectral_window: bool
    supplies_all_depth_native_mass_recurrence: bool
    compiles_binary_endpoint_given_contract: bool
    compiled: bool
    status: str


@dataclass(frozen=True)
class HierarchicalEndpointScalingRecord:
    n: int
    group_order_decimal: str
    selected_copy_count: int
    orientation_leaf_count_decimal: str
    binary_tree_depth: int
    early_child_leaf_width_decimal: str
    early_child_leaf_width_log2: int
    canonical_uniform_frame_normalization_log2: int
    fixed_level_short_metric_lower: float
    fixed_level_short_metric_upper: float
    conditional_endpoint_signal_normalization: float
    per_level_operator_error_budget: float
    required_per_level_native_mass_loss: str
    compact_aggregate_metric_oracle_proved: bool
    all_depth_parent_trim_recurrence_proved: bool
    conditional_binary_compiler_polynomial_given_metric_oracles: bool
    direct_schur_racah_naimark_ruled_out: bool
    status: str


@dataclass(frozen=True)
class HierarchicalEndpointSchurAlgebraTheorem:
    operator_schur_short: str
    binary_endpoint: str
    conditional_block_compiler: str
    endpoint_edge: str
    query_and_error_recurrence: str
    algebra_counterfamily: str
    current_access_verdict: str
    native_mass_boundary: str
    surviving_route: str
    scope: str
    theorem_verified: bool
    status: str


@dataclass(frozen=True)
class HierarchicalEndpointSchurAlgebraReport:
    created_at: str
    theorem_contract: dict[str, Any]
    theorem: HierarchicalEndpointSchurAlgebraTheorem
    schur_short_controls: list[OperatorSchurShortControl]
    conditional_compiler_controls: list[ConditionalEndpointCompilerControl]
    full_algebra_controls: list[FullMatrixAlgebraControl]
    interface_inventory: list[EndpointAccessInterfaceRecord]
    scaling_records: list[HierarchicalEndpointScalingRecord]
    circuit_contract: list[dict[str, str | bool | int | float]]
    proof_obligations: list[dict[str, str | bool]]
    adversarial_audit: list[dict[str, str | bool]]
    literature_links: list[dict[str, str | bool]]
    headline_metrics: dict[str, int | float]
    claim_gate: dict[str, str | bool]
    status: str
    summary: str
    falsifiers_triggered: list[str]


def _hermitian(matrix: np.ndarray) -> np.ndarray:
    return (matrix + matrix.conj().T) / 2.0


def _psd_power(
    matrix: np.ndarray,
    exponent: float,
    *,
    tolerance: float = 1e-10,
) -> np.ndarray:
    values, vectors = np.linalg.eigh(_hermitian(matrix))
    if len(values) and values[0] < -100 * tolerance:
        raise ArithmeticError("matrix must be positive semidefinite")
    powered = np.zeros_like(values)
    positive = values > 100 * tolerance
    powered[positive] = values[positive] ** exponent
    return (vectors * powered) @ vectors.conj().T


def _random_positive_kernel(
    seed: int,
    dimension: int,
    *,
    floor: float,
) -> np.ndarray:
    if dimension < 2 or floor <= 0:
        raise ValueError("invalid positive-kernel parameters")
    rng = np.random.default_rng(seed)
    raw = rng.normal(size=(dimension, dimension)) + 1j * rng.normal(
        size=(dimension, dimension)
    )
    gram = raw.conj().T @ raw / dimension
    return _hermitian(gram + floor * np.eye(dimension, dtype=complex))


def operator_schur_short(
    kernel: np.ndarray,
    internal_dimension: int,
    *,
    tolerance: float = 1e-10,
) -> np.ndarray:
    """Return equation (1) for one PSD internal/crossing block kernel."""

    value = _hermitian(np.asarray(kernel, dtype=complex))
    if value.ndim != 2 or value.shape[0] != value.shape[1]:
        raise ValueError("kernel must be square")
    if not 0 <= internal_dimension < value.shape[0]:
        raise ValueError("invalid internal dimension")
    if np.linalg.eigvalsh(value)[0] < -100 * tolerance:
        raise ValueError("kernel must be positive semidefinite")
    internal = value[:internal_dimension, :internal_dimension]
    cross = value[:internal_dimension, internal_dimension:]
    crossing = value[internal_dimension:, internal_dimension:]
    if not internal_dimension:
        return crossing
    short = crossing - cross.conj().T @ np.linalg.pinv(
        internal,
        rcond=tolerance,
    ) @ cross
    return _hermitian(short)


def embedded_rational_schur_short(
    kernel: np.ndarray,
    internal_dimension: int,
    *,
    tolerance: float = 1e-10,
) -> np.ndarray:
    """Evaluate equation (3) and return its crossing block."""

    dimension = kernel.shape[0]
    if not 0 <= internal_dimension < dimension:
        raise ValueError("invalid internal dimension")
    internal_projection = np.zeros((dimension, dimension), dtype=complex)
    internal_projection[:internal_dimension, :internal_dimension] = np.eye(
        internal_dimension,
        dtype=complex,
    )
    crossing_projection = np.eye(dimension, dtype=complex) - internal_projection
    internal_kernel = internal_projection @ kernel @ internal_projection
    embedded = (
        crossing_projection @ kernel @ crossing_projection
        - crossing_projection
        @ kernel
        @ internal_projection
        @ np.linalg.pinv(internal_kernel, rcond=tolerance)
        @ internal_projection
        @ kernel
        @ crossing_projection
    )
    return _hermitian(embedded[internal_dimension:, internal_dimension:])


def endpoint_from_short_metrics(
    left_short: np.ndarray,
    right_short: np.ndarray,
    *,
    tolerance: float = 1e-10,
) -> dict[str, Any]:
    left = _hermitian(np.asarray(left_short, dtype=complex))
    right = _hermitian(np.asarray(right_short, dtype=complex))
    if left.shape != right.shape or left.ndim != 2 or left.shape[0] != left.shape[1]:
        raise ValueError("short metrics must share one square fiber")
    if min(np.linalg.eigvalsh(left)[0], np.linalg.eigvalsh(right)[0]) <= 100 * tolerance:
        raise ValueError("short metrics must be positive definite")
    parent = left + right
    parent_inverse_root = _psd_power(parent, -0.5, tolerance=tolerance)
    rows = (
        _psd_power(left, 0.5, tolerance=tolerance) @ parent_inverse_root,
        _psd_power(right, 0.5, tolerance=tolerance) @ parent_inverse_root,
    )
    endpoint = np.vstack(rows)
    effects = tuple(_hermitian(row.conj().T @ row) for row in rows)
    return {
        "left": left,
        "right": right,
        "parent": parent,
        "parent_inverse_root": parent_inverse_root,
        "rows": rows,
        "endpoint": endpoint,
        "effects": effects,
    }


def _schur_control_system(
    seed: int,
    *,
    internal_dimension: int,
    crossing_dimension: int,
) -> tuple[np.ndarray, np.ndarray]:
    dimension = internal_dimension + crossing_dimension
    left = _random_positive_kernel(seed, dimension, floor=0.7)
    right = _random_positive_kernel(seed + 193, dimension, floor=0.9)
    return left, right


def audit_operator_schur_endpoint(
    control_id: str,
    left_kernel: np.ndarray,
    right_kernel: np.ndarray,
    internal_dimension: int,
    *,
    tolerance: float = 1e-9,
) -> OperatorSchurShortControl:
    if left_kernel.shape != right_kernel.shape:
        raise ValueError("child kernels must share one shape")
    left_short = operator_schur_short(
        left_kernel,
        internal_dimension,
        tolerance=tolerance,
    )
    right_short = operator_schur_short(
        right_kernel,
        internal_dimension,
        tolerance=tolerance,
    )
    left_rational = embedded_rational_schur_short(
        left_kernel,
        internal_dimension,
        tolerance=tolerance,
    )
    right_rational = embedded_rational_schur_short(
        right_kernel,
        internal_dimension,
        tolerance=tolerance,
    )
    rational_residual = max(
        float(np.linalg.norm(left_short - left_rational, ord=2)),
        float(np.linalg.norm(right_short - right_rational, ord=2)),
    )
    data = endpoint_from_short_metrics(
        left_short,
        right_short,
        tolerance=tolerance,
    )
    identity = np.eye(left_short.shape[0], dtype=complex)
    effect_sum = float(
        np.linalg.norm(sum(data["effects"], np.zeros_like(identity)) - identity, ord=2)
    )
    isometry = float(
        np.linalg.norm(data["endpoint"].conj().T @ data["endpoint"] - identity, ord=2)
    )
    left_values = np.linalg.eigvalsh(left_short)
    right_values = np.linalg.eigvalsh(right_short)
    parent_values = np.linalg.eigvalsh(data["parent"])
    left_full_values = np.linalg.eigvalsh(_hermitian(left_kernel))
    right_full_values = np.linalg.eigvalsh(_hermitian(right_kernel))
    left_internal_values = np.linalg.eigvalsh(
        _hermitian(left_kernel[:internal_dimension, :internal_dimension])
    )
    right_internal_values = np.linalg.eigvalsh(
        _hermitian(right_kernel[:internal_dimension, :internal_dimension])
    )
    effect_values = np.linalg.eigvalsh(data["effects"][0])
    complement_values = np.linalg.eigvalsh(data["effects"][1])
    commutator = float(
        np.linalg.norm(
            left_short @ right_short - right_short @ left_short,
            ord=2,
        )
    )
    verified = bool(
        max(rational_residual, effect_sum, isometry) <= 10_000 * tolerance
        and left_values[0] > 100 * tolerance
        and right_values[0] > 100 * tolerance
    )
    return OperatorSchurShortControl(
        control_id=control_id,
        internal_dimension=internal_dimension,
        crossing_dimension=left_short.shape[0],
        full_kernel_dimension=left_kernel.shape[0],
        left_full_kernel_minimum_eigenvalue=float(left_full_values[0]),
        right_full_kernel_minimum_eigenvalue=float(right_full_values[0]),
        left_internal_minimum_eigenvalue=float(left_internal_values[0]),
        right_internal_minimum_eigenvalue=float(right_internal_values[0]),
        left_short_minimum_eigenvalue=float(left_values[0]),
        left_short_maximum_eigenvalue=float(left_values[-1]),
        right_short_minimum_eigenvalue=float(right_values[0]),
        right_short_maximum_eigenvalue=float(right_values[-1]),
        short_metric_commutator_norm=commutator,
        maximum_direct_to_rational_short_residual=rational_residual,
        parent_metric_minimum_eigenvalue=float(parent_values[0]),
        parent_metric_maximum_eigenvalue=float(parent_values[-1]),
        endpoint_effect_sum_residual=effect_sum,
        endpoint_isometry_residual=isometry,
        endpoint_effect_minimum_eigenvalue=float(effect_values[0]),
        endpoint_complement_minimum_eigenvalue=float(complement_values[0]),
        exact_operator_schur_endpoint_normal_form_verified=verified,
        status=(
            "exact-operator-schur-short-endpoint-normal-form"
            if verified
            else "operator-schur-endpoint-control-failure"
        ),
    )


def audit_conditional_endpoint_compiler(
    control_id: str,
    left_short: np.ndarray,
    right_short: np.ndarray,
    *,
    supplied_normalization: float | None = None,
    requested_error: float = 1e-6,
    tolerance: float = 1e-9,
) -> ConditionalEndpointCompilerControl:
    if not 0 < requested_error < 1:
        raise ValueError("requested error must lie in (0,1)")
    data = endpoint_from_short_metrics(
        left_short,
        right_short,
        tolerance=tolerance,
    )
    left_values = np.linalg.eigvalsh(data["left"])
    right_values = np.linalg.eigvalsh(data["right"])
    lower = float(min(left_values[0], right_values[0]))
    upper = float(max(left_values[-1], right_values[-1]))
    beta = float(upper if supplied_normalization is None else supplied_normalization)
    if beta + 100 * tolerance < upper:
        raise ValueError("block-encoding normalization must dominate the metric norm")
    left_root = _psd_power(data["left"], 0.5, tolerance=tolerance) / math.sqrt(upper)
    right_root = _psd_power(data["right"], 0.5, tolerance=tolerance) / math.sqrt(upper)
    stack = np.vstack((left_root, right_root)) / math.sqrt(2.0)
    parent_filter = math.sqrt(2.0 * lower) * data["parent_inverse_root"]
    compiled = stack @ parent_filter
    scale = math.sqrt(lower / upper)
    target = data["endpoint"]
    residual = float(np.linalg.norm(compiled - scale * target, ord=2))
    identity = np.eye(target.shape[1], dtype=complex)
    target_residual = float(np.linalg.norm(target.conj().T @ target - identity, ord=2))
    effect_values = np.linalg.eigvalsh(data["effects"][0])
    complement_values = np.linalg.eigvalsh(data["effects"][1])
    edge_bound = lower / (2.0 * upper)
    degree_proxy = math.ceil(
        (beta / lower) * math.log(4.0 / requested_error)
    )
    amplification = math.ceil(math.sqrt(upper / lower))
    verified = bool(
        residual <= 10_000 * tolerance
        and target_residual <= 10_000 * tolerance
        and np.linalg.norm(left_root, ord=2) <= 1 + 1000 * tolerance
        and np.linalg.norm(right_root, ord=2) <= 1 + 1000 * tolerance
        and np.linalg.norm(parent_filter, ord=2) <= 1 + 1000 * tolerance
        and effect_values[0] + 1000 * tolerance >= edge_bound
        and complement_values[0] + 1000 * tolerance >= edge_bound
    )
    return ConditionalEndpointCompilerControl(
        control_id=control_id,
        fiber_dimension=target.shape[1],
        short_metric_lower_bound=lower,
        short_metric_upper_bound=upper,
        supplied_block_encoding_normalization=beta,
        normalized_metric_signal_lower_edge=lower / beta,
        normalized_metric_signal_upper_edge=upper / beta,
        parent_inverse_root_contraction_norm=float(
            np.linalg.norm(parent_filter, ord=2)
        ),
        maximum_child_root_contraction_norm=float(
            max(np.linalg.norm(left_root, ord=2), np.linalg.norm(right_root, ord=2))
        ),
        binary_stack_contraction_norm=float(np.linalg.norm(stack, ord=2)),
        direct_endpoint_isometry_residual=target_residual,
        compiled_signal_normalization=1.0 / scale,
        predicted_signal_normalization=math.sqrt(upper / lower),
        compiled_to_scaled_endpoint_residual=residual,
        endpoint_effect_lower_bound=edge_bound,
        observed_endpoint_effect_minimum=float(effect_values[0]),
        observed_endpoint_complement_minimum=float(complement_values[0]),
        qsvt_degree_upper_proxy=degree_proxy,
        robust_amplification_call_proxy=amplification,
        postselection_required_after_amplification=False,
        exact_conditional_endpoint_compiler_verified=verified,
        status=(
            "conditional-binary-endpoint-block-compiler-exact"
            if verified
            else "conditional-endpoint-compiler-control-failure"
        ),
    )


def full_algebra_generators(
    dimension: int,
    *,
    coupling: float = 0.4,
) -> tuple[np.ndarray, np.ndarray]:
    if dimension < 2 or not 0 < coupling <= 0.5:
        raise ValueError("invalid full-algebra parameters")
    diagonal = np.linspace(1.0, 1.5, dimension)
    first = np.diag(diagonal).astype(complex)
    vector = np.ones(dimension, dtype=complex) / math.sqrt(dimension)
    second = np.eye(dimension, dtype=complex) + coupling * np.outer(
        vector,
        vector.conj(),
    )
    return first, second


def audit_full_matrix_algebra_counterfamily(
    dimension: int,
    *,
    coupling: float = 0.4,
    tolerance: float = 1e-9,
) -> FullMatrixAlgebraControl:
    first, second = full_algebra_generators(dimension, coupling=coupling)
    difference = second - np.eye(dimension, dtype=complex)
    residual = 0.0
    constructed = 0
    expected_scale = coupling / dimension
    for row in range(dimension):
        left_projection = np.zeros((dimension, dimension), dtype=complex)
        left_projection[row, row] = 1.0
        for column in range(dimension):
            right_projection = np.zeros((dimension, dimension), dtype=complex)
            right_projection[column, column] = 1.0
            recovered = left_projection @ difference @ right_projection
            expected = np.zeros((dimension, dimension), dtype=complex)
            expected[row, column] = expected_scale
            residual = max(
                residual,
                float(np.linalg.norm(recovered - expected, ord=2)),
            )
            constructed += int(np.linalg.norm(recovered, ord=2) > 100 * tolerance)
    endpoint = endpoint_from_short_metrics(first, second, tolerance=tolerance)
    effect_values = np.linalg.eigvalsh(endpoint["effects"][0])
    complement_values = np.linalg.eigvalsh(endpoint["effects"][1])
    first_values = np.linalg.eigvalsh(first)
    second_values = np.linalg.eigvalsh(second)
    condition = max(
        float(first_values[-1] / first_values[0]),
        float(second_values[-1] / second_values[0]),
    )
    commutator = float(np.linalg.norm(first @ second - second @ first, ord=2))
    full_dimension = dimension**2
    verified = bool(
        residual <= 100 * tolerance
        and constructed == full_dimension
        and condition <= 1.5 + 100 * tolerance
        and min(effect_values[0], complement_values[0]) > 0.25
    )
    return FullMatrixAlgebraControl(
        logical_dimension=dimension,
        generator_count=2,
        first_generator_minimum_eigenvalue=float(first_values[0]),
        first_generator_maximum_eigenvalue=float(first_values[-1]),
        second_generator_minimum_eigenvalue=float(second_values[0]),
        second_generator_maximum_eigenvalue=float(second_values[-1]),
        maximum_generator_condition_number=condition,
        generator_commutator_norm=commutator,
        constructed_matrix_unit_count=constructed,
        generated_algebra_dimension=full_dimension,
        full_matrix_algebra_dimension=full_dimension,
        maximum_matrix_unit_reconstruction_residual=residual,
        endpoint_effect_minimum_eigenvalue=float(effect_values[0]),
        endpoint_complement_minimum_eigenvalue=float(complement_values[0]),
        endpoint_two_sided_edge=float(min(effect_values[0], complement_values[0])),
        fixed_arity_well_conditioned_implies_small_algebra=False,
        exact_full_matrix_algebra_counterfamily_verified=verified,
        status=(
            "two-well-conditioned-generators-produce-full-matrix-algebra"
            if verified
            else "full-matrix-algebra-countercontrol-failure"
        ),
    )


def endpoint_access_interface_inventory() -> list[EndpointAccessInterfaceRecord]:
    return [
        EndpointAccessInterfaceRecord(
            interface_id="gpe-leaf-projector-select",
            supplied_object="coherently addressed leaf projector E_e and support transport",
            normalization="one per address; aggregate q-leaf frame is exposed as F/q",
            reversible_uniform_node_labeler=True,
            supplies_parent_common_fiber=False,
            supplies_aggregate_short_metric_block_encoding=False,
            supplies_retained_spectral_window=False,
            supplies_all_depth_native_mass_recurrence=False,
            compiles_binary_endpoint_given_contract=False,
            compiled=True,
            status="leaf-access-not-aggregate-short-metric",
        ),
        EndpointAccessInterfaceRecord(
            interface_id="addressed-cross-gram-pair",
            supplied_object="one Q_f^*Q_e block and its GPE pair polar",
            normalization="one per pair; uniform dense assembly retains leaf width",
            reversible_uniform_node_labeler=True,
            supplies_parent_common_fiber=False,
            supplies_aggregate_short_metric_block_encoding=False,
            supplies_retained_spectral_window=False,
            supplies_all_depth_native_mass_recurrence=False,
            compiles_binary_endpoint_given_contract=False,
            compiled=True,
            status="pair-local-racah-block-global-schur-short-open",
        ),
        EndpointAccessInterfaceRecord(
            interface_id="finite-vertex-kernel-extractor",
            supplied_object="classical physical/Racah endpoint Gram blocks and exact Schur short",
            normalization="finite explicit matrices only",
            reversible_uniform_node_labeler=False,
            supplies_parent_common_fiber=True,
            supplies_aggregate_short_metric_block_encoding=False,
            supplies_retained_spectral_window=False,
            supplies_all_depth_native_mass_recurrence=False,
            compiles_binary_endpoint_given_contract=False,
            compiled=False,
            status="exact-algebraic-normal-form-not-uniform-circuit",
        ),
        EndpointAccessInterfaceRecord(
            interface_id="fixed-level-natural-window",
            supplied_object="annealed final-root/eight-way spectral edge and o(1) native loss",
            normalization="information-theoretic fixed-level trim",
            reversible_uniform_node_labeler=False,
            supplies_parent_common_fiber=False,
            supplies_aggregate_short_metric_block_encoding=False,
            supplies_retained_spectral_window=True,
            supplies_all_depth_native_mass_recurrence=False,
            compiles_binary_endpoint_given_contract=False,
            compiled=False,
            status="fixed-level-window-no-coherent-projector-or-all-depth-recurrence",
        ),
        EndpointAccessInterfaceRecord(
            interface_id="aggregate-short-metric-block-encoding",
            supplied_object="coherent E_L,E_R block encodings on one parent-propagated fiber",
            normalization="beta with beta/a=poly(n)",
            reversible_uniform_node_labeler=True,
            supplies_parent_common_fiber=True,
            supplies_aggregate_short_metric_block_encoding=True,
            supplies_retained_spectral_window=True,
            supplies_all_depth_native_mass_recurrence=False,
            compiles_binary_endpoint_given_contract=True,
            compiled=False,
            status="minimal-sufficient-hierarchical-interface",
        ),
        EndpointAccessInterfaceRecord(
            interface_id="direct-local-schur-racah-naimark",
            supplied_object="source-adapted two-outcome endpoint isometry T",
            normalization="one",
            reversible_uniform_node_labeler=True,
            supplies_parent_common_fiber=True,
            supplies_aggregate_short_metric_block_encoding=False,
            supplies_retained_spectral_window=True,
            supplies_all_depth_native_mass_recurrence=False,
            compiles_binary_endpoint_given_contract=True,
            compiled=False,
            status="direct-representation-specific-bypass-open",
        ),
    ]


def hierarchical_endpoint_scaling_record(
    n: int,
    *,
    fixed_jump_log2_arity: int = 12,
    target_error: float = 0.01,
) -> HierarchicalEndpointScalingRecord:
    if n < 3 or fixed_jump_log2_arity < 0 or not 0 < target_error < 1:
        raise ValueError("invalid hierarchical scaling parameters")
    order = math.factorial(n)
    selected = (order - 1).bit_length() + 2
    leaf_count = 1 << selected
    early_log2 = max(0, selected - fixed_jump_log2_arity)
    early_width = 1 << early_log2
    lower = 0.1
    upper = 10.0
    depth = selected
    return HierarchicalEndpointScalingRecord(
        n=n,
        group_order_decimal=str(order),
        selected_copy_count=selected,
        orientation_leaf_count_decimal=str(leaf_count),
        binary_tree_depth=depth,
        early_child_leaf_width_decimal=str(early_width),
        early_child_leaf_width_log2=early_log2,
        canonical_uniform_frame_normalization_log2=early_log2,
        fixed_level_short_metric_lower=lower,
        fixed_level_short_metric_upper=upper,
        conditional_endpoint_signal_normalization=math.sqrt(upper / lower),
        per_level_operator_error_budget=target_error / depth,
        required_per_level_native_mass_loss=f"o(1/{depth})",
        compact_aggregate_metric_oracle_proved=False,
        all_depth_parent_trim_recurrence_proved=False,
        conditional_binary_compiler_polynomial_given_metric_oracles=True,
        direct_schur_racah_naimark_ruled_out=False,
        status="binary-endpoint-compiler-conditional-aggregate-metric-access-open",
    )


def run_hierarchical_endpoint_schur_algebra_boundary(
) -> HierarchicalEndpointSchurAlgebraReport:
    systems = [
        _schur_control_system(401, internal_dimension=2, crossing_dimension=3),
        _schur_control_system(809, internal_dimension=3, crossing_dimension=4),
    ]
    schur_controls = [
        audit_operator_schur_endpoint(
            f"OPERATOR-SCHUR-{index}",
            left,
            right,
            internal_dimension=index + 1,
        )
        for index, (left, right) in enumerate(systems, start=1)
    ]
    compiler_controls = []
    for index, ((left, right), schur) in enumerate(zip(systems, schur_controls), start=1):
        left_short = operator_schur_short(left, schur.internal_dimension)
        right_short = operator_schur_short(right, schur.internal_dimension)
        upper = max(
            float(np.linalg.eigvalsh(left_short)[-1]),
            float(np.linalg.eigvalsh(right_short)[-1]),
        )
        compiler_controls.append(
            audit_conditional_endpoint_compiler(
                f"CONDITIONAL-ENDPOINT-{index}",
                left_short,
                right_short,
                supplied_normalization=1.25 * upper,
            )
        )
    algebra_controls = [
        audit_full_matrix_algebra_counterfamily(dimension)
        for dimension in (2, 4, 8, 16)
    ]
    interfaces = endpoint_access_interface_inventory()
    scaling = [
        hierarchical_endpoint_scaling_record(n)
        for n in (12, 16, 24, 32, 40, 48, 64, 80)
    ]
    failures = sum(
        not row.exact_operator_schur_endpoint_normal_form_verified
        for row in schur_controls
    ) + sum(
        not row.exact_conditional_endpoint_compiler_verified
        for row in compiler_controls
    ) + sum(
        not row.exact_full_matrix_algebra_counterfamily_verified
        for row in algebra_controls
    )
    verified = failures == 0
    theorem = HierarchicalEndpointSchurAlgebraTheorem(
        operator_schur_short=(
            "After internal quotient, E_s=C_s-B_s^*D_s^+B_s is the exact operator-valued child short metric and lies in the rational C*-closure of the local Racah kernel and coordinate projections."
        ),
        binary_endpoint=(
            "M=E_L+E_R, T_s=sqrt(E_s)M^-1/2, and K_s=M^-1/2 E_s M^-1/2."
        ),
        conditional_block_compiler=(
            "Given beta-normalized block encodings with aI<=E_s<=bI, QSVT roots and the parent inverse root give YQ=sqrt(a/b)T; robust amplification costs sqrt(b/a) signal calls."
        ),
        endpoint_edge=(
            "Both K_s and I-K_s have minimum eigenvalue at least a/(2b)."
        ),
        query_and_error_recurrence=(
            "A conservative local functional-calculus degree is O((beta/a)log(1/epsilon_v)); coherent tree error and conditional native loss add by level."
        ),
        algebra_counterfamily=(
            "Two PSD generators A=diag(distinct [1,3/2]) and B=I+eta|v><v| generate every matrix unit through P_i(B-I)P_j, so their C*-algebra is M_D despite constant conditioning and endpoint edge."
        ),
        current_access_verdict=(
            "Current GPE and addressed-pair interfaces provide leaf/pair signals, not a reversible polynomial-normalized aggregate E_s oracle on the parent common fiber."
        ),
        native_mass_boundary=(
            "Existing weak laws give fixed-level o(1) loss, but an L-level compiler needs a common parent trim and o(1/L) conditional loss uniformly by level."
        ),
        surviving_route=(
            "Construct aggregate short-metric block encodings directly, carry them recursively with compatible trims, or implement the local Schur/Racah Naimark isometry without materializing E_s."
        ),
        scope=(
            "The algebra counterexample refutes only the small-algebra inference. The access verdict binds the enumerated leaf/pair interfaces and canonical assembly; no arbitrary-query or direct representation-specific circuit lower bound is claimed."
        ),
        theorem_verified=verified,
        status=(
            "hierarchical-endpoint-schur-compiler-reduction-and-full-algebra-boundary-proved"
            if verified
            else "hierarchical-endpoint-schur-algebra-validation-failure"
        ),
    )
    headline = {
        "operator_valued_schur_short_normal_form_theorem_count": int(verified),
        "conditional_binary_endpoint_block_compiler_theorem_count": int(verified),
        "endpoint_two_sided_edge_theorem_count": int(verified),
        "fixed_arity_small_algebra_implication_refutation_count": int(verified),
        "schur_short_control_count": len(schur_controls),
        "conditional_compiler_control_count": len(compiler_controls),
        "full_algebra_control_count": len(algebra_controls),
        "finite_control_failure_count": failures,
        "maximum_schur_rational_residual": max(
            row.maximum_direct_to_rational_short_residual for row in schur_controls
        ),
        "maximum_conditional_compiler_residual": max(
            row.compiled_to_scaled_endpoint_residual for row in compiler_controls
        ),
        "largest_full_algebra_dimension": max(
            row.generated_algebra_dimension for row in algebra_controls
        ),
        "largest_full_algebra_logical_dimension": max(
            row.logical_dimension for row in algebra_controls
        ),
        "compiled_aggregate_short_metric_interface_count": sum(
            row.compiled and row.supplies_aggregate_short_metric_block_encoding
            for row in interfaces
        ),
        "compiled_direct_local_schur_racah_naimark_count": 0,
        "all_depth_native_mass_recurrence_theorem_count": 0,
        "natural_scaling_record_count": len(scaling),
        "physical_pgm_compiler_count": 0,
        "new_quantum_algorithm_count": 0,
    }
    return HierarchicalEndpointSchurAlgebraReport(
        created_at=utc_now(),
        theorem_contract={
            "hypothesis": (
                "Fixed binary arity and constant short-metric conditioning either force a polynomial-dimensional Schur/Racah endpoint algebra or make the current GPE/addressed interfaces sufficient for a uniform local Naimark compiler."
            ),
            "result": (
                "The endpoint is a noncommutative Schur-short rational function and has a polynomial conditional block compiler given aggregate metric access. Fixed arity does not force a small algebra, and current leaf/pair interfaces do not supply the aggregate premise."
            ),
            "scope": theorem.scope,
        },
        theorem=theorem,
        schur_short_controls=schur_controls,
        conditional_compiler_controls=compiler_controls,
        full_algebra_controls=algebra_controls,
        interface_inventory=interfaces,
        scaling_records=scaling,
        circuit_contract=[
            {
                "step": "compute_node_and_parent_trim",
                "operation": "Reversibly compute the node label and enter the single parent-propagated retained fiber.",
                "currently_compiled": False,
            },
            {
                "step": "select_aggregate_short_metric",
                "operation": "Use one address qubit to select beta-normalized block encodings of E_L or E_R.",
                "currently_compiled": False,
            },
            {
                "step": "qsvt_child_roots",
                "operation": "Transform E_s/beta to sqrt(E_s)/sqrt(b) on [a/beta,b/beta].",
                "degree_upper_proxy": "O((beta/a) log(L/epsilon))",
            },
            {
                "step": "qsvt_parent_inverse_root",
                "operation": "LCU the two metrics and transform M/(2beta) to sqrt(2a)M^-1/2.",
                "degree_upper_proxy": "O((beta/a) log(L/epsilon))",
            },
            {
                "step": "binary_stack_and_amplify",
                "operation": "Compose YQ=sqrt(a/b)T and robustly amplify the known isometric signal.",
                "normalization": "sqrt(b/a)",
                "postselection_required": False,
            },
            {
                "step": "uncompute_workspace",
                "operation": "Uncompute functional-calculus, metric SELECT, trim, and node-label workspaces while retaining the endpoint bit.",
                "error_recurrence": "epsilon_root <= sum_level epsilon_level",
                "native_mass_recurrence": "mu_root <= sum_level mu_level",
            },
        ],
        proof_obligations=[
            {
                "obligation": "derive_operator_valued_schur_racah_short_metric",
                "resolved": verified,
                "resolution": "Equations (1) and (3) are the exact positive Schur short in common crossing coordinates, including noncommuting blocks.",
            },
            {
                "obligation": "compile_binary_endpoint_given_aggregate_metric_block_encodings",
                "resolved": verified,
                "resolution": "Equation (5), the two-sided edge, and robust amplification give a leaf-width-independent conditional circuit contract.",
            },
            {
                "obligation": "decide_whether_fixed_arity_forces_poly_dimensional_generator_algebra",
                "resolved": verified,
                "resolution": "Equation (7) explicitly constructs all D^2 matrix units from two well-conditioned generators.",
            },
            {
                "obligation": "construct_uniform_reversible_aggregate_short_metric_oracle",
                "resolved": False,
                "resolution": "Finite kernel extraction and addressed pair access do not implement the global Schur short coherently at polynomial normalization.",
            },
            {
                "obligation": "prove_parent_compatible_all_depth_native_mass_recurrence",
                "resolved": False,
                "resolution": "Fixed-level weak laws do not give the required uniform o(1/L) conditional loss across L=Theta(n log n) levels.",
            },
        ],
        adversarial_audit=[
            {
                "objection": "A binary endpoint necessarily lives in a two-dimensional operator algebra.",
                "resolved": True,
                "resolution": "Binary refers to outcome count, not matrix-algebra dimension; two PSD generators can generate M_D."
            },
            {
                "objection": "A full matrix algebra makes endpoint compilation exponentially hard.",
                "resolved": True,
                "resolution": "Rejected as an inference: succinct block encodings plus a retained window compile the endpoint without enumerating an algebra basis."
            },
            {
                "objection": "Current pairwise Racah blocks already satisfy the aggregate metric premise.",
                "resolved": True,
                "resolution": "Pair blocks are entries; the Schur short contains a global internal inverse and common-fiber compression."
            },
            {
                "objection": "A constant fixed-level edge completes the whole recursion.",
                "resolved": True,
                "resolution": "An L-level tree additionally needs coherent common trims and summable conditional native loss."
            },
            {
                "objection": "The theorem rules out a direct local Schur/Racah Naimark circuit.",
                "resolved": False,
                "resolution": "That circuit bypasses aggregate metric materialization and remains the primary structured escape."
            },
        ],
        literature_links=[
            {
                "paper": "Quantum singular value transformation and beyond",
                "url": QSVT_URL,
                "used_for": "Conditional polynomial functional calculus, products, pseudoinverse filters, and robust oblivious amplification from supplied block encodings.",
                "supplies_wreath_aggregate_metric_oracle": False,
            }
        ],
        headline_metrics=headline,
        claim_gate={
            "operator_valued_schur_short_normal_form_proved": verified,
            "binary_endpoint_compiles_given_aggregate_metric_block_encodings": verified,
            "binary_endpoint_signal_normalization_sqrt_condition_ratio": verified,
            "endpoint_two_sided_edge_a_over_2b_proved": verified,
            "fixed_arity_and_conditioning_imply_poly_dimensional_endpoint_algebra": False,
            "two_well_conditioned_generators_can_generate_full_matrix_algebra": verified,
            "full_matrix_algebra_dimension_is_quantum_circuit_lower_bound": False,
            "current_gpe_supplies_aggregate_short_metric_block_encoding": False,
            "current_addressed_pairs_supply_global_schur_short": False,
            "uniform_reversible_node_labeler_and_parent_trim_compiled": False,
            "all_depth_native_mass_recurrence_proved": False,
            "direct_local_schur_racah_naimark_compiled": False,
            "direct_local_schur_racah_naimark_ruled_out": False,
            "physical_pgm_compiled": False,
            "classical_separation_proved": False,
            "speedup_claim_allowed": False,
        },
        status=theorem.status,
        summary=(
            "Derived the exact operator-valued Schur-short form of every binary endpoint and a leaf-width-independent conditional QSVT/Naimark compiler from aggregate short-metric block encodings. Refuted the proposed polynomial-dimensional-algebra shortcut with two constant-conditioned generators of the full matrix algebra. The remaining gate is a uniform reversible aggregate metric oracle plus parent-compatible all-depth native-mass control; current GPE and addressed-pair interfaces do not provide it."
        ),
        falsifiers_triggered=[
            "Binary fixed arity forces the local Schur/Racah endpoint algebra to have polynomial dimension.",
            "Constant conditioning and a constant endpoint edge force a small generated algebra.",
            "The existing addressed pair-GPE interface already supplies the aggregate short metric required by the conditional binary compiler.",
        ],
    )


def write_hierarchical_endpoint_schur_algebra_boundary_report(
    path: Path = REPORT_PATH,
    *,
    write_registry: bool = True,
) -> dict[str, Any]:
    payload = asdict(run_hierarchical_endpoint_schur_algebra_boundary())
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(
        json.dumps(payload, indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )
    if write_registry:
        upsert_experiment(
            ExperimentRecord(
                id=DEFAULT_EXPERIMENT_ID,
                candidate_id=DEFAULT_CANDIDATE_ID,
                title="Hierarchical endpoint Schur algebra boundary",
                status="completed-exact-conditional-compiler-and-algebra-boundary-theorem",
                hypothesis=payload["theorem_contract"]["hypothesis"],
                protocol=(
                    "Derive the operator-valued internal/crossing Schur short, factor the binary endpoint into block-encoded roots and a parent inverse root, prove the two-sided edge and additive recurrences, construct a full-matrix-algebra counterfamily, and inventory the current typed metric interfaces."
                ),
                positive_signal=(
                    "A uniform reversible node/common-fiber labeler and polynomial-normalized block encoding of each aggregate short metric E_s on parent-compatible trims with summable all-depth native loss."
                ),
                falsifiers=payload["falsifiers_triggered"],
                metrics=list(payload["headline_metrics"].keys()),
                dependencies=[
                    "self_dual_wreath_vertex_kernel_graded_reduction.py",
                    "self_dual_wreath_common_window_access_boundary.py",
                    "self_dual_wreath_positive_naimark_access_equivalence_boundary.py",
                    "self_dual_wreath_recursive_polar_normalization_conservation_boundary.py",
                    "self_dual_wreath_constant_arity_joint_freeness.py",
                ],
                next_actions=[
                    "Attack uniform node labeling and aggregate metric propagation: express the internal/crossing coordinate projections and local Racah kernels as reversible functions of the affine flag, then test whether Schur shorts can be carried upward without returning to leaf-width normalization."
                ],
            )
        )
        upsert_negative_result(
            NegativeResultRecord(
                id=NEGATIVE_RESULT_ID,
                source=str(path),
                claim=(
                    "Fixed binary arity and constant short-metric conditioning force a polynomial-dimensional endpoint Schur/Racah algebra."
                ),
                reason_invalid=(
                    "Two positive generators with spectra in fixed constant windows generate every matrix unit P_i(B-I)P_j and hence all of M_D(C), while their endpoint effect remains uniformly separated from zero and one."
                ),
                lesson=(
                    "Do not enumerate the endpoint algebra. Seek succinct aggregate metric block encodings or a direct local Naimark transform; full algebra dimension alone is not a quantum circuit lower bound."
                ),
                applies_to=[
                    DEFAULT_CANDIDATE_ID,
                    "PO-MECHANISM",
                    "PO-MEASUREMENT",
                    "PO-COMPLEXITY",
                ],
                evidence={
                    "generator_count": 2,
                    "maximum_generator_condition_number": payload["full_algebra_controls"][-1]["maximum_generator_condition_number"],
                    "largest_verified_algebra_dimension": payload["headline_metrics"]["largest_full_algebra_dimension"],
                    "endpoint_two_sided_edge": payload["full_algebra_controls"][-1]["endpoint_two_sided_edge"],
                    "aggregate_metric_conditional_compiler_proved": True,
                    "full_algebra_dimension_is_circuit_lower_bound": False,
                    "direct_schur_racah_naimark_ruled_out": False,
                    "speedup_claim_allowed": False,
                },
            )
        )
    return payload


if __name__ == "__main__":
    result = write_hierarchical_endpoint_schur_algebra_boundary_report()
    print(json.dumps(result["headline_metrics"], indent=2, sort_keys=True))
