"""Operational raw/polar mismatch for the native branch-character ensemble.

The physical joint-character state is generated by the raw isometric field

    K_h=[M_+(h);M_-(h)],

whereas the proposed near-isometric candidate convolution uses the locally
polar-completed field

    J_h=[V_+(h);V_-(h)](P_+(h)+P_-(h))^-1/2.

The predecessor separation theorem proved that the two global fields have
vanishing natural normalized Hilbert--Schmidt overlap.  This module turns that
geometric fact into an operational decoder boundary.

For every ``h``, the cross map is a positive contraction:

    T_h=J_h^*K_h
       =F_h^-1/2 (|M_+(h)|+|M_-(h)|),                  (1)
    0 <= T_h <= I.

For ``k`` source pairs this tensor-factorizes.  Let ``C_J`` and ``C_K`` be the
relative convolutions built from ``J_h`` and ``K_h``, and put

    A=|G|^-1 sum_h J_h^*K_h.                            (2)

Every correct-label diagonal block of ``C_J^*C_K`` is exactly ``A``.  Hence
the correct probability of the unwhitened polar matched filter on the native
raw ensemble is

    P_match=Tr(A^2)/D <= Tr(A)/D
           =Tr(C_J^*C_K)/(|G|D).                        (3)

The right side is precisely the overlap already proved to vanish for natural
globally distinct source portfolios.  Thus direct use of ``C_J^*`` as the
native decoder is asymptotically rejected.

Could global polar whitening rescue it?  Let ``Q=polar(C_J)``,
``E=Q-C_J``,

    R=||C_J^*C_J-I||_F^2/(|G|D),
    kappa=||C_K||^2.

Singular-value calculus gives ``||E||_F^2/(|G|D)<=R``.  Extracting only the
correct candidate blocks is a contraction, so Minkowski and submultiplicity
give the exact portfolio bound

    sqrt(P_Q) <= sqrt(P_match)+sqrt(kappa R),
    P_Q <= (sqrt(overlap)+sqrt(kappa R))^2.              (4)

At ``k=ceil(3log_2|G|)+2``, the quadrant theorem gives
``E R=O(|G|^-0.245...)``.  Therefore any uniform polynomial-in-``n`` bound on
the raw physical concentration ``kappa`` would force the whitened decoder to
fail as well.  Constant success can only come from raw-state concentration on
the Frobenius-small bad singular sector (or from a different decoder).

This reverses the old interpretation of the physical-input gate.  Flat or
polynomial domination does not validate the branch-polar route; together
with raw/polar separation it kills it.  The live question is whether the
native raw frame has sufficiently large, structured concentration and whether
whitening exploits that concentration coherently.  This module neither proves
such concentration nor rules out the actual physical PGM or another decoder.
"""

from __future__ import annotations

import json
import math
from dataclasses import asdict, dataclass
from pathlib import Path
from typing import Any

import numpy as np

from research_registry import utc_now
from self_dual_wreath_branch_character_gpe_dilation_separation import (
    GAMMA,
    raw_branch_isometry,
)
from self_dual_wreath_branch_character_polar_naimark_completion import (
    Label,
    Permutation,
    _inverse_permutation,
    candidate_relative_convolution,
)
from self_dual_wreath_character_moments import compose_permutations
from self_dual_wreath_orientation_fourier_reduction import (
    _source_representation_rows,
)


REPORT_PATH = Path(
    "research/representation/"
    "self_dual_wreath_branch_character_raw_polar_matched_filter_boundary.json"
)
DEFAULT_EXPERIMENT_ID = (
    "EXP-CODE-SELF-DUAL-WREATH-BRANCH-CHARACTER-RAW-POLAR-"
    "MATCHED-FILTER-BOUNDARY"
)
DEFAULT_CANDIDATE_ID = "CODE-COSET-COLLECTIVE"
THREE_QUARTER_EXPONENT = 1.0 + 3.0 * math.log2(3.0 / 4.0)


@dataclass(frozen=True)
class RawPolarMatchedFilterControl:
    control_id: str
    n: int
    source_pair_count: int
    group_order: int
    carrier_dimension: int
    maximum_local_cross_hermiticity_residual: float
    minimum_local_cross_eigenvalue: float
    maximum_local_cross_eigenvalue: float
    matched_cross_hermiticity_residual: float
    matched_cross_minimum_eigenvalue: float
    matched_cross_maximum_eigenvalue: float
    correct_block_identity_residual: float
    global_overlap_identity_residual: float
    normalized_raw_polar_overlap: float
    unwhitened_matched_filter_success: float
    matched_success_upper_bound_residual: float
    polar_convolution_gram_residual: float
    polar_to_convolution_distance: float
    polar_distance_below_gram_residual: bool
    raw_convolution_concentration: float
    whitened_correct_success: float
    whitened_success_upper_bound: float
    whitened_success_bound_verified: bool
    exact_raw_polar_matched_filter_boundary_verified: bool
    status: str


@dataclass(frozen=True)
class RawPolarMatchedFilterScaling:
    n: int
    log2_group_order: float
    copy_count: int
    polynomial_concentration_degree: int
    log2_polynomial_raw_concentration_bound: float
    raw_polar_overlap_upper_bound: float
    log2_polar_gram_residual_upper_bound: float
    log2_concentration_times_gram_upper_bound: float
    whitened_success_upper_bound: float
    three_quarter_power_exponent: float
    polynomial_domination_forces_decoder_failure_asymptotically: bool
    finite_polynomial_domination_failure_visible: bool
    status: str


@dataclass(frozen=True)
class RawPolarMatchedFilterTheorem:
    local_cross_map: str
    correct_block: str
    unwhitened_success: str
    polar_distance: str
    whitened_success: str
    natural_consequence: str
    revised_physical_gate: str
    scope: str
    theorem_verified: bool
    status: str


@dataclass(frozen=True)
class RawPolarMatchedFilterBoundaryReport:
    created_at: str
    theorem_contract: dict[str, Any]
    theorem: RawPolarMatchedFilterTheorem
    finite_controls: list[RawPolarMatchedFilterControl]
    scaling_records: list[RawPolarMatchedFilterScaling]
    proof_obligations: list[dict[str, str | bool]]
    adversarial_audit: list[dict[str, str | bool]]
    headline_metrics: dict[str, int | float]
    claim_gate: dict[str, str | bool]
    status: str
    summary: str
    falsifiers_triggered: list[str]


def _kron_all(matrices: tuple[np.ndarray, ...]) -> np.ndarray:
    output = np.asarray([[1.0]], dtype=complex)
    for matrix in matrices:
        output = np.kron(output, matrix)
    return output


def raw_candidate_relative_convolution(
    labels: tuple[Label, ...],
) -> tuple[np.ndarray, tuple[Permutation, ...], dict[Permutation, np.ndarray]]:
    if not labels:
        raise ValueError("at least one source pair is required")
    group = tuple(_source_representation_rows(labels[0][0]))
    fields = {
        permutation: _kron_all(
            tuple(
                raw_branch_isometry(left, right, permutation)
                for left, right in labels
            )
        )
        for permutation in group
    }
    output_dimension, input_dimension = next(iter(fields.values())).shape
    convolution = np.zeros(
        (
            len(group) * output_dimension,
            len(group) * input_dimension,
        ),
        dtype=complex,
    )
    for output_index, output_group in enumerate(group):
        output_block = slice(
            output_index * output_dimension,
            (output_index + 1) * output_dimension,
        )
        for input_index, input_group in enumerate(group):
            input_block = slice(
                input_index * input_dimension,
                (input_index + 1) * input_dimension,
            )
            relative = compose_permutations(
                _inverse_permutation(input_group),
                output_group,
            )
            convolution[output_block, input_block] = (
                fields[relative] / math.sqrt(len(group))
            )
    return convolution, group, fields


def _canonical_partial_polar(matrix: np.ndarray, tolerance: float) -> np.ndarray:
    left, singular_values, right_star = np.linalg.svd(matrix, full_matrices=False)
    active = singular_values > tolerance
    return left[:, active] @ right_star[active, :]


def _diagonal_block_success(
    decoder_product: np.ndarray,
    group_order: int,
    carrier_dimension: int,
) -> float:
    total = 0.0
    for label in range(group_order):
        block = decoder_product[
            label * carrier_dimension : (label + 1) * carrier_dimension,
            label * carrier_dimension : (label + 1) * carrier_dimension,
        ]
        total += float(np.linalg.norm(block, ord="fro") ** 2)
    return total / (group_order * carrier_dimension)


def audit_raw_polar_matched_filter(
    control_id: str,
    labels: tuple[Label, ...],
    *,
    tolerance: float = 1e-9,
) -> RawPolarMatchedFilterControl:
    polar, group, polar_fields = candidate_relative_convolution(labels)
    raw, raw_group, raw_fields = raw_candidate_relative_convolution(labels)
    if group != raw_group:
        raise ArithmeticError("raw and polar fields enumerate different groups")
    order = len(group)
    carrier = next(iter(polar_fields.values())).shape[1]
    local_cross = {
        element: polar_fields[element].conj().T @ raw_fields[element]
        for element in group
    }
    hermiticity = max(
        float(np.linalg.norm(matrix - matrix.conj().T, ord=2))
        for matrix in local_cross.values()
    )
    local_eigenvalues = np.concatenate(
        [
            np.linalg.eigvalsh((matrix + matrix.conj().T) / 2.0)
            for matrix in local_cross.values()
        ]
    )
    matched = sum(
        local_cross.values(),
        np.zeros((carrier, carrier), dtype=complex),
    ) / order
    matched_hermiticity = float(
        np.linalg.norm(matched - matched.conj().T, ord=2)
    )
    matched_eigenvalues = np.linalg.eigvalsh(
        (matched + matched.conj().T) / 2.0
    )

    product = polar.conj().T @ raw
    block_residual = 0.0
    for label in range(order):
        block = product[
            label * carrier : (label + 1) * carrier,
            label * carrier : (label + 1) * carrier,
        ]
        block_residual = max(
            block_residual,
            float(np.linalg.norm(block - matched, ord=2)),
        )
    overlap = float(np.trace(polar.conj().T @ raw).real / (order * carrier))
    matched_overlap = float(np.trace(matched).real / carrier)
    overlap_residual = abs(overlap - matched_overlap)
    matched_success = float(np.trace(matched.conj().T @ matched).real / carrier)
    matched_bound_residual = max(0.0, matched_success - overlap)

    identity = np.eye(order * carrier, dtype=complex)
    gram_residual = float(
        np.linalg.norm(polar.conj().T @ polar - identity, ord="fro") ** 2
        / (order * carrier)
    )
    polar_isometry = _canonical_partial_polar(polar, tolerance)
    polar_distance = float(
        np.linalg.norm(polar_isometry - polar, ord="fro") ** 2
        / (order * carrier)
    )
    raw_singular_maximum = float(np.linalg.svd(raw, compute_uv=False)[0])
    concentration = raw_singular_maximum**2
    whitened_product = polar_isometry.conj().T @ raw
    whitened_success = _diagonal_block_success(
        whitened_product,
        order,
        carrier,
    )
    upper = (
        math.sqrt(max(0.0, matched_success))
        + math.sqrt(max(0.0, concentration * gram_residual))
    ) ** 2
    upper_verified = whitened_success <= upper + 1000 * tolerance
    distance_verified = polar_distance <= gram_residual + 1000 * tolerance
    verified = bool(
        hermiticity <= 1000 * tolerance
        and local_eigenvalues[0] >= -1000 * tolerance
        and local_eigenvalues[-1] <= 1.0 + 1000 * tolerance
        and matched_hermiticity <= 1000 * tolerance
        and matched_eigenvalues[0] >= -1000 * tolerance
        and matched_eigenvalues[-1] <= 1.0 + 1000 * tolerance
        and block_residual <= 1000 * tolerance
        and overlap_residual <= 1000 * tolerance
        and matched_bound_residual <= 1000 * tolerance
        and distance_verified
        and upper_verified
    )
    return RawPolarMatchedFilterControl(
        control_id=control_id,
        n=sum(labels[0][0]),
        source_pair_count=len(labels),
        group_order=order,
        carrier_dimension=carrier,
        maximum_local_cross_hermiticity_residual=hermiticity,
        minimum_local_cross_eigenvalue=float(local_eigenvalues[0]),
        maximum_local_cross_eigenvalue=float(local_eigenvalues[-1]),
        matched_cross_hermiticity_residual=matched_hermiticity,
        matched_cross_minimum_eigenvalue=float(matched_eigenvalues[0]),
        matched_cross_maximum_eigenvalue=float(matched_eigenvalues[-1]),
        correct_block_identity_residual=block_residual,
        global_overlap_identity_residual=overlap_residual,
        normalized_raw_polar_overlap=overlap,
        unwhitened_matched_filter_success=matched_success,
        matched_success_upper_bound_residual=matched_bound_residual,
        polar_convolution_gram_residual=gram_residual,
        polar_to_convolution_distance=polar_distance,
        polar_distance_below_gram_residual=distance_verified,
        raw_convolution_concentration=concentration,
        whitened_correct_success=whitened_success,
        whitened_success_upper_bound=upper,
        whitened_success_bound_verified=upper_verified,
        exact_raw_polar_matched_filter_boundary_verified=verified,
        status=(
            "raw-polar-matched-filter-and-whitening-dichotomy-verified"
            if verified
            else "raw-polar-matched-filter-control-failure"
        ),
    )


def raw_polar_matched_filter_scaling(
    n: int,
    *,
    polynomial_concentration_degree: int = 20,
) -> RawPolarMatchedFilterScaling:
    if n < 2 or polynomial_concentration_degree < 0:
        raise ValueError("invalid scaling parameters")
    log_order = math.log2(math.factorial(n))
    copies = math.ceil(3.0 * log_order) + 2
    low_order_log = math.log2(n + 1) - n / 4.0
    gamma_log = copies * math.log2(GAMMA)
    low_order = 2.0**low_order_log if low_order_log > -1074 else 0.0
    gamma_term = 2.0**gamma_log if gamma_log > -1074 else 0.0
    overlap = min(1.0, low_order + gamma_term)
    inverse_order = 2.0**(-log_order) if log_order < 1074 else 0.0
    log_order_minus_one = log_order + math.log2(1.0 - inverse_order)
    gram_log = log_order_minus_one + copies * math.log2(3.0 / 4.0)
    concentration_log = polynomial_concentration_degree * math.log2(n)
    product_log = concentration_log + gram_log
    product = 2.0**product_log if product_log > -1074 else 0.0
    upper = (math.sqrt(overlap) + math.sqrt(product)) ** 2
    visible = upper < 0.1
    return RawPolarMatchedFilterScaling(
        n=n,
        log2_group_order=log_order,
        copy_count=copies,
        polynomial_concentration_degree=polynomial_concentration_degree,
        log2_polynomial_raw_concentration_bound=concentration_log,
        raw_polar_overlap_upper_bound=overlap,
        log2_polar_gram_residual_upper_bound=gram_log,
        log2_concentration_times_gram_upper_bound=product_log,
        whitened_success_upper_bound=upper,
        three_quarter_power_exponent=THREE_QUARTER_EXPONENT,
        polynomial_domination_forces_decoder_failure_asymptotically=True,
        finite_polynomial_domination_failure_visible=visible,
        status=(
            "polynomially-dominated-raw-state-forces-polar-decoder-failure"
            if visible
            else "asymptotic-raw-domination-separation-not-yet-visible"
        ),
    )


def run_raw_polar_matched_filter_boundary() -> RawPolarMatchedFilterBoundaryReport:
    controls = [
        audit_raw_polar_matched_filter(
            "S3-SINGLE-PAIR-RAW-POLAR-MATCHED-FILTER",
            (((3,), (2, 1)),),
        ),
        audit_raw_polar_matched_filter(
            "S3-THRESHOLD-RAW-POLAR-MATCHED-FILTER",
            (
                ((3,), (2, 1)),
                ((3,), (1, 1, 1)),
                ((2, 1), (1, 1, 1)),
            ),
        ),
    ]
    scaling = [
        raw_polar_matched_filter_scaling(n)
        for n in (64, 128, 256, 512)
    ]
    verified = bool(
        all(row.exact_raw_polar_matched_filter_boundary_verified for row in controls)
        and scaling[-1].finite_polynomial_domination_failure_visible
    )
    theorem = RawPolarMatchedFilterTheorem(
        local_cross_map=(
            "J_h^*K_h=F_h^-1/2(|M_+|+|M_-|) is a positive contraction; "
            "the k-pair cross map is its tensor product."
        ),
        correct_block=(
            "Every correct-label block of C_J^*C_K equals "
            "A=|G|^-1 sum_h J_h^*K_h."
        ),
        unwhitened_success=(
            "P_match=Tr(A^2)/D<=Tr(A)/D, exactly the normalized raw/polar overlap."
        ),
        polar_distance=(
            "For Q=polar(C_J), ||Q-C_J||_F^2/(|G|D) is at most the normalized "
            "Gram Frobenius residual R."
        ),
        whitened_success=(
            "With kappa=||C_K||^2, sqrt(P_Q)<=sqrt(P_match)+sqrt(kappa R)."
        ),
        natural_consequence=(
            "The overlap vanishes and E R=O(|G|^-0.245...); any uniform "
            "polynomial-in-n raw concentration bound forces P_Q to vanish."
        ),
        revised_physical_gate=(
            "A flat/dominated native raw state kills this polar decoder. A rescue "
            "requires structured concentration on the polar bad singular sector."
        ),
        scope=(
            "This rejects the unwhitened matched filter and conditionally rejects "
            "its global polar under raw-state domination. It does not analyze every "
            "physical PGM or prove the required concentration absent."
        ),
        theorem_verified=verified,
        status=(
            "raw-polar-native-matched-filter-rejected-whitening-requires-concentration"
            if verified
            else "raw-polar-matched-filter-boundary-control-failure"
        ),
    )
    tail = scaling[-1]
    return RawPolarMatchedFilterBoundaryReport(
        created_at=utc_now(),
        theorem_contract=asdict(theorem),
        theorem=theorem,
        finite_controls=controls,
        scaling_records=scaling,
        proof_obligations=[
            {
                "obligation": "evaluate_polar_completed_convolution_on_native_raw_ensemble",
                "resolved": verified,
                "resolution": (
                    "The unwhitened correct probability is at most the proved "
                    "vanishing raw/polar overlap."
                ),
            },
            {
                "obligation": "determine_when_global_polar_whitening_can_rescue_overlap",
                "resolved": verified,
                "resolution": (
                    "It can matter only through kappa R: concentration of the raw "
                    "state on the Frobenius-small bad singular sector."
                ),
            },
            {
                "obligation": "prove_or_refute_natural_raw_convolution_concentration",
                "resolved": False,
                "resolution": (
                    "Bound ||C_K||^2 and, more sharply, the joint spectral alignment "
                    "of C_K C_K^* with |polar(C_J)-C_J|^2 on natural portfolios."
                ),
            },
            {
                "obligation": "compile_actual_physical_pgm_and_prove_classical_separation",
                "resolved": False,
                "resolution": "Other multiplicity-whitened decoders remain outside scope.",
            },
        ],
        adversarial_audit=[
            {
                "objection": "Both local fields are isometries, so the polar matched filter should accept the raw field.",
                "resolved": True,
                "resolution": "False asymptotically: tensor copies drive their natural global overlap, and therefore unwhitened correct success, to zero.",
            },
            {
                "objection": "Near-isometry of C_J guarantees its polar works on the native state.",
                "resolved": True,
                "resolution": "False without state alignment. The exact correction term is bounded by kappa R, which can be large if the raw state concentrates on bad modes.",
            },
            {
                "objection": "Proving physical-input domination would complete this decoder.",
                "resolved": True,
                "resolution": "The direction is reversed: polynomial domination plus raw/polar separation proves decoder failure.",
            },
            {
                "objection": "This rejects the known constant-success physical PGM information-theoretically.",
                "resolved": False,
                "resolution": "No. That PGM may use a different multiplicity whitening and is not identified with Q=polar(C_J) here.",
            },
        ],
        headline_metrics={
            "positive_raw_polar_cross_map_theorem_count": int(verified),
            "unwhitened_native_matched_filter_no_go_count": int(verified),
            "whitening_concentration_dichotomy_theorem_count": int(verified),
            "finite_control_count": len(controls),
            "finite_control_failure_count": sum(
                not row.exact_raw_polar_matched_filter_boundary_verified
                for row in controls
            ),
            "three_quarter_power_exponent": THREE_QUARTER_EXPONENT,
            "tail_n": tail.n,
            "tail_polynomial_concentration_degree": tail.polynomial_concentration_degree,
            "tail_whitened_success_upper_bound": tail.whitened_success_upper_bound,
            "natural_raw_concentration_theorem_count": 0,
            "new_quantum_algorithm_count": 0,
        },
        claim_gate={
            "raw_field_is_native_joint_character_dilation": True,
            "local_raw_polar_cross_map_positive_contraction": verified,
            "unwhitened_polar_matched_filter_success_vanishes": verified,
            "polynomial_raw_domination_would_force_whitened_decoder_failure": verified,
            "physical_input_domination_is_positive_completion_gate": False,
            "natural_raw_bad_sector_concentration_proved": False,
            "branch_polar_whitened_decoder_succeeds": False,
            "actual_physical_pgm_rejected": False,
            "classical_separation_proved": False,
            "speedup_claim_allowed": False,
        },
        status=theorem.status,
        summary=(
            "Converted raw/polar transform separation into an operational decoder "
            "boundary: the native unwhitened matched filter fails, and global polar "
            "whitening can rescue it only through strong raw-state concentration on "
            "the polar bad sector. Polynomial physical domination would kill the route."
        ),
        falsifiers_triggered=[
            "The polar-completed near-isometry is not automatically matched to the native raw joint-character state.",
            "A flat or polynomially dominated native input would prove failure, not success, for this decoder.",
            "Any rescue must demonstrate structured raw-state concentration or use a different physical PGM.",
        ],
    )


def write_raw_polar_matched_filter_boundary_report(
    path: Path = REPORT_PATH,
) -> dict[str, Any]:
    payload = asdict(run_raw_polar_matched_filter_boundary())
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    return payload


if __name__ == "__main__":
    report = write_raw_polar_matched_filter_boundary_report()
    print(json.dumps(report["headline_metrics"], indent=2, sort_keys=True))
