"""Exact maximal-outlier exclusion for affine orientation nodes.

Let ``T`` be a coordinate-aligned affine subcube of the orientation cube with
``d`` varying source pairs.  Lift the target and source slots to regular
representations.  Coordinates with the same membership function on ``T``
move diagonally together.  There are exactly

    r = 2d + 1

distinct nonempty membership functions: the constant function and the two
complementary coordinate functions for every varying pair.  Their incidence
matrix has binary rank ``d+1``.

For ``G=S_n``, ``n>=5``, the subgroup generated by the orientation diagonals
contains an independent ``A_n`` on every membership block.  Its remaining
sign vectors are exactly the row span of the incidence matrix.  Consequently

    |L_T| = |A_n|^(2d+1) 2^(d+1)
           = |S_n|^(2d+1) / 2^d.                         (1)

The normalized subgroup-projection walk has eigenvalue one precisely on the
``L_T``-invariant space, so its regular scalar mass is ``1/|L_T|``.  For the
physical node frame ``A_T=sum_(e in T) E_e``, eigenvalue ``|T|`` is equivalent
to a common vector in every ``Ran(E_e)``.

Every varying source slot is a singleton membership block.  Independent
``A_n`` on that block forces its ``S_n`` irrep to be trivial or sign.  Thus a
``d``-dimensional node can have the maximal eigenvalue only if all ``2d``
varying source irreps are one-dimensional.  Under independent Plancherel law,

    Pr[maximal outlier at a fixed node] <= (2/|S_n|)^(2d). (2)

There are ``2^(K-d)`` coordinate nodes of dimension ``d``.  Under global
source distinctness, (2) is impossible for ``d>=2`` because ``S_n`` has only
two one-dimensional irreps.  At ``d=1`` the varying pair must be the ordered
trivial/sign pair, giving the unconditioned numerator

    2^(K-1) * 2/|S_n|^2 = 2^K/|S_n|^2 < 2/|S_n|.         (3)

After conditioning, divide (3) by the global collision-free mass, which tends
to one.  Exact width-sized outliers therefore disappear simultaneously over
the natural hierarchy with factorially small failure probability.

This is not an upper-edge theorem.  It does not exclude eigenvalues
``(1-epsilon)|T|``, much less prove the required natural edge
``Theta(|T|/|S_n|)``.  Its value is to remove the most severe regular-master
outlier and to identify robust almost-invariance, rather than exact common
invariance, as the next subgroup-walk problem.
"""

from __future__ import annotations

import itertools
import json
import math
from collections import deque
from dataclasses import asdict, dataclass
from pathlib import Path
from typing import Any

import numpy as np

from representation_obstruction import integer_partitions
from research_registry import utc_now
from self_dual_wreath_orientation_fourier_reduction import (
    orientation_invariant_projector,
)


REPORT_PATH = Path(
    "research/representation/self_dual_wreath_affine_node_common_outlier.json"
)
DEFAULT_EXPERIMENT_ID = (
    "EXP-CODE-SELF-DUAL-WREATH-AFFINE-NODE-COMMON-OUTLIER"
)
DEFAULT_CANDIDATE_ID = "CODE-COSET-COLLECTIVE"

Partition = tuple[int, ...]
Permutation = tuple[int, ...]
ProductElement = tuple[Permutation, ...]


@dataclass(frozen=True)
class AffineSubgroupControl:
    n: int
    affine_dimension: int
    orientation_count: int
    distinct_nonempty_membership_pattern_count: int
    incidence_rank_over_f2: int
    predicted_generated_subgroup_order: int
    exact_generated_subgroup_order: int
    generated_subgroup_formula_verified: bool
    status: str


@dataclass(frozen=True)
class PhysicalCommonOutlierControl:
    n: int
    copy_count: int
    varying_pair_index: int
    physical_block_count: int
    common_outlier_block_count: int
    singleton_one_dimensional_necessity_violation_count: int
    maximum_projector_sum_eigenvalue_residual: float
    exact_singleton_necessity_verified: bool
    status: str


@dataclass(frozen=True)
class CommonOutlierScalingRecord:
    n: int
    group_order_log2: float
    information_threshold_copy_count: int
    independent_all_dimension_union_upper_bound: float
    independent_all_dimension_union_upper_bound_log2: float
    globally_distinct_event_numerator_upper_bound: float
    globally_distinct_event_numerator_upper_bound_log2: float
    conditioned_bound_formula: str
    dimensions_at_least_two_impossible_under_global_distinctness: bool
    exact_maximal_outlier_excluded_with_high_probability: bool
    near_maximal_outlier_excluded: bool
    natural_edge_proved: bool
    status: str


@dataclass(frozen=True)
class AffineNodeCommonOutlierReport:
    created_at: str
    theorem_contract: dict[str, Any]
    subgroup_controls: list[AffineSubgroupControl]
    physical_controls: list[PhysicalCommonOutlierControl]
    scaling_records: list[CommonOutlierScalingRecord]
    proof_obligations: list[dict[str, str | bool]]
    adversarial_audit: list[dict[str, str | bool]]
    headline_metrics: dict[str, int | float]
    claim_gate: dict[str, str | bool]
    status: str
    summary: str
    falsifiers_triggered: list[str]


def _compose(left: Permutation, right: Permutation) -> Permutation:
    return tuple(left[right[index]] for index in range(len(left)))


def coordinate_membership_columns(affine_dimension: int) -> tuple[int, ...]:
    """Return membership columns as bitsets over ``F_2^d`` orientations."""

    if affine_dimension < 0:
        raise ValueError("affine dimension must be nonnegative")
    orientation_count = 1 << affine_dimension
    full = (1 << orientation_count) - 1
    columns = [full]
    for coordinate in range(affine_dimension):
        one = sum(
            1 << orientation
            for orientation in range(orientation_count)
            if orientation & (1 << coordinate)
        )
        columns.extend((full ^ one, one))
    if len(set(columns)) != len(columns) or any(column == 0 for column in columns):
        raise ArithmeticError("coordinate membership columns must be distinct")
    return tuple(columns)


def _f2_rank(vectors: tuple[int, ...]) -> int:
    basis: dict[int, int] = {}
    for vector in vectors:
        value = vector
        while value:
            pivot = value.bit_length() - 1
            if pivot not in basis:
                basis[pivot] = value
                break
            value ^= basis[pivot]
    return len(basis)


def coordinate_incidence_rows(affine_dimension: int) -> tuple[int, ...]:
    columns = coordinate_membership_columns(affine_dimension)
    return tuple(
        sum(
            ((column >> orientation) & 1) << index
            for index, column in enumerate(columns)
        )
        for orientation in range(1 << affine_dimension)
    )


def affine_generated_subgroup_order(group_order: int, affine_dimension: int) -> int:
    if group_order < 2 or group_order % 2:
        raise ValueError("an even group order is required")
    pattern_count = 2 * affine_dimension + 1
    return (group_order // 2) ** pattern_count * (1 << (affine_dimension + 1))


def _orientation_embedding(
    element: Permutation,
    affine_dimension: int,
    orientation: int,
) -> ProductElement:
    identity = tuple(range(len(element)))
    output = [element]
    for coordinate in range(affine_dimension):
        selected = int(bool(orientation & (1 << coordinate)))
        output.extend(
            element if slot == selected else identity for slot in (0, 1)
        )
    return tuple(output)


def _product_compose(left: ProductElement, right: ProductElement) -> ProductElement:
    return tuple(_compose(a, b) for a, b in zip(left, right))


def exact_generated_subgroup_order(n: int, affine_dimension: int) -> int:
    """Enumerate the small finite control subgroup by breadth-first closure."""

    if n > 3 or affine_dimension > 2:
        raise ValueError("exact closure is restricted to S3 and d at most two")
    group = tuple(itertools.permutations(range(n)))
    identity_permutation = tuple(range(n))
    identity = (identity_permutation,) * (2 * affine_dimension + 1)
    generators = tuple(
        _orientation_embedding(element, affine_dimension, orientation)
        for orientation in range(1 << affine_dimension)
        for element in group
        if element != identity_permutation
    )
    discovered = {identity}
    frontier = deque((identity,))
    while frontier:
        current = frontier.popleft()
        for generator in generators:
            candidate = _product_compose(generator, current)
            if candidate not in discovered:
                discovered.add(candidate)
                frontier.append(candidate)
    return len(discovered)


def audit_affine_subgroup(
    n: int = 3,
    affine_dimension: int = 1,
) -> AffineSubgroupControl:
    rows = coordinate_incidence_rows(affine_dimension)
    predicted = affine_generated_subgroup_order(
        math.factorial(n),
        affine_dimension,
    )
    exact = exact_generated_subgroup_order(n, affine_dimension)
    pattern_count = len(coordinate_membership_columns(affine_dimension))
    rank = _f2_rank(rows)
    verified = bool(
        pattern_count == 2 * affine_dimension + 1
        and rank == affine_dimension + 1
        and exact == predicted
    )
    return AffineSubgroupControl(
        n=n,
        affine_dimension=affine_dimension,
        orientation_count=1 << affine_dimension,
        distinct_nonempty_membership_pattern_count=pattern_count,
        incidence_rank_over_f2=rank,
        predicted_generated_subgroup_order=predicted,
        exact_generated_subgroup_order=exact,
        generated_subgroup_formula_verified=verified,
        status=(
            "exact-affine-generated-subgroup-formula-verified"
            if verified
            else "affine-generated-subgroup-formula-failure"
        ),
    )


def _common_rank(left: np.ndarray, right: np.ndarray, tolerance: float) -> int:
    eigenvalues = np.linalg.eigvalsh(left + right)
    return int(np.count_nonzero(eigenvalues >= 2 - tolerance))


def audit_physical_singleton_necessity(
    n: int = 3,
    copy_count: int = 2,
    varying_pair_index: int = 0,
    *,
    tolerance: float = 1e-9,
) -> PhysicalCommonOutlierControl:
    if n != 3 or copy_count != 2 or varying_pair_index not in (0, 1):
        raise ValueError("the complete physical control uses S3 and two pairs")
    partitions = tuple(integer_partitions(n))
    one_dimensional = {(n,), (1,) * n}
    block_count = 0
    common_count = 0
    violations = 0
    maximum_residual = 0.0
    fixed_mask = 0
    left_mask = fixed_mask & ~(1 << varying_pair_index)
    right_mask = left_mask | (1 << varying_pair_index)
    for target in partitions:
        for sources in itertools.product(partitions, repeat=2 * copy_count):
            labels = tuple(
                (sources[2 * index], sources[2 * index + 1])
                for index in range(copy_count)
            )
            left = orientation_invariant_projector(target, labels, left_mask)
            right = orientation_invariant_projector(target, labels, right_mask)
            common = _common_rank(left, right, tolerance)
            maximum = float(np.linalg.eigvalsh(left + right)[-1])
            maximum_residual = max(
                maximum_residual,
                abs(maximum - 2.0) if common else max(0.0, maximum - (2 - tolerance)),
            )
            variable_sources = sources[
                2 * varying_pair_index : 2 * varying_pair_index + 2
            ]
            block_count += 1
            common_count += common > 0
            violations += bool(
                common > 0
                and any(source not in one_dimensional for source in variable_sources)
            )
    verified = violations == 0
    return PhysicalCommonOutlierControl(
        n=n,
        copy_count=copy_count,
        varying_pair_index=varying_pair_index,
        physical_block_count=block_count,
        common_outlier_block_count=common_count,
        singleton_one_dimensional_necessity_violation_count=violations,
        maximum_projector_sum_eigenvalue_residual=maximum_residual,
        exact_singleton_necessity_verified=verified,
        status=(
            "exact-singleton-membership-necessity-verified"
            if verified
            else "singleton-membership-necessity-failure"
        ),
    )


def common_outlier_scaling_record(n: int) -> CommonOutlierScalingRecord:
    if n < 2:
        raise ValueError("n must be at least two")
    log2_group = math.lgamma(n + 1) / math.log(2)
    copy_count = math.ceil(log2_group)
    group_order = math.factorial(n)
    independent_terms = [
        (1 << (copy_count - dimension))
        * (2 / group_order) ** (2 * dimension)
        for dimension in range(1, copy_count + 1)
    ]
    independent = math.fsum(independent_terms)
    distinct_numerator_log2 = copy_count - 2 * log2_group
    distinct_numerator = (
        2.0 ** distinct_numerator_log2
        if distinct_numerator_log2 > -1074
        else 0.0
    )
    independent_log2 = math.log2(independent) if independent > 0 else -math.inf
    return CommonOutlierScalingRecord(
        n=n,
        group_order_log2=log2_group,
        information_threshold_copy_count=copy_count,
        independent_all_dimension_union_upper_bound=independent,
        independent_all_dimension_union_upper_bound_log2=independent_log2,
        globally_distinct_event_numerator_upper_bound=distinct_numerator,
        globally_distinct_event_numerator_upper_bound_log2=distinct_numerator_log2,
        conditioned_bound_formula="2^K/(|S_n|^2 P_cf(n,K))",
        dimensions_at_least_two_impossible_under_global_distinctness=True,
        exact_maximal_outlier_excluded_with_high_probability=True,
        near_maximal_outlier_excluded=False,
        natural_edge_proved=False,
        status="exact-common-outlier-rare-near-outlier-open",
    )


def run_affine_node_common_outlier() -> AffineNodeCommonOutlierReport:
    subgroup_controls = [
        audit_affine_subgroup(3, dimension) for dimension in (0, 1, 2)
    ]
    physical_controls = [
        audit_physical_singleton_necessity(varying_pair_index=index)
        for index in (0, 1)
    ]
    scaling = [common_outlier_scaling_record(n) for n in (5, 8, 16, 32, 48, 64)]
    subgroup_failures = sum(
        not row.generated_subgroup_formula_verified for row in subgroup_controls
    )
    physical_failures = sum(
        not row.exact_singleton_necessity_verified for row in physical_controls
    )
    verified = subgroup_failures == 0 and physical_failures == 0
    metrics: dict[str, int | float] = {
        "affine_generated_subgroup_theorem_count": 1,
        "maximal_physical_outlier_necessity_theorem_count": 1,
        "global_distinct_all_level_outlier_bound_theorem_count": 1,
        "subgroup_control_count": len(subgroup_controls),
        "subgroup_control_failure_count": subgroup_failures,
        "physical_control_count": len(physical_controls),
        "physical_control_failure_count": physical_failures,
        "maximum_n_scaling_record": max(row.n for row in scaling),
        "near_maximal_outlier_theorem_count": 0,
        "natural_node_edge_theorem_count": 0,
        "new_quantum_algorithm_count": 0,
    }
    return AffineNodeCommonOutlierReport(
        created_at=utc_now(),
        theorem_contract={
            "affine_membership_geometry": (
                "A coordinate d-subcube has 2d+1 distinct nonempty membership "
                "blocks and binary incidence rank d+1."
            ),
            "generated_subgroup": (
                "For S_n, n>=5, independent A_n factors on those blocks plus "
                "the incidence sign code give order |S_n|^(2d+1)/2^d."
            ),
            "maximal_outlier": (
                "A_T has eigenvalue |T| exactly on the common range; every "
                "varying singleton source factor must be trivial or sign."
            ),
            "global_distinct_bound": (
                "Distinctness makes common ranges impossible for d>=2; the "
                "all-bottom-node unconditioned numerator is 2^K/|S_n|^2."
            ),
            "scope": (
                "No robust almost-invariance estimate, near-outlier bound, "
                "natural O(|T|/|S_n|) edge, or quantum speedup is proved."
            ),
        },
        subgroup_controls=subgroup_controls,
        physical_controls=physical_controls,
        scaling_records=scaling,
        proof_obligations=[
            {
                "obligation": "classify_affine_node_generated_subgroup",
                "resolved": verified,
                "resolution": (
                    "Distinct membership columns split the A_n subdirect "
                    "product, while signs give the incidence row span."
                ),
            },
            {
                "obligation": "exclude_exact_maximal_outliers_over_natural_hierarchy",
                "resolved": verified,
                "resolution": (
                    "Singleton membership factors force one-dimensional labels; "
                    "global distinctness leaves only a factorially rare d=1 event."
                ),
            },
            {
                "obligation": "upgrade_exact_common_invariance_to_robust_almost_invariance",
                "resolved": False,
                "resolution": (
                    "Need a block-restricted stability or local-law theorem at "
                    "the 1/|S_n| spectral scale, not merely a gap below one."
                ),
            },
        ],
        adversarial_audit=[
            {
                "objection": "The global regular walk's eigenvalue one refutes every natural block edge.",
                "resolved": True,
                "resolution": (
                    "Its affine-node common sector requires singleton variable "
                    "labels to be trivial/sign and is absent with high natural probability."
                ),
            },
            {
                "objection": "Absence of eigenvalue one bounds the physical top edge.",
                "resolved": False,
                "resolution": (
                    "False without quantitative stability: eigenvalues can be "
                    "arbitrarily close to one while the exact common range is zero."
                ),
            },
            {
                "objection": "A conventional subgroup-walk spectral gap is enough.",
                "resolved": False,
                "resolution": (
                    "The required normalized edge is Theta(1/|S_n|), far below "
                    "a statement of the form lambda<=1-1/poly(n)."
                ),
            },
        ],
        headline_metrics=metrics,
        claim_gate={
            "affine_generated_subgroup_classified": verified,
            "exact_maximal_outlier_rare_over_natural_hierarchy": verified,
            "global_regular_eigenvalue_one_is_typical_block_obstruction": False,
            "near_maximal_outliers_excluded": False,
            "block_restricted_natural_edge_proved": False,
            "center_valued_local_law_proved": False,
            "speedup_claim_allowed": False,
            "reason": (
                "Exact common invariants are now controlled, but the full "
                "noncommon spectrum at scale 1/|S_n| remains open."
            ),
        },
        status=(
            "exact-common-outlier-removed-robust-edge-open"
            if verified
            else "affine-common-outlier-control-failure"
        ),
        summary=(
            "Classified affine-node generated subgroups and proved that exact "
            "width-sized outliers are factorially rare under natural sources."
        ),
        falsifiers_triggered=[
            "The global regular-master eigenvalue one is supported on atypical one-dimensional source labels.",
            "Exact absence of a common range is not a quantitative upper-edge theorem.",
            "A gap below one is on the wrong scale for the natural node-frame edge.",
        ],
    )


def write_affine_node_common_outlier_report(
    path: Path = REPORT_PATH,
    write_registry: bool = True,
    registry_experiment_id: str = (
        "EXP-CODE-SELF-DUAL-WREATH-AFFINE-NODE-COMMON-OUTLIER"
    ),
    registry_candidate_id: str = "CODE-COSET-COLLECTIVE",
    registry_result_id: str = "",
) -> dict[str, Any]:
    payload = asdict(run_affine_node_common_outlier())
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payload, indent=2) + "\n")

    return payload


if __name__ == "__main__":
    report = write_affine_node_common_outlier_report()
    print(json.dumps(report, indent=2))
