"use strict";
// Native counts, population moments and independent nuisance-ensemble physics.
const fs=require("fs"),path=require("path"),crypto=require("crypto");
const report=JSON.parse(fs.readFileSync(process.argv[2]||path.join(__dirname,"../classical_baselines/ternary_single_layer_fourier_gate.json"),"utf8"));
function check(x,m){if(!x)throw Error(m);}
const same=(a,b,m)=>check(JSON.stringify(a)===JSON.stringify(b),m),mod=(a,q)=>(a%q+q)%q,near=(a,b,m)=>check(Number.isFinite(a)&&Math.abs(a-b)<3e-11,m);
function I(x){check(typeof x==="string"&&/^(0|[1-9][0-9]*)$/.test(x),"integer encoding");return BigInt(x);}
function gcd(a,b){a=a<0n?-a:a;b=b<0n?-b:b;while(b)[a,b]=[b,a%b];return a;}
function F(a,b=1n){check(b>0n,"denominator");const g=gcd(a,b);return[a/g,b/g];}
const add=(a,b)=>F(a[0]*b[1]+b[0]*a[1],a[1]*b[1]),mul=(a,b)=>F(a[0]*b[0],a[1]*b[1]),sub=(a,b)=>add(a,[-b[0],b[1]]),eq=(a,b)=>a[0]*b[1]===b[0]*a[1],le=(a,b)=>a[0]*b[1]<=b[0]*a[1],num=a=>Number(a[0])/Number(a[1]);
function Q(x){check(typeof x==="string","fraction string");const t=x.split("/");check(t.length<=2,"fraction syntax");const v=F(BigInt(t[0]),t.length===2?BigInt(t[1]):1n);check(x===(v[1]===1n?String(v[0]):v[0]+"/"+v[1]),"canonical fraction");return v;}
function choose(n,k){let v=1n;for(let i=1;i<=k;i++)v=v*BigInt(n-i+1)/BigInt(i);return v;}
function population(n,r,M){const D=3n**BigInt(M),G=3n**BigInt(n*r),A=F(5n**BigInt(M),D),energy=mul(F(2n*D*D),add(mul(sub(A,F(1n)),F(1n,G)),mul(sub(F(D),A),F(1n,G*G)))),uncapped=mul(F(2n,9n*D*D),energy);return{D,G,A,energy,squared:le(uncapped,F(4n,9n))?uncapped:F(4n,9n)};}
function verifyPopulation(c,n,r,M){const v=population(n,r,M);same([c.dimension,c.root_digits,c.original_qutrits],[n,r,M],"population source parameters");check(I(c.native_words)===v.D&&I(c.secret_group_size)===v.G&&eq(Q(c.expected_phase_independent_offset_energy),v.energy)&&eq(Q(c.mean_raw_trit_advantage_upper_squared),v.squared),"exact population envelope");
  check(c.support_moments.length===M,"every support class");let sum=F(0n);c.support_moments.forEach((row,i)=>{const k=i+1,three=3n**BigInt(k),moment=add(F(v.D*v.D,three*v.G),F(v.D*v.D*(three-1n),three*v.G*v.G)),offsets=choose(M,k)*2n**BigInt(k);check(row.support===k&&I(row.offsets)===offsets&&eq(Q(row.second_moment_per_oriented_high_class),moment),"inactive-coordinate multiplicity and support moment");sum=add(sum,mul(F(2n*offsets),moment));});check(eq(sum,v.energy),"support sum equals closed formula");
  for(const k of["label_dependent_collective_initial_diagonal_covered","all_classical_postprocessing_covered","uniform_full_secret_prior_required","word_Fourier_readout_fixed","IID_original_full_native_frequency_rows_required","label_independent_word_permutations_covered","label_dependent_invertible_affine_word_maps_covered"])check(c[k]===true,"covered receiver: "+k);
  for(const k of["earlier_noncommuting_mixing_or_word_permutation_covered","generic_quantum_lower_bound","large_word_space_executed","polynomial_surplus_copies_excluded"])check(c[k]===false,"scope limitation: "+k);
}
const hash=crypto.createHash("sha256").update(fs.readFileSync(path.join(__dirname,"../TERNARY_SINGLE_LAYER_FOURIER_GATE.md"))).digest("hex");
check(report.derivation_sha256===hash&&report.status==="LABEL_AWARE_SINGLE_DIAGONAL_FOURIER_LAYER_GATE_REVIEW_PENDING","pinned derivation and review status");
for(const k of["candidate_record_accepted","quantum_speedup_proved","novelty_claim","generic_quantum_lower_bound","multiple_noncommuting_layers_or_word_permutations_covered","label_dependent_nonlinear_word_permutations_covered"])check(report[k]===false,"no broader algorithm/lower bound: "+k);
for(const k of["label_dependent_collective_initial_phases_covered","partial_block_and_top_digit_initial_phases_covered","label_independent_word_permutations_covered","label_dependent_affine_word_permutations_covered"])check(report[k]===true,"precise extension: "+k);
check(report.source_law==="ALL_IID_ORIGINAL_FULL_NATIVE_FREQUENCY_ROWS; UNIFORM_FULL_SECRET_PRIOR","source and prior");
same(report.transition_rows,[[[1,0],[-1,1],[0,-1]],[[0,1],[-1,0],[1,-1]]],"native transitions");for(const rows of report.transition_rows)for(let i=0;i<3;i++)for(let j=i+1;j<3;j++)check(Math.abs(rows[i][0]*rows[j][1]-rows[i][1]*rows[j][0])===1,"local native unit minors");check(gcd(2n,3n**64n)===1n,"mixed-sign minor2 is a unit, not a field substitution");
const schedule=[[1,8],[1,16],[1,32],[1,64],[2,16]];check(report.population_certificates.length===5,"scaling schedule");report.population_certificates.forEach((c,i)=>verifyPopulation(c,...schedule[i],schedule[i][0]*schedule[i][1]-2));verifyPopulation(report.copy_surplus_control,1,4,16);check(report.copy_surplus_control.mean_raw_trit_advantage_upper_squared==="4/9","surplus can make the bound vacuous");
check(report.nonlinear_routing_requirements.length===4,"routing target scaling schedule");report.nonlinear_routing_requirements.forEach((c,i)=>{const[n,r]=[[1,16],[1,32],[1,64],[2,16]][i],M=n*r-2,D=3n**BigInt(M),G=3n**BigInt(n*r),epsilon=F(1n,BigInt((n*r)**2)),required=mul(F(9n*D*D,2n),mul(epsilon,epsilon)),cap=mul(F(9n*D*G,4n*(D-1n)),mul(epsilon,epsilon));same([c.dimension,c.root_digits,c.original_qutrits],[n,r,M],"required routing geometry");check(eq(Q(c.target_mean_raw_trit_advantage),epsilon)&&eq(Q(c.required_mean_phase_weighted_offset_energy_at_least),required)&&eq(Q(c.required_mean_phase_independent_offset_energy_at_least),required)&&I(c.necessary_uniform_worst_case_offset_multiplicity_cap_at_least)===(cap[0]+cap[1]-1n)/cap[1]&&eq(Q(c.expected_total_informative_directed_edges_invariant_under_word_permutation),F(2n*D*(D-1n),G)),"necessary coherent energy and macroscopic routing cap");check(c.uniform_worst_case_cap_not_unproved_independent_average_cap===true&&c.energy_is_necessary_not_sufficient_for_efficient_readout_or_decoder===true&&c.label_dependent_nonlinear_route_or_its_computation_supplied===false,"routing resource requirement not a solver or sufficiency theorem");});
function words(M,q=3){return Array.from({length:q**M},(_,i)=>Array.from({length:M},(_,j)=>Math.floor(i/q**(M-j-1))%q));}
const key=x=>JSON.stringify(x);
function offsetEdges(ws,frequencies,q,j,images=ws){const lookup=new Map(images.map((w,i)=>[key(w),i])),Q0=q/3;return ws.slice(1).map(delta=>{const edges=[[],[]];images.forEach((w,x)=>{const y=lookup.get(key(w.map((a,k)=>(a+delta[k])%3))),difference=frequencies[x].map((a,k)=>mod(frequencies[y][k]-a,q));for(let h=1;h<=2;h++)if(difference.every((a,k)=>a===(k===j?h*Q0:0)))edges[h-1].push([x,y]);});return{delta,edges};});}
let censusCases=0;
check(report.complete_source_censuses.length===2,"prime and composite source census");
report.complete_source_censuses.forEach((c,i)=>{const q=i===0?3:9,M=2,D=9,ws=words(M),squares=[0,0],offsets=[4,4];let E=0;for(const flat of words(2*M,q)){const f=ws.map(w=>[mod(w.reduce((s,d,k)=>s+(d?flat[2*k+d-1]:0),0),q)]);for(const row of offsetEdges(ws,f,q,0)){const counts=row.edges.map(e=>e.length);squares[row.delta.filter(a=>a).length-1]+=counts[0]**2;E+=counts[0]**2+counts[1]**2;}}
  same([c.modulus,c.width,c.entire_IID_frequency_cases],[q,M,q**4],"entire IID frequency census");check(eq(Q(c.actual_mean_offset_energy),F(BigInt(E),BigInt(q**4)))&&eq(Q(c.actual_mean_offset_energy),population(1,i+1,M).energy)&&c.calibration_not_a_new_oracle_problem===true,"exact complete census energy");check(c.support_moments.length===2,"all support census moments");c.support_moments.forEach((row,k)=>check(row.support===k+1&&eq(Q(row.actual_second_moment_per_positive_class),F(BigInt(squares[k]),BigInt(q**4*offsets[k]))),"complete support census including inactive coordinates"));censusCases+=q**4;
});
function matmul(A,B){return A.map(row=>B[0].map((_,j)=>row.reduce((v,a,k)=>v+a*B[k][j],0n)));}
function chart(r){let V=[[1n,0n],[0n,1n]],B=[[-1n,-1n],[1n,-2n]];for(let i=0;i<2*r-1;i++)V=matmul(V,B);const q=3n**BigInt(r),den=3n*(V[0][0]*V[1][1]-V[0][1]*V[1][0]),u=q*(2n*V[1][1]+V[1][0]),v=q*(-2n*V[0][1]-V[0][0]);check(u%den===0n&&v%den===0n,"integer native ideal chart");const a=u/den,b=v/den;check(gcd(a*a+a*b+b*b,q)===1n,"full native row-pair bijection at composite roots");return[a,b];}
for(const r of[1,2,4,6,16,32,64])chart(r);
function phaseValues(kind,rows,ws,f,q,j){const cut=Math.max(1,Math.floor(rows.length/2)),inv2=(q+1)/2;return ws.map((w,x)=>{const a=mod(w.slice(0,cut).reduce((s,d,k)=>s+(d?rows[k][d-1][j]:0),0),q),b=mod(f[x][j]-a,q),total=f[x][j];let p;if(kind==="zero")p=0;else if(kind==="total_quadratic")p=inv2*total*total;else if(kind==="partial_quadratic")p=inv2*a*a;else if(kind==="cross_quadratic")p=a*b;else if(kind==="top_digit")p=q/3*Math.floor(total/(q/3))**2;else{check(kind==="word_label_coupled","public macro whitelist");p=5*a*a+w.reduce((s,d,k)=>s+(rows[k][0][j]+2*rows[k][1][j])*d*d,0);}return mod(p,q);});}
const macros=["zero","total_quadratic","partial_quadratic","cross_quadratic","top_digit","word_label_coupled"];
let physicalMacroLaws=0,exactNativeOffsets=0;
check(report.native_controls.length===3,"all native controls");
report.native_controls.forEach((c,index)=>{const [n,r,M,j]=[[1,4,2,0],[1,6,4,0],[2,3,4,1]][index],q=3**r,D=3**M,ws=words(M),[u,v]=chart(r);
  same([c.dimension,c.root_digits,c.modulus,c.original_qutrits,c.target_coordinate],[n,r,q,M,j],"native case schedule");check(c.native_labels.length===M&&c.full_frequency_rows.length===M,"entire native source batch");
  for(let k=0;k<M;k++){check(c.native_labels[k].length===n&&c.full_frequency_rows[k].length===2&&c.full_frequency_rows[k].every(row=>row.length===n),"native row shapes");for(let a=0;a<n;a++){const [l,h]=c.native_labels[k][a];check([l,h,...c.full_frequency_rows[k].map(row=>row[a])].every(x=>Number.isSafeInteger(x)&&x>=0&&x<q),"canonical original native labels");same(c.full_frequency_rows[k].map(row=>row[a]),[Number(mod(u*BigInt(l)+v*BigInt(h),BigInt(q))),Number(mod((u+v)*BigInt(l)-u*BigInt(h),BigInt(q)))],"native label-to-frequency chart");}}
  const f=ws.map(w=>Array.from({length:n},(_,a)=>mod(w.reduce((s,d,k)=>s+(d?c.full_frequency_rows[k][d-1][a]:0),0),q))),edges=offsetEdges(ws,f,q,j),E=edges.reduce((s,row)=>s+row.edges.reduce((v,a)=>v+a.length**2,0),0),upper=F(BigInt(2*E),BigInt(9*D*D)),cap=le(upper,F(4n,9n))?upper:F(4n,9n);
  same(c.words,ws,"all original words");same(c.word_frequencies,f,"all public word frequencies");same(c.offset_counts,edges.map(row=>({delta:row.delta,positive_count:row.edges[0].length,negative_count:row.edges[1].length})),"all exact useful native directed edges");check(I(c.exact_phase_independent_offset_energy)===BigInt(E)&&eq(Q(c.every_phase_raw_advantage_squared_upper),cap),"per-label phase-independent bound");
  check(c.complete_uniform_secret_count_calibration_only===q**n&&c.complete_amplitude_cells_calibration_only===q**n*D&&c.selected_or_prespecified_labels_not_population_evidence===true&&c.quantum_speedup_proved===false,"full-prior calibration, not population claim");
  const groups=new Map();f.forEach((v,x)=>{const S=v.map((a,k)=>k===j?a%(q/3):a),s=key(S);if(!groups.has(s))groups.set(s,[]);groups.get(s).push(x);});
  check(c.phase_controls.length===6,"prespecified structural macros");c.phase_controls.forEach((p,i)=>{check(p.macro===macros[i],"macro schedule");const ps=phaseValues(p.macro,c.full_frequency_rows,ws,f,q,j);same(p.public_phase_numerators,ps,"public phase arithmetic with no unknown secret");
    const laws=[0,1,2].map(t=>ws.map(z=>{let value=0;for(const group of groups.values()){let re=0,im=0;for(const x of group){const angle=2*Math.PI*(ps[x]/q+(t*Math.floor(f[x][j]/(q/3))-ws[x].reduce((s,a,k)=>s+a*z[k],0))/3);re+=Math.cos(angle);im+=Math.sin(angle);}value+=(re*re+im*im)/(D*D);}return value;}));
    for(const row of laws)near(row.reduce((a,b)=>a+b,0),1,"all physical Born outcomes");const score=ws.reduce((s,_,o)=>s+Math.max(...laws.map(row=>row[o])),0)/3,average=ws.map((_,o)=>laws.reduce((s,row)=>s+row[o],0)/3),lhs=laws.reduce((s,row)=>s+row.reduce((v,a,o)=>v+(a-average[o])**2,0),0);
    let C=0;for(const row of edges)for(const group of row.edges){let re=0,im=0;for(const[x,y]of group){const a=2*Math.PI*(ps[x]-ps[y])/q;re+=Math.cos(a);im+=Math.sin(a);}C+=re*re+im*im;}
    const rhs=3*C/D**3;near(lhs,rhs,"independently reconstructed Parseval equality");near(p.physical_uniform_prior_raw_MAP_success,score,"independent nuisance-ensemble score vs full-secret physical replay");near(p.physical_advantage_squared,(score-1/3)**2,"actual squared raw signal");near(p.phase_weighted_offset_energy,C,"label-dependent phase interference");near(p.actual_Parseval_left,lhs,"actual signal norm");near(p.predicted_Parseval_right,rhs,"exact offset Parseval prediction");check(C<=E+3e-10&&(score-1/3)**2<=num(cap)+3e-12,"unconditioned score lies in the phase-independent envelope");for(const k of["Parseval_residual","Born_normalization_residual"])check(Number.isFinite(p[k])&&p[k]>=0&&p[k]<3e-11,"complete physical residual: "+k);check(p.efficient_classical_decoder_supplied===false,"MAP remains an exponential reference");physicalMacroLaws++;
  });exactNativeOffsets+=D-1;
});
check(report.fixed_permutation_signature_controls.length===2,"identity and nonlinear Toffoli routing");
report.fixed_permutation_signature_controls.forEach((c,index)=>{const ws=words(3),images=index===0?ws:ws.map(([a,b,d])=>[a,b,(d+a*b)%3]),basis=[[0,0],[1,0],[0,1]],buckets=new Map();same(c.permutation_images,images,"fixed public word map, not label-conditioned routing");
  for(let x=0;x<27;x++)for(let y=0;y<27;y++)if(x!==y){const d=key(images[x].map((a,k)=>mod(images[y][k]-a,3))),sig=ws[x].flatMap((a,k)=>basis[a].map((v,j)=>basis[ws[y][k]][j]-v)),s=key(sig);if(!buckets.has(d))buckets.set(d,new Map());const bucket=buckets.get(d);bucket.set(s,(bucket.get(s)||0)+1);}
  let concentration=0n,opposite=0n;for(const bucket of buckets.values()){check([...bucket.values()].reduce((a,b)=>a+b,0)===27,"routing bucket mass");for(const[s,m]of bucket){concentration+=BigInt(m*m);opposite+=BigInt(m*(bucket.get(key(JSON.parse(s).map(a=>-a)))||0));}}
  const D=27n,q=9n,identity=mul(F(D*D),sub(F(125n,27n),F(1n))),expected=mul(F(2n),sub(add(F((D-1n)*D*D,q*q),mul(sub(F(1n,q),F(1n,q*q)),F(concentration))),F(opposite,q*q)));
  check(c.modulus===9&&c.width===3&&I(c.signature_bucket_square_sum)===concentration&&I(c.opposite_signature_bucket_product_sum)===opposite&&eq(Q(c.identity_signature_concentration_upper),identity)&&eq(Q(c.exact_expected_offset_energy_after_permutation),expected)&&le(expected,population(1,2,3).energy),"independent exact permutation moment including opposite signatures");check(c.permutation_fixed_independently_of_native_labels_required===true&&c.arbitrary_label_dependent_nonlinear_permutation_covered===false,"permutation independence scope");
});
same(report.tight_selected_control,{exact_MAP_success:"19/27",exact_advantage_squared:"100/729",IID_population_algorithm:false},"selected bound saturation is not an IID algorithm");check(report.native_controls[0].exact_phase_independent_offset_energy==="50","tight native edge energy");near(report.native_controls[0].phase_controls[0].physical_uniform_prior_raw_MAP_success,19/27,"tight physical score");
console.log(JSON.stringify({status:"independent_single_layer_Fourier_gate_certificates_passed",populationCertificates:5,completeSourceCases:censusCases,exactNativeOffsets,physicalMacroLaws,fixedPermutationMoments:2,genericQuantumLowerBound:false,quantumSpeedupProved:false}));
