"use strict";
// Reconstruct native labels, the whole affine basis map and exact probability bounds.
const fs=require("fs"),path=require("path"),crypto=require("crypto");
const report=JSON.parse(fs.readFileSync(process.argv[2]||path.join(__dirname,"../phase_workbench/ternary_affine_line_extractor.json"),"utf8"));
const check=(x,m)=>{if(!x)throw Error(m);},same=(a,b,m)=>check(JSON.stringify(a)===JSON.stringify(b),m),mod=(a,q)=>(a%q+q)%q;
function gcd(a,b){while(b)[a,b]=[b,a%b];return a<0n?-a:a;}
function frac(a,b=1n){a=BigInt(a);b=BigInt(b);const g=gcd(a,b);a/=g;b/=g;return b===1n?String(a):a+"/"+b;}
function ratio(x){const[a,b]=x.split("/").map(BigInt);return[a,b||1n];}
function less(a,b){return a[0]*b[1]<b[0]*a[1];}
function words(M,q=3){return Array.from({length:q**M},(_,x)=>Array.from({length:M},(_,j)=>Math.floor(x/q**(M-j-1))%q));}
function matmul(A,B){return A.map(row=>B[0].map((_,j)=>row.reduce((s,a,k)=>s+a*B[k][j],0n)));}
function native(rows,labels,n,r){let V=[[1n,0n],[0n,1n]],B=[[-1n,-1n],[1n,-2n]];for(let i=0;i<2*r-1;i++)V=matmul(V,B);const q=3n**BigInt(r),den=3n*(V[0][0]*V[1][1]-V[0][1]*V[1][0]),a=q*(2n*V[1][1]+V[1][0])/den,b=q*(-2n*V[0][1]-V[0][0])/den;check(labels.length===rows.length,"original native labels and input rows");rows.forEach((pair,i)=>{check(pair.length===2&&pair.every(row=>row.length===n)&&labels[i].length===n,"rectangular original frequency matrix");for(let j=0;j<n;j++){const[u,v]=labels[i][j];check([u,v,...pair.map(row=>row[j])].every(x=>Number.isSafeInteger(x)&&x>=0&&x<Number(q)),"canonical native full-root values");same(pair.map(row=>row[j]),[Number(mod(a*BigInt(u)+b*BigInt(v),q)),Number(mod((a+b)*BigInt(u)-a*BigInt(v),q))],"actual even-native chart");}});}
function quadratic(rows,n){return[Array.from({length:n},(_,j)=>rows.map(pair=>mod(pair[1][j]-pair[0][j],3))),Array.from({length:n},(_,j)=>rows.map(pair=>mod(2*pair[0][j]-pair[1][j],3)))];}
const mv=(A,v)=>A.map(row=>mod(row.reduce((s,a,j)=>s+a*v[j],0),3));
function span(columns,n){let images=new Map([[JSON.stringify(Array(n).fill(0)),Array(n).fill(0)]]);columns.forEach(column=>{const before=[...images.values()];for(const x of before)for(let a=1;a<3;a++){const y=x.map((b,j)=>mod(b+a*column[j],3));images.set(JSON.stringify(y),y);}});return images;}
function line(rows,v,n){const[A,B]=quadratic(rows,n),curvature=mv(B,v.map(x=>x*x)),linear=mv(A,v),columns=v.map((x,j)=>B.map(row=>row[j]*x%3)).filter((_,j)=>v[j]),images=span(columns,n),R=Math.round(Math.log(images.size)/Math.log(3)),consistent=curvature.every(x=>x===0)&&images.has(JSON.stringify(linear));const augmented=images.has(JSON.stringify(linear))?R:R+1;return{A,B,curvature,linear,R,augmented,consistent};}
function minor(ws){const basis=[[0,0],[1,0],[0,1]],rows=ws.slice(1).map(w=>w.flatMap((a,i)=>basis[a].map((b,j)=>b-basis[ws[0][i]][j])));for(let a=0;a<rows[0].length;a++)for(let b=a+1;b<rows[0].length;b++){const determinant=rows[0][a]*rows[1][b]-rows[0][b]*rows[1][a];if(Math.abs(determinant)===1)return{coefficient_rows:rows,columns:[a,b],determinant};}throw Error("native pointed unit minor");}
function ledger(c,rows,n,M){const v=c.direction;check(v.length===M&&v.every(x=>Number.isInteger(x)&&x>=0&&x<3)&&v.some(Boolean)&&v.find(Boolean)===1,"canonical nonzero projective direction");const p=v.findIndex(Boolean),L=line(rows,v,n);same(c.quadratic_rows,[L.A,L.B],"actual native F3 quadratic representation");same(c.curvature,L.curvature,"true line curvature");same(c.linear_offset,L.linear,"true line derivative offset");check(c.pivot===p&&c.support_rank===L.R&&c.augmented_rank===L.augmented&&c.predicate_consistent===L.consistent,"rank checked independently by complete column span, not Gaussian elimination");check(c.exact_raw_success_probability===(L.consistent?frac(1,3**L.R):"0")&&c.accepted_tag_count===(L.consistent?3**(M-L.R-1):0),"unconditioned raw coverage and tag count");check(c.supplied_direction_field_operation_upper===8*n*M+8*M&&c.supplied_direction_finding_cost_included===false&&c.source_preparation_inverse_granted===false&&c.logical_output_qutrits_per_successful_batch===1,"supplied direction costs and one physical output");return L;}
const hash=crypto.createHash("sha256").update(fs.readFileSync(path.join(__dirname,"../TERNARY_AFFINE_LINE_EXTRACTOR.md"))).digest("hex");check(report.derivation_sha256===hash&&report.status==="NATIVE_AFFINE_LINE_INSTRUMENT_REVIEW_PENDING_TYPICAL_COVERAGE_BLOCKED","pinned derivation");for(const k of["candidate_record_accepted","quantum_speedup_proved","novelty_claim","source_preparation_inverse_granted","nonlinear_or_coherent_direction_compilers_ruled_out"])check(report[k]===false,"scoped obstruction, no promoted algorithm: "+k);
const names=["rank-one","rank-two","inconsistent-linear","nonzero-curvature","easy-additive","IID-native-best-exhaustive-direction-calibration"],expected=["1/3","1/9","0","0","1",null];let wholeWords=0,acceptedTags=0,physicalBranches=0;
check(report.native_full_cube_controls.length===6,"complete positive and negative native controls");
report.native_full_cube_controls.forEach((c,index)=>{
  check(c.name===names[index],"prespecified native control family");const n=c.dimension,M=c.original_qutrits,r=c.parent_root_digits,q=3**r,rows=c.full_frequency_rows;check(n===2&&M===(index===5?5:4)&&r===(index===5?2:3)&&c.parent_modulus===q,"native control dimensions");native(rows,c.native_labels,n,r);const L=ledger(c,rows,n,M),v=c.direction,p=c.pivot,ws=words(M),tags=ws.filter(w=>w[p]===0),mapping=[],accepted=[];
  const secrets=[Array(n).fill(0),Array(n).fill(1),Array(n).fill(q-1)];same(c.calibration_secrets,secrets,"specified phase controls");
  for(const u of tags){const triple=Array.from({length:3},(_,t)=>u.map((a,j)=>mod(a+t*v[j],3)));mapping.push(...triple);triple.forEach((w,t)=>same(w.map((a,j)=>mod(a-w[p]*v[j],3)),u,"complete reversible coordinate map"));const derivative=L.linear.map((a,j)=>mod(a+2*L.B[j].reduce((s,b,k)=>s+b*v[k]*u[k],0),3));if(L.curvature.some(Boolean)||derivative.some(Boolean))continue;
    const f=triple.map(w=>Array.from({length:n},(_,j)=>mod(w.reduce((s,d,k)=>s+(d?rows[k][d-1][j]:0),0),q)));check(f.every(row=>row.every((a,j)=>a%3===f[0][j]%3)),"accepted original line is prefix constant");const childRows=f.slice(1).map(row=>row.map((a,j)=>mod(a-f[0][j],q)/3));check(childRows.every(row=>row.every(Number.isInteger)),"exact parent-to-child frequencies");for(const s of secrets){const base=f[0].reduce((z,a,j)=>z+a*s[j],0);for(let t=0;t<3;t++){const original=f[t].reduce((z,a,j)=>z+a*s[j],0),delta=t?3*childRows[t-1].reduce((z,a,j)=>z+a*s[j],0):0;check(mod(original-base-delta,q)===0,"all-secret componentwise phase identity");const theta=2*Math.PI*mod(original,q)/q,phi=2*Math.PI*mod(base+delta,q)/q;check(Math.hypot(Math.cos(theta)-Math.cos(phi),Math.sin(theta)-Math.sin(phi))/Math.sqrt(3**M)<3e-11,"independent physical phase replay");}physicalBranches++;}
    accepted.push({quotient_word:u,original_words:triple,full_frequencies:f,child_rows:childRows,pointed_unit_minor:minor(triple),raw_tag_probability:frac(3,3**M)});
  }
  same(c.accepted_tags,accepted,"all physically accepted tags and pointed minors, not a selected witness");check(new Set(mapping.map(JSON.stringify)).size===3**M&&mapping.length===3**M,"entire original cube bijection");check(c.coordinate_map_sha256===crypto.createHash("sha256").update(JSON.stringify(mapping)).digest("hex")&&c.whole_original_words_replayed===3**M&&c.all_quotient_tags_replayed===3**(M-1),"whole coordinate map digest and replay counts");check(frac(3*accepted.length,3**M)===c.exact_raw_success_probability&&accepted.length===c.accepted_tag_count,"actual raw source acceptance equals rank formula");if(expected[index]!==null)check(c.exact_raw_success_probability===expected[index],"known easy/failed controls");check(Number.isFinite(c.physical_phase_residual)&&c.physical_phase_residual>=0&&c.physical_phase_residual<3e-11,"reported phase residual");for(const k of["all_potential_tags_counted_as_outputs","efficient_direction_finder_supplied","probability_and_direction_finding_cost_may_be_ignored","quantum_speedup_proved"])check(c[k]===false,"no free coverage or direction search: "+k);wholeWords+=3**M;acceptedTags+=accepted.length;
});
const census=report.complete_low_label_direction_census,n=2,M=5;check(census.dimension===n&&census.original_qutrits===M&&census.parent_root_digits===2,"bounded original direction census");native(census.full_frequency_rows,census.native_labels,n,2);const[B]=quadratic(census.full_frequency_rows,n).slice(1),all=words(M),canonical=all.filter(v=>v.some(Boolean)&&v.find(Boolean)===1),kernel=all.filter(v=>v.some(Boolean)&&mv(B,v).every(x=>!x)),weight=Math.min(...kernel.map(v=>v.filter(Boolean).length));same(census.menu.map(c=>c.direction),canonical,"EVERY projective direction, not a heuristic search");check(census.projective_direction_count===canonical.length&&canonical.length===121&&census.smallest_nonzero_kernel_weight===weight&&census.all_direction_support_rank_implications_checked===true&&census.full_direction_enumeration_is_scalable===false,"complete native sparse-kernel control and cost");census.menu.forEach(c=>{const L=ledger(c,census.full_frequency_rows,n,M);check(!L.consistent||L.R>=weight-1,"sparse-kernel-free implies feasible support rank lower bound");});
check(report.polynomial_menu_population_bounds.length===5,"large-dimension exact rational bounds");
report.polynomial_menu_population_bounds.forEach((c,index)=>{
  const n=64*2**index,M=n*n,T=M;check(c.dimension===n&&c.original_qutrits===M&&c.direction_menu_size===T,"polynomial batch and menu schedule");let sum=0n,binomial=1n,best={s:0,volume:0n,eta:[0n,1n],p:[1n,1n]},den=3n**BigInt(n);
  for(let s=1;s<=n;s++){binomial=binomial*BigInt(M-s+1)/BigInt(s);sum+=binomial*2n**BigInt(s);const eta=sum>=den?[1n,1n]:[sum,den],three=3n**BigInt(s);let p=[eta[0]*three+BigInt(T)*eta[1],eta[1]*three];if(p[0]>=p[1])p=[1n,1n];if(less(p,best.p))best={s,volume:sum,eta,p};if(sum>=den)break;}
  check(c.sparse_kernel_cutoff===best.s&&c.nonzero_sparse_coefficient_vectors===String(best.volume)&&c.exceptional_label_probability_upper===frac(...best.eta)&&c.mean_raw_menu_success_probability_upper===frac(...best.p),"independent BigInt binomial population gate and cutoff optimization");check(c.directions_may_depend_on_all_low_labels===true&&c.coherent_direction_interference_or_nonlinear_partitions_excluded===false&&c.quantum_speedup_proved===false,"uniform label-adaptive menu bound, not arbitrary quantum hardness");
});
console.log(JSON.stringify({status:"independent_native_affine_line_certificates_passed",wholeOriginalWords:wholeWords,acceptedTags,physicalBranches,completeProjectiveDirections:121,populationBounds:5,quantumSpeedupProved:false}));
