"use strict";
const fs=require("fs"),path=require("path"),crypto=require("crypto");
const {check,same,rat,zero,one,add:ra,mul:rm,div:rd,str,parse,cmp}=require("./cyclotomic_exact.js");
const root=path.join(__dirname,"../.."),R=JSON.parse(fs.readFileSync(process.argv[2]||path.join(root,"research/phase_workbench/ternary_two_layer_path_transfer.json"),"utf8"));
check(R.derivation_sha256===crypto.createHash("sha256").update(fs.readFileSync(path.join(root,"research/TERNARY_TWO_LAYER_PATH_TRANSFER.md"))).digest("hex"),"pinned two-layer derivation");
for(const flag of["general_mixer_shape_or_deeper_circuit_lower_bound","coherent_fiber_eraser_supplied","quantum_speedup_proved","candidate_record_accepted","novelty_claim"])check(R[flag]===false,"unsupported two-layer claim: "+flag);
for(const flag of["graph_is_constant_size_for_this_two_layer_template","no_original_word_cube_or_secret_group_in_scaling_transfer","signed_weights_are_not_Markov_probabilities","all_IID_uniform_full_native_rows_required","fixed_public_quarter_turn_angles_only"])check(R[flag]===true,"transfer premise: "+flag);
const key=JSON.stringify,abs=a=>a<0n?-a:a,gcd=(a,b)=>{a=abs(a);b=abs(b);while(b){[a,b]=[b,a%b];}return a;};
function combos(n,k){const out=[];function rec(w,start){if(w.length===k){out.push(w);return;}for(let i=start;i<n;i++)rec([...w,i],i+1);}rec([],0);return out;}
function cube(q,n){let out=[[]];for(let i=0;i<n;i++)out=out.flatMap(w=>Array.from({length:q},(_,j)=>[...w,j]));return out;}
function det(A){const n=A.length;if(!n)return 1n;A=A.map(r=>r.map(BigInt));let sign=1n,previous=1n;for(let k=0;k<n-1;k++){let j=k;while(j<n&&A[j][k]===0n)j++;if(j===n)return 0n;if(j!==k){[A[k],A[j]]=[A[j],A[k]];sign=-sign;}const p=A[k][k];for(let i=k+1;i<n;i++){for(let j=k+1;j<n;j++){const value=A[i][j]*p-A[i][k]*A[k][j];check(value%previous===0n,"exact Bareiss determinant division");A[i][j]=value/previous;}A[i][k]=0n;}previous=p;}return sign*A[n-1][n-1];}
const matrix=C=>Array.from({length:4},(_,i)=>C.map(c=>BigInt(c[i])));
function minorGcd(A,k){if(k===0)return 1n;if(!A.length||!A[0].length)return 0n;let d=0n;for(const rows of combos(A.length,k))for(const cols of combos(A[0].length,k)){d=gcd(d,det(rows.map(i=>cols.map(j=>A[i][j]))));if(d===1n)return d;}return d;}
function invariants(A){const out=[];let previous=1n;for(let k=1;k<=Math.min(A.length,A.length?A[0].length:0);k++){const d=minorGcd(A,k);if(!d)break;check(d%previous===0n,"integer determinantal divisors");out.push(d/previous);previous=d;}return out;}
function contains(C,v){const r=C.length;if(!r)return v.every(x=>x===0);const A=matrix(C);let rows=null,d=0n;for(const I of combos(4,r)){d=det(I.map(i=>A[i]));if(d){rows=I;break;}}check(rows!==null,"independent column basis");const small=rows.map(i=>A[i]),coeff=[];for(let j=0;j<r;j++){const replacement=small.map((row,k)=>row.map((x,l)=>l===j?BigInt(v[rows[k]]):x)),num=det(replacement);if(num%d)return false;coeff.push(num/d);}return A.every((row,i)=>row.reduce((s,a,j)=>s+a*coeff[j],0n)===BigInt(v[i]));}
function hnf(C){let pivots=[];C.forEach((col,j)=>{check(col.length===4&&col.every(Number.isInteger),"canonical integer four-row columns");let p=3;while(p>=0&&col[p]===0)p--;check(p>=0&&col[p]>0&&(j===0||p>pivots[j-1]),"positive increasing column-Hermite pivots");for(let k=0;k<j;k++)check(col[pivots[k]]>=0&&col[pivots[k]]<C[k][pivots[k]],"reduced upper Hermite residues");pivots.push(p);});}
const states=R.complete_integer_lattice_graph,P=cube(3,4),S=states.length;
same(P,R.native_coordinate_patterns,"complete81 original one-hot coordinate patterns");check(S===137&&S<=32768,"complete compressed lattice graph");same(states[0].basis_columns,[],"zero initial lattice");check(new Set(states.map(s=>key(s.basis_columns))).size===S,"unique canonical HNF states");
const transitionSeen=new Set();let transitionsChecked=0,smithChecks=0;
states.forEach((state,i)=>{const C=state.basis_columns;hnf(C);check(state.coordinate_pattern_next_states.length===81,"whole coordinate transition row");P.forEach((p,k)=>{const j=state.coordinate_pattern_next_states[k];check(Number.isInteger(j)&&j>=0&&j<S,"valid next state");const columns=[1,2].map(t=>p.map(a=>Number(a===t))).filter(c=>c.some(Boolean)),D=states[j].basis_columns,tag=key([i,j,columns.slice().sort()]);if(!transitionSeen.has(tag)){for(const col of [...C,...columns])check(contains(D,col),"all old/native columns contained in new lattice");if(i!==j){const oldAndNew=matrix([...C,...columns]),target=matrix(D),rank=invariants(oldAndNew).length;check(rank===D.length&&minorGcd(oldAndNew,rank)===minorGcd(target,rank),"matching integer covolume, not just rational/field rank");}transitionSeen.add(tag);}transitionsChecked++;});
  check(state.zero_subset_Smith_invariants.length===16,"whole zero-subset count certificate");for(let mask=0;mask<16;mask++){const rows=matrix(C).filter((_,i)=>!(mask&(1<<i))),d=invariants(rows),c=state.zero_subset_Smith_invariants[mask];check(c.remaining_rows===rows.length,"deleted-row dimension");same(c.invariants.map(String),d.map(String),"independent maximal-minor Smith invariants");smithChecks++;}
});
const reachable=new Set([0]),queue=[0];while(queue.length){const i=queue.pop();for(const j of states[i].coordinate_pattern_next_states)if(!reachable.has(j)){reachable.add(j);queue.push(j);}}check(reachable.size===S,"no orphan or truncated reachable graph");
const visiting=new Set(),depths=new Map();function depth(i){if(depths.has(i))return depths.get(i);check(!visiting.has(i),"no strict lattice cycle");visiting.add(i);let d=0;for(const j of new Set(states[i].coordinate_pattern_next_states))if(j!==i)d=Math.max(d,1+depth(j));visiting.delete(i);depths.set(i,d);return d;}
const Z=[0n,0n],O=[1n,0n],Q=[[1n,0n],[0n,-1n],[-1n,0n],[0n,1n]],ca=(a,b)=>[a[0]+b[0],a[1]+b[1]],cm=(a,b)=>[a[0]*b[0]-a[1]*b[1],a[0]*b[1]+a[1]*b[0]],conj=a=>[a[0],-a[1]],eq=(a,b)=>a[0]===b[0]&&a[1]===b[1];
function cpow(a,n){let out=O;for(;n;n=Math.floor(n/2)){if(n%2)out=cm(out,a);a=cm(a,a);}return out;}
function gate(phase,equal){return equal?[1n+2n*phase[0],2n*phase[1]]:[1n-phase[0],-phase[1]];}
function weight(p,b1,b2){const[x,t,xp,tp]=p;return cm(cm(gate(Q[b2],t===0),gate(Q[b1],t===x)),conj(cm(gate(Q[b2],tp===0),gate(Q[b1],tp===xp))));}
const edgeCache=new Map(),terminalCache=new Map(),momentCache=new Map();
function edges(b1,b2){const tag=key([b1,b2]);if(edgeCache.has(tag))return edgeCache.get(tag);const W=P.map(p=>weight(p,b1,b2)),out=states.map(state=>{const row=new Map();state.coordinate_pattern_next_states.forEach((j,k)=>row.set(j,ca(row.get(j)||Z,W[k])));const all=[...row].filter(([,a])=>!eq(a,Z));check(eq(all.map(([,a])=>a).reduce(ca,Z),[81n,0n]),"whole signed coordinate transfer normalizes");return all;});edgeCache.set(tag,out);return out;}
function terminal(M,b1,b2){const tag=key([M,b1,b2]);if(terminalCache.has(tag))return terminalCache.get(tag);let W=new Map([[0,O]]);const E=edges(b1,b2);for(let t=0;t<M;t++){const next=new Map();for(const[i,a]of W)for(const[j,b]of E[i])next.set(j,ca(next.get(j)||Z,cm(a,b)));W=new Map([...next].filter(([,a])=>!eq(a,Z)));check(eq([...W.values()].reduce(ca,Z),[81n**BigInt(t+1),0n]),"complete signed path weights normalize at every input");}terminalCache.set(tag,W);return W;}
function zeroCounts(i,q){const subset=states[i].zero_subset_Smith_invariants.map(c=>q**BigInt(c.remaining_rows-c.invariants.length)*c.invariants.reduce((v,d)=>v*gcd(q,BigInt(d)),1n)),counts=[];for(let z=0;z<16;z++){const complement=15^z;let t=complement,c=0n;for(;;){c+=(t.toString(2).replace(/0/g,"").length%2?-1n:1n)*subset[z|t];if(t===0)break;t=(t-1)&complement;}check(c>=0n,"nonnegative full-root zero-pattern count");counts.push(c);}check(counts.reduce((a,b)=>a+b,0n)===subset[0]&&counts[15]===1n,"whole annihilator and unique zero character");return counts;}
function moment(i,q,g1,g2){const tag=key([i,String(q),g1,g2]);if(momentCache.has(tag))return momentCache.get(tag);const a=[g1,g2].map(g=>[1n+(q-1n)*Q[g][0],(q-1n)*Q[g][1]]),b=[g1,g2].map(g=>[1n-Q[g][0],-Q[g][1]]),coeff=[[a[0],b[0]],[a[1],b[1]],[conj(a[0]),conj(b[0])],[conj(a[1]),conj(b[1])]];let out=Z;zeroCounts(i,q).forEach((c,mask)=>{let x=O;for(let j=0;j<4;j++)x=cm(x,coeff[j][mask&(1<<j)?0:1]);out=ca(out,[c*x[0],c*x[1]]);});check(out[0]*out[0]+out[1]*out[1]<=q**8n,"exact phase-moment norm<=1");momentCache.set(tag,out);return out;}
function isqrt(a){if(a<2n)return a;let x=1n<<BigInt(Math.ceil(a.toString(2).length/2));for(;;){const y=(x+a/x)/2n;if(y>=x)return x;x=y;}}
function sqrtUpper(a){const scale=1n<<80n,v=a[0]*a[1]*scale*scale,x=isqrt(v);return rat(x*x===v?x:x+1n,scale*a[1]);}
function capped(a){return cmp(a,one)<0n?a:one;}
function born(s,q,n,M){return capped(ra(s,sqrtUpper(rm(rat(q**BigInt(n)-1n,3n**BigInt(M)),s))));}
function probability(n,q,M,angles,details=null){const[g1,b1,g2,b2]=angles,W=terminal(M,b1,b2);let total=Z;const terms=[];for(const[i,a]of[...W].sort((a,b)=>a[0]-b[0])){const m=moment(i,q,g1,g2);total=ca(total,cm(a,cpow(m,n)));terms.push({state:i,terminal_signed_weight_numerator:a.map(String),phase_moment_numerator_over_q_to_four:m.map(String)});}const den=81n**BigInt(M)*q**BigInt(5*n);check(total[1]===0n&&total[0]>=0n&&total[0]<=den,"complete probability real in[0,1]");const p=rat(total[0],den);if(details){same(terms,details.terminal_terms,"every terminal signed weight and full-root phase term");check(details.complete_signed_path_denominator===String(den)&&details.complete_probability_numerator===String(total[0])&&details.active_terminal_lattice_states===W.size&&details.complete_graph_states===S,"complete path normalization and state count");check(details.enumerates_original_word_cube_or_secret_group===false&&details.keeps_integer_lattice_and_full_root_torsion===true&&details.coherent_fiber_eraser_supplied===false&&details.continuous_or_label_adaptive_angles_covered===false,"exact mean scope");}return p;}
let menuCases=0;
for(const c of R.growing_population_menus){const n=c.dimension,q=BigInt(c.modulus),M=c.original_native_inputs;check(c.fixed_angle_population_menu.length===256,"complete fixed quarter-angle menu");let best=zero;for(const [k,r]of c.fixed_angle_population_menu.entries()){same(r.quarters_gamma1_beta1_gamma2_beta2,cube(4,4)[k],"committed quarter-angle tuple");const p=probability(n,q,M,r.quarters_gamma1_beta1_gamma2_beta2);check(r.uniform_full_target_population_success_exact===str(p)&&r.ratio_to_classical_uniform_target_rejection_exact===str(rm(p,rat(q**BigInt(n))))&&r.Born_weighted_population_success_upper===str(born(p,q,n,M)),"complete fixed-angle exact mean, rejection ratio and Born envelope");if(cmp(p,best)>0n)best=p;menuCases++;}const r=c.best_fixed_angle_mean_case,p=probability(n,q,M,r.quarters_gamma1_beta1_gamma2_beta2,r);check(cmp(p,best)===0n&&r.uniform_full_target_population_success_exact===str(p),"maximum mean, not mean of instance-adaptive maxima");check(c.menu_selects_maximum_mean_not_instance_adaptive_mean_of_maxima===true&&c.finite_quarter_menu_does_not_bound_all_continuous_angles===true,"fixed population menu premises");}
let directCases=0;
for(const c of R.exact_direct_circuit_censuses){const q=Number(c.modulus),M=c.original_native_inputs,W=cube(3,M),D=W.length,angles=c.quarters_gamma1_beta1_gamma2_beta2;let uniform=zero,Born=zero,total=0;for(const flat of cube(q,2*M)){const F=W.map(w=>w.reduce((s,t,i)=>s+(t===0?0:flat[2*i+t-1]),0)%q);for(let y=0;y<q;y++){let state=W.map(()=>O),den=1n;for(let layer=0;layer<2;layer++){const gamma=angles[2*layer],beta=angles[2*layer+1];state=state.map((a,i)=>cm(a,F[i]===y?O:Q[gamma]));for(let axis=0;axis<M;axis++){state=W.map(word=>{let a=Z;for(let t=0;t<3;t++){const w=word.slice();w[axis]=t;const i=w.reduce((s,t)=>3*s+t,0);a=ca(a,cm(gate(Q[beta],t===word[axis]),state[i]));}return a;});den*=3n;}}const indices=F.map((v,i)=>v===y?i:-1).filter(i=>i>=0),num=indices.reduce((s,i)=>s+state[i][0]**2n+state[i][1]**2n,0n),p=rat(num,BigInt(D)*den*den);uniform=ra(uniform,rd(p,rat(BigInt(q))));Born=ra(Born,rm(p,rat(BigInt(indices.length),BigInt(D))));}total++;}uniform=rd(uniform,rat(BigInt(total)));Born=rd(Born,rat(BigInt(total)));check(c.entire_IID_label_matrices===total&&c.complete_uniform_target_cases===total*q&&c.actual_direct_circuit_uniform_mean_exact===str(uniform)&&c.actual_direct_circuit_Born_mean_exact===str(Born)&&cmp(uniform,probability(1,BigInt(q),M,angles))===0n,"independent complete native circuit census, no field shadow");directCases+=total*q;}
const certificate=R.signed_transfer_structure_certificate;check(certificate.maximum_strict_lattice_path_length===depth(0)&&depth(0)===5,"maximum strict path length");same(certificate.state_strict_remaining_depths,states.map((s,i)=>depth(i)),"all DAG depths");let largest=0n;
states.forEach((s,i)=>{const coeff=new Map();P.forEach((p,k)=>{if(s.coordinate_pattern_next_states[k]!==i)return;const[x,t,xp,tp]=p,pc=[t===0?2:-1,t===x?2:-1,tp===0?2:-1,tp===xp?2:-1];for(let mask=0;mask<16;mask++){const a=Number(!!(mask&2))-Number(!!(mask&8)),b=Number(!!(mask&1))-Number(!!(mask&4)),tag=key([a,b]);let v=1n;for(let j=0;j<4;j++)if(mask&(1<<j))v*=BigInt(pc[j]);coeff.set(tag,(coeff.get(tag)||0n)+v);}});const entries=[];for(const a of[0,1,-1])for(const b of[0,1,-1])entries.push({beta1_exponent:a,beta2_exponent:b,coefficient_numerator_over81:String(coeff.get(key([a,b]))||0n)});same(certificate.all_self_loop_Laurent_coefficients[i],{state:i,Laurent_coefficients:entries},"all-angle self loops expanded from actual gate monomials, not sampled fit");const l1=entries.reduce((s,c)=>s+abs(BigInt(c.coefficient_numerator_over81)),0n);if(l1>largest)largest=l1;check(entries.reduce((s,c)=>s+BigInt(c.coefficient_numerator_over81),0n)===81n,"zero-angle normalization");for(let b1=0;b1<4;b1++)for(let b2=0;b2<4;b2++){let value=Z;for(const e of entries)value=ca(value,cm([BigInt(e.coefficient_numerator_over81),0n],Q[((e.beta1_exponent*b1+e.beta2_exponent*b2)%4+4)%4]));const w=edges(b1,b2)[i].find(([j])=>j===i)?.[1]||Z;check(eq(value,w)&&w[0]**2n+w[1]**2n<=81n**2n,"quarter self-loop exact evaluation and modulus<=1");const off=edges(b1,b2)[i].filter(([j])=>j!==i).reduce((a,[j,w])=>a+abs(w[0])+abs(w[1]),0n);check(off<=18n*81n,"conservative off-diagonal row norm");}});
check(certificate.all_quarter_self_loop_moduli_at_most_one===true&&certificate.continuous_self_loop_modulus_upper===str(rat(largest,81n))&&largest===129n&&certificate.continuous_Laurent_degree_per_angle===1&&certificate.off_diagonal_complex_weight_row_norm_upper==="18"&&certificate.continuous_self_loop_modulus_one_not_certified_by_this_report===true,"coarse report keeps negative coefficients and does not certify the separate sharper claim");
function choose(n,k){let v=1n;for(let j=0;j<k;j++)v=v*BigInt(n-j)/BigInt(j+1);return v;}
function rpow(a,n){return rat(a[0]**BigInt(n),a[1]**BigInt(n));}
for(const c of R.global_two_layer_family_envelopes){const n=c.dimension,q=BigInt(c.modulus),M=c.original_native_inputs,G=q**BigInt(n),L=rat(43n,27n);let quarter=zero,continuous=zero;for(let j=0;j<=Math.min(5,M);j++){const v=rat(choose(M,j)*18n**BigInt(j),G);quarter=ra(quarter,v);continuous=ra(continuous,rm(v,rpow(L,M-j)));}quarter=capped(quarter);continuous=capped(continuous);const menu=capped(rm(rat(256n),quarter)),inverse=(continuous[1]+continuous[0]-1n)/continuous[0],m=BigInt(c.implicit_four_angle_net_axis_points),error=rat(BigInt(88*(n+M)),7n*m),tuned=capped(ra(rm(rat(m**4n),continuous),error));check((m-1n)**5n<inverse&&m**5n>=inverse&&c.implicit_four_angle_net_total_points===String(m**4n),"implicit four-angle net exact ceiling root");check(c.strict_path_depth===5&&c.off_diagonal_weight_row_norm_upper==="18"&&c.continuous_loop_growth_upper==="43/27"&&c.all_fixed_quarter_angles_uniform_success_upper===str(quarter)&&c.label_and_target_adaptive_quarter_menu_uniform_success_upper===str(menu)&&c.label_and_target_adaptive_quarter_menu_Born_success_upper===str(born(menu,q,n,M))&&c.all_fixed_continuous_angles_uniform_success_upper===str(continuous)&&c.implicit_net_rounding_probability_error_upper===str(error)&&c.label_and_target_adaptive_continuous_angles_uniform_success_upper===str(tuned)&&c.label_and_target_adaptive_continuous_angles_Born_success_upper===str(born(tuned,q,n,M)),"global signed-transfer envelope and public-angle/Born correction");for(const flag of["continuous_near_entropy_regime_requires_M_equals_n_log3_q_plus_logarithmic_surplus","continuous_bound_can_be_vacuous_for_much_larger_polynomial_batches","arbitrary_mixer_shapes_more_layers_or_other_receivers_not_covered"])check(c[flag]===true,"continuous envelope scope: "+flag);}
console.log(JSON.stringify({status:"PASS",integer_lattice_transitions:transitionsChecked,deleted_row_Smith_checks:smithChecks,exact_growing_menu_cases:menuCases,exact_direct_circuit_target_cases:directCases,strict_path_depth:depth(0)}));
