"use strict";
// Rebuild the low-only policies and every clean orbit coordinate independently.
const fs=require("fs"),path=require("path"),crypto=require("crypto");
const report=JSON.parse(fs.readFileSync(process.argv[2]||path.join(__dirname,"../phase_workbench/ternary_nonlinear_cycle_compiler.json"),"utf8"));
const check=(x,m)=>{if(!x)throw Error(m);},same=(a,b,m)=>check(JSON.stringify(a)===JSON.stringify(b),m),mod=(a,q)=>(a%q+q)%q,key=JSON.stringify;
function gcd(a,b){while(b)[a,b]=[b,a%b];return a<0n?-a:a;}
function frac(a,b){a=BigInt(a);b=BigInt(b);const g=gcd(a,b);a/=g;b/=g;return b===1n?String(a):a+"/"+b;}
function words(M){return Array.from({length:3**M},(_,x)=>Array.from({length:M},(_,j)=>Math.floor(x/3**(M-j-1))%3));}
function order(a,b){for(let j=0;j<a.length;j++)if(a[j]!==b[j])return a[j]-b[j];return 0;}
function matmul(A,B){return A.map(row=>B[0].map((_,j)=>row.reduce((s,a,k)=>s+a*B[k][j],0n)));}
function native(rows,labels,n,r){let V=[[1n,0n],[0n,1n]],B=[[-1n,-1n],[1n,-2n]];for(let i=0;i<2*r-1;i++)V=matmul(V,B);const q=3n**BigInt(r),den=3n*(V[0][0]*V[1][1]-V[0][1]*V[1][0]),numA=q*(2n*V[1][1]+V[1][0]),numB=q*(-2n*V[0][1]-V[0][0]);check(numA%den===0n&&numB%den===0n,"integer native chart");const a=numA/den,b=numB/den;check(labels.length===rows.length,"native input count");rows.forEach((pair,i)=>{check(pair.length===2&&pair.every(row=>row.length===n)&&labels[i].length===n,"rectangular actual source");for(let j=0;j<n;j++){const[u,v]=labels[i][j];check([u,v,...pair.map(row=>row[j])].every(x=>Number.isInteger(x)&&x>=0&&x<Number(q)),"canonical native full rows");same(pair.map(row=>row[j]),[Number(mod(a*BigInt(u)+b*BigInt(v),q)),Number(mod((a+b)*BigInt(u)-a*BigInt(v),q))],"true native labels");}});}
function minor(ws){const basis=[[0,0],[1,0],[0,1]],rows=ws.slice(1).map(w=>w.flatMap((a,i)=>basis[a].map((b,j)=>b-basis[ws[0][i]][j])));for(let a=0;a<rows[0].length;a++)for(let b=a+1;b<rows[0].length;b++){const determinant=rows[0][a]*rows[1][b]-rows[0][b]*rows[1][a];if(Math.abs(determinant)===1)return{coefficient_rows:rows,columns:[a,b],determinant};}throw Error("original pointed unit minor");}
const hash=crypto.createHash("sha256").update(fs.readFileSync(path.join(__dirname,"../TERNARY_NONLINEAR_CYCLE_COMPILER.md"))).digest("hex");check(report.derivation_sha256===hash&&report.status==="NATIVE_NONLINEAR_CYCLE_COMPILER_REVIEW_PENDING_FAST_CYCLE_ACTION_MISSING","derivation and missing fast action");for(const k of["candidate_record_accepted","quantum_speedup_proved","novelty_claim","source_preparation_inverse_granted","tag_compression_or_global_ranking_required","efficient_constant_coverage_nonlinear_action_supplied","all_quantum_receivers_equivalent_to_cycle_actions_claimed"])check(report[k]===false,"conditional architecture scope: "+k);
const schedule=[[1,3,2,9],[2,2,1,5],[2,3,1,4]];check(report.native_complete_controls.length===3,"all complete original source controls");let wholeWords=0,allCycles=0,nonaffineCycles=0,erasedWords=0;
report.native_complete_controls.forEach((c,index)=>{
  const[n,r,d,M]=schedule[index],q=3**r,H=3**d,D=3**M,ws=words(M),rows=c.full_frequency_rows;native(rows,c.native_labels,n,r);same([c.dimension,c.parent_root_digits,c.parent_modulus,c.prefix_digits,c.original_qutrits],[n,r,q,d,M],"complete native schedule");const frequency=w=>Array.from({length:n},(_,j)=>mod(w.reduce((s,t,i)=>s+(t?rows[i][t-1][j]:0),0),q)),low=w=>frequency(w).map(a=>a%H);let step;
  if(index<2){check(c.evaluator_mode==="exponential-low-fiber-atlas"&&c.supplied_direction===null,"reference stays exponential");const groups=new Map();ws.forEach(w=>{const k=key(low(w));if(!groups.has(k))groups.set(k,[]);groups.get(k).push(w);});const atlas=new Map();for(const group of groups.values()){check(group.length%3===0,"balanced complete fibers");for(let i=0;i<group.length;i+=3)for(let j=0;j<3;j++)atlas.set(key(group[i+j]),group[i+(j+1)%3]);}step=w=>atlas.get(key(w));
  }else{check(c.evaluator_mode==="supplied-low-affine-direction","partial affine control");same(c.supplied_direction,[1,1,0,0],"low-only direction");const v=c.supplied_direction,A=Array.from({length:n},(_,j)=>rows.map(pair=>mod(pair[1][j]-pair[0][j],3))),B=Array.from({length:n},(_,j)=>rows.map(pair=>mod(2*pair[0][j]-pair[1][j],3)));step=w=>{const accept=B.every(row=>mod(row.reduce((s,b,i)=>s+b*v[i]*v[i],0),3)===0)&&A.every((row,j)=>mod(row.reduce((s,a,i)=>s+a*v[i]+2*B[j][i]*v[i]*w[i],0),3)===0);return accept?w.map((a,i)=>mod(a+v[i],3)):w;};}
  const coordinates=[],orbits=new Map();for(const x of ws){const y=step(x),z=step(y);same(step(z),x,"EVERY word satisfies order3");same(low(y),low(x),"EVERY actual native prefix preserved");const orbit=[x,y,z],fixed=key(x)===key(y);check(fixed||new Set(orbit.map(key)).size===3,"fixed or actual three-cycle");const u=[...orbit].sort(order)[0],position=fixed?0:orbit.findIndex(w=>key(w)===key(u)),t=mod(-position,3),success=!fixed;coordinates.push([u,t,success]);let reconstructed=u;for(let j=0;j<t;j++)reconstructed=step(reconstructed);same(reconstructed,x,"original index reconstructed without rank or count");check(x.every((a,j)=>mod(a-reconstructed[j],3)===0),"original register erased on EVERY basis word");erasedWords++;if(success&&!orbits.has(key(u)))orbits.set(key(u),[u,step(u),step(step(u))]);}
  check(new Set(coordinates.map(key)).size===D,"isometry with uncompressed tags");const tags=[...orbits.values()].sort((a,b)=>order(a[0],b[0])),moved=3*tags.length,nonaffine=tags.filter(triple=>Array.from({length:M},(_,j)=>mod(triple.reduce((s,w)=>s+w[j],0),3)).some(Boolean)).length;
  check(c.complete_coordinate_map_sha256===crypto.createHash("sha256").update(key(coordinates)).digest("hex")&&c.whole_original_words_audited===D&&c.nonfixed_original_word_count===moved&&c.accepted_three_cycle_count===tags.length&&c.raw_success_probability===frac(moved,D)&&c.nonaffine_three_cycle_count===nonaffine,"complete original coordinates, coverage and nonlinear orbits");check(c.raw_success_probability===(index<2?"1":"1/3"),"reference all accepted, partial control cost charged");
  const selected=[...new Set([0,Math.floor(tags.length/2),tags.length-1])].sort((a,b)=>a-b),controls=[];const secrets=[Array(n).fill(0),Array(n).fill(1),Array(n).fill(q-1)];same(c.calibration_secrets,secrets,"native phase controls");tags.forEach((triple,k)=>{const f=triple.map(frequency),childRows=f.slice(1).map(row=>row.map((a,j)=>mod(a-f[0][j],q)/H));check(childRows.every(row=>row.every(Number.isInteger)),"actual child rows");for(let endpoint=1;endpoint<3;endpoint++)for(let j=0;j<n;j++)check(mod(f[endpoint][j]-f[0][j]-H*childRows[endpoint-1][j],q)===0,"every original component child phase identity");for(const secret of secrets){const base=f[0].reduce((s,a,j)=>s+a*secret[j],0);for(let endpoint=0;endpoint<3;endpoint++){const original=f[endpoint].reduce((s,a,j)=>s+a*secret[j],0),delta=endpoint?H*childRows[endpoint-1].reduce((s,a,j)=>s+a*secret[j],0):0;check(mod(original-base-delta,q)===0,"physical phase exponents for every accepted branch");}}if(selected.includes(k))controls.push({tag_word:triple[0],original_words:triple,full_frequencies:f,child_rows:childRows,pointed_unit_minor:minor(triple),raw_tag_probability:frac(3,D)});});
  same(c.selected_child_controls,controls,"prespecified real branch controls");check(c.low_rows_only_policy===true&&c.canonical_tag_register_trits===M&&c.logical_register_trits===1&&c.original_word_scratch_erasure_failures===0&&c.output_qutrits_per_accepted_batch===1&&c.clean_evaluator_compute_uncompute_call_upper===10&&c.all_accepted_child_phases_checked===tags.length,"clean conditional recipe and no compressed-rank dependency");for(const k of["global_fiber_rank_or_unrank_called","all_potential_orbits_counted_as_outputs","efficient_nonlinear_cycle_evaluator_supplied","whole_instrument_approximation_error_bound_supplied","quantum_speedup_proved"])check(c[k]===false,"no invented efficient action or approximation proof: "+k);check(Number.isFinite(c.physical_phase_residual)&&c.physical_phase_residual>=0&&c.physical_phase_residual<3e-11,"bounded physical residual");wholeWords+=D;allCycles+=tags.length;nonaffineCycles+=nonaffine;
});
check(nonaffineCycles>0,"actual nonaffine cycles, not just the prior line compiler");
check(report.full_depth_supply_comparisons.length===4,"full-depth baseline comparison, not shallow novelty");
report.full_depth_supply_comparisons.forEach((c,index)=>{
  const r=index+2,n=3**r,d=r-1,s=c.existing_sieve;check(c.dimension===n&&c.parent_root_digits===r&&c.prefix_digits===d&&c.conditional_direct_batch_original_copies===n*(3**d-1)+1,"conditional direct batch source ledger");check(c.shallow_perfect_acceptance_is_already_known===true&&c.comparison_is_not_an_implemented_direct_algorithm===true,"known shallow baseline and missing direct compiler");check(s.dimension===n&&s.root_digits===r&&s.root_lowerings===d&&s.guaranteed_SDE_label_window===(n+1)**2&&s.minimum_one_output_protocol_original_copies===String(BigInt(n+1)**BigInt(d))&&s.fresh_batch_protocol_copies_for_one_final_field_qutrit===String(BigInt(n+1)**BigInt(3*d))&&s.fresh_batch_protocol_all_levels_acceptance==="1","independent exact known sieve depth ledgers");check(s.lower_bound_scope==="disjoint one-odd-child supports and one lower-even child per n+1 odd states"&&s.inactive_register_recycling_is_included_in_lower_bound===true&&s.coherent_pointer_or_multi_output_phase_transducers_excluded_from_lower_bound===true&&s.end_to_end_field_decoder_and_full_secret_bootstrap_costs_additional===true&&s.polynomial_in_r_complete_speedup_claim_allowed===false,"protocol-specific baseline scope");
});
console.log(JSON.stringify({status:"independent_native_nonlinear_cycle_certificates_passed",wholeOriginalWords:wholeWords,completeAcceptedCycles:allCycles,nonaffineCycles,erasedOriginalWords:erasedWords,fastNonlinearActionSupplied:false,quantumSpeedupProved:false}));
