"use strict";
// Complete native cube partitions and exact carry/child-law certificates.
const fs=require("fs"),path=require("path"),crypto=require("crypto");
const report=JSON.parse(fs.readFileSync(process.argv[2]||path.join(__dirname,"../phase_workbench/ternary_batch_fiber_compiler.json"),"utf8"));
function check(x,m){if(!x)throw Error(m);}
const same=(a,b,m)=>check(JSON.stringify(a)===JSON.stringify(b),m),mod=(a,q)=>(a%q+q)%q;
function gcd(a,b){a=a<0n?-a:a;b=b<0n?-b:b;while(b)[a,b]=[b,a%b];return a;}
function frac(a,b){a=BigInt(a);b=BigInt(b);const g=gcd(a,b);a/=g;b/=g;return b===1n?String(a):a+"/"+b;}
function matmul(A,B){return A.map(row=>B[0].map((_,j)=>row.reduce((s,a,k)=>s+a*B[k][j],0n)));}
function chart(r){let V=[[1n,0n],[0n,1n]],B=[[-1n,-1n],[1n,-2n]];for(let i=0;i<2*r-1;i++)V=matmul(V,B);const q=3n**BigInt(r),den=3n*(V[0][0]*V[1][1]-V[0][1]*V[1][0]),u=q*(2n*V[1][1]+V[1][0]),v=q*(-2n*V[0][1]-V[0][0]);check(u%den===0n&&v%den===0n,"integer original native chart");const a=u/den,b=v/den;check(gcd(a*a+a*b+b*b,q)===1n,"native row-pair chart bijective over the composite root");return[a,b];}
function native(rows,labels,n,r){const q=3**r,[u,v]=chart(r);check(labels.length===rows.length,"original label/row count");for(let i=0;i<rows.length;i++){check(labels[i].length===n&&rows[i].length===2&&rows[i].every(row=>row.length===n),"rectangular original native rows");for(let k=0;k<n;k++){const[a,b]=labels[i][k];check([a,b,...rows[i].map(row=>row[k])].every(x=>Number.isSafeInteger(x)&&x>=0&&x<q),"canonical full-root labels");same(rows[i].map(row=>row[k]),[Number(mod(u*BigInt(a)+v*BigInt(b),BigInt(q))),Number(mod((u+v)*BigInt(a)-u*BigInt(b),BigInt(q)))],"actual native chart, not a generated oracle");}}}
function words(M){return Array.from({length:3**M},(_,x)=>Array.from({length:M},(_,j)=>Math.floor(x/3**(M-j-1))%3));}
function values(rows,ws,n,q){return ws.map(w=>Array.from({length:n},(_,j)=>mod(w.reduce((s,d,i)=>s+(d?rows[i][d-1][j]:0),0),q)));}
function order(a,b){for(let i=0;i<a.length;i++)if(a[i]!==b[i])return a[i]-b[i];return 0;}
function minor(ws){const basis=[[0,0],[1,0],[0,1]],rows=ws.slice(1).map(w=>w.flatMap((a,i)=>basis[a].map((v,j)=>v-basis[ws[0][i]][j])));for(let a=0;a<rows[0].length;a++)for(let b=a+1;b<rows[0].length;b++){const determinant=rows[0][a]*rows[1][b]-rows[0][b]*rows[1][a];if(Math.abs(determinant)===1)return{coefficient_rows:rows,columns:[a,b],determinant};}throw Error("pointed triple has no unit minor");}
const hash=crypto.createHash("sha256").update(fs.readFileSync(path.join(__dirname,"../TERNARY_BATCH_FIBER_COMPILER.md"))).digest("hex");
check(report.derivation_sha256===hash&&report.status==="BATCH_NATIVE_FIBER_EXTRACTION_ARCHITECTURE_REVIEW_PENDING_COMPILER_MISSING","pinned derivation and compiler debt");
for(const k of["candidate_record_accepted","quantum_speedup_proved","novelty_claim","efficient_coherent_partition_implemented"])check(report[k]===false,"not an efficient algorithm: "+k);
check(report.all_fiber_divisibility_is_existence_not_algorithm===true,"existence not search/instrument");
check(report.polynomial_supply_controls.length===4,"charged source-supply schedule");
report.polynomial_supply_controls.forEach((c,i)=>{const r=i+2,n=3**r,d=r-1,H=3**d,M=n*(H-1)+1;same([c.dimension,c.parent_root_digits,c.prefix_digits,c.parent_modulus,c.child_modulus],[n,r,d,String(n),"3"],"q=n batch regime");same(c.per_coordinate_digit_degree_bounds,Array.from({length:d},(_,j)=>2*3**j),"true carry polynomial degree bounds");check(c.total_constraint_degree_upper===n*(H-1)&&c.minimum_original_qutrits_for_all_fibers_divisible_by_three===M&&c.word_cube_exponent_base_three===M&&c.possible_measurement_tags_exponent_base_three===M-1&&c.output_qutrits_per_actual_input_batch===1,"strict Chevalley-Warning threshold and one child per batch");check(Number.isSafeInteger(c.generating_coefficient_circuit_scalar_operation_upper)&&c.generating_coefficient_circuit_scalar_operation_upper===n*M*(H+1)**2,"algebraic coefficient-circuit cost not a root solver");for(const k of["batch_supply_polynomial_in_n_only_if_q_polynomial_in_n","independent_child_law_requires_low_only_partition_and_fresh_batches"])check(c[k]===true,"conditional polynomial-supply premise");for(const k of["batch_supply_polynomial_in_log_q_claimed","known_integer_frequency_evaluation_is_a_fiber_inverse","efficient_coherent_partition_implemented","quantum_speedup_proved"])check(c[k]===false,"no hidden exponential-cost erasure");});
let wholeWords=0,allTags=0,physicalBranches=0,liftCases=0;
const schedule=[[1,3,2,9],[2,2,1,5],[3,4,1,7]];
check(report.native_complete_partition_controls.length===3,"all original native batches");
report.native_complete_partition_controls.forEach((c,index)=>{
  const[n,r,d,M]=schedule[index],q=3**r,H=3**d,child=q/H,D=3**M,ws=words(M),f=values(c.full_frequency_rows,ws,n,q);
  same([c.dimension,c.parent_root_digits,c.prefix_digits,c.modulus,c.child_modulus,c.original_qutrits],[n,r,d,q,child,M],"native complete-reference schedule");native(c.full_frequency_rows,c.native_labels,n,r);check(M>n*(H-1),"strict all-label threshold");
  const groups=new Map();f.forEach((v,i)=>{const S=v.map(a=>a%H),k=JSON.stringify(S);if(!groups.has(k))groups.set(k,{syndrome:S,indices:[]});groups.get(k).indices.push(i);});
  const fibers=[...groups.values()].sort((a,b)=>order(a.syndrome,b.syndrome)),mapping=fibers.flatMap(v=>v.indices),tags=D/3;
  same(c.occupied_fiber_counts,fibers.map(v=>({syndrome:v.syndrome,count:v.indices.length})),"all actual occupied fibers and exact counts");check(fibers.every(v=>v.indices.length%3===0)&&mapping.length===D&&new Set(mapping).size===D,"all words retained exactly once in balanced triples");
  const digest=crypto.createHash("sha256").update(JSON.stringify(mapping)).digest("hex");check(c.complete_partition_sha256===digest&&c.whole_word_reference_count===D&&c.complete_measurement_tag_count===tags&&c.pointed_unit_minors_checked_for_all_tags===tags,"whole reference map and every child minor, no partial enumeration");
  const secrets=[Array(n).fill(0),Array(n).fill(1),Array(n).fill(3),Array(n).fill(q-1)];same(c.calibration_secrets_only,secrets,"all specified primitive/nonprimitive controls");const selected=[0,Math.floor(tags/2),tags-1];check(c.selected_tag_controls.length===3,"prespecified tag controls");let controlIndex=0;
  for(let tag=0;tag<tags;tag++){
    const indices=mapping.slice(3*tag,3*tag+3),w=indices.map(x=>ws[x]),F=indices.map(x=>f[x]),R=F.slice(1).map(v=>v.map((a,k)=>mod(a-F[0][k],q)/H)),proof=minor(w);
    check(new Set(w.map(JSON.stringify)).size===3&&F.every(v=>v.every((a,j)=>a%H===F[0][j]%H))&&R.every(row=>row.every(a=>Number.isInteger(a)&&a>=0&&a<child)),"genuine three-word same-prefix child");
    for(let endpoint=1;endpoint<=2;endpoint++)for(let j=0;j<n;j++)check(mod(F[endpoint][j]-F[0][j]-H*R[endpoint-1][j],q)===0,"symbolic child exponent identity for EVERY secret component");
    for(const s of secrets){const base=mod(F[0].reduce((v,a,j)=>v+a*s[j],0),q)/q;let mass=0;for(let endpoint=0;endpoint<3;endpoint++){const original=mod(F[endpoint].reduce((v,a,j)=>v+a*s[j],0),q)/q,extra=endpoint?mod(R[endpoint-1].reduce((v,a,j)=>v+a*s[j],0),child)/child:0;const re=(Math.cos(2*Math.PI*original)-Math.cos(2*Math.PI*(base+extra)))/Math.sqrt(D),im=(Math.sin(2*Math.PI*original)-Math.sin(2*Math.PI*(base+extra)))/Math.sqrt(D);check(Math.hypot(re,im)<3e-11,"independent physical source-to-child phase replay");mass+=1/D;}check(Math.abs(mass-3/D)<3e-11,"all actual tags retained with raw Born mass");physicalBranches++;}
    if(selected.includes(tag)){
      const row=c.selected_tag_controls[controlIndex++];check(row.tag===tag&&row.actual_branch_Born_probability===frac(3,D),"measured tag probability, not success normalization");same(row.original_words,w,"actual original words in tag");same(row.full_frequencies,F,"actual parent full-root frequencies");same(row.child_frequency_rows,R,"actual lower-root rows");same(row.pointed_unit_minor,proof,"complete pointed coefficient rows and unit witness");
      const[a,b]=proof.columns,images=new Set();for(let u=0;u<child;u++)for(let v=0;v<child;v++)images.add(JSON.stringify(proof.coefficient_rows.map(row=>mod(row[a]*u+row[b]*v,child))));check(images.size===child**2&&row.complete_two_high_column_lift_cases===child**2&&row.distinct_child_frequency_pairs_for_each_coordinate===child**2,"full conditional high-lift pair bijection, including composite child roots");liftCases+=child**2;
    }
  }
  for(const k of["all_original_basis_words_covered_exactly_once","complete_permutation_state_replayed","conditional_IID_child_law_is_population_not_fixed_label_histogram","reference_time_and_memory_exponential_in_original_qutrits"])check(c[k]===true,"reference/coherence scope: "+k);
  for(const k of["all_measurement_tags_are_simultaneously_available_child_samples","partition_reads_high_frequency_lifts","independence_between_outputs_from_reused_original_batches_claimed","efficient_coherent_partition_implemented","source_preparation_inverse_or_free_QRAM_supplied","quantum_speedup_proved"])check(c[k]===false,"ungranted access/lineage: "+k);check(c.output_qutrits_per_input_batch===1,"no cloning from alternative tags");for(const k of["physical_all_tag_phase_residual","physical_all_tag_Born_mass_residual"])check(Number.isFinite(c[k])&&c[k]>=0&&c[k]<3e-11,"bounded complete permutation residual: "+k);
  wholeWords+=D;allTags+=tags;
});
const rows=report.digit_polynomial_control_full_rows,ws=words(3),frequencies=values(rows,ws,1,9);native(rows,report.digit_polynomial_control_native_labels,1,3);check(rows.length===3&&report.true_ring_digit_polynomial_controls.length===2,"bounded TRUE-ring polynomial controls");let circuitCases=0;
report.true_ring_digit_polynomial_controls.forEach((p,digit)=>{check(p.coordinate===0&&p.digit===digit&&p.degree_upper===Math.min(6,2*3**digit)&&p.entire_words_enumerated_calibration_only===27&&p.constant_degree_diagonal_solver_premise_certified===false,"degree scope and no diagonal solver import");const powers=new Set();for(const t of p.terms){check(t.powers.length===3&&t.powers.every(a=>Number.isInteger(a)&&a>=0&&a<=2)&&[1,2].includes(t.coefficient),"reduced F3 monomial");check(!powers.has(JSON.stringify(t.powers)),"no duplicate monomial");powers.add(JSON.stringify(t.powers));}const degree=Math.max(0,...p.terms.map(t=>t.powers.reduce((a,b)=>a+b,0))),mixed=p.terms.some(t=>t.powers.filter(a=>a).length>1);check(p.degree===degree&&degree<=p.degree_upper&&p.contains_mixed_variable_terms===mixed,"actual high-carry degree and mixed terms");
  ws.forEach((w,index)=>{const value=mod(p.terms.reduce((v,t)=>v+t.coefficient*t.powers.reduce((a,e,j)=>a*w[j]**e,1),0),3),trueDigit=Math.floor(frequencies[index][0]/3**digit)%3;check(value===trueDigit,"ALL words match their actual native ring digits");const L=3**digit,coeff=Array(L+1).fill(0);coeff[0]=1;for(let i=0;i<3;i++){const exponent=w[i]?rows[i][w[i]-1][0]%9:0;for(let step=0;step<exponent;step++)for(let k=L;k>=1;k--)coeff[k]=(coeff[k]+coeff[k-1])%3;}check(coeff[L]===trueDigit,"independent Pascal generating-function digit identity, not Python Lucas replay");circuitCases++;});
});check(report.complete_coefficient_circuit_identity_cases===circuitCases&&circuitCases===54&&report.true_ring_digit_polynomial_controls[1].contains_mixed_variable_terms===true,"full circuit calibration and failed high-degree diagonal premise");
let countingWords=0;
const countingSchedule=[[1,[[1],[-1]]],[2,[[1,2]]],[1,[[1,1,1]]]];
check(report.lexicographic_basis_compiler_counting_reduction_controls.length===3,"all worst-case counting controls");
report.lexicographic_basis_compiler_counting_reduction_controls.forEach((c,index)=>{
  const[V,clauses]=countingSchedule[index],gate=V+1,gated=[];let variables=gate;
  clauses.forEach(clause=>{if(clause.length<3)gated.push([gate,...clause]);else{const[a,b,d]=clause,y=++variables;gated.push([-gate,y],[-a,y],[gate,a,-y],[y,b,d]);}});
  same([c.original_boolean_variables,c.original_clauses,c.gated_boolean_variables,c.gated_clauses],[V,clauses,variables,gated],"parsimonious gate and unique OR extensions");
  const n=variables+gated.length,M=8*n+1,K=M-n,known=Array.from({length:variables},(_,j)=>Number(j>=V)),target=[...Array(variables).fill(0),...gated.map(clause=>3-clause.filter(a=>a<0).length)];
  const rows=Array.from({length:n},()=>[Array(n).fill(0),Array(n).fill(0)]);
  for(let j=0;j<variables;j++){rows[j][1][j]=1;gated.forEach((clause,k)=>rows[j][0][variables+k]=mod(clause.reduce((v,a)=>v+(Math.abs(a)===j+1?(a>0?1:-1):0),0),27));}
  for(let j=0;j<gated.length;j++){rows[variables+j][0][variables+j]=1;rows[variables+j][1][variables+j]=2;}
  const full=[...Array.from({length:K},()=>[Array(n).fill(0),Array(n).fill(0)]),...rows];
  same([c.native_dimension,c.parent_modulus,c.prefix_modulus,c.original_qutrits,c.zero_frequency_dummy_prefix_width],[n,27,9,M,K],"polynomial padded original-native instance, constant modulus");
  same(c.real_frequency_rows,rows,"actual Boolean domains and clause-slack frequency encoding");same(c.native_full_rows,full,"actual zero-frequency padding, not unenumerated arbitrary rows");native(full,c.native_labels,n,3);same(c.target_native_prefix,target,"native target prefix");same(c.known_satisfying_gated_assignment,known,"explicit known promised assignment");
  const sat=(w,C)=>C.every(clause=>clause.some(a=>Boolean(w[Math.abs(a)-1])===(a>0))),binary=width=>Array.from({length:2**width},(_,x)=>Array.from({length:width},(_,j)=>Math.floor(x/2**(width-j-1))%2));
  const originalCount=binary(V).filter(w=>sat(w,clauses)).length,gatedCount=binary(variables).filter(w=>sat(w,gated)).length;
  for(const w of binary(gate)){const completions=binary(variables-gate).map(y=>[...w,...y]).filter(a=>sat(a,gated));check(completions.length===(w[V]||sat(w.slice(0,V),clauses)?1:0),"unique auxiliary extension for each satisfying gated assignment");}
  const ws=words(n),f=values(rows,ws,n,9),solutions=ws.filter((_,i)=>JSON.stringify(f[i])===JSON.stringify(target));
  check(solutions.length===gatedCount&&gatedCount===originalCount+2**V&&c.real_fiber_count===gatedCount&&c.original_CNF_satisfying_assignment_count_calibration_only===originalCount&&c.whole_real_words_enumerated_calibration_only===3**n,"complete real fiber, not the exponential padded cube");
  const realKnown=[...known,...gated.map(clause=>3-clause.filter(a=>Boolean(known[Math.abs(a)-1])===(a>0)).length)],rank=solutions.findIndex(w=>JSON.stringify(w)===JSON.stringify(realKnown));check(rank>=0,"promised known real word is in native fiber");
  const first=[...Array(K).fill(0),...realKnown],second=[...Array(K-1).fill(0),1,...realKnown];same(c.first_promised_native_word,first,"first actual promised basis query");same(c.second_promised_native_word,second,"second actual promised basis query");same(values(full,[first,second],n,9),[target,target],"both promised basis queries have the same actual syndrome");
  const trits=[rank%3,(rank+gatedCount)%3];same(c.lex_logical_trits_from_exact_rank_formula_not_compiler,trits,"rank difference gives real fiber count modulo3");check(c.recovered_original_model_count_mod_three===mod(trits[1]-trits[0]-2**V,3)&&c.recovered_original_model_count_mod_three===originalCount%3,"two queries recover original model count modulo3");
  check(c.hard_labels_are_worst_case_not_IID_average_case===true,"counting reduction not random-source hardness");for(const k of["whole_padded_source_words_enumerated","actual_coherent_basis_compiler_supplied","nonlexicographic_or_source_state_only_compilers_ruled_out"])check(c[k]===false,"reduction scope, not general impossibility: "+k);countingWords+=ws.length;
});
console.log(JSON.stringify({status:"independent_native_batch_fiber_certificates_passed",completeNativePartitions:3,wholeNativeWords:wholeWords,completeTags:allTags,physicalBranches,conditionalLiftCases:liftCases,trueDigitCircuitCases:circuitCases,countingReductions:3,completeCountingCalibrationWords:countingWords,efficientCompilerSupplied:false,quantumSpeedupProved:false}));
