"use strict";
// Exact source-weighted Schmidt count certificates, not quantum hardness.
const fs=require("fs"),path=require("path"),crypto=require("crypto");
const report=JSON.parse(fs.readFileSync(process.argv[2]||path.join(__dirname,"../phase_workbench/ternary_prefix_schmidt.json"),"utf8"));
function check(x,m){if(!x)throw Error(m);}
const abs=x=>x<0n?-x:x;
function gcd(a,b){a=abs(a);b=abs(b);while(b)[a,b]=[b,a%b];return a;}
function F(a,b=1n){check(b!==0n,"denominator");if(b<0n){a=-a;b=-b;}const g=gcd(a,b);return [a/g,b/g];}
const add=(a,b)=>F(a[0]*b[1]+b[0]*a[1],a[1]*b[1]),mul=(a,b)=>F(a[0]*b[0],a[1]*b[1]),div=(a,b)=>F(a[0]*b[1],a[1]*b[0]),sub=(a,b)=>add(a,[-b[0],b[1]]),sq=a=>mul(a,a),eq=(a,b)=>a[0]*b[1]===b[0]*a[1],le=(a,b)=>a[0]*b[1]<=b[0]*a[1],cap=a=>le(a,F(1n))?a:F(1n);
function Q(x){check(typeof x==="string","canonical rational string");const t=x.split("/");check(t.length<=2,"syntax");const v=F(BigInt(t[0]),t.length===2?BigInt(t[1]):1n);check(x===(v[1]===1n?String(v[0]):v[0]+"/"+v[1]),"canonical rational");return v;}
const I=x=>{check(typeof x==="string"&&/^(0|[1-9][0-9]*)$/.test(x),"canonical nonnegative integer");return BigInt(x);},same=(a,b,m)=>check(JSON.stringify(a)===JSON.stringify(b),m),near=(a,b,m)=>check(Number.isFinite(a)&&Math.abs(a-b)<3e-11,m);
const derivation=fs.readFileSync(path.join(__dirname,"../TERNARY_PREFIX_SCHMIDT.md"));check(crypto.createHash("sha256").update(derivation).digest("hex")===report.derivation_sha256,"derivation hash");
check(report.status==="SOURCE_WEIGHTED_NATIVE_PREFIX_SCHMIDT_AUDIT_NOT_QUANTUM_HARDNESS"&&report.local_derivation_review_pending===true,"review scope");
for(const k of ["novelty_claim","candidate_record_accepted","quantum_speedup_proved","generic_quantum_or_tensor_network_lower_bound"])check(report[k]===false,"not a quantum/hardness result: "+k);
check(report.classical_prefix_outcome_law_exactly_reproduced===true&&report.prefix_outcomes_depend_on_unknown_secret===false&&report.classical_sampler_prepares_coherent_conditioned_state===false,"outcome marginal is dequantized, not coherent state preparation");
const schedule=[[1,16,7,7],[1,32,15,15],[1,64,31,31],[2,16,7,15]];check(report.population_certificates.length===4,"population schedule");
report.population_certificates.forEach((c,i)=>{const [n,r,d,l]=schedule[i],M=n*r-2,L=3n**BigInt(l),R=3n**BigInt(M-l),D=L*R,H=3n**BigInt(n*d),mu=F(D,H),a=mul(add(F(1n),F(L-1n,H)),add(F(1n),F(R-1n,H))),bad=cap(div(mul(F(2n),sub(F(1n),F(1n,H))),mu)),good=div(mul(F(2n),a),mu),purity=cap(add(bad,good)),bond=(n*r)**2,minBond=div(F(81n,100n),purity);
  check(c.dimension===n&&c.root_digits===r&&c.source_qutrits===M&&c.prefix_digits===d&&c.fixed_left_width===l&&I(c.left_words)===L&&I(c.right_words)===R&&I(c.native_words)===D&&I(c.prefix_group_size)===H,"fixed-cut native group geometry");
  for(const [k,v]of [["mean_uniform_target_fiber_size",mu],["uniform_target_fiber_variance",mul(mu,sub(F(1n),F(1n,H)))],["independent_half_collision_factor",a],["mean_Born_mass_of_fibers_below_half_mean_upper",bad],["mean_purity_good_sector_upper",good],["mean_Born_weighted_Schmidt_purity_upper",purity],["mean_squared_overlap_upper_squared",cap(mul(F(BigInt(bond)),purity))]])check(eq(Q(c[k]),v),"exact source-weighted population formula: "+k);
  check(c.mean_bond_budget===bond&&c.label_outcome_dependent_bond_allocation_covered_by_mean_cost_bound===true&&I(c.necessary_bond_for_mean_squared_overlap_ge_nine_tenths)===(minBond[0]+minBond[1]-1n)/minBond[1],"average fidelity bond cost including adaptive allocation on the fixed cut");near(c.mean_Renyi2_entropy_bits_lower_diagnostic,Math.log2(Number(purity[1]))-Math.log2(Number(purity[0])),"entropy diagnostic not proof-bearing");
  check(c.source_law==="ALL_IID_ORIGINAL_NATIVE_LABELS_AND_ACTUAL_PREFIX_BORN_MEASUREMENTS"&&c.secret_scope==="EVERY_FIXED_SECRET; SCHMIDT_WEIGHTS_INDEPENDENT_OF_SECRET"&&c.partition_scope==="FIXED_PUBLIC_WORD_SPLIT_INDEPENDENT_OF_RANDOM_LABELS"&&c.low_bond_full_state_fidelity_scope_only===true,"not uniform-target or per-label guarantees");for(const k of ["adaptive_label_partition_covered","general_tensor_network_or_quantum_no_go","quantum_speedup_proved","large_word_space_executed"])check(c[k]===false,"bounded representation scope: "+k);
});
const mod=(a,q)=>(a%q+q)%q,key=z=>JSON.stringify(z),order=(a,b)=>{for(let i=0;i<a.length;i++)if(a[i]!==b[i])return a[i]-b[i];return 0;};
function words(width){return Array.from({length:3**width},(_,x)=>{const w=[];for(let i=0;i<width;i++){w.push(x%3);x=Math.floor(x/3);}return w;});}
function values(f,n,q,start,width){return words(width).map(w=>Array.from({length:n},(_,j)=>mod(w.reduce((s,d,i)=>s+(d?f[start+i][d-1][j]:0),0),q)));}
function counts(v,Q0){const result=new Map();for(const z of v){const w=z.map(x=>x%Q0),k=key(w);if(!result.has(k))result.set(k,{syndrome:w,count:0});result.get(k).count++;}return [...result.values()].sort((a,b)=>order(a.syndrome,b.syndrome));}
function branch(L,R,target,Q0,D,chi){const right=new Map(R.map(v=>[key(v.syndrome),v.count])),weights=[];for(const a of L){const w=target.map((x,j)=>mod(x-a.syndrome[j],Q0)),b=right.get(key(w))||0;if(b)weights.push({left_syndrome:a.syndrome,right_syndrome:w,integer_weight:String(a.count*b)});}const ns=weights.map(w=>I(w.integer_weight)),C=ns.reduce((a,b)=>a+b,0n);return {weights,C,born:F(C,BigInt(D)),purity:C?F(ns.reduce((a,b)=>a+b*b,0n),C*C):null,fidelity:C?F(ns.sort((a,b)=>a>b?-1:a<b?1:0).slice(0,chi).reduce((a,b)=>a+b,0n),C):null};}
function verifyBranch(row,b,target){same(row.target,target,"every original prefix target");check(I(row.fiber_size)===b.C&&eq(Q(row.Born_probability),b.born),"exact physical target Born weight");same(row.Schmidt_integer_weights,b.weights,"every complementary syndrome product retained");if(!b.C){check(row.status==="EMPTY_PHYSICAL_BRANCH"&&row.conditional_purity===null&&row.conditional_best_rank_chi_squared_overlap===null,"empty cannot be normalized");}else check(row.status==="EXACT_NATIVE_PREFIX_SCHMIDT_BRANCH"&&row.Schmidt_rank===b.weights.length&&eq(Q(row.conditional_purity),b.purity)&&eq(Q(row.conditional_best_rank_chi_squared_overlap),b.fidelity),"exact conditional Schmidt spectrum/purity/fidelity");}
let variance=F(0n),collision=F(0n),meanPurity=F(0n);
for(let a=0;a<3;a++)for(let c=0;c<3;c++)for(let b=0;b<3;b++)for(let e=0;e<3;e++){const L=counts([[0],[a],[c]],3),R=counts([[0],[b],[e]],3);collision=add(collision,F(BigInt(L.reduce((s,v)=>s+v.count*v.count,0)*R.reduce((s,v)=>s+v.count*v.count,0))));for(let y=0;y<3;y++){const z=branch(L,R,[y],3,9,1);variance=add(variance,F((z.C-3n)**2n,3n));if(z.C)meanPurity=add(meanPurity,mul(z.born,z.purity));}}
const census=report.complete_low_label_census;check(census.complete_IID_low_label_cases===81&&census.prefix_targets_per_case===3&&eq(Q(census.uniform_target_variance),div(variance,F(81n)))&&eq(Q(census.uniform_target_variance),F(2n))&&eq(Q(census.independent_half_collision_product_mean),div(collision,F(81n)))&&eq(Q(census.independent_half_collision_product_mean),F(25n))&&eq(Q(census.Born_weighted_purity_mean),div(meanPurity,F(81n)))&&census.IID_full_root_lifts_preserve_this_low_law===true&&census.not_a_quantum_candidate===true,"entire IID low label law, exact size bias");
function matmul(A,B){return A.map(row=>B[0].map((_,j)=>row.reduce((s,a,k)=>s+a*B[k][j],0n)));}
function chart(r){let V=[[1n,0n],[0n,1n]],B=[[-1n,-1n],[1n,-2n]];for(let i=0;i<2*r-1;i++)V=matmul(V,B);const det=V[0][0]*V[1][1]-V[0][1]*V[1][0],q=3n**BigInt(r),den=3n*det,u=q*(2n*V[1][1]+V[1][0]),v=q*(-2n*V[0][1]-V[0][0]);check(u%den===0n&&v%den===0n,"integer native chart");return [Number(u/den),Number(v/den)];}
const cases=[[1,8,3,3,99501],[1,10,4,4,99502],[2,4,1,3,99503]];check(report.prespecified_native_cases.length===3,"all prespecified cases");let branches=0,physical=0,unknowns=0;
report.prespecified_native_cases.forEach((c,i)=>{const [n,r,d,split,seed]=cases[i],M=n*r-2,q=3**r,D=3**M,Lsize=3**split,Rsize=3**(M-split),[u,v]=chart(r);same([c.dimension,c.root_digits,c.seed],[n,r,seed],"native case schedule");check(c.native_labels.length===M&&c.full_frequencies.length===M,"native row count");for(let k=0;k<M;k++){check(c.native_labels[k].length===n&&c.full_frequencies[k].length===2&&c.full_frequencies[k].every(row=>row.length===n),"two full rows per native register");for(let j=0;j<n;j++){const [a,b]=c.native_labels[k][j];check([a,b,...c.full_frequencies[k].map(row=>row[j])].every(x=>Number.isSafeInteger(x)&&0<=x&&x<q),"canonical full-root native labels");check(c.full_frequencies[k][0][j]===mod(u*a+v*b,q)&&c.full_frequencies[k][1][j]===mod((u+v)*a-u*b,q),"native chart not a toy oracle");}}
  const left=values(c.full_frequencies,n,q,0,split),right=values(c.full_frequencies,n,q,split,M-split),depths=n===1?[0,d,r-1]:[0,d,2];check(c.count_controls.length===3,"all prefix depths");
  c.count_controls.forEach((control,index)=>{const depth=depths[index],Q0=3**depth,H=Q0**n;check(control.prefix_digits===depth,"depth schedule");if(H>300){check(control.status==="WHOLE_PREFIX_DIAGNOSTIC_PREFLIGHT_UNKNOWN"&&I(control.prefix_group_size)===BigInt(H)&&control.complete_target_budget===300&&control.classification_complete===false&&control.Born_weighted_purity===null&&!control.complete_branches,"no partial proof beyond whole target budget");unknowns++;return;}
    const L=counts(left,Q0),R=counts(right,Q0);same(control.left_syndrome_counts,L.map(v=>({syndrome:v.syndrome,count:String(v.count)})),"all left counts");same(control.right_syndrome_counts,R.map(v=>({syndrome:v.syndrome,count:String(v.count)})),"all right counts");check(control.fixed_left_width===split&&control.bond_cap===2&&control.complete_branches.length===H,"fixed source cut and all branch schedule");let norm=F(0n),purity=F(0n),fidelity=F(0n);
    for(let y=0;y<H;y++){const target=Array.from({length:n},(_,j)=>Math.floor(y/Q0**(n-j-1))%Q0),b=branch(L,R,target,Q0,D,2);verifyBranch(control.complete_branches[y],b,target);norm=add(norm,b.born);if(b.C){purity=add(purity,mul(b.born,b.purity));fidelity=add(fidelity,mul(b.born,b.fidelity));}branches++;}
    check(eq(norm,F(1n))&&eq(Q(control.Born_probability_sum),norm)&&eq(Q(control.Born_weighted_purity),purity)&&eq(Q(control.Born_weighted_best_rank_chi_squared_overlap),fidelity)&&le(sq(fidelity),mul(F(2n),purity)),"source-weighted mean, not uniform targets");check(control.half_words_enumerated===Lsize+Rsize&&control.full_native_words_enumerated_for_counts===0&&control.all_branch_classification_not_population_estimate===true,"diagnostic costs and population scope");
  });
  check(c.physical_controls.length===9,"physical target/all-secret schedule");const Q0=3**d,L=counts(left,Q0),R=counts(right,Q0);let index=0;
  for(const target of [Array(n).fill(0),Array(n).fill(1),Array(n).fill(Q0-1)])for(const secret of [Array(n).fill(0),Array(n).fill(3),Array(n).fill(q-1)]){const row=c.physical_controls[index++],b=branch(L,R,target,Q0,D,1);same(row.target,target,"prespecified physical target");same(row.calibration_secret_only,secret,"all secret types");check(eq(Q(row.Born_probability),b.born),"physical branch Born mass");if(!b.C)check(row.status==="EMPTY_PHYSICAL_BRANCH","empty physical branch retained");else{const expected=b.weights.map(w=>Number(I(w.integer_weight))/Number(b.C)).sort((a,b)=>b-a);while(expected.length<Math.min(Lsize,Rsize))expected.push(0);check(row.status==="NATIVE_PREFIX_PROJECTOR_DENSE_SCHMIDT_REPLAY"&&row.observed_squared_singular_values.length===expected.length&&row.predicted_squared_singular_values.length===expected.length,"complete exact spectrum/control dimension");for(let k=0;k<expected.length;k++){near(row.predicted_squared_singular_values[k],expected[k],"formula spectrum");near(row.observed_squared_singular_values[k],expected[k],"actual native phase SVD spectrum");}check(row.spectrum_residual>=0&&row.spectrum_residual<3e-11&&row.matrix_norm_residual>=0&&row.matrix_norm_residual<3e-11&&row.dense_calibration_cells===D&&row.unknown_secret_used_in_receiver_recipe===false,"physical diagnostic scope/norm/cost");}physical++;}
});
console.log(JSON.stringify({status:"independent_native_prefix_Schmidt_controls_passed",populationCertificates:4,completeNativeBranches:branches,physicalControls:physical,wholePreflightUnknowns:unknowns,completeLowLabelCases:81,quantumSpeedupProved:false,genericQuantumNoGo:false}));
