"use strict";
const fs=require("fs"),path=require("path"),crypto=require("crypto");
const {check,same,rat,zero,one,add,mul,div,str,parse,cmp}=require("./cyclotomic_exact.js");
const root=path.join(__dirname,"../.."),R=JSON.parse(fs.readFileSync(process.argv[2]||path.join(root,"research/classical_baselines/ternary_native_block_walk.json"),"utf8"));
const key=JSON.stringify,mod=(a,q)=>(a%q+q)%q;
const hash=p=>crypto.createHash("sha256").update(fs.readFileSync(p)).digest("hex");
check(R.derivation_sha256===hash(path.join(root,"research/TERNARY_NATIVE_BLOCK_WALK.md")),"pinned block-walk derivation");
for(const flag of["quantum_walk_gate_export_supplied","stationary_state_preparation_or_inverse_granted","efficient_fiber_eraser_supplied","generic_quantum_receiver_lower_bound","quantum_speedup_proved","candidate_record_accepted","novelty_claim"])check(R[flag]===false,"unsupported walk claim: "+flag);
function cube(q,n){let out=[[]];for(let i=0;i<n;i++)out=out.flatMap(v=>Array.from({length:q},(_,a)=>[...v,a]));return out;}
function combinations(m,k){if(k===0)return[[]];let out=[];function rec(v,start){if(v.length===k){out.push(v);return;}for(let i=start;i<m;i++)rec([...v,i],i+1);}rec([],0);return out;}
function choose(m,k){let a=1n;for(let i=0;i<k;i++)a=a*BigInt(m-i)/BigInt(i+1);return a;}
function vocabulary(m,k){let a=0n;for(let j=1;j<=k;j++)a+=choose(m,j)*6n**BigInt(j);return a/2n;}
const source=R.native_source,q=source.modulus,n=source.dimension,m=source.source_inputs;
check(q===9&&n===2&&m===5&&source.native_level===4&&source.seed===89881&&source.seed_is_population_scaling_evidence===false,"actual preregistered source / seed not population evidence");
function chart(level){let V=[[1n,0n],[0n,1n]],pi=[[-1n,-1n],[1n,-2n]];for(let j=0;j<level-1;j++)V=V.map(row=>pi[0].map((_,i)=>row.reduce((s,a,k)=>s+a*pi[k][i],0n)));const q=3n**BigInt(level/2),den=3n*(V[0][0]*V[1][1]-V[0][1]*V[1][0]),a=q*(2n*V[1][1]+V[1][0]),b=q*(-2n*V[0][1]-V[0][0]);check(a%den===0n&&b%den===0n,"integer native chart");const u=a/den,v=b/den;return label=>{const[x,y]=label.map(BigInt);return[Number((u*x+v*y)%q+q)%Number(q),Number(((u+v)*x-u*y)%q+q)%Number(q)];};}
const at=chart(4),F=source.original_ring_labels.map(row=>{const pairs=row.map(at);return[pairs.map(x=>x[0]),pairs.map(x=>x[1])];});same(F,source.native_frequencies,"original native chart, no field-shadow substitution");
const W=cube(3,m),D=W.length,lookup=new Map(W.map((w,i)=>[key(w),i]));
const value=w=>Array.from({length:n},(_,j)=>mod(w.reduce((s,t,i)=>s+(t===0?0:F[i][t-1][j]),0),q)),V=W.map(value);
const signatures=[[1,0],[0,1],[-1,0],[-1,1],[0,-1],[1,-1]],oldNew=[[0,1],[0,2],[1,0],[1,2],[2,0],[2,1]];
let rowsChecked=0,signaturesChecked=0,zeroGaps=0;
same(R.live_trials.map(t=>[t.reference.prefix,t.reference.support]),[[9,1],[9,2],[9,3],[9,5],[3,2]],"same-source full/low prefix and support controls");
for(const trial of R.live_trials){
  const ref=trial.reference,H=ref.prefix,k=ref.support,B=combinations(m,k),assignments=cube(3,k),local=(block,digits)=>Array.from({length:n},(_,j)=>mod(block.reduce((s,i,l)=>s+(digits[l]===0?0:F[i][digits[l]-1][j]),0),H));
  same(W,ref.complete_words,"whole native word cube retained");same(V,ref.full_frequency_values,"full-root values retained at every prefix");
  const rows=W.map(word=>{const row=new Map();B.forEach(block=>{const target=key(local(block,block.map(i=>word[i]))),compatible=assignments.filter(d=>key(local(block,d))===target),p=rat(1n,BigInt(B.length*compatible.length));check(compatible.length>0,"current word missing from its conditional class");compatible.forEach(d=>{const w=word.slice();block.forEach((i,l)=>w[i]=d[l]);const j=lookup.get(key(w));row.set(j,add(row.get(j)||zero,p));});});return row;});
  check(ref.conditional_transition_rows.length===D,"all transition rows required");
  rows.forEach((row,i)=>{const encoded=[...row].sort((a,b)=>a[0]-b[0]).map(([j,p])=>[j,str(p)]);same(encoded,ref.conditional_transition_rows[i],"every conditional transition recomputed from the complete local table");check(cmp([...row.values()].reduce(add,zero),one)===0n,"exact row stochasticity");for(const[j,p]of row){check(cmp(p,rows[j].get(i)||zero)===0n,"exact reversibility");same(V[i].map(x=>x%H),V[j].map(x=>x%H),"committed prefix preserved");}rowsChecked++;});
  const unseen=new Set(Array.from({length:D},(_,i)=>i)),components=[];
  while(unseen.size){const start=Math.min(...unseen),seen=new Set([start]),stack=[start];while(stack.length){const i=stack.pop();for(const j of rows[i].keys())if(!seen.has(j)){seen.add(j);stack.push(j);}}for(const i of seen)unseen.delete(i);components.push([...seen].sort((a,b)=>a-b));}
  same(components,ref.connected_components,"complete communication classes");
  const ci=new Map();components.forEach((C,j)=>C.forEach(i=>ci.set(i,j)));const fibers=new Map();V.forEach((v,i)=>{const a=key(v.map(x=>x%H));if(!fibers.has(a))fibers.set(a,[]);fibers.get(a).push(i);});
  const rebuilt=[...fibers].sort((a,b)=>{const x=JSON.parse(a[0]),y=JSON.parse(b[0]);for(let i=0;i<n;i++)if(x[i]!==y[i])return x[i]-y[i];return 0;}).map(([raw,indices])=>{const ids=[...new Set(indices.map(i=>ci.get(i)))].sort((a,b)=>a-b),disconnected=ids.length>1,C=indices.length;let gap=one;if(disconnected){gap=zero;zeroGaps++;}else if(C>1&&k<m){let min=null;indices.forEach(i=>{for(const[j,p]of rows[i])if(i!==j&&(min===null||cmp(p,min)<0n))min=p;});check(min!==null,"connected nontrivial fiber has no off-diagonal edge");gap=div(mul(rat(2n),min),rat(BigInt(C*(C-1))));}return{prefix_frequency:JSON.parse(raw),word_indices:indices,component_indices:ids,uniform_fiber_stationary_subspace_dimension:ids.length,fiber_mixing_gap_certified_lower:str(gap),exact_gap_zero_certified:disconnected,exact_gap_one_complete_heatbath:k===m};});
  same(rebuilt,ref.prefix_fibers,"full-fiber zero-gap and connected path certificates");
  const fullCounts=new Map();V.forEach(v=>fullCounts.set(key(v),(fullCounts.get(key(v))||0)+1));
  const nontrivial=[...fullCounts.values()].filter(a=>a>1).reduce((s,a)=>s+a,0),bad=rebuilt.filter(f=>f.exact_gap_zero_certified).reduce((s,f)=>s+f.word_indices.length,0),stationary=rows.every((row,i)=>[...row.keys()].every(j=>key(V[i])===key(V[j])));
  check(ref.raw_source_mass_in_nontrivial_FULL_frequency_fibers===str(rat(BigInt(nontrivial),BigInt(D)))&&ref.raw_uniform_source_mass_in_disconnected_prefix_fibers===str(rat(BigInt(bad),BigInt(D)))&&ref.full_native_source_family_stationary_certified===stationary,"raw source weighting and full-root stationarity");
  check(ref.whole_reference_word_count===D&&ref.whole_reference_work_upper===String(BigInt(D*B.length*3**k))&&ref.all_rows_exactly_symmetric_stochastic===true&&ref.kernel_PSD_by_average_of_conditional_projection_blocks===true&&ref.reference_enumerates_whole_native_word_cube===true&&ref.reference_is_scalable_walk_compiler===false&&ref.efficient_fiber_eraser_supplied===false,"reference cost/scope and projection construction");
  const audit=trial.signature_audit,zeros=[];let count=0;
  for(let j=1;j<=k;j++)for(const positions of combinations(m,j))for(const indices of cube(6,j)){
    const coefficients=indices.map(i=>signatures[i]),first=coefficients[0].find(x=>x!==0);if(first<0)continue;count++;
    const residual=Array.from({length:n},(_,l)=>mod(positions.reduce((s,i,a)=>s+coefficients[a][0]*F[i][0][l]+coefficients[a][1]*F[i][1][l],0),H));
    if(residual.every(x=>x===0)){const a=Array(m).fill(0),b=a.slice();positions.forEach((i,l)=>{[a[i],b[i]]=oldNew[indices[l]];});same(value(a).map(x=>x%H),value(b).map(x=>x%H),"signature witness has an actual original native collision");zeros.push({positions,coefficients,first_word:a,second_word:b});}}
  same(zeros,audit.zero_signatures,"entire zero-signature atlas reconstructed");check(BigInt(count)===vocabulary(m,k)&&audit.unoriented_signatures_checked===String(count)&&audit.complete_vocabulary_checked===true&&audit.all_small_moves_frozen_certified===(zeros.length===0)&&audit.generic_quantum_receiver_lower_bound===false,"no incomplete signature scan can certify freezing");signaturesChecked+=count;
  if(!zeros.length)check(components.length===D,"certified no-move source has nontrivial components");
  const live=trial.live_step,block=live.block,input=live.initial_word,compatible=assignments.filter(d=>key(local(block,d))===key(local(block,block.map(i=>input[i]))));
  check(block.length===k&&new Set(block).size===k&&block.every((i,j)=>Number.isInteger(i)&&i>=0&&i<m&&(j===0||block[j-1]<i))&&live.conditional_candidates===compatible.length&&live.local_word_evaluations_charged===3**k,"live conditional block access and cost");
  check(compatible.some(d=>key(input.map((t,i)=>block.includes(i)?d[block.indexOf(i)]:t))===key(live.word))&&live.full_secret_grid_enumerated===false&&live.full_fiber_count_oracle_used===false&&live.quantum_state_preparation_implemented===false,"live output belongs to the fully enumerated legal local class");
}
check(R.live_trials[0].signature_audit.all_small_moves_frozen_certified===true&&R.live_trials[0].reference.raw_source_mass_in_nontrivial_FULL_frequency_fibers==="233/243","non-singleton source mass, not an empty-fiber artifact");
check(R.live_trials[3].reference.prefix_fibers.every(f=>f.fiber_mixing_gap_certified_lower==="1"&&!f.exact_gap_zero_certified),"complete-block positive control restores connectivity at exponential access cost");
check(R.live_trials[4].reference.full_native_source_family_stationary_certified===false,"low-prefix moves cannot be substituted for full-root moves");
for(const L of R.global_small_move_population_ledgers){const n=L.dimension,q=BigInt(L.modulus),m=L.source_inputs,k=L.maximum_changed_word_coordinates,V=vocabulary(m,k),G=q**BigInt(n),p=V<G?rat(V,G):one;check(L.unoriented_nonzero_difference_signatures===String(V)&&L.full_frequency_group===String(G)&&L.probability_any_nontrivial_small_support_fiber_collision_upper===str(p)&&L.probability_all_small_support_fiber_walks_frozen_lower===str(add(one,rat(-p[0],p[1]))),"exact global adaptive-small-move population bound");for(const flag of["requires_all_IID_uniform_full_native_rows","label_and_word_adaptive_block_policies_covered","all_moves_must_exactly_preserve_frequency_prefix","temporary_prefix_violations_or_nonlocal_macros_are_outside_scope"])check(L[flag]===true,"small-move scope: "+flag);check(L.generic_quantum_receiver_lower_bound===false,"narrow walk gate is not a receiver lower bound");}
same(R.near_entropy_quarter_distance_certificates.map(c=>[c.dimension,c.modulus,c.sample_surplus_over_group_entropy]),[[128,"243",8],[512,"729",8]],"near-entropy extensive-distance controls");
for(const c of R.near_entropy_quarter_distance_certificates){const n=c.dimension,q=BigInt(c.modulus),r=c.root_digits,surplus=c.sample_surplus_over_group_entropy,M=n*r+surplus,k=Math.floor(M/4),G=q**BigInt(n),V=vocabulary(M,k),exact=V<G?rat(V,G):one;check(3n**BigInt(r)===q&&c.source_inputs===M&&c.maximum_changed_coordinates===k&&c.minimum_full_fiber_collision_distance_on_no_event===k+1,"committed entropy/copy regime and support fraction");const base=rat(512n,729n),comparison=rat(11n**4n,12n**4n),raw=rat((3n**BigInt(surplus))*(11n**BigInt(M)),2n*(12n**BigInt(M))),simple=cmp(raw,one)<0n?raw:one;check(c.fourth_power_base_comparison_left===str(base)&&c.fourth_power_base_comparison_right===str(comparison)&&cmp(base,comparison)<=0n&&c.simple_rational_collision_probability_upper===str(simple)&&cmp(exact,simple)<=0n,"exact quarter-distance Chernoff envelope without floating entropy");const L=c.exact_signature_population_ledger;check(L.source_inputs===M&&L.maximum_changed_word_coordinates===k&&L.unoriented_nonzero_difference_signatures===String(V)&&L.full_frequency_group===String(G)&&L.probability_any_nontrivial_small_support_fiber_collision_upper===str(exact)&&L.generic_quantum_receiver_lower_bound===false,"complete combinatorial quarter-distance ledger");check(c.requires_M_equals_n_times_root_digits_plus_surplus===true&&c.polynomial_gate_macros_with_many_changed_coordinates_not_excluded===true&&c.distance_certificate_is_efficient_partner_finder===false&&c.conditional_block_enumeration_if_such_a_block_used===String(3n**BigInt(k)),"distance is not a partner finder or general circuit lower bound");}
check(R.uniform_block_selection_does_not_enumerate_the_block_menu===true&&R.small_block_step_is_polynomial_at_logarithmic_support===true,"actual step, not complete-reference loop, controls its runtime");
console.log(JSON.stringify({status:"PASS",exact_native_transition_rows:rowsChecked,unoriented_difference_signatures:signaturesChecked,disconnected_fiber_gap_certificates:zeroGaps,efficient_fiber_eraser_supplied:false}));
