"use strict";
// Independent native chart, SDE masks, word-dependent RREF and unseen-lift counts.
const fs=require("fs"),path=require("path"),crypto=require("crypto");
const report=JSON.parse(fs.readFileSync(process.argv[2]||path.join(__dirname,"../phase_workbench/ternary_shallow_kernel_cycle.json"),"utf8"));
const check=(x,m)=>{if(!x)throw Error(m);},same=(a,b,m)=>check(JSON.stringify(a)===JSON.stringify(b),m),mod=(a,q)=>(a%q+q)%q,key=JSON.stringify;
function gcd(a,b){while(b)[a,b]=[b,a%b];return a<0n?-a:a;}
function frac(a,b){a=BigInt(a);b=BigInt(b);const g=gcd(a,b);a/=g;b/=g;return b===1n?String(a):a+"/"+b;}
function words(M){return Array.from({length:3**M},(_,x)=>Array.from({length:M},(_,j)=>Math.floor(x/3**(M-j-1))%3));}
function order(a,b){for(let j=0;j<a.length;j++)if(a[j]!==b[j])return a[j]-b[j];return 0;}
function matmul(A,B){return A.map(row=>B[0].map((_,j)=>row.reduce((s,a,k)=>s+a*B[k][j],0n)));}
function native(rows,labels,n,r){let V=[[1n,0n],[0n,1n]],B=[[-1n,-1n],[1n,-2n]];for(let i=0;i<2*r-1;i++)V=matmul(V,B);const q=3n**BigInt(r),den=3n*(V[0][0]*V[1][1]-V[0][1]*V[1][0]),u=q*(2n*V[1][1]+V[1][0]),v=q*(-2n*V[0][1]-V[0][0]);check(u%den===0n&&v%den===0n,"exact original native chart");const a=u/den,b=v/den;check(labels.length===rows.length,"native input count");rows.forEach((pair,i)=>{check(pair.length===2&&pair.every(row=>row.length===n)&&labels[i].length===n,"native frequency shape");for(let j=0;j<n;j++){const[x,y]=labels[i][j];check([x,y,...pair.map(row=>row[j])].every(t=>Number.isSafeInteger(t)&&t>=0&&t<Number(q)),"canonical native labels");same(pair.map(row=>row[j]),[Number(mod(a*BigInt(x)+b*BigInt(y),q)),Number(mod((a+b)*BigInt(x)-a*BigInt(y),q))],"original native label-frequency relation");}});}
function rref(A){A=A.map(row=>row.map(a=>mod(a,3)));const pivots=[];let r=0;for(let j=0;j<A[0].length&&r<A.length;j++){let pivot=-1;for(let k=r;k<A.length;k++)if(A[k][j]){pivot=k;break;}if(pivot<0)continue;[A[r],A[pivot]]=[A[pivot],A[r]];const inverse=A[r][j];A[r]=A[r].map(a=>a*inverse%3);for(let k=0;k<A.length;k++)if(k!==r){const factor=A[k][j];A[k]=A[k].map((a,i)=>mod(a-factor*A[r][i],3));}pivots.push(j);r++;}return{rows:A,pivots};}
function kernel(columns){const n=columns[0].length,m=columns.length,R=rref(Array.from({length:n},(_,j)=>columns.map(v=>v[j])));const free=Array.from({length:m},(_,i)=>i).find(i=>!R.pivots.includes(i));check(free!==undefined,"one free coordinate exists");const c=Array(m).fill(0);c[free]=1;R.pivots.forEach((p,i)=>c[p]=mod(-R.rows[i][free],3));check(c.some(Boolean)&&Array.from({length:n},(_,j)=>mod(columns.reduce((s,v,i)=>s+v[j]*c[i],0),3)).every(x=>!x),"exact deterministic nonzero tangent kernel");return c;}
function sum(vectors,indices){return vectors[0].map((_,j)=>mod(indices.reduce((s,i)=>s+vectors[i][j],0),3));}
function zeroSupport(vectors){const n=vectors[0].length,inner=[],common=[];for(let g=0;g<n+1;g++){const indices=Array.from({length:n+1},(_,j)=>g*(n+1)+j),c=kernel(indices.map(i=>vectors[i])),left=indices.filter((_,j)=>c[j]===1),right=indices.filter((_,j)=>c[j]===2);same(sum(vectors,left),sum(vectors,right),"inner equal-sum relation");if(!left.length||!right.length)return left.length?left:right;inner.push([left,right]);common.push(sum(vectors,left));}const c=kernel(common),left=c.flatMap((a,j)=>a===1?[j]:[]),right=c.flatMap((a,j)=>a===2?[j]:[]);same(sum(common,left),sum(common,right),"outer equal-sum relation");if(!left.length||!right.length)return(left.length?left:right).flatMap(j=>inner[j][0]).sort((a,b)=>a-b);const four=[left.flatMap(j=>inner[j][0]),left.flatMap(j=>inner[j][1]),right.flatMap(j=>inner[j][0]),right.flatMap(j=>inner[j][1])];return four.slice(0,3).flat().sort((a,b)=>a-b);}
function makePolicy(c,mode){const n=c.dimension,M=c.original_qutrits,rows=c.full_frequency_rows,p=c.policy,A=Array.from({length:n},(_,j)=>rows.map(pair=>mod(pair[1][j]-pair[0][j],3))),B=Array.from({length:n},(_,j)=>rows.map(pair=>mod(2*pair[0][j]-pair[1][j],3)));same([p.dimension,p.original_qutrits,p.A,p.B],[n,M,A,B],"cached low quadratic rows from actual source");check(p.mask_policy===mode&&p.disjoint_masks.length===n+1,"reviewed mask acquisition policy");if(mode==="known-disjoint-SDE-windows"){const W=(n+1)**2;check(M===(n+1)**3,"known guaranteed source window");const masks=Array.from({length:n+1},(_,j)=>{const indices=Array.from({length:W},(_,i)=>j*W+i);return zeroSupport(indices.map(i=>B.map(row=>row[i]))).map(i=>indices[i]);});same(p.disjoint_masks,masks,"independent SDE preprocessing, not a supplied witness");}const all=[];p.disjoint_masks.forEach(mask=>{check(mask.length>0&&mask.every((a,j)=>Number.isInteger(a)&&a>=0&&a<M&&(j===0||a>mask[j-1]))&&B.every(row=>mod(mask.reduce((s,i)=>s+row[i],0),3)===0),"nonempty canonical true curvature-zero mask");all.push(...mask);});check(new Set(all).size===all.length,"disjoint masks for invariant tangents");same(p.mask_support_ranks,p.disjoint_masks.map(mask=>rref(B.map(row=>mask.map(i=>row[i]))).pivots.length),"actual mask column ranks");check(p.word_evaluation_arithmetic_cost==="O(n*M+n^3)"&&p.guaranteed_mask_preprocessing_polynomial===(mode==="known-disjoint-SDE-windows")&&p.explicit_polynomial_word_algorithm_supplied===true&&p.acceptance_for_all_low_matrices==="1","known host algorithm and conditional valid-mask guarantee");for(const k of["policy_stores_or_reads_high_frequency_rows","word_cube_table_or_rank_oracle_loaded","native_quantum_gate_synthesis_supplied","whole_instrument_hardware_error_bound_supplied","full_depth_polynomial_supply_supplied"])check(p[k]===false,"no ungranted oracle, hardware or full-depth claim: "+k);
  check(p.one_step_polynomial_original_supply_supplied===true&&p.full_depth_polynomial_supply_supplied===false,"one-step polynomial supply is known; full-depth gain is not");
  function control(word){check(word.length===M&&word.every(x=>Number.isInteger(x)&&x>=0&&x<3),"canonical original word");const T=p.disjoint_masks.map(mask=>Array.from({length:n},(_,j)=>mod(mask.reduce((s,i)=>s+A[j][i]+2*B[j][i]*word[i],0),3))),coefficients=kernel(T),v=Array(M).fill(0);p.disjoint_masks.forEach((mask,j)=>mask.forEach(i=>v[i]=coefficients[j]));return{T,coefficients,v};}
  const step=word=>{const v=control(word).v;return word.map((a,i)=>mod(a+v[i],3));};return{control,step};
}
function minor(ws){const basis=[[0,0],[1,0],[0,1]],R=ws.slice(1).map(w=>w.flatMap((a,i)=>basis[a].map((b,j)=>b-basis[ws[0][i]][j])));for(let a=0;a<R[0].length;a++)for(let b=a+1;b<R[0].length;b++){const determinant=R[0][a]*R[1][b]-R[0][b]*R[1][a];if(Math.abs(determinant)===1)return{coefficient_rows:R,columns:[a,b],determinant};}throw Error("pointed native minor");}
const hash=crypto.createHash("sha256").update(fs.readFileSync(path.join(__dirname,"../TERNARY_SHALLOW_KERNEL_CYCLE.md"))).digest("hex");check(report.derivation_sha256===hash&&report.status==="KNOWN_SHALLOW_NONLINEAR_CYCLE_VERIFIED_FULL_DEPTH_LIFT_BLOCKED_REVIEW_PENDING","pinned derivation");for(const k of["candidate_record_accepted","quantum_speedup_proved","novelty_claim","all_polynomial_cycle_programs_are_polynomial_explicit_menus_claimed","full_depth_polynomial_time_and_supply_algorithm_supplied","source_preparation_inverse_granted"])check(report[k]===false,"known baseline and gate scope: "+k);check(report.complete_n1_seed_selected_for_nonconstant_direction_control===true,"selected calibration seed, not a population sample");
check(report.native_controls.length===3,"all prespecified native controls");let wholeWords=0,sampledWords=0,physicalTags=0,liftCases=0;
report.native_controls.forEach((c,index)=>{
  const n=index+1,M=(n+1)**3,r=3,q=27;check(c.dimension===n&&c.parent_root_digits===r&&c.parent_modulus===q&&c.original_qutrits===M,"original source schedule");native(c.full_frequency_rows,c.native_labels,n,r);const policy=makePolicy(c,"known-disjoint-SDE-windows"),complete=index===0,ws=complete?words(M):c.audited_words;check(c.source_cube_enumerated_completely===complete&&c.original_words_audited===(complete?3**M:48)&&ws.length===c.original_words_audited&&(complete?c.audited_words===null:true),"whole native cube vs bounded calibration, not implicit scalability");const frequency=w=>Array.from({length:n},(_,j)=>mod(w.reduce((s,t,i)=>s+(t?c.full_frequency_rows[i][t-1][j]:0),0),q)),coordinates=[],directions=new Set(),tags=new Map();let extra=0;
  for(const w of ws){const first=policy.step(w),second=policy.step(first);same(policy.step(second),w,"global order-three identity on each audited original word");check(new Set([w,first,second].map(key)).size===3,"no fixed point");same(policy.control(first),policy.control(w),"kernel choice invariant after one shift");same(policy.control(second),policy.control(w),"kernel choice invariant after two shifts");const f=[w,first,second].map(frequency);check(new Set(f.map(row=>key(row.map(a=>a%3)))).size===1,"true native first prefix, not a field-shadow claim");extra+=Number(new Set(f.map(row=>key(row.map(a=>a%9)))).size===1);directions.add(key(policy.control(w).v));const orbit=[w,first,second],u=[...orbit].sort(order)[0],position=orbit.findIndex(x=>key(x)===key(u)),t=mod(-position,3);let reconstructed=u;for(let j=0;j<t;j++)reconstructed=policy.step(reconstructed);same(reconstructed,w,"canonical coordinates erase original index");coordinates.push([u,t]);tags.set(key(u),u);}
  check(new Set(coordinates.map(key)).size===new Set(ws.map(key)).size,"all audited words map injectively");check(c.complete_or_sample_coordinate_sha256===crypto.createHash("sha256").update(key(coordinates)).digest("hex")&&c.distinct_direction_values_on_audited_words===directions.size&&c.distinct_tags_on_audited_words===tags.size&&c.unchanged_cycles_with_prefix9_match_on_audited_words===extra,"complete independent word controls and real higher-prefix failures");if(complete)check(tags.size===2187&&directions.size>1&&extra<ws.length,"nonconstant direction program, all tags and failed naive root9 lift");check(c.raw_first_prefix_acceptance==="1"&&c.one_output_per_actual_batch===true,"actual one-step instrument retains all source mass, one child");for(const k of["sample_fraction_is_population_survival_factor_claimed","all_orbit_tags_counted_as_separate_outputs","novel_shallow_algorithm_claimed","full_depth_polynomial_supply_supplied"])check(c[k]===false,"no empirical/hierarchical promotion: "+k);
  const sorted=[...tags.values()].sort(order),selected=[...new Set([0,Math.floor(sorted.length/2),sorted.length-1])].sort((a,b)=>a-b);check(c.selected_child_controls.length===selected.length,"specified child controls");selected.forEach((k,index)=>{const row=c.selected_child_controls[index],u=sorted[k],triple=[u,policy.step(u),policy.step(policy.step(u))],f=triple.map(frequency),childRows=f.slice(1).map(values=>values.map((a,j)=>mod(a-f[0][j],q)/3)),proof=minor(triple);same(row.tag_word,u,"canonical physical tag");same(row.original_words,triple,"actual source words");same(row.full_frequencies,f,"actual full-root phases");same(row.child_rows,childRows,"actual divided child frequencies");same(row.pointed_unit_minor,proof,"pointed unit witness");check(row.raw_tag_probability_exponent_base_three===1-M,"unconditioned Born tag mass");const secrets=[Array(n).fill(0),Array(n).fill(1),Array(n).fill(q-1)];same(row.calibration_secrets,secrets,"physical controls");for(const secret of secrets)for(let endpoint=1;endpoint<3;endpoint++)check(mod(f[endpoint].reduce((s,a,j)=>s+a*secret[j],0)-f[0].reduce((s,a,j)=>s+a*secret[j],0)-3*childRows[endpoint-1].reduce((s,a,j)=>s+a*secret[j],0),q)===0,"exact parent-to-child phase identity");check(Number.isFinite(row.physical_phase_residual)&&row.physical_phase_residual>=0&&row.physical_phase_residual<3e-11,"numerical phase residual");
    const[a,b]=proof.columns,success=[];for(let j=0;j<n;j++){const pairs=new Set();for(let x=0;x<9;x++)for(let y=0;y<9;y++){const altered=f.map((values,k)=>mod(values[j]+3*x*Number(triple[k][Math.floor(a/2)]===a%2+1)+3*y*Number(triple[k][Math.floor(b/2)]===b%2+1),q));pairs.add(key(altered.slice(1).map(v=>mod(v-altered[0],q)/3)));}check(pairs.size===81,"actual two-column source-frequency census, not a symbolic histogram");success.push([...pairs].map(JSON.parse).filter(pair=>pair.every(a=>a%3===0)).length);liftCases+=81;}const census=row.conditional_lift_census;check(census.per_coordinate_complete_two_column_lifts===81&&census.actual_source_frequency_lift_census_coordinates===n&&census.joint_prefix9_survival_factor_from_independent_coordinates===frac(1n,9n**BigInt(n))&&census.whole_joint_high_lift_cartesian_cube_enumerated===false,"independent-coordinate population law, joint cube not enumerated");same(census.per_coordinate_child_pairs_divisible_by_three,success,"complete actual coordinate match counts");check(success.every(a=>a===9),"exact extra-prefix coordinate survival");physicalTags++;});
  if(complete)wholeWords+=ws.length;else sampledWords+=ws.length;
});
const implicit=report.implicit_exponential_menu_control;check(implicit.dimension===2&&implicit.original_qutrits===9&&implicit.parent_root_digits===3,"native implicit-menu witness dimensions");native(implicit.full_frequency_rows,implicit.native_labels,2,3);const policy=makePolicy(implicit,"provided-validated-disjoint-masks");same(implicit.policy.disjoint_masks,[[0,1,2],[3,4,5],[6,7,8]],"given full-rank disjoint masks, not a random-source guarantee");check(implicit.policy.mask_support_ranks.every(a=>a===2)&&implicit.all_c_vectors_controls.length===9&&implicit.distinct_direction_count===9&&implicit.provided_full_rank_masks_are_guaranteed_on_IID_labels_claimed===false&&implicit.algorithm_candidate_record_accepted===false,"conditional exponential-menu calibration only");const directions=new Set();implicit.all_c_vectors_controls.forEach((row,index)=>{const c=words(2)[index],targets=[[1,0],[0,1],c.map(a=>mod(-a,3))],word=targets.flatMap(column=>[...column.map(a=>a*2%3),0]),actual=policy.control(word);same(row.chosen_c,c,"all coefficient vectors");same(row.original_word,word,"actual witness word");same(row.actual_tangents,targets,"requested tangent columns realized on native source");same(actual.T,targets,"true cached tangent equations");same(row.kernel_coefficients,[...c,1],"first-free kernel rule realizes every(c,1)");same(row.kernel_coefficients,actual.coefficients,"independent kernel check");same(row.word_direction,actual.v,"distinct original directions");directions.add(key(actual.v));});check(directions.size===9,"polynomial program can encode an exponential implicit menu");
const gates=[[1,3,1,2],[2,3,1,2],[8,5,1,4],[32,6,2,5],[128,7,1,6]];check(report.unseen_prefix_population_gates.length===gates.length,"all unseen-prefix gates");report.unseen_prefix_population_gates.forEach((g,index)=>{const[n,r,e,d]=gates[index],J=3**(d-e),child=3**(r-e);same([g.dimension,g.parent_root_digits,g.available_prefix_digits,g.requested_prefix_digits,g.extra_prefix_modulus,g.conditional_child_modulus],[n,r,e,d,J,child],"available vs unseen prefix schedule");check(g.per_coordinate_uniform_child_pair_count===child**2&&g.per_coordinate_extra_prefix_match_count===(child/J)**2&&g.mean_extra_prefix_survival_factor===frac(1n,BigInt(J)**BigInt(2*n)),"exact independent child-row gate, not a fitted exponent");check(g.cycle_policy_is_unchanged_and_reads_only_available_prefix===true&&g.full_high_label_instance_success_equal_to_population_factor_claimed===false&&g.higher_prefix_informed_actions_or_secret_digit_correction_excluded===false&&g.quantum_speedup_proved===false,"gate scope: higher-informed and nonpartition receivers remain open");});
check(report.known_full_depth_supply_controls.length===4,"known full-depth baseline supply");report.known_full_depth_supply_controls.forEach((c,index)=>{const r=index+2,n=3**r,d=r-1;check(c.dimension===n&&c.root_digits===r&&c.root_lowerings===d&&c.minimum_one_output_protocol_original_copies===String(BigInt(n+1)**BigInt(d))&&c.fresh_batch_protocol_copies_for_one_final_field_qutrit===String(BigInt(n+1)**BigInt(3*d))&&c.fresh_batch_protocol_all_levels_acceptance==="1"&&c.polynomial_in_r_complete_speedup_claim_allowed===false,"perfect acceptance is not full-depth polynomial supply");check(c.lower_bound_scope==="disjoint one-odd-child supports and one lower-even child per n+1 odd states"&&c.coherent_pointer_or_multi_output_phase_transducers_excluded_from_lower_bound===true,"scoped one-output resource lower bound, not generic quantum hardness");});
console.log(JSON.stringify({status:"independent_native_shallow_kernel_cycle_certificates_passed",wholeOriginalWords:wholeWords,sampledOriginalWords:sampledWords,physicalTagControls:physicalTags,actualCoordinateHighLiftCases:liftCases,implicitDirectionWitnesses:9,unseenPrefixGates:5,fullDepthAlgorithmSupplied:false,quantumSpeedupProved:false}));
