import sys

sys.path.insert(0, "scratch")
from wire_generic_batch import wire_batch

BATCH_3_MODULES = [('coset_whitening_rank_sandwich_no_go', 'EXP-COSET-WHITENING-RANK-SANDWICH-NO-GO', 'write_coset_whitening_rank_sandwich_report', 'coset-whitening-rank-sandwich-no-go'), ('dcp_adaptive_layout_uniform_entanglement_no_go', 'EXP-DHS-DCP-ADAPTIVE-LAYOUT-UNIFORM-ENTANGLEMENT-NO-GO', 'write_dcp_adaptive_layout_uniform_entanglement_report', 'dcp-adaptive-layout-uniform-entanglement-no-go'), ('dcp_arbitrary_measurement_witness_reduction', 'EXP-DHS-DCP-ARBITRARY-MEASUREMENT-WITNESS-REDUCTION', 'write_arbitrary_measurement_witness_reduction_report', 'dcp-arbitrary-measurement-witness-reduction'), ('dcp_canonical_pgm_erasure_equivalence', 'EXP-DHS-DCP-CANONICAL-PGM-ERASURE-EQUIVALENCE', 'write_canonical_pgm_erasure_equivalence', 'dcp-canonical-pgm-erasure-equivalence'), ('dcp_covariant_rank_one_measurement_reduction', 'EXP-DHS-DCP-COVARIANT-RANK-ONE-MEASUREMENT-REDUCTION', 'write_covariant_rank_one_measurement_reduction_report', 'dcp-covariant-rank-one-measurement-reduction'), ('dcp_four_block_ksum_noncollapse', 'EXP-DHS-DCP-FOUR-BLOCK-KSUM-NONCOLLAPSE', 'write_four_block_ksum_noncollapse', 'dcp-four-block-ksum-noncollapse'), ('dcp_linear_depth_fiber_walk_no_go', 'EXP-DHS-DCP-LINEAR-DEPTH-FIBER-WALK-NO-GO', 'write_linear_depth_fiber_walk_no_go', 'dcp-linear-depth-fiber-walk-no-go'), ('dcp_low_bit_candidate_list_no_go', 'EXP-DHS-DCP-LOW-BIT-CANDIDATE-LIST-NO-GO', 'write_low_bit_candidate_list_no_go_report', 'dcp-low-bit-candidate-list-no-go'), ('dcp_multiplicity_oracle_query_lower_bound', 'EXP-DHS-DCP-MULTIPLICITY-ORACLE-QUERY-LOWER-BOUND', 'write_multiplicity_oracle_query_lower_bound', 'dcp-multiplicity-oracle-query-lower-bound'), ('dcp_per_target_stratum_obstruction', 'EXP-DHS-DCP-PER-TARGET-STRATUM-OBSTRUCTION', 'write_per_target_stratum_obstruction', 'dcp-per-target-stratum-obstruction'), ('dcp_pgm_bootstrap_perturbation_reduction', 'EXP-DHS-DCP-PGM-BOOTSTRAP-PERTURBATION-REDUCTION', 'write_pgm_bootstrap_perturbation_reduction', 'dcp-pgm-bootstrap-perturbation-reduction')]

if __name__ == "__main__":
    wire_batch(BATCH_3_MODULES)
