import sys

sys.path.insert(0, "scratch")
from wire_generic_batch import wire_batch

BATCH_2_MODULES = [('self_dual_wreath_component_dependency_ridge_physical_curl', 'EXP-CODE-SELF-DUAL-WREATH-COMPONENT-DEPENDENCY-RIDGE-PHYSICAL-CURL', 'write_component_dependency_ridge_physical_curl_report', 'self-dual-wreath-component-dependency-ridge-physical-curl'), ('self_dual_wreath_component_dependency_ridge_physical_hamming', 'EXP-CODE-SELF-DUAL-WREATH-COMPONENT-DEPENDENCY-RIDGE-PHYSICAL-HAMMING', 'write_component_dependency_ridge_physical_hamming_report', 'self-dual-wreath-component-dependency-ridge-physical-hamming'), ('self_dual_wreath_component_dependency_ridge_physical_spectrum', 'EXP-CODE-SELF-DUAL-WREATH-COMPONENT-DEPENDENCY-RIDGE-PHYSICAL-SPECTRUM', 'write_component_dependency_ridge_physical_spectrum_report', 'self-dual-wreath-component-dependency-ridge-physical-spectrum'), ('self_dual_wreath_component_dependency_ridge_single_frame_tail', 'EXP-CODE-SELF-DUAL-WREATH-COMPONENT-DEPENDENCY-RIDGE-SINGLE-FRAME-TAIL', 'write_component_dependency_ridge_single_frame_tail_report', 'self-dual-wreath-component-dependency-ridge-single-frame-tail'), ('self_dual_wreath_component_diagonal_leakage_bridge', 'EXP-CODE-SELF-DUAL-WREATH-COMPONENT-DIAGONAL-LEAKAGE-BRIDGE', 'write_component_diagonal_leakage_bridge_report', 'self-dual-wreath-component-diagonal-leakage-bridge'), ('self_dual_wreath_component_leaf_fourier_commutator_duality', 'EXP-CODE-SELF-DUAL-WREATH-COMPONENT-LEAF-FOURIER-COMMUTATOR-DUALITY', 'write_component_leaf_fourier_commutator_duality_report', 'self-dual-wreath-component-leaf-fourier-commutator-duality'), ('self_dual_wreath_component_leaf_fourier_leverage', 'EXP-CODE-SELF-DUAL-WREATH-COMPONENT-LEAF-FOURIER-LEVERAGE', 'write_component_leaf_fourier_leverage_report', 'self-dual-wreath-component-leaf-fourier-leverage'), ('self_dual_wreath_component_leaf_fourier_strata', 'EXP-CODE-SELF-DUAL-WREATH-COMPONENT-LEAF-FOURIER-STRATA', 'write_component_leaf_fourier_strata_report', 'self-dual-wreath-component-leaf-fourier-strata'), ('self_dual_wreath_component_m4_operational_boundary', 'EXP-CODE-SELF-DUAL-WREATH-COMPONENT-M4-OPERATIONAL-BOUNDARY', 'write_component_m4_operational_boundary_report', 'self-dual-wreath-component-m4-operational-boundary'), ('self_dual_wreath_component_polar_traffic_curl', 'EXP-CODE-SELF-DUAL-WREATH-COMPONENT-POLAR-TRAFFIC-CURL', 'write_component_polar_traffic_curl_report', 'self-dual-wreath-component-polar-traffic-curl'), ('self_dual_wreath_component_single_leaf_diagonal_reduction', 'EXP-CODE-SELF-DUAL-WREATH-COMPONENT-SINGLE-LEAF-DIAGONAL-REDUCTION', 'write_component_single_leaf_diagonal_reduction_report', 'self-dual-wreath-component-single-leaf-diagonal-reduction'), ('self_dual_wreath_component_size_biased_effect_law', 'EXP-CODE-SELF-DUAL-WREATH-COMPONENT-SIZE-BIASED-EFFECT-LAW', 'write_component_size_biased_effect_law_report', 'self-dual-wreath-component-size-biased-effect-law')]

if __name__ == "__main__":
    wire_batch(BATCH_2_MODULES)
