import sys

sys.path.insert(0, "scratch")
from wire_generic_batch import wire_batch

BATCH_5_MODULES = [('self_dual_wreath_codimension_one_commuting_compression_no_go', 'EXP-CODE-SELF-DUAL-WREATH-CODIMENSION-ONE-COMMUTING-COMPRESSION-NO-GO', 'write_codimension_one_commuting_compression_no_go_report', 'codimension-one-commuting-compression-no-go'), ('self_dual_wreath_codimension_two_universal_no_go', 'EXP-CODE-SELF-DUAL-WREATH-CODIMENSION-TWO-UNIVERSAL-NO-GO', 'write_codimension_two_universal_no_go_report', 'codimension-two-universal-no-go'), ('self_dual_wreath_commutator_sector_filter_no_go', 'EXP-CODE-SELF-DUAL-WREATH-COMMUTATOR-SECTOR-FILTER-NO-GO', 'write_commutator_sector_filter_no_go_report', 'commutator-sector-filter-no-go'), ('self_dual_wreath_component_block_coherence_boundary', 'EXP-CODE-SELF-DUAL-WREATH-COMPONENT-BLOCK-COHERENCE-BOUNDARY', 'write_component_block_coherence_boundary_report', 'component-block-coherence-boundary'), ('self_dual_wreath_component_coefficient_projection_normal_form', 'EXP-CODE-SELF-DUAL-WREATH-COMPONENT-COEFFICIENT-PROJECTION-NORMAL-FORM', 'write_component_coefficient_projection_normal_form_report', 'component-coefficient-projection-normal-form'), ('self_dual_wreath_component_noncrossing_lower_bound', 'EXP-CODE-SELF-DUAL-WREATH-COMPONENT-NONCROSSING-LOWER-BOUND', 'write_component_noncrossing_lower_bound_report', 'component-noncrossing-lower-bound'), ('self_dual_wreath_full_support_pair_budget_no_go', 'EXP-CODE-SELF-DUAL-WREATH-FULL-SUPPORT-PAIR-BUDGET-NO-GO', 'write_full_support_pair_budget_no_go_report', 'full-support-pair-budget-no-go'), ('self_dual_wreath_information_set_universal_no_go', 'EXP-CODE-SELF-DUAL-WREATH-INFORMATION-SET-UNIVERSAL-NO-GO', 'write_information_set_universal_no_go_report', 'information-set-universal-no-go'), ('self_dual_wreath_interleaved_even_parity_no_go', 'EXP-CODE-SELF-DUAL-WREATH-INTERLEAVED-EVEN-PARITY-NO-GO', 'write_interleaved_even_parity_no_go_report', 'interleaved-even-parity-no-go'), ('self_dual_wreath_interleaved_leaf_pressure_no_go', 'EXP-CODE-SELF-DUAL-WREATH-INTERLEAVED-LEAF-PRESSURE-NO-GO', 'write_interleaved_leaf_pressure_no_go_report', 'interleaved-leaf-pressure-no-go'), ('self_dual_wreath_interleaved_product_lift_no_go', 'EXP-CODE-SELF-DUAL-WREATH-INTERLEAVED-PRODUCT-LIFT-NO-GO', 'write_interleaved_product_lift_no_go_report', 'interleaved-product-lift-no-go')]

if __name__ == "__main__":
    wire_batch(BATCH_5_MODULES)
