import sys

sys.path.insert(0, "scratch")
from wire_generic_batch import wire_batch

BATCH_1_MODULES = [('dcp_carry_quadratic_extension_boundary', 'EXP-DHS-DCP-CARRY-QUADRATIC-EXTENSION-BOUNDARY', 'write_carry_quadratic_extension_report', 'dcp-carry-quadratic-extension-boundary'), ('dcp_label_incidence_rank_width_no_go', 'EXP-DHS-DCP-LABEL-INCIDENCE-RANK-WIDTH-NO-GO', 'write_incidence_rank_width_report', 'dcp-label-incidence-rank-width-no-go'), ('hidden_shift_public_evaluator_admission_theorem', 'EXP-HIDDEN-SHIFT-PUBLIC-EVALUATOR-ADMISSION-THEOREM', 'write_public_evaluator_admission_report', 'hidden-shift-public-evaluator-admission-theorem'), ('self_dual_wreath_all_level_component_trim', 'EXP-CODE-SELF-DUAL-WREATH-ALL-LEVEL-COMPONENT-TRIM', 'write_all_level_component_trim_report', 'self-dual-wreath-all-level-component-trim'), ('self_dual_wreath_branch_character_decoder_boundary', 'EXP-CODE-SELF-DUAL-WREATH-BRANCH-CHARACTER-DECODER-BOUNDARY', 'write_branch_character_decoder_boundary_report', 'self-dual-wreath-branch-character-decoder-boundary'), ('self_dual_wreath_coherent_component_trim_hybrid', 'EXP-CODE-SELF-DUAL-WREATH-COHERENT-COMPONENT-TRIM-HYBRID', 'write_coherent_component_trim_hybrid_report', 'self-dual-wreath-coherent-component-trim-hybrid'), ('self_dual_wreath_coherent_gpe_router_boundary', 'EXP-CODE-SELF-DUAL-WREATH-COHERENT-GPE-ROUTER-BOUNDARY', 'write_coherent_gpe_router_boundary_report', 'self-dual-wreath-coherent-gpe-router-boundary'), ('self_dual_wreath_collective_point_activation', 'EXP-CODE-SELF-DUAL-WREATH-COLLECTIVE-POINT-ACTIVATION', 'write_collective_point_activation_report', 'self-dual-wreath-collective-point-activation'), ('self_dual_wreath_common_window_access_boundary', 'EXP-CODE-SELF-DUAL-WREATH-COMMON-WINDOW-ACCESS-BOUNDARY', 'write_common_window_access_boundary_report', 'self-dual-wreath-common-window-access-boundary'), ('self_dual_wreath_component_common_codimension_curl_reduction', 'EXP-CODE-SELF-DUAL-WREATH-COMPONENT-COMMON-CODIMENSION-CURL-REDUCTION', 'write_component_common_codimension_curl_reduction_report', 'self-dual-wreath-component-common-codimension-curl-reduction'), ('self_dual_wreath_component_dependency_ridge_moment_method_bridge', 'EXP-CODE-SELF-DUAL-WREATH-COMPONENT-DEPENDENCY-RIDGE-MOMENT-METHOD-BRIDGE', 'write_component_dependency_ridge_moment_method_bridge_report', 'self-dual-wreath-component-dependency-ridge-moment-method-bridge'), ('self_dual_wreath_component_dependency_ridge_parity_stability', 'EXP-CODE-SELF-DUAL-WREATH-COMPONENT-DEPENDENCY-RIDGE-PARITY-STABILITY', 'write_component_dependency_ridge_parity_stability_report', 'self-dual-wreath-component-dependency-ridge-parity-stability')]

if __name__ == "__main__":
    wire_batch(BATCH_1_MODULES)
