import sys

sys.path.insert(0, "scratch")
from wire_generic_batch import wire_batch

BATCH_4_MODULES = [('dcp_pgm_garbage_bootstrap_reduction', 'EXP-DHS-DCP-PGM-GARBAGE-BOOTSTRAP-REDUCTION', 'write_pgm_garbage_bootstrap_reduction', 'dcp-pgm-garbage-bootstrap-reduction'), ('dcp_polynomial_feature_contraction_no_go', 'EXP-DHS-DCP-POLYNOMIAL-FEATURE-CONTRACTION-NO-GO', 'write_polynomial_feature_contraction_no_go', 'dcp-polynomial-feature-contraction-no-go'), ('dcp_source_weighted_inversion_tradeoff', 'EXP-DHS-DCP-SOURCE-WEIGHTED-INVERSION-TRADEOFF', 'write_dcp_source_weighted_inversion_tradeoff', 'dcp-source-weighted-inversion-tradeoff'), ('dcp_subset_sum_cube_section_gap_theorem', 'EXP-DHS-DCP-SUBSET-SUM-CUBE-SECTION-GAP-THEOREM', 'write_cube_section_gap_theorem', 'dcp-subset-sum-cube-section-gap-theorem'), ('dcp_subset_sum_sparse_character_obstruction', 'EXP-DHS-DCP-SUBSET-SUM-ADAPTIVE-SPARSE-CHARACTER-OBSTRUCTION', 'write_sparse_character_obstruction', 'dcp-subset-sum-sparse-character-obstruction'), ('dcp_uniform_legal_multiplicity_no_go', 'EXP-DHS-DCP-UNIFORM-LEGAL-MULTIPLICITY-NO-GO', 'write_uniform_legal_multiplicity_no_go_report', 'dcp-uniform-legal-multiplicity-no-go'), ('dcp_varying_hms_fiber_normal_form', 'EXP-DHS-DCP-VARYING-HMS-FIBER-NORMAL-FORM', 'write_dcp_varying_hms_fiber_normal_form', 'dcp-varying-hms-fiber-normal-form'), ('diagram_hidden_subalgebra_coset_no_go', 'EXP-DIAGRAM-HIDDEN-SUBALGEBRA-COSET-NO-GO', 'write_diagram_hidden_subalgebra_coset_no_go', 'diagram-hidden-subalgebra-coset-no-go'), ('diagram_multiplicity_source_mass_gate', 'EXP-DIAGRAM-MULTIPLICITY-SOURCE-MASS-GATE', 'write_diagram_multiplicity_source_mass_gate', 'diagram-multiplicity-source-mass-gate'), ('self_dual_wreath_all_codimension_baba_no_go', 'EXP-CODE-SELF-DUAL-WREATH-ALL-CODIMENSION-BABA-NO-GO', 'write_all_codimension_baba_no_go_report', 'all-codimension-baba-no-go'), ('self_dual_wreath_class_uniform_commutator_moment', 'EXP-CODE-SELF-DUAL-WREATH-CLASS-UNIFORM-COMMUTATOR-MOMENT', 'write_class_uniform_commutator_moment_report', 'class-uniform-commutator-moment')]

if __name__ == "__main__":
    wire_batch(BATCH_4_MODULES)
