import sys

sys.path.insert(0, "scratch")
from wire_generic_batch import wire_batch

BATCH_1_MODULES = [('coset_arbitrary_covariant_measurement_reduction', 'EXP-COSET-ARBITRARY-COVARIANT-MEASUREMENT-REDUCTION', 'write_arbitrary_covariant_measurement_reduction', 'coset-arbitrary-covariant-measurement-reduction'), ('coset_centralizer_whitening_rank_bound', 'EXP-COSET-CENTRALIZER-WHITENING-RANK-BOUND', 'write_coset_centralizer_whitening_rank_report', 'coset-centralizer-whitening-rank-bound'), ('coset_covariant_measurement_multiplicity_width_no_go', 'EXP-COSET-COVARIANT-MEASUREMENT-MULTIPLICITY-WIDTH-NO-GO', 'write_coset_covariant_measurement_multiplicity_width_report', 'coset-covariant-measurement-multiplicity-width-no-go'), ('coset_covariant_multiplicity_whitening_escape', 'EXP-COSET-COVARIANT-MULTIPLICITY-WHITENING-ESCAPE', 'write_coset_covariant_multiplicity_whitening_report', 'coset-covariant-multiplicity-whitening-escape'), ('coset_gelfand_row_orientation_no_go', 'EXP-COSET-GELFAND-ROW-ORIENTATION-NO-GO', 'write_gelfand_row_orientation_no_go', 'coset-gelfand-row-orientation-no-go'), ('coset_hidden_involution_binary_decision_reduction', 'EXP-COSET-HIDDEN-INVOLUTION-BINARY-DECISION-REDUCTION', 'write_hidden_involution_binary_decision_report', 'coset-hidden-involution-binary-decision-reduction'), ('coset_hidden_involution_fourth_moment_threshold', 'EXP-COSET-HIDDEN-INVOLUTION-FOURTH-MOMENT-THRESHOLD', 'write_hidden_involution_fourth_moment_report', 'coset-hidden-involution-fourth-moment-threshold'), ('coset_hidden_involution_multiplicity_support_obstruction', 'EXP-COSET-HIDDEN-INVOLUTION-MULTIPLICITY-SUPPORT-OBSTRUCTION', 'write_multiplicity_support_obstruction_report', 'coset-hidden-involution-multiplicity-support-obstruction'), ('coset_hidden_involution_orbit_hull_twirl_reduction', 'EXP-COSET-HIDDEN-INVOLUTION-ORBIT-HULL-TWIRL-REDUCTION', 'write_hidden_involution_orbit_hull_report', 'coset-hidden-involution-orbit-hull-twirl-reduction'), ('coset_hidden_involution_query_separation_boundary', 'EXP-COSET-HIDDEN-INVOLUTION-QUERY-SEPARATION-BOUNDARY', 'write_hidden_involution_query_separation_report', 'coset-hidden-involution-query-separation-boundary'), ('coset_hidden_involution_support_span_reduction', 'EXP-COSET-HIDDEN-INVOLUTION-SUPPORT-SPAN-REDUCTION', 'write_hidden_involution_support_span_report', 'coset-hidden-involution-support-span-reduction')]

if __name__ == "__main__":
    wire_batch(BATCH_1_MODULES)
