import sys

sys.path.insert(0, "scratch")
from wire_generic_batch import wire_batch

BATCH_4_MODULES = [('self_dual_wreath_joint_character_multiplicity_gram', 'EXP-CODE-SELF-DUAL-WREATH-JOINT-CHARACTER-MULTIPLICITY-GRAM', 'write_joint_multiplicity_gram_report', 'self-dual-wreath-joint-character-multiplicity-gram'), ('self_dual_wreath_joint_character_purity_decoupling', 'EXP-CODE-SELF-DUAL-WREATH-JOINT-CHARACTER-PURITY-DECOUPLING', 'write_joint_character_purity_decoupling_report', 'self-dual-wreath-joint-character-purity-decoupling'), ('self_dual_wreath_orientation_kernel_hash_thinning', 'EXP-CODE-SELF-DUAL-WREATH-ORIENTATION-KERNEL-HASH-THINNING', 'write_orientation_kernel_hash_thinning_report', 'self-dual-wreath-orientation-kernel-hash-thinning'), ('self_dual_wreath_orientation_partition_traffic', 'EXP-CODE-SELF-DUAL-WREATH-ORIENTATION-PARTITION-TRAFFIC', 'write_orientation_partition_traffic_report', 'self-dual-wreath-orientation-partition-traffic'), ('self_dual_wreath_partial_holonomy_sheaf_resolver', 'EXP-CODE-SELF-DUAL-WREATH-PARTIAL-HOLONOMY-SHEAF-RESOLVER', 'write_partial_holonomy_sheaf_resolver_report', 'self-dual-wreath-partial-holonomy-sheaf-resolver'), ('self_dual_wreath_physical_branch_erasure_boundary', 'EXP-CODE-SELF-DUAL-WREATH-PHYSICAL-BRANCH-ERASURE-BOUNDARY', 'write_physical_branch_erasure_boundary_report', 'self-dual-wreath-physical-branch-erasure-boundary'), ('self_dual_wreath_physical_row_copy_erasure_no_go', 'EXP-CODE-SELF-DUAL-WREATH-PHYSICAL-ROW-COPY-ERASURE-NO-GO', 'write_physical_row_copy_erasure_no_go_report', 'self-dual-wreath-physical-row-copy-erasure-no-go'), ('self_dual_wreath_plancherel_recoupling_stationarity', 'EXP-CODE-SELF-DUAL-WREATH-PLANCHEREL-RECOUPLING-STATIONARITY', 'write_plancherel_recoupling_stationarity_report', 'self-dual-wreath-plancherel-recoupling-stationarity'), ('self_dual_wreath_point_child_star_energy', 'EXP-CODE-SELF-DUAL-WREATH-POINT-CHILD-STAR-ENERGY', 'write_point_child_star_energy_report', 'self-dual-wreath-point-child-star-energy'), ('self_dual_wreath_point_effect_access_boundary', 'EXP-CODE-SELF-DUAL-WREATH-POINT-EFFECT-ACCESS-BOUNDARY', 'write_point_effect_access_boundary_report', 'self-dual-wreath-point-effect-access-boundary'), ('self_dual_wreath_point_effect_qsvt_no_go', 'EXP-CODE-SELF-DUAL-WREATH-POINT-EFFECT-QSVT-NO-GO', 'write_point_effect_qsvt_no_go_report', 'self-dual-wreath-point-effect-qsvt-no-go'), ('self_dual_wreath_point_linear_povm', 'EXP-CODE-SELF-DUAL-WREATH-POINT-LINEAR-POVM', 'write_point_linear_povm_report', 'self-dual-wreath-point-linear-povm')]

if __name__ == "__main__":
    wire_batch(BATCH_4_MODULES)
