import sys

sys.path.insert(0, "scratch")
from wire_generic_batch import wire_batch

BATCH_6_MODULES = [('self_dual_wreath_nonsystematic_incidence_lattice_bound', 'EXP-CODE-SELF-DUAL-WREATH-NONSYSTEMATIC-INCIDENCE-LATTICE-BOUND', 'write_nonsystematic_incidence_lattice_bound_report', 'nonsystematic-incidence-lattice-bound'), ('self_dual_wreath_nonsystematic_mod_four_no_go', 'EXP-CODE-SELF-DUAL-WREATH-NONSYSTEMATIC-MOD-FOUR-NO-GO', 'write_nonsystematic_mod_four_no_go_report', 'nonsystematic-mod-four-no-go'), ('self_dual_wreath_nonsystematic_pair_witness_collapse', 'EXP-CODE-SELF-DUAL-WREATH-NONSYSTEMATIC-PAIR-WITNESS-COLLAPSE', 'write_nonsystematic_pair_witness_collapse_report', 'nonsystematic-pair-witness-collapse'), ('self_dual_wreath_nonsystematic_twisted_star_no_go', 'EXP-CODE-SELF-DUAL-WREATH-NONSYSTEMATIC-TWISTED-STAR-NO-GO', 'write_nonsystematic_twisted_star_no_go_report', 'nonsystematic-twisted-star-no-go'), ('self_dual_wreath_plancherel_target_word_collapse', 'EXP-CODE-SELF-DUAL-WREATH-PLANCHEREL-TARGET-WORD-COLLAPSE', 'write_plancherel_target_word_collapse_report', 'plancherel-target-word-collapse'), ('self_dual_wreath_poisson_ridge_word_mixture', 'EXP-CODE-SELF-DUAL-WREATH-POISSON-RIDGE-WORD-MIXTURE', 'write_poisson_ridge_word_mixture_report', 'poisson-ridge-word-mixture'), ('self_dual_wreath_same_support_triangle_target_no_go', 'EXP-CODE-SELF-DUAL-WREATH-SAME-SUPPORT-TRIANGLE-TARGET-NO-GO', 'write_same_support_triangle_target_no_go_report', 'same-support-triangle-target-no-go'), ('self_dual_wreath_separator_defect_frontier', 'EXP-CODE-SELF-DUAL-WREATH-SEPARATOR-DEFECT-FRONTIER', 'write_separator_defect_frontier_report', 'separator-defect-frontier'), ('self_dual_wreath_systematic_stopping_core_no_go', 'EXP-CODE-SELF-DUAL-WREATH-SYSTEMATIC-STOPPING-CORE-NO-GO', 'write_systematic_stopping_core_no_go_report', 'systematic-stopping-core-no-go'), ('self_dual_wreath_translated_parity_commutator_no_go', 'EXP-CODE-SELF-DUAL-WREATH-TRANSLATED-PARITY-COMMUTATOR-NO-GO', 'write_translated_parity_commutator_no_go_report', 'translated-parity-commutator-no-go'), ('semidirect_hms_transfer_boundary', 'EXP-SEMIDIRECT-HMS-TRANSFER-BOUNDARY', 'write_semidirect_hms_transfer_boundary', 'semidirect-hms-transfer-boundary')]

if __name__ == "__main__":
    wire_batch(BATCH_6_MODULES)
