import sys

sys.path.insert(0, "scratch")
from wire_generic_batch import wire_batch

BATCH_2_MODULES = [('coset_hidden_involution_threshold_compiler_boundary', 'EXP-COSET-HIDDEN-INVOLUTION-THRESHOLD-COMPILER-BOUNDARY', 'write_hidden_involution_threshold_compiler_report', 'coset-hidden-involution-threshold-compiler-boundary'), ('coset_hyperoctahedral_branching_polar_boundary', 'EXP-COSET-HYPEROCTAHEDRAL-BRANCHING-POLAR-BOUNDARY', 'write_coset_hyperoctahedral_branching_polar_report', 'coset-hyperoctahedral-branching-polar-boundary'), ('coset_kronecker_marginal_conservation', 'EXP-COSET-KRONECKER-MARGINAL-CONSERVATION', 'write_kronecker_marginal_conservation_report', 'coset-kronecker-marginal-conservation'), ('coset_measurement_copy_width_whitening_tradeoff', 'EXP-COSET-MEASUREMENT-COPY-WIDTH-WHITENING-TRADEOFF', 'write_coset_measurement_copy_width_whitening_report', 'coset-measurement-copy-width-whitening-tradeoff'), ('coset_multiplicity_whitening_copy_window', 'EXP-COSET-MULTIPLICITY-WHITENING-COPY-WINDOW', 'write_coset_multiplicity_whitening_copy_window_report', 'coset-multiplicity-whitening-copy-window'), ('coset_perfect_matching_spherical_boundary', 'EXP-COSET-PERFECT-MATCHING-SPHERICAL-BOUNDARY', 'write_perfect_matching_spherical_boundary', 'coset-perfect-matching-spherical-boundary'), ('coset_prefix_polar_holonomy_reduction', 'EXP-COSET-PREFIX-POLAR-HOLONOMY-REDUCTION', 'write_coset_prefix_polar_holonomy_report', 'coset-prefix-polar-holonomy-reduction'), ('coset_prefix_relative_gap_inference_no_go', 'EXP-COSET-PREFIX-RELATIVE-GAP-INFERENCE-NO-GO', 'write_coset_prefix_relative_gap_inference_report', 'coset-prefix-relative-gap-inference-no-go'), ('coset_restriction_principal_angle_polar_reduction', 'EXP-COSET-RESTRICTION-PRINCIPAL-ANGLE-POLAR-REDUCTION', 'write_coset_restriction_principal_angle_polar_report', 'coset-restriction-principal-angle-polar-reduction'), ('coset_sector_coherence_degree_no_go', 'EXP-COSET-SECTOR-COHERENCE-DEGREE-NO-GO', 'write_sector_coherence_degree_no_go_report', 'coset-sector-coherence-degree-no-go'), ('coset_source_weighted_frame_inversion_tradeoff', 'EXP-COSET-SOURCE-WEIGHTED-FRAME-INVERSION-TRADEOFF', 'write_coset_source_weighted_frame_inversion_report', 'coset-source-weighted-frame-inversion-tradeoff')]

if __name__ == "__main__":
    wire_batch(BATCH_2_MODULES)
