import sys

sys.path.insert(0, "scratch")
from wire_generic_batch import wire_batch

BATCH_5_MODULES = [('self_dual_wreath_point_parent_coherence_witness', 'EXP-CODE-SELF-DUAL-WREATH-POINT-PARENT-COHERENCE-WITNESS', 'write_point_parent_coherence_witness_report', 'self-dual-wreath-point-parent-coherence-witness'), ('self_dual_wreath_point_pgm_coarse_graining', 'EXP-CODE-SELF-DUAL-WREATH-POINT-PGM-COARSE-GRAINING', 'write_point_pgm_coarse_graining_report', 'self-dual-wreath-point-pgm-coarse-graining'), ('self_dual_wreath_point_stabilizer_collision_free_kernel', 'EXP-CODE-SELF-DUAL-WREATH-POINT-STABILIZER-COLLISION-FREE-KERNEL', 'write_collision_free_point_kernel_report', 'self-dual-wreath-point-stabilizer-collision-free-kernel'), ('self_dual_wreath_point_stabilizer_quotient', 'EXP-CODE-SELF-DUAL-WREATH-POINT-STABILIZER-QUOTIENT', 'write_point_stabilizer_quotient_report', 'self-dual-wreath-point-stabilizer-quotient'), ('self_dual_wreath_point_standard_energy', 'EXP-CODE-SELF-DUAL-WREATH-POINT-STANDARD-ENERGY', 'write_point_standard_energy_report', 'self-dual-wreath-point-standard-energy'), ('self_dual_wreath_point_young_star_naimark', 'EXP-CODE-SELF-DUAL-WREATH-POINT-YOUNG-STAR-NAIMARK', 'write_young_star_naimark_report', 'self-dual-wreath-point-young-star-naimark'), ('self_dual_wreath_recursive_kernel_isometry', 'EXP-CODE-SELF-DUAL-WREATH-RECURSIVE-KERNEL-ISOMETRY', 'write_recursive_kernel_isometry_report', 'self-dual-wreath-recursive-kernel-isometry'), ('self_dual_wreath_reversible_automaton_fiber_collapse', 'EXP-CODE-SELF-DUAL-WREATH-REVERSIBLE-AUTOMATON-FIBER-COLLAPSE', 'write_reversible_automaton_fiber_report', 'self-dual-wreath-reversible-automaton-fiber-collapse'), ('self_dual_wreath_shared_pair_recoupling_decoupling', 'EXP-CODE-SELF-DUAL-WREATH-SHARED-PAIR-RECOUPLING-DECOUPLING', 'write_shared_pair_recoupling_decoupling_report', 'self-dual-wreath-shared-pair-recoupling-decoupling'), ('self_dual_wreath_sibling_frame_all_fixed_joint', 'EXP-CODE-SELF-DUAL-WREATH-SIBLING-FRAME-ALL-FIXED-JOINT', 'write_sibling_frame_all_fixed_joint_report', 'self-dual-wreath-sibling-frame-all-fixed-joint'), ('self_dual_wreath_sibling_frame_all_fixed_mp', 'EXP-CODE-SELF-DUAL-WREATH-SIBLING-FRAME-ALL-FIXED-MP', 'write_sibling_frame_all_fixed_mp_report', 'self-dual-wreath-sibling-frame-all-fixed-mp'), ('self_dual_wreath_sign_twist_collective_activation', 'EXP-CODE-SELF-DUAL-WREATH-SIGN-TWIST-COLLECTIVE-ACTIVATION', 'write_sign_twist_collective_activation_report', 'self-dual-wreath-sign-twist-collective-activation')]

if __name__ == "__main__":
    wire_batch(BATCH_5_MODULES)
