import sys

sys.path.insert(0, "scratch")
from wire_generic_batch import wire_batch

BATCH_3_MODULES = [('self_dual_wreath_component_support_geometry_no_go', 'EXP-CODE-SELF-DUAL-WREATH-COMPONENT-SUPPORT-GEOMETRY-NO-GO', 'write_component_support_geometry_no_go_report', 'self-dual-wreath-component-support-geometry-no-go'), ('self_dual_wreath_component_support_ridge_poisson_scale_no_go', 'EXP-CODE-SELF-DUAL-WREATH-COMPONENT-SUPPORT-RIDGE-POISSON-SCALE-NO-GO', 'write_component_support_ridge_poisson_scale_no_go_report', 'self-dual-wreath-component-support-ridge-poisson-scale-no-go'), ('self_dual_wreath_component_trimmed_support_scalarization', 'EXP-CODE-SELF-DUAL-WREATH-COMPONENT-TRIMMED-SUPPORT-SCALARIZATION', 'write_component_trimmed_support_scalarization_report', 'self-dual-wreath-component-trimmed-support-scalarization'), ('self_dual_wreath_conjugate_pair_admission_no_go', 'EXP-CODE-SELF-DUAL-WREATH-CONJUGATE-PAIR-ADMISSION-NO-GO', 'write_conjugate_pair_admission_no_go_report', 'self-dual-wreath-conjugate-pair-admission-no-go'), ('self_dual_wreath_constant_arity_joint_freeness', 'EXP-CODE-SELF-DUAL-WREATH-CONSTANT-ARITY-JOINT-FREENESS', 'write_constant_arity_joint_freeness_report', 'self-dual-wreath-constant-arity-joint-freeness'), ('self_dual_wreath_final_root_common_window_metric', 'EXP-CODE-SELF-DUAL-WREATH-FINAL-ROOT-COMMON-WINDOW-METRIC', 'write_final_root_common_window_metric_report', 'self-dual-wreath-final-root-common-window-metric'), ('self_dual_wreath_final_root_joint_aspect_sharpening', 'EXP-CODE-SELF-DUAL-WREATH-FINAL-ROOT-JOINT-ASPECT-SHARPENING', 'write_final_root_joint_aspect_sharpening_report', 'self-dual-wreath-final-root-joint-aspect-sharpening'), ('self_dual_wreath_final_root_relative_jacobi_transfer', 'EXP-CODE-SELF-DUAL-WREATH-FINAL-ROOT-RELATIVE-JACOBI-TRANSFER', 'write_final_root_relative_jacobi_transfer_report', 'self-dual-wreath-final-root-relative-jacobi-transfer'), ('self_dual_wreath_fixed_arity_support_sum_compiler', 'EXP-CODE-SELF-DUAL-WREATH-FIXED-ARITY-SUPPORT-SUM-COMPILER', 'write_fixed_arity_support_sum_compiler_report', 'self-dual-wreath-fixed-arity-support-sum-compiler'), ('self_dual_wreath_flat_holonomy_component_no_go', 'EXP-CODE-SELF-DUAL-WREATH-FLAT-HOLONOMY-COMPONENT-NO-GO', 'write_flat_holonomy_component_no_go_report', 'self-dual-wreath-flat-holonomy-component-no-go'), ('self_dual_wreath_interleaved_target_margin_stability', 'EXP-CODE-SELF-DUAL-WREATH-INTERLEAVED-TARGET-MARGIN-STABILITY', 'write_target_margin_stability_report', 'self-dual-wreath-interleaved-target-margin-stability'), ('self_dual_wreath_joint_character_correlation_decoder', 'EXP-CODE-SELF-DUAL-WREATH-JOINT-CHARACTER-CORRELATION-DECODER', 'write_joint_character_correlation_decoder_report', 'self-dual-wreath-joint-character-correlation-decoder')]

if __name__ == "__main__":
    wire_batch(BATCH_3_MODULES)
